import { config as loadEnv } from "dotenv";
loadEnv({ path: ".env.local" });

const DESCRIPTIONS: Record<string, string> = {
  "grateful-dead":
    "American rock band formed in Palo Alto, California in 1965. Original lineup: Jerry Garcia (vocals/guitar, 1965-1995), Bob Weir (vocals/guitar), Phil Lesh (bass, 1965-2024), Bill Kreutzmann (drums), Mickey Hart (drums, 1967-present), and Ron \"Pigpen\" McKernan (keyboards/vocals, 1965-1972, died 1973). Foundational to American jam-band culture and the practice of audience taping and trading.\n\nThirteen studio albums plus dozens of official live releases. Critical peak: *Live/Dead* (1969), *Workingman's Dead* (1970), *American Beauty* (1970), and *Europe '72* (1972). Garcia died in 1995, ending the band; surviving members have toured under names like the Other Ones, the Dead, Furthur, and Dead & Company. Lesh died in 2024. Inducted into the Rock and Roll Hall of Fame in 1994.",
  "scorpions":
    "German hard rock band formed in Hanover in 1965. Long-running lineup: Klaus Meine (vocals, since 1969), Rudolf Schenker (guitar, since formation), Matthias Jabs (guitar, since 1978), and various rhythm sections.\n\nNineteen studio albums starting with *Lonesome Crow* (1972). Commercial peak: *Blackout* (1982), *Love at First Sting* (1984, featuring \"Rock You Like a Hurricane\"), and *Crazy World* (1990, featuring \"Wind of Change\" — one of the best-selling singles of all time). The band announced a farewell tour in 2010 but continued recording and performing. Still active.",
  "shelter":
    "American hardcore band formed in New York City in 1989 by Ray Cappo (vocals, formerly of Youth of Today) and John Porcelly (guitar). Distinguished by Krishna-conscious lyrical themes alongside straightedge messaging — bridging hardcore with elements of devotional music.\n\nSeven studio albums between 1990 and 2001 including *Quest for Certainty* (1992), *Mantra* (1995), and *Beyond Planet Earth* (1997). Released on Equal Vision Records, the label co-founded by Cappo. The band has been on extended hiatus since the early 2000s with periodic reunion shows.",
  "sheryl-crow":
    "American singer-songwriter born February 11, 1962, in Kennett, Missouri. First gained prominence as a backing vocalist for Michael Jackson's *Bad* tour (1987-1989) before launching her solo career.\n\nEleven studio albums starting with *Tuesday Night Music Club* (1993), which sold over 7 million copies on the strength of \"All I Wanna Do\" and \"Strong Enough.\" Commercial peak continued through *Sheryl Crow* (1996), *The Globe Sessions* (1998), and *C'mon, C'mon* (2002). Nine Grammy Awards. Inducted into the Rock and Roll Hall of Fame in 2023.",
  "simon-garfunkel":
    "American folk-rock duo of Paul Simon and Art Garfunkel, originally formed as Tom & Jerry in Forest Hills, Queens in 1956. Active under the Simon & Garfunkel name from 1963 to 1970, with periodic reunion performances thereafter.\n\nFive studio albums: *Wednesday Morning, 3 A.M.* (1964), *Sounds of Silence* (1966), *Parsley, Sage, Rosemary and Thyme* (1966), *Bookends* (1968), and *Bridge over Troubled Water* (1970). The final album sold over 25 million copies. Inducted into the Rock and Roll Hall of Fame in 1990. The 1981 \"Concert in Central Park\" reunion drew an estimated 500,000 attendees.",
  "son-volt":
    "American alternative country band formed in St. Louis in 1994 by Jay Farrar (vocals/guitar) after the breakup of Uncle Tupelo. Original lineup also included Jim Boquist (bass), Dave Boquist (guitar), and Mike Heidorn (drums); subsequent lineups have rotated around Farrar.\n\nTen studio albums starting with *Trace* (1995). Best-known releases include *Straightaways* (1997), *Wide Swing Tremolo* (1998), and *Okemah and the Melody of Riot* (2005). The band paused from 1999 to 2005 while Farrar pursued solo work; resumed with a new lineup that has remained largely stable.",
  "sonic-youth":
    "American rock band formed in New York City in 1981 by Thurston Moore (guitar/vocals), Kim Gordon (bass/vocals/guitar), Lee Ranaldo (guitar/vocals), and various drummers — Steve Shelley joined in 1985 and remained continuous. Foundational to no-wave, noise rock, and alternative rock; key influence on the 1990s indie scene.\n\nFifteen studio albums between *Sonic Youth* (1982) and *The Eternal* (2009). Critical peaks: *Daydream Nation* (1988), *Goo* (1990), and *Dirty* (1992). The band dissolved in 2011 after Moore and Gordon's high-profile divorce. Members have continued in various solo projects since.",
  "squeeze":
    "English rock band formed in Greenwich, London in 1974. Long-running lineup centered on songwriting partners Chris Difford (lyrics/guitar) and Glenn Tilbrook (music/vocals/guitar). Other key members included Jools Holland (keyboards, 1974-1980, with later reunions) and a rotating rhythm section.\n\nFifteen studio albums starting with *Squeeze* (1978). Commercial peak: *Cool for Cats* (1979), *Argybargy* (1980), *East Side Story* (1981, produced by Elvis Costello), and *Sweets from a Stranger* (1982). The Difford-Tilbrook partnership has been compared to Lennon-McCartney by various critics; their songwriting is the band's defining feature.",
  "stone-temple-pilots":
    "American rock band formed in San Diego in 1989. Original lineup: Scott Weiland (vocals, 1989-2013, died 2015), Dean DeLeo (guitar), Robert DeLeo (bass), and Eric Kretz (drums). Often associated with the grunge era despite the band's diverse stylistic range across albums.\n\nSeven studio albums total. Their first three — *Core* (1992), *Purple* (1994), and *Tiny Music... Songs from the Vatican Gift Shop* (1996) — sold a combined 16 million-plus copies in the US. Weiland was fired in 2013 (replaced by Chester Bennington of Linkin Park, 2013-2015, who died in 2017). Jeff Gutt has fronted the band since 2017.",
  "the-b-52s":
    "American new wave band formed in Athens, Georgia in 1976. Lineup: Fred Schneider (vocals), Kate Pierson (vocals), Cindy Wilson (vocals), Ricky Wilson (guitar, died 1985), and Keith Strickland (guitar/drums). Pioneers of dance-oriented new wave with retro-pop aesthetics — beehive hairdos, kitsch imagery, and call-and-response vocals.\n\nEight studio albums starting with the 1979 self-titled debut (featuring \"Rock Lobster\"). Ricky Wilson died of AIDS in 1985. Commercial breakthrough came with *Cosmic Thing* (1989, featuring \"Love Shack\" and \"Roam\"). The band performed a 2022 farewell tour but continues to make occasional festival appearances.",
  "the-beach-boys":
    "American rock band formed in Hawthorne, California in 1961. Original lineup: brothers Brian Wilson (bass/vocals, 1961-1998, 1999-present), Dennis Wilson (drums, died 1983), and Carl Wilson (guitar/vocals, died 1998), cousin Mike Love (vocals), and friend Al Jardine (guitar/vocals). Among the most commercially successful and influential bands of the 1960s.\n\nTwenty-nine studio albums between *Surfin' Safari* (1962) and *That's Why God Made the Radio* (2012). Critical peak: *Pet Sounds* (1966), produced by Brian Wilson and frequently cited as one of the greatest albums ever made. The band's complex internal politics — particularly between Brian Wilson and Mike Love — have shaped its long history. Inducted into the Rock and Roll Hall of Fame in 1988.",
  "the-bouncing-souls":
    "American punk rock band formed in New Brunswick, New Jersey in 1989. Long-running lineup: Greg Attonito (vocals), Pete Steinkopf (guitar), Bryan Kienlen (bass), and various drummers — Michael McDermott joined in 2000 and remains continuous.\n\nTen studio albums starting with *The Good, the Bad and the Argyle* (1994). Best-known releases include *Maniacal Laughter* (1996), *The Bouncing Souls* (1997), and *How I Spent My Summer Vacation* (2001). Released primarily on Chunksaah and Epitaph. The band has remained active continuously since 1989, with a strong East Coast touring schedule.",
  "the-dave-brubeck-quartet":
    "American jazz group led by pianist Dave Brubeck (1920-2012). Classic lineup: Brubeck (piano), Paul Desmond (alto saxophone, 1951-1967), Eugene Wright (bass, 1958-1968), and Joe Morello (drums, 1956-1968). Among the most commercially successful jazz acts of the 1950s and 1960s.\n\nReleased dozens of albums in the classic-quartet era. Critical and commercial peak: *Time Out* (1959), one of the best-selling jazz albums ever — featuring Desmond's composition \"Take Five.\" The album popularized unusual time signatures in jazz (5/4, 9/8). The classic quartet disbanded in 1967; Brubeck continued with various lineups until his death in 2012.",
  "the-dillinger-escape-plan":
    "American mathcore band formed in Morris Plains, New Jersey in 1997. Long-running lineup centered on guitarist Ben Weinman and vocalist Greg Puciato (2001-2017). Distinguished by highly technical, dissonant arrangements and physically extreme live performances.\n\nSix studio albums between *Calculating Infinity* (1999) and *Dissociation* (2016). The band announced their dissolution in 2016 with the release of their final album; their final tour ended in late 2017. Considered a defining influence on mathcore and post-hardcore subgenres.",
  "the-moody-blues":
    "English rock band formed in Birmingham in 1964. Long-running classic lineup: Justin Hayward (vocals/guitar, since 1966), John Lodge (bass/vocals, since 1966), Mike Pinder (keyboards, 1964-1978, died 2024), Ray Thomas (flute/vocals, 1964-2002, died 2018), and Graeme Edge (drums, 1964-2021, died 2021). Pioneers of progressive rock and the use of orchestral arrangement in rock recordings.\n\nSixteen studio albums. Their second album *Days of Future Passed* (1967), recorded with the London Festival Orchestra and featuring \"Nights in White Satin,\" was a defining work of progressive rock. Subsequent peaks: *In Search of the Lost Chord* (1968), *On the Threshold of a Dream* (1969), and *Seventh Sojourn* (1972). Inducted into the Rock and Roll Hall of Fame in 2018.",
  "the-offspring":
    "American punk rock band formed in Garden Grove, California in 1984. Lineup: Dexter Holland (vocals/guitar), Noodles (Kevin Wasserman, guitar), Greg K. (Greg Kriesel, bass, 1984-2018), and Ron Welty (drums, 1987-2003, replaced by various since). Pete Parada played drums from 2007 to 2021.\n\nTen studio albums starting with the self-titled debut (1989). Commercial breakthrough: *Smash* (1994), which remains the best-selling album ever on an independent label (Epitaph) at over 11 million copies. Subsequent peaks: *Ixnay on the Hombre* (1997), *Americana* (1998), and *Conspiracy of One* (2000). Holland completed a PhD in molecular biology in 2017 while touring.",
  "the-reverend-horton-heat":
    "Same artist as the Reverend Horton Heat — Discogs/setlist.fm credit variation. American psychobilly trio formed in Dallas, Texas in 1985 by Jim Heath (vocals/guitar, \"the Reverend\"). Long-running lineup also includes Jimbo Wallace (bass).\n\nTwelve studio albums on labels including Sub Pop, Interscope, and Yep Roc — among them *Smoke 'em If You Got 'em* (1991), *Liquor in the Front* (1994), *Lucky 7* (2002), and *Whole New Life* (2018). The band has toured continuously since its formation.",
  "the-romantics":
    "American rock band formed in Detroit in 1977. Original lineup: Wally Palmar (vocals/rhythm guitar), Mike Skill (guitar/bass), Rich Cole (bass/guitar), and Jimmy Marinos (drums/vocals). Distinguished by power-pop hooks, matching red leather suits, and a 1960s British Invasion influence.\n\nSix studio albums starting with the 1980 self-titled debut. Best-known singles include \"What I Like About You\" (1980) and \"Talking in Your Sleep\" (1983, from *In Heat*). The band cycled through lineup changes and litigation over royalties for much of the 1990s and 2000s. Reunited in the original-lineup configuration in 2007.",
  "the-suicide-machines":
    "American ska-punk band formed in Detroit in 1991. Long-running lineup: Jay Navarro (vocals, 1991-2002, 2005-present), Dan Lukacinsky (guitar), Royce Nunley (bass, 1996-present), and Ryan Vandeberghe (drums). Style draws on hardcore punk, ska, and pop-punk.\n\nSeven studio albums starting with *Destruction by Definition* (1996). Best-known releases include *Battle Hymns* (1998) and *The Suicide Machines* (2000). The band briefly broke up in 2006 and reformed in 2009.",
  "the-travelin-mccourys":
    "American bluegrass band consisting of brothers Ronnie McCoury (mandolin) and Rob McCoury (banjo) — sons of bluegrass patriarch Del McCoury — plus longtime Del McCoury Band members Jason Carter (fiddle) and Alan Bartram (bass), and guitarist Cody Kilby. The band tours as their own act while also backing their father in the Del McCoury Band.\n\nThree studio albums starting with the self-titled debut (2018), which won the Grammy for Best Bluegrass Album in 2019. The band represents a younger-generation continuation of traditional bluegrass alongside experimental collaborations with jam-band figures.",
  "tom-petty-and-the-heartbreakers":
    "American rock band formed in Gainesville, Florida in 1976 by Tom Petty (vocals/guitar, died 2017). Long-running lineup also included Mike Campbell (lead guitar), Benmont Tench (keyboards), Stan Lynch (drums, 1976-1994), Howie Epstein (bass, 1982-2002, died 2003), and Ron Blair (bass, 1976-1982, 2002-2017). One of the most commercially consistent American rock acts of the 1976-2017 period.\n\nThirteen studio albums plus three Petty solo records. Commercial peak: *Damn the Torpedoes* (1979), *Hard Promises* (1981), *Full Moon Fever* (1989, a solo album), *Into the Great Wide Open* (1991), and *Wildflowers* (1994). Petty also co-founded the Traveling Wilburys (1988-1991). Petty died of an accidental overdose in October 2017. Inducted into the Rock and Roll Hall of Fame in 2002.",
  "tool":
    "American progressive metal band formed in Los Angeles in 1990. Lineup: Maynard James Keenan (vocals), Adam Jones (guitar), Justin Chancellor (bass, since 1995), and Danny Carey (drums). Bassist Paul D'Amour preceded Chancellor. Distinguished by extended song structures, complex time signatures, and visual art produced by Adam Jones.\n\nFive studio albums in 33 years: *Undertow* (1993), *Ænima* (1996), *Lateralus* (2001), *10,000 Days* (2006), and *Fear Inoculum* (2019). The 13-year gap before *Fear Inoculum* was followed by its #1 Billboard debut. Keenan also fronts A Perfect Circle and Puscifer.",
  "trouble":
    "American doom metal band formed in Aurora, Illinois in 1979. Long-running lineup: Eric Wagner (vocals, 1979-1997, 2000-2008, died 2021), Rick Wartell (guitar), Bruce Franklin (guitar), and various rhythm sections. Foundational to American doom metal alongside Saint Vitus and Pentagram.\n\nSeven studio albums starting with *Psalm 9* (1984). Best-known releases include *The Skull* (1985), *Trouble* (1990, produced by Rick Rubin), and *Manic Frustration* (1992). The band's lyrical content originally drew from Christian themes; this distinguished them from peers in the early American doom scene.",
  "type-o-negative":
    "American gothic metal band formed in Brooklyn, New York in 1989. Lineup: Peter Steele (vocals/bass, died 2010), Kenny Hickey (guitar), Josh Silver (keyboards), and Sal Abruscato (drums, 1989-1992, 1999-2003) / Johnny Kelly (drums, 1992-1999, 2003-2010).\n\nSeven studio albums between *Slow, Deep and Hard* (1991) and *Dead Again* (2007). Commercial peak: *Bloody Kisses* (1993, featuring \"Black No. 1\") and *October Rust* (1996). Peter Steele died of heart failure in April 2010 at age 48, ending the band.",
  "u2":
    "Irish rock band formed in Dublin in 1976. Lineup: Bono (Paul Hewson, vocals), the Edge (David Evans, guitar/keyboards), Adam Clayton (bass), and Larry Mullen Jr. (drums). The same four members have been continuous for nearly 50 years — exceptionally rare for a major rock band.\n\nFourteen studio albums between *Boy* (1980) and *Songs of Surrender* (2023). Commercial peak: *The Joshua Tree* (1987), one of the best-selling albums of all time at 25 million-plus copies sold. Subsequent peaks include *Achtung Baby* (1991), *All That You Can't Leave Behind* (2000), and *How to Dismantle an Atomic Bomb* (2004). Twenty-two Grammy Awards. Inducted into the Rock and Roll Hall of Fame in 2005.",
  "voodoo-glow-skulls":
    "American ska-punk band formed in Riverside, California in 1988. Long-running lineup: Frank Casillas (vocals, 1988-2018), Eddie Casillas (guitar), Jorge Casillas (bass), and a horns-driven backing band. Three of the band's members are brothers.\n\nNine studio albums starting with *Who Is, This Is?* (1993). Best-known releases include *Firme* (1995), *Baile de los Locos* (1997), and *The Band Geek Mafia* (1998). Released primarily on Epitaph during the late-1990s third-wave ska revival. Continues to tour with various vocalists after Frank Casillas's 2018 departure.",
  "xdisciplex-ad":
    "American Christian hardcore band formed in Erie, Pennsylvania in 1991. Long-running lineup centered on vocalist Joel Sechrist. Associated with the straightedge and \"Spirit-filled hardcore\" scenes.\n\nSix studio albums starting with *Heaven for the Weak* (1996). Best-known releases include *Bear the Burden of a Thousand Generations* (1997) and *Doxology* (1998). Released primarily on Tooth & Nail and Solid State Records.",
  "yes":
    "English progressive rock band formed in London in 1968. Long-running lineup centered on bassist Chris Squire (1968-2015, died 2015). Other key members included vocalist Jon Anderson (1968-1980, 1983-2008, 2016-present), guitarist Steve Howe (1970-1981, 1991-present), keyboardist Rick Wakeman (1971-1974, 1976-1980, 1995-1997, 2002-2004), and drummers Bill Bruford and Alan White.\n\nTwenty-three studio albums starting with *Yes* (1969). Critical peak: *The Yes Album* (1971), *Fragile* (1971), *Close to the Edge* (1972), and *Going for the One* (1977). Commercial second act: *90125* (1983, featuring \"Owner of a Lonely Heart\"). Inducted into the Rock and Roll Hall of Fame in 2017.",
  "311":
    "American rock band formed in Omaha, Nebraska in 1988. Lineup: Nick Hexum (vocals/guitar), SA Martinez (vocals/turntables), Tim Mahoney (guitar), Aaron \"P-Nut\" Wills (bass), and Chad Sexton (drums). The five-piece lineup has been continuous since 1992. Style fuses rock, reggae, hip-hop, and funk.\n\nFourteen studio albums starting with *Music* (1993). Commercial breakthrough: the 1995 self-titled \"Blue Album,\" which sold over 3 million copies on the strength of \"Down\" and \"All Mixed Up.\" Subsequent peaks: *Transistor* (1997) and *Soundsystem* (1999). Hosts the annual \"311 Day\" concerts on March 11 (3/11).",
  "ace-frehley":
    "American guitarist born April 27, 1951, in The Bronx, New York. Founding lead guitarist of KISS (1973-1982, 1996-2002), where he performed as the Spaceman. Launched a parallel solo career during his first KISS departure.\n\nReleased nine solo studio albums starting with the eponymous *Ace Frehley* (1978) — one of four solo KISS albums released simultaneously. Subsequent solo work includes *Frehley's Comet* (1987), *Anomaly* (2009), and *Origins Vol. 1* (2016, a covers album). Has performed regularly as a solo artist since departing KISS for the second time in 2002.",
  "adolescents":
    "American punk rock band formed in Fullerton, California in 1980. Original lineup: Tony Cadena (vocals), Frank Agnew (guitar), Rikk Agnew (guitar), Steve Soto (bass, died 2018), and Casey Royer (drums). Foundational to the Orange County hardcore scene; their 1981 self-titled debut (sometimes called the \"Blue Album\") is widely considered a classic of the era.\n\nEleven studio albums total. After multiple breakups in the 1980s and 1990s, the band reunited periodically and stabilized in the 2000s. Bassist Steve Soto died in 2018; the band has continued with new bassists.",
  "alabama":
    "American country band formed in Fort Payne, Alabama in 1969 (originally as Wildcountry). Long-running lineup: cousins Randy Owen (vocals/guitar), Teddy Gentry (bass/vocals), and Jeff Cook (guitar/fiddle/keyboards, 1969-2017, died 2022). Among the most commercially successful country acts of the 1980s.\n\nReleased 21 studio albums between *My Home's in Alabama* (1980) and *Southern Drawl* (2015). Won the Country Music Association's Entertainer of the Year three years in a row (1982-1984). Career sales exceed 75 million units. Inducted into the Country Music Hall of Fame in 2005.",
  "ani-difranco":
    "American singer-songwriter born September 23, 1970, in Buffalo, New York. Founded her own independent label, Righteous Babe Records, in 1990 — a pioneering move that allowed her to maintain creative control across her entire career.\n\nReleased over 20 studio albums starting with the self-titled debut (1990). Critical peak: *Out of Range* (1994), *Not a Pretty Girl* (1995), *Dilate* (1996), and *Little Plastic Castle* (1998). DiFranco's confessional, politically engaged songwriting and DIY business model made her a defining figure in 1990s alternative folk.",
  "armored-saint":
    "American heavy metal band formed in Los Angeles in 1982. Long-running lineup: John Bush (vocals, 1982-1990, 1999-present), Joey Vera (bass), Phil Sandoval (guitar), Gonzo Sandoval (drums), and Jeff Duncan (guitar, since 1990). Bush left in 1990 to join Anthrax (until 2005) before rejoining Armored Saint.\n\nEight studio albums starting with *March of the Saint* (1984). Best-known releases include *Delirious Nomad* (1985), *Raising Fear* (1987), and *Symbol of Salvation* (1991). Guitarist Dave Prichard died of leukemia in 1990; the band reformed with Duncan replacing him.",
  "asia":
    "English progressive rock supergroup formed in London in 1981. Original lineup: John Wetton (vocals/bass, formerly of King Crimson), Steve Howe (guitar, formerly of Yes), Geoff Downes (keyboards, formerly of Yes and the Buggles), and Carl Palmer (drums, formerly of Emerson, Lake & Palmer).\n\nFifteen studio albums starting with the self-titled debut (1982), which sold over 10 million copies and produced the top-10 hit \"Heat of the Moment.\" Subsequent releases — *Alpha* (1983), *Astra* (1985) — did not match the debut's commercial impact. Wetton died in 2017; Howe departed in 2013. The band has continued with various lineups.",
  "be-taylor":
    "American singer (1953-2016). B.E. Taylor (William Berton Edward Taylor) led the B.E. Taylor Group, a Pittsburgh-area rock band that gained regional success in the early 1980s. Later in his career, he became known for his hugely popular annual Christmas concert tours throughout western Pennsylvania, Ohio, and West Virginia.\n\nReleased multiple studio albums under both B.E. Taylor Group and as a solo artist, including *Innermission* (1984) and the *Christmas* album series (1996-2010). Taylor died of brain cancer in 2016; tribute concerts featuring his backing band have continued in his honor.",
  "barenaked-ladies":
    "Canadian rock band formed in Scarborough, Ontario in 1988. Original lineup: Steven Page (vocals/guitar, 1988-2009), Ed Robertson (vocals/guitar), Jim Creeggan (bass), Andrew Creeggan (keyboards, 1988-1995), and Tyler Stewart (drums). Kevin Hearn replaced Andrew Creeggan on keyboards in 1995.\n\nSixteen studio albums starting with *Gordon* (1992). Commercial peak in the US: *Stunt* (1998), featuring the #1 hit \"One Week.\" Robertson and Page co-wrote the theme song for *The Big Bang Theory* (2007). Page departed in 2009; the band has continued as a Robertson-led quartet.",
  "beck":
    "American singer-songwriter and multi-instrumentalist born July 8, 1970, in Los Angeles. Known by the mononym Beck (originally Beck Hansen). His genre-fluid approach has spanned alternative rock, folk, hip-hop, electronic, country, and orchestral music.\n\nFourteen studio albums between *Golden Feelings* (1993) and *Hyperspace* (2019). Commercial breakthrough: \"Loser\" from *Mellow Gold* (1994). Critical peaks include *Odelay* (1996), *Mutations* (1998), *Midnite Vultures* (1999), *Sea Change* (2002), and *Morning Phase* (2014, which won the Grammy for Album of the Year). Eight Grammy Awards.",
  "belinda-carlisle":
    "American singer born August 17, 1958, in Hollywood, California. First gained prominence as lead vocalist of the Go-Go's (1978-1985, intermittent reunions thereafter) before launching a solo career.\n\nSeven solo studio albums starting with *Belinda* (1986). Commercial peak: *Heaven on Earth* (1987, featuring \"Heaven Is a Place on Earth\" — her only US #1) and *Runaway Horses* (1989). Subsequent career has shifted toward European markets and adult-contemporary territory. Continues to record and tour.",
  "bert-kreischer":
    "American stand-up comedian and podcaster born November 3, 1972, in Tampa, Florida. Achieved internet fame in 1997 when *Rolling Stone* named him \"the Top Partier at the Number One Party School in the Country\" while attending Florida State University.\n\nReleased multiple comedy specials including *Comfortably Dumb* (2009), *The Machine* (2016), *Secret Time* (2018), and *Hey Big Boy* (2020). Hosts the podcast *Bertcast* and co-hosts *2 Bears, 1 Cave* with Tom Segura. The 2023 feature film *The Machine* was based on his most famous bit.",
  "big-sandy":
    "American singer Robert Williams (born 1965) who leads the rockabilly/Western swing band Big Sandy and His Fly-Rite Boys. Based in Anaheim, California. Active in the rockabilly revival scene since the late 1980s.\n\nMore than a dozen albums on labels including HighTone, Yep Roc, and Sun. Best-known releases include *Jumping from 6 to 6* (1994), *Swingin' West* (1995), and *Night Tide* (2000). The band has been a fixture on the international rockabilly festival circuit for over three decades.",
  "billy-squier":
    "American rock musician born May 12, 1950, in Wellesley Hills, Massachusetts. First gained attention with bands Piper and the Sidewinders before launching a solo career. Distinguished by guitar-driven hard-rock production that bridged late-1970s arena rock with early-1980s MTV aesthetics.\n\nNine solo studio albums between *The Tale of the Tape* (1980) and *Happy Blue* (1998). Commercial peak: *Don't Say No* (1981, featuring \"The Stroke\" and \"Lonely Is the Night\") and *Emotions in Motion* (1982). The 1984 \"Rock Me Tonite\" music video — widely mocked at the time — is sometimes credited as derailing his commercial momentum.",
  "black-flag":
    "American hardcore punk band formed in Hermosa Beach, California in 1976 by guitarist Greg Ginn. Foundational to the development of American hardcore punk. Multiple vocalists during the band's history; Henry Rollins (1981-1986) is the best-known.\n\nSeven studio albums between *Damaged* (1981) and *In My Head* (1985). Co-founded SST Records, which became one of the most influential American indie labels. The original lineup disbanded in 1986; Ginn revived the band in 2003 and 2013 with varying lineups. The band's logo — four black bars in a row — is among the most recognized in punk rock.",
  "blindside":
    "Swedish Christian post-hardcore band formed in Stockholm in 1994. Lineup: Christian Lindskog (vocals), Simon Grenehed (guitar), Tomas Näslund (bass), and Marcus Dahlström (drums). Style spans melodic hardcore, post-hardcore, and metalcore.\n\nSeven studio albums between 1997 and 2011, including *A Thought Crushed My Mind* (2000), *Silence* (2002, featuring \"Pitiful\"), and *About a Burning Fire* (2004). Released primarily on Solid State and Elektra. The band has been on hiatus since 2011.",
  "blondie":
    "American rock band formed in New York City in 1974. Long-running lineup centered on Debbie Harry (vocals), Chris Stein (guitar), and Clem Burke (drums, 1975-2025, died 2025). Pioneers of new wave; key in popularizing punk-rock-influenced aesthetics for mainstream pop audiences.\n\nEleven studio albums starting with the 1976 self-titled debut. Commercial peak: *Parallel Lines* (1978, featuring \"Heart of Glass\" and \"One Way or Another\"), *Eat to the Beat* (1979), and *Autoamerican* (1980, featuring the band's pioneering hip-hop crossover \"Rapture\"). The band broke up in 1982 and reunited in 1997. Inducted into the Rock and Roll Hall of Fame in 2006.",
  "blue-man-group":
    "American performance art collective founded in New York City in 1987 by Chris Wink, Matt Goldman, and Phil Stanton. Performers appear painted blue and bald (using latex skullcaps) and rarely speak; the act combines percussion-driven music, comedy, and audience interaction.\n\nReleased four studio albums starting with *Audio* (1999), which received a Grammy nomination. Subsequent albums include *The Complex* (2003, featuring Tracy Bonham, Dave Matthews, and Esthero), *How to Be a Megastar Live!* (2008), and *Three* (2016). Long-running theatrical residencies in Las Vegas, New York, Boston, Chicago, Orlando, Berlin, and elsewhere.",
  "bob-seger-the-silver-bullet-band":
    "American rock band led by Bob Seger (born May 6, 1945, in Dearborn, Michigan). Seger formed the Silver Bullet Band in 1973 after a series of earlier groups; long-running lineup included Drew Abbott (guitar), Robyn Robbins (keyboards), Chris Campbell (bass), and Charlie Allen Martin (drums).\n\nReleased 11 studio albums between *Live Bullet* (1976) and *Ride Out* (2014). Commercial peak: *Night Moves* (1976), *Stranger in Town* (1978, featuring \"Old Time Rock and Roll\"), *Against the Wind* (1980, a #1 album), and *The Distance* (1982). Seger announced retirement from touring in 2019. Inducted into the Rock and Roll Hall of Fame in 2004.",
  "bowling-for-soup":
    "American pop-punk band formed in Wichita Falls, Texas in 1994. Long-running lineup: Jaret Reddick (vocals/guitar), Chris Burney (guitar), Erik Chandler (bass), and Gary Wiseman (drums). Distinguished by humorous lyrics and pop-culture references.\n\nTwelve studio albums starting with *Rock On Honorable Ones!!!* (1998). Commercial peak: *Drunk Enough to Dance* (2002, featuring \"Girl All the Bad Guys Want\") and *A Hangover You Don't Deserve* (2004, featuring \"1985\"). The band has remained active with extensive touring through the 2020s.",
  "boz-scaggs":
    "American singer-songwriter and guitarist born June 8, 1944, in Canton, Ohio. First gained attention as a member of the Steve Miller Band (1967-1969) before launching a successful solo career.\n\nReleased over 20 solo studio albums starting with *Boz Scaggs* (1969). Commercial peak: *Silk Degrees* (1976), which sold over 5 million copies on the strength of \"Lowdown,\" \"Lido Shuffle,\" and \"It's Over.\" Subsequent work has shifted toward jazz, blues, and standards interpretation, particularly on the *But Beautiful* (2003) and *Speak Low* (2008) standards albums.",
  "bracket":
    "American pop-punk band formed in Forestville, California in 1992. Long-running lineup: Marty Gregori (vocals/guitar), Larry Tinney (guitar), Zack Charlos (bass), and Ray Castro (drums). Closely associated with Caroline Records and later Fat Wreck Chords.\n\nEight studio albums starting with *924 Forestville St.* (1994). Best-known releases include *4-Wheel Vibe* (1995), *Novelty Forever* (1997), and *Hold Your Applause* (2014). Released primarily on Fat Wreck Chords and Take a Chance Records.",
  "brad-paisley":
    "American country singer-songwriter born October 28, 1972, in Glen Dale, West Virginia. Known for his technically accomplished guitar playing and humor-driven songwriting.\n\nReleased 13 studio albums starting with *Who Needs Pictures* (1999). Commercial peak: *Mud on the Tires* (2003), *Time Well Wasted* (2005), *American Saturday Night* (2009), and *This Is Country Music* (2011). Three Grammy Awards. Co-hosted the Country Music Association Awards (CMAs) annually with Carrie Underwood from 2008 to 2018.",
  "brimstone-coven":
    "American doom rock band formed in Wheeling, West Virginia in 2011. Lineup: John \"Chevy\" Williams (vocals), Corey Roth (guitar), Andrew D'Cagna (bass/keyboards/vocals), and Justin Wood (drums). Style draws on 1970s heavy psych, Sabbath-influenced doom, and folk/occult lyrical themes.\n\nFour studio albums starting with the self-titled debut (2012). Subsequent releases include *Black Magic* (2016), *The Woes of a Mortal Earth* (2020), and *The Children of a Past Forgotten* (2024). Released primarily on Metal Blade Records.",
  "brooks-dunn":
    "American country duo of Kix Brooks (born May 12, 1955, in Shreveport, Louisiana) and Ronnie Dunn (born June 1, 1953, in Coleman, Texas). Active 1990-2010, reunited 2015 for select projects. One of the best-selling country duos in history.\n\nReleased ten studio albums between *Brand New Man* (1991) and *#1s... and Then Some* (2009). Commercial peak: *Waitin' on Sundown* (1994), *Borderline* (1996), and *If You See Her* (1998). Won the Country Music Association's Vocal Duo of the Year 14 years in a row (1992-2006). Each pursued solo work after the 2010 split.",
  "buckonine":
    "American ska-punk band formed in San Diego in 1991. Long-running lineup: Jon Pebsworth (vocals), Tony Curry (drums), Daniel Albert (bass), and a horns section. Style draws on traditional ska, dancehall, and pop-punk.\n\nSeven studio albums starting with *Songs in the Key of Bree* (1995). Best-known releases include *Twenty-Eight Teeth* (1997) and *Libido* (1999). Released primarily on Taang!, Stubborn, and BYO Records.",
  "buddy-guy":
    "American blues guitarist and vocalist born July 30, 1936, in Lettsworth, Louisiana. Foundational influence on the development of electric blues guitar, with a direct influence on Eric Clapton, Jimi Hendrix, Stevie Ray Vaughan, and Jeff Beck.\n\nReleased over 30 studio albums starting in 1959. Commercial peak: *Damn Right, I've Got the Blues* (1991), which began a long-running creative second act on Silvertone Records and continued through *The Blues Don't Lie* (2022). Eight Grammy Awards. Inducted into the Rock and Roll Hall of Fame in 2005.",
  "cactus":
    "American hard rock supergroup formed in 1969 by Carmine Appice (drums) and Tim Bogert (bass) after the breakup of Vanilla Fudge. Original lineup also included Rusty Day (vocals) and Jim McCarty (guitar). Considered an early proto-metal act, with Bogert and Appice's rhythm section a major influence on subsequent hard-rock players.\n\nFour studio albums in the original run: *Cactus* (1970), *One Way... or Another* (1971), *Restrictions* (1971), and *'Ot 'N' Sweaty* (1972). Bogert and Appice departed in 1972 to form Beck, Bogert & Appice with Jeff Beck. Cactus has been periodically reformed in various configurations since 2006.",
  "cannibal-corpse":
    "American death metal band formed in Buffalo, New York in 1988. Long-running lineup centered on Alex Webster (bass) and Paul Mazurkiewicz (drums) — both since formation. Vocalists: Chris Barnes (1988-1995) and George \"Corpsegrinder\" Fisher (1995-present). Among the most commercially successful and influential death metal acts in history.\n\nFifteen studio albums starting with *Eaten Back to Life* (1990). Best-known releases include *Tomb of the Mutilated* (1992), *The Bleeding* (1994), *Vile* (1996), and *Kill* (2006). The band's graphic album artwork and lyrical content have led to bans of their material in multiple countries.",
  "cat-stevens":
    "British singer-songwriter born Steven Demetre Georgiou in 1948 in London. Performed and recorded as Cat Stevens from 1966 to 1978, then converted to Islam, changed his name to Yusuf Islam, and stepped back from secular music for two decades. Returned to recording in 2006, performing variously as Yusuf, Yusuf / Cat Stevens, and Cat Stevens again.\n\nReleased ten studio albums in the Cat Stevens era. Commercial peak: *Tea for the Tillerman* (1970), *Teaser and the Firecat* (1971), *Catch Bull at Four* (1972), and *Buddha and the Chocolate Box* (1974). Notable singles include \"Wild World,\" \"Morning Has Broken,\" \"Peace Train,\" \"Father and Son,\" and \"Moonshadow.\" Inducted into the Rock and Roll Hall of Fame in 2014.",
  "charger":
    "American hard rock band formed in Oakland, California in 2018 by Matt Freeman (bass/vocals, also of Rancid and Operation Ivy) and Andrew McGee (guitar/vocals). Style draws on Motörhead-influenced rock, hardcore punk, and heavy metal.\n\nTwo studio albums: the self-titled debut (2020) and *Warhorse* (2022). Released on Pirates Press Records. Active intermittently between Freeman's commitments with Rancid.",
  "christopher-cross":
    "American singer-songwriter born May 3, 1951, in San Antonio, Texas. Commercial breakthrough came with his 1979 self-titled debut, which won the Grammy for Album of the Year, Record of the Year (\"Sailing\"), Song of the Year, and Best New Artist — a four-Grammy sweep no other artist had previously accomplished in a single night.\n\nReleased 12 studio albums between 1979 and 2017. Commercial peak singles: \"Ride Like the Wind\" and \"Sailing\" (1980), and \"Arthur's Theme (Best That You Can Do)\" from the 1981 film *Arthur* (which won the Academy Award for Best Original Song).",
  "civ":
    "American hardcore band formed in New York City in 1994 by vocalist Civ (Anthony Civarelli, formerly of Gorilla Biscuits), with members of NYC hardcore peers Quicksand, Side By Side, and Burn. Lineup also included Sammy Siegler (drums), Arthur Smilios (bass), and Charlie Garriga (guitar).\n\nTwo studio albums: *Set Your Goals* (1995) and *Thirteen Day Getaway* (1998). The 1995 single \"Can't Wait One Minute More\" received MTV rotation. The band has been on extended hiatus since 1998; members reunited periodically with the related Gorilla Biscuits reunions.",
  "coal-chamber":
    "American nu-metal band formed in Los Angeles in 1993. Lineup: Dez Fafara (vocals), Meegs Rascón (guitar), Rayna Foss (bass), and Mike Cox (drums). Often associated with the late-1990s nu-metal wave alongside Korn, Limp Bizkit, and Sevendust.\n\nFour studio albums between 1997 and 2015: the self-titled debut (1997), *Chamber Music* (1999), *Dark Days* (2002), and *Rivals* (2015). Fafara left in 2002 to form DevilDriver; the band briefly reunited from 2011 to 2016. Currently on hiatus.",
  "culture-club":
    "English new wave band formed in London in 1981. Lineup: Boy George (George O'Dowd, vocals), Roy Hay (guitar/keyboards), Mikey Craig (bass), and Jon Moss (drums). Defined by Boy George's gender-blurring fashion sense and the band's pop-soul-reggae fusion.\n\nSeven studio albums between *Kissing to Be Clever* (1982) and *Life* (2018). Commercial peak: *Colour by Numbers* (1983, featuring \"Karma Chameleon\") and *Waking Up with the House on Fire* (1984). The band split in 1986 amid Boy George's heroin addiction, reunited periodically through the 1990s and 2000s.",
  "dag-nasty":
    "American hardcore punk band formed in Washington, D.C. in 1985 by Brian Baker (guitar, formerly of Minor Threat). Multiple vocalists during the band's run: Shawn Brown (briefly), Dave Smalley (1985-1987), Peter Cortner (1987-1989), and Roger Marbury (later).\n\nFive studio albums between *Can I Say* (1986) and *Cold Heart* (2002). Best-known releases include *Wig Out at Denko's* (1987) and *Field Day* (1988). The band has reunited periodically since 2002. Baker has been the only continuous member throughout.",
  "dale-watson-and-his-lone-stars":
    "American country band led by Dale Watson (born October 7, 1962, in Birmingham, Alabama). Watson has positioned himself as a defender of traditional honky-tonk and Bakersfield-sound country in opposition to mainstream Nashville production trends.\n\nReleased over 20 studio albums starting with *Cheatin' Heart Attack* (1995). Best-known releases include *I Hate These Songs* (1997), *From the Cradle to the Grave* (2002), and *Call Me Insane* (2015). Has owned and operated the Continental Club, a major Austin music venue, and the Big T Roadhouse in St. Hedwig, Texas.",
  "dar-williams":
    "American folk singer-songwriter born April 19, 1967, in Mount Kisco, New York. Associated with the Boston folk scene of the early 1990s alongside Patty Griffin, Jonatha Brooke, and Catie Curtis.\n\nReleased ten studio albums starting with *The Honesty Room* (1993). Best-known releases include *Mortal City* (1996), *End of the Summer* (1997), and *The Green World* (2000). Released primarily on Razor & Tie and Razor & Tie's Burnside imprint. Continues to record and tour.",
  "daryl-hall-john-oates":
    "American pop duo of Daryl Hall (born 1946) and John Oates (born 1948), formed in Philadelphia in 1970. One of the best-selling musical duos of all time, with estimated worldwide sales over 80 million units.\n\nReleased 18 studio albums between *Whole Oats* (1972) and *Home for Christmas* (2006). Commercial peak: *Voices* (1980), *Private Eyes* (1981), *H2O* (1982, featuring \"Maneater\"), and *Big Bam Boom* (1984). Six #1 US singles. Inducted into the Rock and Roll Hall of Fame in 2014. The duo legally dissolved their partnership in acrimony in 2023.",
  "death-angel":
    "American thrash metal band formed in Concord, California in 1982 by cousins Mark Osegueda (vocals), Rob Cavestany (guitar), Gus Pepa (guitar, original), Dennis Pepa (bass), and Andy Galeon (drums) — all of Filipino descent, all related. The original lineup formed when the members were teenagers.\n\nNine studio albums starting with *The Ultra-Violence* (1987). Best-known releases include *Frolic Through the Park* (1988), *Act III* (1990), and the post-reunion *Killing Season* (2008) and *The Evil Divide* (2016). The band disbanded in 1991 after a tour bus crash injured drummer Andy Galeon; reformed in 2001.",
  "depeche-mode":
    "English electronic band formed in Basildon, Essex in 1980. Long-running lineup: Dave Gahan (vocals), Martin Gore (keyboards/guitar/vocals), and Andy Fletcher (keyboards, died 2022). Early member Vince Clarke departed in 1981 to form Yazoo and later Erasure. Foundational to the development of synth-pop and dark electronic music.\n\nFifteen studio albums starting with *Speak & Spell* (1981). Commercial peak: *Music for the Masses* (1987), *Violator* (1990, featuring \"Personal Jesus\" and \"Enjoy the Silence\"), and *Songs of Faith and Devotion* (1993). Fletcher died in 2022; the band continued as a Gahan/Gore duo with *Memento Mori* (2023). Inducted into the Rock and Roll Hall of Fame in 2020.",
};

async function main() {
  const dryRun = process.argv.includes("--dry-run");
  const force = process.argv.includes("--force");
  const { containers } = await import("../lib/cosmos");
  const { getStoredArtist } = await import("../lib/artists");

  let written = 0;
  let skipped = 0;
  let missing = 0;

  for (const [slug, description] of Object.entries(DESCRIPTIONS)) {
    const existing = await getStoredArtist(slug);
    if (!existing) {
      console.log(`✗ ${slug}: no stored doc found`);
      missing += 1;
      continue;
    }
    if (existing.description && !force) {
      console.log(`↷ ${slug}: already has description — skipping`);
      skipped += 1;
      continue;
    }
    if (dryRun) {
      console.log(`◌ ${slug}: would write ${description.length} chars`);
      written += 1;
      continue;
    }
    const updated = {
      ...existing,
      description,
      updatedAt: new Date().toISOString(),
    };
    await containers.artists.item(slug, slug).replace(updated);
    console.log(`✓ ${slug}: ${description.length} chars`);
    written += 1;
  }

  console.log(`\nDone. written=${written} skipped=${skipped} missing=${missing}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
