import { config as loadEnv } from "dotenv";
loadEnv({ path: ".env.local" });

const DESCRIPTIONS: Record<string, string> = {
  "the-aquabats":
    "American ska-punk band formed in Huntington Beach, California in 1994 (officially stylized The Aquabats!). Performs in matching superhero-style costumes with stage names like The MC Bat Commander, Crash McLarson, and Jimmy the Robot. Original drummer Travis Barker (later of Blink-182) played in the band 1996-1998.\n\nReleased seven studio albums between *The Return of the Aquabats* (1996) and *Kooky Spooky... in Stereo!* (2018). Toured extensively on the Warped Tour circuit. Launched *The Aquabats! Super Show!* (The Hub, 2012-2014; YouTube, 2018-present), a live-action superhero comedy series.",
  "the-ataris":
    "American pop-punk band formed in Anderson, Indiana in 1995. Long-running lineup centered on Kris Roe (vocals/guitar). Distinguished by their melodic pop-punk songwriting drawing on the Get Up Kids and Saves the Day.\n\nReleased six studio albums between *Anywhere But Here* (1997) and *Welcome the Night* (2007). Commercial peak: *So Long, Astoria* (2003), featuring the band's gold-certified cover of Don Henley's \"The Boys of Summer.\"",
  "the-australian-pink-floyd-show":
    "Australian Pink Floyd tribute band formed in Adelaide in 1988. Among the longest-running and most commercially successful Pink Floyd tribute acts in the world. Distinguished by their elaborate stage productions matching the original Pink Floyd's pyramid screens, lasers, and inflatable pigs.\n\nDavid Gilmour invited them to perform at his 50th birthday celebration in 1996. The band has continued to tour internationally, performing classic Pink Floyd material with rotating personnel.",
  "the-avett-brothers":
    "American folk-rock band formed in Concord, North Carolina in 2000. Long-running lineup: brothers Scott Avett (banjo/vocals) and Seth Avett (guitar/vocals), plus Bob Crawford (bass, since 2001) and Joe Kwon (cello, since 2007). Distinguished by their fusion of bluegrass instrumentation with punk-rock energy and indie-rock songwriting.\n\nReleased 11 studio albums between *Country Was* (2002) and *The Avett Brothers* (2024). Critical peak: *I and Love and You* (2009, produced by Rick Rubin), *The Carpenter* (2012), and *Magpie and the Dandelion* (2013).",
  "the-band":
    "Canadian-American rock band formed in Toronto in 1968 (as a continuation of the Hawks, the longtime backing band for Ronnie Hawkins and later Bob Dylan). Lineup: Robbie Robertson (guitar, 1943-2023), Levon Helm (drums/vocals, 1940-2012), Rick Danko (bass/vocals, 1942-1999), Richard Manuel (piano/vocals, 1943-1986), and Garth Hudson (keyboards, 1937-2025). Foundational influence on roots rock and Americana.\n\nReleased 10 studio albums between *Music from Big Pink* (1968) and *Jubilation* (1998). Critical peak: *Music from Big Pink* and *The Band* (1969). Martin Scorsese's documentary *The Last Waltz* (1978) captured their 1976 farewell concert. Inducted into the Rock and Roll Hall of Fame in 1994.",
  "the-band-from-utopia":
    "American rock band formed in 1992 by former members of Frank Zappa's mid-1970s and 1980s touring bands. Lineup has included Mike Keneally, Tommy Mars, Arthur Barrow, Robert Martin, Ed Mann, and other Zappa alumni. Performs original Zappa repertoire from those eras.\n\nReleased the live album *A Tribute to the Music of Frank Zappa* (1996). Has performed sporadic tribute concerts and tours featuring rotating lineups of Zappa-band alumni.",
  "the-black-crowes":
    "American rock band formed in Marietta, Georgia in 1984. Long-running lineup centered on brothers Chris Robinson (vocals) and Rich Robinson (guitar). Distinguished by their throwback Southern-rock-meets-Faces/Stones aesthetic during the early-1990s alternative-rock dominance.\n\nReleased nine studio albums between *Shake Your Money Maker* (1990) and *Happiness Bastards* (2024). Commercial peak: *Shake Your Money Maker* (5x platinum, featuring \"Hard to Handle\" and \"She Talks to Angels\") and *The Southern Harmony and Musical Companion* (1992, #1 on the Billboard 200). The Robinson brothers have famously feuded throughout the band's history.",
  "the-blues-brothers":
    "American R&B revue formed in 1978 by *Saturday Night Live* cast members Dan Aykroyd and John Belushi (1949-1982). Originally a recurring SNL sketch (1976-1979) before launching the recording and touring band with a backing ensemble of veteran R&B session musicians including Steve Cropper, Donald \"Duck\" Dunn, and Tom Malone.\n\nReleased *Briefcase Full of Blues* (1978, #1 on the Billboard 200) and the soundtrack to the *The Blues Brothers* film (1980, directed by John Landis). Belushi died in 1982 of a drug overdose; Aykroyd has continued the project with various replacement \"Blues Brothers\" including Jim Belushi (John's brother) and John Goodman.",
  "the-breeders":
    "American alternative rock band formed in 1989 by Pixies bassist Kim Deal and Throwing Muses guitarist Tanya Donelly. Long-running classic lineup historically: Kim Deal (vocals/guitar), Kelley Deal (guitar, Kim's twin sister, joined 1992), Josephine Wiggs (bass), and Jim Macpherson (drums). Donelly left for Belly in 1992.\n\nReleased five studio albums between *Pod* (1990) and *All Nerve* (2018). Commercial peak: *Last Splash* (1993, featuring \"Cannonball\") at the height of the post-Pixies / pre-Pixies-reunion alternative-rock boom.",
  "the-broadway-singers-orchestra":
    "Studio ensemble used for budget-label compilations of Broadway show tunes during the 1950s-1970s LP era. Like many similarly-named studio orchestras (the Living Strings, the Mantovani Orchestra), the Broadway Singers & Orchestra was a marketing name rather than a fixed performing ensemble.\n\nReleased numerous compilation LPs of show-tune medleys on labels including RCA Camden and Pickwick. Records credited to this name typically feature uncredited session musicians performing then-current Broadway hits.",
  "the-brothers-johnson":
    "American funk/disco duo of brothers George Johnson (guitar/vocals, b. 1953) and Louis Johnson (bass/vocals, 1955-2015). Discovered by Quincy Jones (who first hired them as session musicians on his solo albums), who produced all of their commercial-peak releases.\n\nReleased six studio albums between *Look Out for #1* (1976) and *Out of Control* (1984). Commercial peak: *Right on Time* (1977, featuring \"Strawberry Letter 23\") and *Blam!!* (1978). Louis Johnson's slap-bass technique was foundational; he played the bass on Michael Jackson's *Thriller* (1982) and *Off the Wall* (1979). Louis Johnson died in 2015.",
  "the-business":
    "English Oi! / punk rock band formed in Lewisham in 1979. Long-running lineup centered on Micky Fitz (vocals, 1958-2016) and Steve Whale (guitar). Among the foundational bands of the early-1980s Oi! scene alongside Cock Sparrer, Cockney Rejects, and the Angelic Upstarts.\n\nReleased over a dozen studio albums between *Suburban Rebels* (1983) and *Mob Mentality* (2016, split with Cock Sparrer). Critical peak: *Welcome to the Real World* (1988) and *Saturday's Heroes* (1996). Micky Fitz died in 2016 of cancer.",
  "the-catalogs":
    "American doo-wop and R&B vocal group formed in the late 1950s. Limited public documentation; like many small doo-wop acts of the era, the Catalogs released a handful of singles on smaller labels (often credited variously, with rotating lineups).\n\nThe group's recordings have appeared on doo-wop compilation albums alongside other minor acts of the late-1950s vocal-group era.",
  "the-chariot":
    "American metalcore band formed in Douglasville, Georgia in 2003. Long-running lineup centered on Josh Scogin (vocals, formerly of Norma Jean). Distinguished by their chaotic, dissonant approach to metalcore drawing on Botch, Converge, and the Dillinger Escape Plan.\n\nReleased five studio albums between *Everything Is Alive, Everything Is Breathing, Nothing Is Dead, and Nothing Is Bleeding* (2004) and *One Wing* (2012). The band dissolved in 2013; Scogin has subsequently led '68.",
  "the-charlie-daniels-band":
    "American country/Southern rock band formed in 1971 by Charlie Daniels (1936-2020). Long-running lineup featured Charlie Daniels (vocals/fiddle/guitar) with various supporting personnel. Distinguished by their fusion of Southern rock with country and bluegrass instrumentation, and Daniels's fiddle showcases.\n\nReleased over 25 studio albums between *Te John, Grease, and Wolfman* (1972) and *Beau Weevils* (2018). Best-known recording: \"The Devil Went Down to Georgia\" (1979, from *Million Mile Reflections*, winning the Grammy for Best Country Vocal Performance by a Duo or Group). Inducted into the Country Music Hall of Fame in 2016. Daniels died in 2020 of a hemorrhagic stroke.",
  "the-cheats":
    "American punk rock band formed in Pittsburgh in 2002. Long-running lineup centered on Sean Finnegan (vocals/guitar). Distinguished by their throwback street-punk style drawing on the Ramones, the Saints, and the Dictators.\n\nReleased three studio albums between *Cheap Pills* (2003) and *Pussycats and Rocketships* (2012). Released primarily on Get Hip Recordings.",
  "the-chicks":
    "American country band formed in Dallas in 1989 (officially the Dixie Chicks until 2020, when they shortened the name to The Chicks following the renewed racial-justice movement). Long-running classic lineup: Natalie Maines (vocals, joined 1995), Martie Maguire (fiddle/mandolin), and Emily Strayer (banjo/guitar, the latter two are sisters).\n\nReleased nine studio albums between *Thank Heavens for Dale Evans* (1990) and *Gaslighter* (2020). Commercial peak: *Wide Open Spaces* (1998, 13x platinum), *Fly* (1999, 10x platinum), and *Home* (2002, 6x platinum). After Maines's 2003 anti-Bush comment at a London show triggered a massive country-radio boycott, the band shifted toward broader Americana with *Taking the Long Way* (2006, Grammy for Album of the Year). 13 Grammy Awards.",
  "the-chipmunks":
    "American animated music group created by Ross Bagdasarian Sr. (1919-1972, performing as David Seville) in 1958. The original Chipmunks — Alvin, Simon, and Theodore — debuted on the novelty recording \"The Chipmunk Song (Christmas Don't Be Late)\" (1958), which won three Grammy Awards. The recordings were created by recording vocals at half speed and playing them back at normal speed to produce the high-pitched effect.\n\nReleased numerous studio albums starting with *Let's All Sing with the Chipmunks* (1959). Bagdasarian Jr. continued the franchise after his father's death, including the 2007 live-action/CGI film *Alvin and the Chipmunks* (which launched a series of three sequels). The Chipmunks have won five Grammy Awards.",
  "the-costello-show":
    "Recording project of Elvis Costello (b. Declan Patrick MacManus, August 25, 1954, Paddington, London). The \"Costello Show\" name was used for the album *King of America* (1986), credited to \"The Costello Show featuring the Attractions and Confederates,\" Costello's first album without the full Attractions backing band as his primary support.\n\n*King of America* featured James Burton (guitar), Jerry Scheff (bass), and Ron Tutt (drums) — Elvis Presley's TCB Band — along with T Bone Burnett as co-producer. Critical peak of Costello's mid-1980s output.",
  "the-datsuns":
    "New Zealand rock band formed in Cambridge, Waikato in 1995 (originally as Trinket). Long-running lineup centered on Dolf de Borst (vocals/bass, performing as Dolf de Datsun). Distinguished by their throwback 1970s hard-rock revivalism in the vein of the Hellacopters and the early Foo Fighters.\n\nReleased seven studio albums between *The Datsuns* (2002) and *Eye to Eye* (2014). Critical peak: *The Datsuns* and *Outta Sight/Outta Mind* (2004, produced by Led Zeppelin's John Paul Jones).",
  "the-dead-daisies":
    "Australian-American rock supergroup formed in Sydney in 2012. Long-running lineup has included David Lowy (rhythm guitar, founder), Doug Aldrich (lead guitar, formerly of Whitesnake/Dio), and various vocalists including John Corabi (formerly of Mötley Crüe), Glenn Hughes (formerly of Deep Purple), and others.\n\nReleased six studio albums between *The Dead Daisies* (2013) and *Light 'Em Up* (2024). Distinguished by their rotating-frontman supergroup format, with the lineup changing significantly between albums.",
  "the-distillers":
    "American punk rock band formed in Los Angeles in 1998. Long-running lineup centered on Brody Dalle (vocals/guitar, b. 1979, Australian). Distinguished by Dalle's raspy vocals and the band's fusion of melodic hardcore with punk and rock.\n\nReleased three studio albums between *The Distillers* (2000) and *Coral Fang* (2003) before going on hiatus. Reunited in 2017 for touring; no new studio album has been released since the reunion. Dalle has subsequently led Spinnerette.",
  "the-doobie-brothers":
    "American rock band formed in San Jose, California in 1970. Long-running lineup has rotated between two distinct configurations: the early Tom Johnston era (1970-1975, with the harder-rock signature sound) and the Michael McDonald era (1975-1982, with the bluer-eyed-soul direction). Both eras' lineups have toured together since 1989.\n\nReleased 15 studio albums between *The Doobie Brothers* (1971) and *Liberté* (2021). Commercial peak: *The Captain and Me* (1973), *What Were Once Vices Are Now Habits* (1974), *Stampede* (1975), and *Minute by Minute* (1978, featuring \"What a Fool Believes,\" winner of the 1980 Grammy for Record of the Year and Song of the Year). Inducted into the Rock and Roll Hall of Fame in 2020.",
  "the-doors-of-the-21st-century":
    "American rock band formed in 2002 by former Doors members Ray Manzarek (keyboards, 1939-2013) and Robby Krieger (guitar). Initially with Ian Astbury (vocals, of The Cult) and Stewart Copeland (drums, of The Police). Distinguished as a continuation/touring tribute to the original Doors after Jim Morrison's 1971 death.\n\nDrummer John Densmore and the Morrison estate sued over the use of the Doors name; the band was renamed Riders on the Storm and later Manzarek-Krieger. Manzarek died in 2013 of cancer; Krieger continues to perform as a solo artist.",
  "the-dynamite-band":
    "Studio rhythm section used by Stax Records and various Memphis-area producers during the late 1960s and early 1970s. Limited public documentation; recordings credited to the Dynamite Band typically appear on soundtrack and compilation albums of Memphis-soul instrumental material.\n\nThe group's lineup is not consistently documented and likely rotated among Memphis session musicians of the period.",
  "the-electric-moog-orchestra":
    "American studio project led by Hugo Montenegro (1925-1981) and other arrangers in the late 1960s and 1970s. Featured Moog synthesizer covers of contemporary pop, classical, and film music. Part of the late-1960s and 1970s \"Moog\" exotica/easy-listening fad sparked by Wendy Carlos's *Switched-On Bach* (1968).\n\nReleased *Music from Star Wars* (1977) and *Music from the Empire Strikes Back* (1980), early Moog-synthesizer covers of John Williams's scores. Records credited to the Electric Moog Orchestra typically feature uncredited Moog players (Mike Melvoin being a likely candidate).",
  "the-english-beat":
    "British 2 Tone ska band formed in Birmingham in 1978 (officially the Beat in the UK; renamed the English Beat for the US market to distinguish from American singer Paul Collins's the Beat). Long-running classic lineup: Dave Wakeling (vocals/guitar), Ranking Roger (vocals, 1963-2019), Andy Cox (guitar), David Steele (bass), Everett Morton (drums), and Saxa (1930-2017, saxophone).\n\nReleased three studio albums during their original run: *I Just Can't Stop It* (1980), *Wha'ppen?* (1981), and *Special Beat Service* (1982). Members went on to form Fine Young Cannibals (Cox and Steele) and General Public (Wakeling and Ranking Roger). Two competing English Beat lineups — Wakeling's American version and Ranking Roger's British version — toured separately for decades; Ranking Roger died in 2019.",
  "the-fabulous-thunderbirds":
    "American blues-rock band formed in Austin, Texas in 1974. Long-running lineup historically centered on Kim Wilson (vocals/harmonica) and Jimmie Vaughan (guitar, brother of Stevie Ray Vaughan, until 1989). The Thunderbirds served as the Antone's nightclub house band during their early years, backing visiting blues legends.\n\nReleased 11 studio albums between *The Fabulous Thunderbirds* (1979) and *Strong Like That* (2016). Commercial peak: *Tuff Enuff* (1986, featuring the title-track hit). Kim Wilson has been the only constant member since the late 1980s.",
  "the-flaming-lips":
    "American rock band formed in Oklahoma City in 1983. Long-running lineup: Wayne Coyne (vocals/guitar), Steven Drozd (multi-instrumentalist, joined 1991), and Michael Ivins (bass). Distinguished by their elaborate live productions (giant balloons, Wayne Coyne's space-bubble stage entrance) and stylistic restlessness across psychedelia, art rock, and experimental rock.\n\nReleased 17 studio albums between *Hear It Is* (1986) and *American Head* (2020). Critical peak: *The Soft Bulletin* (1999), *Yoshimi Battles the Pink Robots* (2002, Grammy for Best Rock Instrumental Performance), *Embryonic* (2009), and *American Head*. Three Grammy Awards.",
  "the-four-lads":
    "Canadian vocal quartet formed in Toronto in 1948. Original lineup: Bernie Toorish (tenor), Connie Codarini (bass), Frank Busseri (baritone), and Jimmy Arnold (lead). Distinguished by their close-harmony pop vocals in the pre-rock-and-roll \"belt\" tradition.\n\nReleased numerous singles starting in the early 1950s. Best-known recordings: \"Moments to Remember\" (1955), \"Standing on the Corner\" (1956), and \"Who Needs You\" (1956). Backed Johnnie Ray on the 1951 #1 \"Cry,\" their first major recording session. Continued performing in revival circuits into the 2000s.",
  "the-get-up-kids":
    "American rock band formed in Kansas City, Kansas in 1995. Long-running lineup: Matt Pryor (vocals/guitar), Jim Suptic (guitar/vocals), Rob Pope (bass), Ryan Pope (drums), and James Dewees (keyboards). Foundational influence on the second-wave emo and pop-punk movements of the late 1990s and early 2000s.\n\nReleased six studio albums between *Four Minute Mile* (1997) and *Problems* (2019). Critical peak: *Something to Write Home About* (1999). Members have led numerous side projects including the New Amsterdams (Pryor), Reggie and the Full Effect (Dewees), and the Architects.",
  "the-gotobeds":
    "American post-punk band formed in Pittsburgh in 2009. Long-running lineup centered on Eli Kasan (vocals). Distinguished by their fusion of post-punk, garage rock, and noise rock drawing on Pavement, Television, and the Fall.\n\nReleased three studio albums between *Poor People Are Revolting* (2014) and *Debt Begins at 30* (2019). Released primarily on Sub Pop Records.",
  "the-grateful-dead":
    "American rock band formed in Palo Alto, California in 1965 (originally as the Warlocks). Long-running classic lineup: Jerry Garcia (vocals/guitar, 1942-1995), Bob Weir (guitar/vocals, b. 1947), Phil Lesh (bass/vocals, 1940-2024), Bill Kreutzmann (drums), and Mickey Hart (drums, since 1967). Pigpen (Ron McKernan, 1945-1973), Keith Godchaux (1948-1980), Brent Mydland (1952-1990), and Vince Welnick (1951-2006) successively played keyboards. The defining band of the American jam-band tradition; their devoted fanbase the \"Deadheads\" pioneered the modern touring-fan culture.\n\nReleased 13 studio albums between *The Grateful Dead* (1967) and *Built to Last* (1989). Critical peak: *American Beauty* (1970) and *Workingman's Dead* (1970). Garcia died in 1995, effectively ending the band; subsequent projects (The Other Ones, The Dead, Furthur, Dead & Company) have continued the catalog. Inducted into the Rock and Roll Hall of Fame in 1994.",
  "the-hu":
    "Mongolian rock band formed in Ulaanbaatar in 2016. Long-running lineup of four members: Gala (lead vocals/morin khuur), Jaya (jaw harp/tsuur/throat singing), Temka (tovshuur/throat singing), and Enkush (morin khuur). Distinguished by their fusion of traditional Mongolian throat singing and instruments (morin khuur fiddle, tovshuur lute) with hard rock and metal.\n\nReleased two studio albums: *The Gereg* (2019, featuring \"Wolf Totem\" and \"Yuve Yuve Yu,\" both of which went viral on YouTube) and *Rumble of Thunder* (2022). Contributed the song \"Sugaan Essena\" to the *Star Wars Jedi: Fallen Order* video game (2019).",
  "the-human-league":
    "British synth-pop band formed in Sheffield in 1977. Long-running classic lineup after a 1980 split: Philip Oakey (vocals), Susan Ann Sulley (vocals, recruited from a discothèque), Joanne Catherall (vocals, also recruited from a discothèque), Jo Callis (synthesizers), Ian Burden (bass synth), and Philip Adrian Wright (slides/synthesizers). Distinguished by their early all-electronic instrumentation.\n\nReleased nine studio albums between *Reproduction* (1979) and *Credo* (2011). Commercial peak: *Dare* (1981, featuring the international #1 \"Don't You Want Me\"). Won the 1983 Grammy for Best New Artist. Continues to tour with Oakey, Sulley, and Catherall.",
  "the-icarus-line":
    "American rock band formed in Los Angeles in 1998. Long-running lineup centered on Joe Cardamone (vocals/guitar, b. 1979). Distinguished by their fusion of post-hardcore, noise rock, and glam-influenced art rock.\n\nReleased nine studio albums between *Mono* (2001) and *All Things Under Heaven* (2015). Critical peak: *Penance Soiree* (2004) and *Black Lives at the Golden Coast* (2007). The band dissolved in 2017; Cardamone has subsequently led the project Holy War.",
  "the-iguanas":
    "American roots-rock band formed in New Orleans in 1989 (disambiguated as the Iguanas (3) on Discogs). Long-running lineup: Joe Cabral (saxophone/vocals), Rod Hodges (vocals/guitar/accordion), Rene Coman (bass), Doug Garrison (drums), and Derek Huston (saxophone). Distinguished by their fusion of New Orleans R&B, Tex-Mex, Cuban son, and rock.\n\nReleased nine studio albums between *The Iguanas* (1993) and *Juarez* (2014). Released primarily on MCA and (later) Yep Roc Records.",
  "the-interrupters":
    "American ska-punk band formed in Los Angeles in 2011. Lineup: Aimee Allen (vocals) and brothers Kevin (guitar/vocals), Justin (bass/vocals), and Jesse Bivona (drums). Distinguished by Allen's powerful vocals and the band's throwback 2 Tone ska revivalism.\n\nReleased four studio albums between *The Interrupters* (2014) and *In the Wild* (2022). Commercial peak: *Fight the Good Fight* (2018, featuring the breakthrough \"She's Kerosene\"). Frequent touring partners with Rancid and the Skints.",
  "the-j-geils-band":
    "American rock band formed in Worcester, Massachusetts in 1967. Long-running lineup: Peter Wolf (vocals, until 1983), J. Geils (guitar, 1946-2017), Magic Dick (harmonica), Seth Justman (keyboards), Danny Klein (bass), and Stephen Jo Bladd (drums). Distinguished by their fusion of blues, R&B, and rock with Wolf's high-energy live performances.\n\nReleased 11 studio albums between *The J. Geils Band* (1970) and *You're Gettin' Even While I'm Gettin' Odd* (1984). Commercial peak: *Freeze Frame* (1981, featuring the #1 \"Centerfold\"). J. Geils died in 2017 of natural causes.",
  "the-jasons":
    "American horror-punk band, members wearing Jason Voorhees-style hockey masks. The Jasons exist primarily as a live act in the broader Misfits/horror-punk tradition rather than as a major recording band.\n\nReleased *We're Gonna Kill You* (2013) and several other releases on small independent labels. Active in the New York and East Coast horror-punk scenes.",
  "the-jesus-and-mary-chain":
    "Scottish rock band formed in East Kilbride in 1983. Long-running lineup historically centered on brothers Jim Reid (vocals) and William Reid (guitar). Distinguished by their fusion of melodic pop songwriting with extreme feedback and noise (early albums) and pioneering influence on shoegaze, dream-pop, and noise pop.\n\nReleased seven studio albums between *Psychocandy* (1985) and *Glasgow Eyes* (2024). Critical peak: *Psychocandy*, *Darklands* (1987), and *Automatic* (1989). Their early shows became famous for the brothers' on-stage hostility and short, feedback-soaked sets. Bobby Gillespie (later of Primal Scream) was an early member.",
  "the-jesus-lizard":
    "American noise rock band formed in Austin, Texas in 1987 (relocated to Chicago shortly thereafter). Long-running lineup: David Yow (vocals), Duane Denison (guitar), David Wm. Sims (bass), and Mac McNeilly (drums). Distinguished by Yow's deranged on-stage persona (frequent crowd-walking, occasional brief partial nudity) and the band's foundational influence on noise rock.\n\nReleased six studio albums between *Head* (1990) and *Blue* (1998), plus the reunion album *Rack* (2024) following a long gap. Critical peak: *Goat* (1991), *Liar* (1992), and *Down* (1994). Released primarily on Touch and Go Records.",
  "the-jim-rose-circus-sideshow":
    "American freak-show / performance-art collective founded in 1991 by Jim Rose (b. 1956). Featured performers including the Enigma (covered head-to-toe in puzzle-piece tattoos), Bébé the Circus Queen, the Amazing Mr. Lifto, and others performing classic sideshow stunts (sword swallowing, body suspension, hot-coal walking).\n\nReleased the album *Live Album* (1996). Featured prominently on the 1992 Lollapalooza tour. The troupe has continued touring intermittently into the 2010s with rotating performers.",
  "the-juliana-hatfield-three":
    "American rock band formed in Boston in 1992 by Juliana Hatfield (b. July 27, 1967, Wiscasset, Maine), formerly of the Blake Babies and Some Girls. The Three additionally featured Dean Fisher (bass) and Todd Phillips (drums).\n\nReleased *Become What You Are* (1993, featuring \"My Sister\" and \"Spin the Bottle\") under the band name. Hatfield reunited the lineup for *Whatever, My Love* (2015). Hatfield has otherwise pursued a prolific solo career — over 20 albums under her own name since the 1990s.",
  "the-knack":
    "American rock band formed in Los Angeles in 1978. Long-running lineup: Doug Fieger (vocals/guitar, 1952-2010), Berton Averre (lead guitar), Prescott Niles (bass), and Bruce Gary (drums, 1951-2006). Distinguished by their throwback power-pop sound during the late-1970s new-wave era.\n\nReleased seven studio albums between *Get the Knack* (1979) and *Normal as the Next Guy* (2001). Commercial peak: *Get the Knack* (which produced the #1 \"My Sharona\" and spent five weeks atop the Billboard 200). Bruce Gary died in 2006 of lymphoma; Doug Fieger died in 2010 of lung cancer.",
  "the-lemonheads":
    "American alternative rock band formed in Boston in 1986. Long-running lineup centered on Evan Dando (vocals/guitar). Began as a hardcore-influenced punk band before shifting toward power-pop and college-rock starting around 1990.\n\nReleased 10 studio albums between *Hate Your Friends* (1987) and *Love Chord* (2025). Commercial peak: *It's a Shame About Ray* (1992) and *Come On Feel the Lemonheads* (1993). Best-known singles: \"Mrs. Robinson\" (1992, a cover) and \"Into Your Arms\" (1993).",
  "the-linda-lindas":
    "American punk rock band formed in Los Angeles in 2018. Lineup: Bela Salazar (guitar/vocals, b. 2005), Lucia de la Garza (guitar/vocals, b. 2007), Eloise Wong (bass/vocals, b. 2008), and Mila de la Garza (drums/vocals, b. 2010, Lucia's younger sister). Distinguished by their young age and their viral 2021 performance of \"Racist, Sexist Boy\" at the Los Angeles Public Library, which led to a record deal with Epitaph.\n\nReleased two studio albums: *Growing Up* (2022) and *No Obligation* (2024). Opened for Yeah Yeah Yeahs, Paramore, and the Linda Lindas's heroes Bikini Kill on various tours.",
  "the-misfits":
    "American horror-punk band formed in Lodi, New Jersey in 1977. Long-running classic lineup: Glenn Danzig (vocals, 1955), Jerry Only (bass, b. Gerald Caiafa, 1959), and various guitarists and drummers including Doyle Wolfgang von Frankenstein (Jerry's brother) and Bobby Steele. Distinguished by their hooky punk-rock songwriting paired with horror-movie iconography, including the band's distinctive \"Crimson Ghost\" mascot.\n\nReleased three studio albums during Danzig's original tenure: *Static Age* (recorded 1978, released 1996), *Walk Among Us* (1982), and *Earth A.D./Wolfs Blood* (1983). Danzig left in 1983; the band reformed in 1995 under Jerry Only with various replacement vocalists. The classic Danzig/Only/Doyle lineup has reunited for occasional tours since 2016.",
  "the-modern-jazz-quartet":
    "American jazz ensemble formed in New York City in 1952. Long-running classic lineup: John Lewis (piano, 1920-2001), Milt Jackson (vibraphone, 1923-1999), Percy Heath (bass, 1923-2005), and Connie Kay (drums, 1927-1994). Distinguished by their fusion of bebop with European classical-music structural elements (Lewis's particular interest) and their formal concert-attire stage presentation.\n\nReleased numerous studio albums between *Modern Jazz Quartet* (1952) and *Dedicated to Connie* (1995, posthumously released). Critical peak: *Django* (1956, dedicated to Django Reinhardt), *Fontessa* (1956), and *No Sun in Venice* (1957). Continued performing together for over 40 years until Connie Kay's death in 1994 effectively ended the group.",
  "the-monkees":
    "American pop-rock band formed in 1965 for the NBC television sitcom *The Monkees* (1966-1968). Lineup: Davy Jones (vocals/percussion, 1945-2012), Micky Dolenz (vocals/drums, b. 1945), Michael Nesmith (vocals/guitar, 1942-2021), and Peter Tork (vocals/bass, 1942-2019). Assembled via audition by Bert Schneider and Bob Rafelson.\n\nReleased 13 studio albums between *The Monkees* (1966) and *Good Times!* (2016). Commercial peak: their first four albums all hit #1, with *The Monkees* (1966) and *More of the Monkees* (1967) being the two best-selling albums of the 1960s. Best-known singles: \"Last Train to Clarksville\" (1966), \"I'm a Believer\" (1966, written by Neil Diamond), and \"Daydream Believer\" (1967). The 1968 Bob Rafelson-directed film *Head* effectively ended their TV-era moment.",
  "the-mothers":
    "Same artist as the Mothers of Invention — abbreviated credit variation. American rock band formed in Pomona, California in 1964 by Frank Zappa (1940-1993). Long-running lineup historically: Zappa (vocals/guitar) with rotating personnel including Don Preston (keyboards), Ian Underwood (woodwinds/keyboards), Aynsley Dunbar (drums), and many others.\n\nReleased over a dozen studio albums credited to the Mothers / Mothers of Invention between *Freak Out!* (1966) and *One Size Fits All* (1975). Zappa increasingly began crediting albums to himself alone (rather than to the Mothers) starting in the early 1970s.",
  "the-new-cactus-band":
    "American rock band formed in 1973, a reformed version of the original Cactus (whose original 1970-1972 lineup featured Tim Bogert and Carmine Appice, who left to form Beck, Bogert & Appice with Jeff Beck). The new lineup featured original Cactus guitarist Jim McCarty (Detroit Wheels alum) with replacement personnel.\n\nReleased *Son of Cactus* (1973). The band dissolved shortly thereafter. The original Cactus reunited periodically in subsequent decades.",
  "the-nixons":
    "American post-grunge band formed in Oklahoma City in 1990. Long-running lineup centered on Zac Maloy (vocals/guitar). Distinguished by their alternative-rock songwriting and mid-1990s commercial peak with \"Sister\" (1995) from the major-label debut.\n\nReleased four studio albums between *Halo* (1993) and *The Nixons* (2000). Maloy has subsequently become a successful Nashville songwriter, co-writing material for Carrie Underwood, Tim McGraw, and others.",
  "the-oc-supertones":
    "American Christian ska-punk band formed in Orange County, California in 1991 (officially the O.C. Supertones). Long-running lineup centered on Matt Morginsky (vocals). Distinguished by their fusion of ska with Christian rock and their major role in the late-1990s Christian-music ska boom.\n\nReleased seven studio albums between *Adventures of the O.C. Supertones* (1996) and *Faith of a Child* (2005). Released on Tooth & Nail Records. The band dissolved in 2005 and reunited intermittently thereafter.",
  "the-obsessed":
    "American doom metal band formed in Potomac, Maryland in 1976 (originally as Warhorse). Long-running lineup centered on Scott \"Wino\" Weinrich (vocals/guitar). Distinguished as foundational to the early American doom metal scene alongside Pentagram and the Saint Vitus.\n\nReleased four studio albums between *The Obsessed* (1990) and *Sacred* (2017). Wino has also led Saint Vitus (1986-1991), Spirit Caravan (1996-2002), the Hidden Hand (2003-2007), and Premonition 13.",
  "the-other-ones":
    "American rock band formed in 1998 by surviving Grateful Dead members Bob Weir, Phil Lesh, Mickey Hart, and Bill Kreutzmann (with various guests including Steve Kimock and Mark Karan on guitars) — the first major touring project after Jerry Garcia's 1995 death. The lineup performed primarily Grateful Dead material plus a few originals.\n\nThe project ran 1998-2002 before transitioning into The Dead (2003-2009), Furthur (2009-2014), and Dead & Company (2015-present). Released the live album *The Strange Remain* (1999).",
  "the-phantom-surfers":
    "American instrumental surf rock band formed in San Francisco in 1989. Long-running lineup centered on \"Bossman\" Mel Bergman (drums) and other costumed performers. Distinguished by their masked stage presentation (the band performs in luchador-style masks) and throwback 1960s instrumental surf style.\n\nReleased six studio albums between *Skaterhater* (1991) and *Skatin' the Dimension* (1998). Released primarily on Estrus Records and Lookout! Records.",
  "the-pharcyde":
    "American hip-hop group formed in South Central Los Angeles in 1989. Lineup: Imani, SlimKid3 (Tre Hardson), Bootie Brown, and Fatlip. Distinguished by their playful, jazz-inflected production and their stylistic break from the prevailing gangsta-rap aesthetic of early-1990s West Coast hip-hop.\n\nReleased four studio albums between *Bizarre Ride II the Pharcyde* (1992) and *Humboldt Beginnings* (2004). Critical peak: *Bizarre Ride II the Pharcyde* and *Labcabincalifornia* (1995, produced largely by J Dilla). Internal tensions between members have led to recurring lineup splits.",
  "the-pretenders":
    "British-American rock band formed in Hereford, England in 1978. Long-running lineup historically centered on Chrissie Hynde (vocals/guitar, b. September 7, 1951, Akron, Ohio). The original lineup also included James Honeyman-Scott (guitar, 1956-1982) and Pete Farndon (bass, 1952-1983), both of whom died young of drug overdoses.\n\nReleased 11 studio albums between *Pretenders* (1980) and *Relentless* (2023). Commercial peak: *Pretenders* (featuring \"Brass in Pocket\"), *Pretenders II* (1981), and *Learning to Crawl* (1984, featuring \"Back on the Chain Gang\" and \"Middle of the Road\"). Hynde has remained the only constant member. Inducted into the Rock and Roll Hall of Fame in 2005.",
  "the-pretty-reckless":
    "American rock band formed in New York City in 2009. Long-running lineup centered on Taylor Momsen (vocals, b. July 26, 1993, formerly an actress on *Gossip Girl*). Distinguished by Momsen's powerful vocals and the band's classic-hard-rock style drawing on Black Sabbath, Soundgarden, and the Stooges.\n\nReleased four studio albums between *Light Me Up* (2010) and *Death by Rock and Roll* (2021). Commercial peak: *Going to Hell* (2014) and *Who You Selling For* (2016).",
  "the-raven-age":
    "British heavy metal band formed in London in 2009. Long-running lineup centered on George Harris (guitar, son of Iron Maiden's Steve Harris) and Dan Wright (guitar). Distinguished by their melodic heavy metal style with influences from progressive metal and metalcore.\n\nReleased three studio albums between *Darkness Will Rise* (2017) and *Blood Omen* (2023). Toured extensively as the opening act on Iron Maiden's *Legacy of the Beast* tour (2018-2019).",
  "the-rippingtons":
    "American smooth jazz / contemporary jazz band formed in Los Angeles in 1985 by guitarist Russ Freeman (b. 1960). Distinguished by their hybrid of fusion-era guitar instrumentals with bright, contemporary-jazz production and the band's signature Russ Freeman jazz-cat mascot on every album cover.\n\nReleased over 25 studio albums between *Moonlighting* (1986) and *Big Stylish Groove* (2023). Long association with GRP Records during the label's smooth-jazz peak.",
  "the-rivieras":
    "American garage rock band formed in South Bend, Indiana in 1962. Long-running lineup historically featured Marty Fortson (vocals/saxophone) and Joe Pennell (lead guitar). Distinguished by their two top-40 instrumental and vocal hits during the mid-1960s.\n\nBest-known recording: \"California Sun\" (1964), a top-five US hit that became a definitive surf/garage-rock track and was covered by the Ramones in 1977. The band dissolved in 1966 amid lineup shifts and a member's Vietnam-era draft notice.",
  "the-roots":
    "American hip-hop band formed in Philadelphia in 1987. Long-running classic lineup: Tariq \"Black Thought\" Trotter (vocals), Ahmir \"Questlove\" Thompson (drums), Kamal Gray (keyboards), F. Knuckles (drums), and various other personnel. Distinguished by their live-band approach to hip-hop production (as opposed to sample-based or beat-machine production) and their late-2000s pivot to becoming the house band on *The Tonight Show*.\n\nReleased 14 studio albums between *Organix* (1993) and *End Game* (2024). Critical peak: *Things Fall Apart* (1999), *Phrenology* (2002), and *How I Got Over* (2010). Five Grammy Awards. Since 2009, the band has been the house band on *Late Night with Jimmy Fallon* and (from 2014) *The Tonight Show Starring Jimmy Fallon*.",
  "the-royal-philharmonic-orchestra":
    "British symphony orchestra founded in London in 1946 by conductor Sir Thomas Beecham (1879-1961). One of the world's leading symphony orchestras, with a particular reputation for recording the standard classical repertoire as well as crossover and film-score work.\n\nThe orchestra has recorded extensively for major classical and crossover-pop labels. \"The Royal Philharmonic Orchestra\" appears on countless symphonic-rock crossover recordings, soundtracks, and Christmas albums, as well as their core classical catalog.",
  "the-scofflaws":
    "American ska band formed in Long Island, New York in 1988. Long-running lineup centered on \"Black Pope\" Sammy (vocals) and brass section including Buford O'Sullivan (trombone). Distinguished by their traditional second-wave-style ska in the vein of the Skatalites rather than the punk-ska of the 1990s third-wave revival.\n\nReleased four studio albums between *The Scofflaws* (1991) and *Live Vol. 2* (2002). Released primarily on Moon Ska Records.",
  "the-selecter":
    "British 2 Tone ska band formed in Coventry in 1979. Long-running lineup historically centered on Pauline Black (vocals, b. 1953) and Arthur \"Gaps\" Hendrickson (vocals). Distinguished as one of the foundational bands of the late-1970s 2 Tone ska revival alongside the Specials and Madness.\n\nReleased two studio albums during their initial run: *Too Much Pressure* (1980) and *Celebrate the Bullet* (1981). The band reformed in the 1990s and again in 2010; Pauline Black has continued to lead the Selecter through their multiple reunions.",
  "the-shangri-las":
    "American girl group formed in Queens, New York in 1963. Lineup: sisters Mary Weiss (lead, 1948-2024) and Betty Weiss, plus identical twins Mary Ann Ganser (1948-1970) and Marge Ganser (1948-1996). Distinguished by their dark, melodramatic songwriting (largely by George \"Shadow\" Morton) addressing teen-romance tragedies.\n\nReleased two studio albums during their original run: *Leader of the Pack* (1965) and *Shangri-Las 65!* (1965). Best-known recordings: \"Leader of the Pack\" (1964, #1) and \"Remember (Walking in the Sand)\" (1964). Mary Ann Ganser died in 1970 of encephalitis; Marge Ganser died in 1996 of breast cancer; Mary Weiss died in 2024.",
  "the-smithereens":
    "American power pop band formed in Carteret, New Jersey in 1980. Long-running lineup: Pat DiNizio (vocals/guitar, 1955-2017), Jim Babjak (guitar), Mike Mesaros (bass, until 2006), and Dennis Diken (drums). Distinguished by their Beatles- and Beach Boys-influenced melodic songwriting.\n\nReleased 11 studio albums between *Especially for You* (1986) and *2011* (2011). Commercial peak: *11* (1989, featuring \"A Girl Like You\" and \"Blues Before and After\") and *Blow Up* (1991, featuring \"Top of the Pops\"). Pat DiNizio died in 2017 of complications from a fall.",
  "the-stooges":
    "American rock band formed in Ann Arbor, Michigan in 1967. Long-running classic lineup: Iggy Pop (vocals, b. April 21, 1947), Ron Asheton (guitar, 1948-2009), Scott Asheton (drums, 1949-2014, Ron's brother), and Dave Alexander (bass, 1947-1975). James Williamson replaced Ron Asheton on guitar for the third album. Foundational influence on punk rock.\n\nReleased three studio albums during their original run: *The Stooges* (1969), *Fun House* (1970), and *Raw Power* (1973). Reformed in 2003 with Iggy Pop, Ron and Scott Asheton, and Mike Watt on bass. Released *The Weirdness* (2007) and *Ready to Die* (2013, with Williamson returning to guitar after Ron Asheton's 2009 death). Inducted into the Rock and Roll Hall of Fame in 2010.",
  "the-temptations":
    "American R&B/soul group formed in Detroit in 1960. Long-running lineup has rotated extensively but historically centered on Otis Williams (b. 1941, the only original member still active as of 2025) with David Ruffin (1941-1991), Eddie Kendricks (1939-1992), Paul Williams (1939-1973), and Melvin Franklin (1942-1995) defining the classic mid-1960s lineup. The defining male vocal group of the Motown era.\n\nReleased over 40 studio albums between *Meet the Temptations* (1964) and *Temptations 60* (2022). Commercial peak: a string of mid-1960s hits including \"My Girl,\" \"The Way You Do the Things You Do,\" \"Get Ready,\" \"Ain't Too Proud to Beg,\" \"I Wish It Would Rain,\" and the psychedelic-soul late-1960s era (\"Cloud Nine,\" \"Psychedelic Shack,\" \"Just My Imagination,\" \"Papa Was a Rollin' Stone\"). Inducted into the Rock and Roll Hall of Fame in 1989.",
  "the-tonight-show-band":
    "The house band of NBC's *The Tonight Show*, which has gone through multiple incarnations matched to different *Tonight Show* hosts and bandleaders. The most famous configuration is the Doc Severinsen-led band (1967-1992) during Johnny Carson's *Tonight Show* tenure, featuring trumpet bandleader Severinsen and drummer Ed Shaughnessy.\n\nReleased numerous albums during the Severinsen era. The Severinsen-led band was a big-band-jazz ensemble; later iterations under Jay Leno (Branford Marsalis, then Kevin Eubanks) and Jimmy Fallon (The Roots, since 2014) have taken different musical directions.",
  "the-used":
    "American post-hardcore band formed in Orem, Utah in 2001. Long-running lineup centered on Bert McCracken (vocals). Distinguished by their fusion of post-hardcore with emo, screamo, and pop-punk during the early-2000s emo boom.\n\nReleased nine studio albums between *The Used* (2002) and *Toxic Positivity* (2023). Commercial peak: *The Used* and *In Love and Death* (2004, featuring \"All That I've Got\" and \"I Caught Fire\"). McCracken was the boyfriend of My Chemical Romance's Gerard Way's late friend Kate, whose death informed the My Chemical Romance album *The Black Parade*.",
  "the-verve":
    "English rock band formed in Wigan in 1990. Long-running lineup: Richard Ashcroft (vocals), Nick McCabe (guitar), Simon Jones (bass), and Peter Salisbury (drums). Distinguished by their layered, atmospheric rock production and Ashcroft's prominent stage presence.\n\nReleased four studio albums between *A Storm in Heaven* (1993) and *Forth* (2008). Commercial peak: *Urban Hymns* (1997, featuring \"Bitter Sweet Symphony\" — which famously had its publishing royalties surrendered to Mick Jagger and Keith Richards over a sampling dispute that was eventually resolved in 2019). The band has split and reformed multiple times.",
  "the-waitresses":
    "American new wave band formed in Akron, Ohio in 1978. Long-running lineup centered on Patty Donahue (vocals, 1956-1996) and Chris Butler (guitar/songwriter). Distinguished by their wry, deadpan female-fronted songs about everyday life and the band's modest cult following.\n\nReleased two studio albums and an EP between *Wasn't Tomorrow Wonderful?* (1982) and *Bruiseology* (1983). Best-known recordings: \"I Know What Boys Like\" (1982) and the perennial \"Christmas Wrapping\" (1981). Patty Donahue died in 1996 of lung cancer at age 40.",
  "the-wonder-years":
    "American pop-punk band formed in Lansdale, Pennsylvania in 2005. Long-running lineup centered on Dan \"Soupy\" Campbell (vocals). Distinguished by their emotionally autobiographical lyrics and their role in the early-2010s pop-punk revival alongside Man Overboard and the Story So Far.\n\nReleased seven studio albums between *Get Stoked on It!* (2007) and *The Hum Goes On Forever* (2022). Critical peak: *Suburbia I've Given You All and Now I'm Nothing* (2011), *The Greatest Generation* (2013), and *No Closer to Heaven* (2015).",
  "the-young-rascals":
    "American rock band formed in Garfield, New Jersey in 1965 (renamed simply The Rascals in 1968). Lineup: Felix Cavaliere (vocals/keyboards, b. 1942), Eddie Brigati (vocals/percussion, b. 1945), Gene Cornish (guitar/vocals, b. 1944), and Dino Danelli (drums, 1944-2022). Distinguished by their fusion of R&B and rock — among the earliest white American bands to embrace what would later be called \"blue-eyed soul.\"\n\nReleased seven studio albums between *The Young Rascals* (1966) and *Search and Nearness* (1971). Commercial peak: a string of mid-1960s hits including \"Good Lovin'\" (1966, #1), \"Groovin'\" (1967, #1), \"A Beautiful Morning\" (1968), and \"People Got to Be Free\" (1968, #1). Inducted into the Rock and Roll Hall of Fame in 1997.",
  "theory-of-a-deadman":
    "Canadian rock band formed in Delta, British Columbia in 2001 (officially Theory of a Deadman through 2019, shortened to Theory thereafter, then back). Long-running lineup centered on Tyler Connolly (vocals/guitar). Discovered by Chad Kroeger of Nickelback and signed to Kroeger's 604 Records.\n\nReleased eight studio albums between *Theory of a Deadman* (2002) and *Dinosaur* (2023). Commercial peak: *Scars & Souvenirs* (2008, featuring \"Bad Girlfriend\") and *Wake Up Call* (2017, featuring \"Rx (Medicate)\").",
  "third-eye-blind":
    "American alternative rock band formed in San Francisco in 1993. Long-running lineup centered on Stephan Jenkins (vocals/guitar). Distinguished by their hybrid power-pop / alternative rock sound and Jenkins's verbose, dense lyrical style.\n\nReleased seven studio albums between *Third Eye Blind* (1997) and *Our Bande Apart* (2021). Commercial peak: *Third Eye Blind* (6x platinum, featuring \"Semi-Charmed Life,\" \"Jumper,\" \"How's It Going to Be,\" and \"Graduate\") and *Blue* (1999, featuring \"Never Let You Go\").",
  "thomas-dolby":
    "English musician and producer born Thomas Morgan Robertson on October 14, 1958, in Cairo, Egypt; raised in England. Distinguished by his pioneering use of synthesizers in pop and his polymath career bridging music, technology entrepreneurship (he founded Beatnik Inc., a mobile-ringtone-technology company), and academia (Johns Hopkins, since 2014).\n\nReleased six studio albums between *The Golden Age of Wireless* (1982) and *A Map of the Floating City* (2011). Commercial peak: *The Golden Age of Wireless* (featuring the international hit \"She Blinded Me with Science\") and *The Flat Earth* (1984).",
  "thompson-twins":
    "British synth-pop band formed in Sheffield in 1977. After a 1982 lineup reduction, the long-running trio was Tom Bailey (vocals/keyboards), Alannah Currie (percussion/vocals), and Joe Leeway (vocals/percussion, until 1986). The band's name references the Thomson Twins (with no \"p\") from the *Tintin* comics.\n\nReleased eight studio albums between *A Product Of...* (1981) and *Queer* (1991). Commercial peak: *Quick Step & Side Kick* (1983, featuring \"Love on Your Side\") and *Into the Gap* (1984, featuring \"Hold Me Now\" and \"Doctor! Doctor!\"). Bailey continues to tour as Thompson Twins' Tom Bailey.",
  "tiffany":
    "American singer born Tiffany Renee Darwish on October 2, 1971, in Norwalk, California. Best known for her 1987 cover of Tommy James and the Shondells' \"I Think We're Alone Now,\" which reached #1 on the Billboard Hot 100 when Tiffany was 16. Famously promoted her debut album by performing at American shopping malls in the \"Beautiful You: Celebrating the Good Life Shopping Mall Tour 87.\"\n\nReleased nine studio albums between *Tiffany* (1987) and *Shadows* (2022). Commercial peak: *Tiffany* (4x platinum) and *Hold an Old Friend's Hand* (1988). Has subsequently pursued an acting career on the Hallmark Channel and reality TV.",
  "time-zone":
    "Side project featuring Afrika Bambaataa (b. April 17, 1957, Bronx, New York), with various collaborators. Most famous for the 1984 single \"World Destruction,\" a collaboration with John Lydon (Public Image Ltd / former Sex Pistols), one of the earliest hip-hop / rock crossover records.\n\nLimited subsequent Time Zone output; the project was primarily a vehicle for the \"World Destruction\" single. Bambaataa's more extensive recording work appears under his own name and with the Soulsonic Force.",
  "tinashe":
    "American singer-songwriter, dancer, and producer born Tinashe Jorgensen Kachingwe on February 6, 1993, in Lexington, Kentucky; raised in Los Angeles. Began her career as a child actress (*Two and a Half Men*, the Bratz films) before pivoting to music in 2011.\n\nReleased seven studio albums between *Aquarius* (2014) and *Quantum Baby* (2024). Best-known single: \"2 On\" (2014, featuring Schoolboy Q). Released most of her later material independently after parting ways with RCA Records in 2019.",
  "toad-the-wet-sprocket":
    "American rock band formed in Santa Barbara, California in 1986. Long-running lineup: Glen Phillips (vocals/guitar), Todd Nichols (guitar), Dean Dinning (bass), and Randy Guss (drums). The band's name comes from a Monty Python's Flying Circus sketch.\n\nReleased seven studio albums between *Bread & Circus* (1989) and *Starting Now* (2021). Commercial peak: *Fear* (1991, featuring \"All I Want\" and \"Walk on the Ocean\") and *Dulcinea* (1994, featuring \"Fall Down\"). On hiatus 1998-2006; has continued touring since the 2006 reunion.",
  "toadies":
    "American rock band formed in Fort Worth, Texas in 1989. Long-running lineup centered on Vaden Todd Lewis (vocals/guitar). Distinguished by their hybrid post-grunge / hard rock style.\n\nReleased seven studio albums between *Rubberneck* (1994) and *The Lower Side of Uptown* (2017). Commercial peak: *Rubberneck* (platinum-certified, featuring the breakthrough single \"Possum Kingdom\"). Lewis has subsequently led the Burden Brothers.",
  "tommy-cowan":
    "Jamaican reggae singer and producer born December 16, 1948. Founding member of the Jamaicans (1965), the vocal trio that recorded the rocksteady hit \"Things You Say You Love\" (1968). Subsequently became a leading reggae producer and promoter — co-founder of Talent Corporation (which managed Bob Marley & the Wailers among others).\n\nMember of Light of Saba (early 1970s) and the Sons of Negus before pursuing solo recording. Has continued performing and producing into the 2020s.",
  "tommy-james-the-shondells":
    "American rock band formed in Niles, Michigan in 1964. Long-running lineup centered on Tommy James (vocals, born Thomas Gregory Jackson on April 29, 1947). Distinguished by their bubblegum-meets-psychedelia pop hits during the late 1960s.\n\nReleased six studio albums between *Hanky Panky* (1966) and *Travelin'* (1970). Commercial peak: a string of late-1960s hits including \"Hanky Panky\" (1966, #1), \"I Think We're Alone Now\" (1967), \"Mony Mony\" (1968), \"Crimson and Clover\" (1969, #1), and \"Crystal Blue Persuasion\" (1969). James's 2010 memoir *Me, the Mob, and the Music* recounted his career and Roulette Records label boss Morris Levy's mob connections.",
  "tonic":
    "American rock band formed in Los Angeles in 1993. Long-running lineup: Emerson Hart (vocals/guitar), Jeff Russo (lead guitar), and Dan Lavery (bass). Distinguished by their post-grunge / power-pop hybrid sound.\n\nReleased four studio albums between *Lemon Parade* (1996) and *Tonic* (2010). Commercial peak: *Lemon Parade* (platinum-certified, featuring \"If You Could Only See\"). Russo has subsequently become a prominent film and TV composer (*Fargo*, *Star Trek: Discovery*, *Watchmen*, etc.).",
  "tonight-alive":
    "Australian rock band formed in Sydney in 2008. Long-running lineup centered on Jenna McDougall (vocals). Distinguished by their pop-rock / pop-punk style with strong melodic emphasis.\n\nReleased four studio albums between *What Are You So Scared Of?* (2011) and *Underworld* (2018). Commercial peak: *The Other Side* (2013) and *Limitless* (2016). The band has been on indefinite hiatus since 2019.",
  "tony-iommi":
    "English guitarist born February 19, 1948, in Aston, Birmingham. Founding lead guitarist for Black Sabbath (1968-present, with various hiatuses). Foundational influence on heavy metal guitar; his use of detuned guitars (a workaround after losing the tips of two fingers on his fretting hand in a sheet-metal factory accident at age 17) and dark, minor-key riffing largely defined the heavy-metal genre.\n\nReleased two solo studio albums: *Iommi* (2000, featuring guest vocalists Ozzy Osbourne, Henry Rollins, Dave Grohl, Skin, Phil Anselmo, and others) and *Fused* (2005, with Glenn Hughes). Inducted into the Rock and Roll Hall of Fame as a member of Black Sabbath in 2006.",
  "trans-siberian-orchestra":
    "American symphonic rock band formed in Tampa, Florida in 1996 by Paul O'Neill (1956-2017), Robert Kinkel, Jon Oliva (Savatage), and Al Pitrelli. Distinguished by their elaborate Christmas-themed stage productions combining rock and classical music; the band tours two simultaneous productions every winter holiday season.\n\nReleased seven studio albums between *Christmas Eve and Other Stories* (1996) and *Letters from the Labyrinth* (2015). Commercial peak: *Christmas Eve and Other Stories* (3x platinum). The band's annual winter tours have grossed hundreds of millions of dollars and become a holiday-music institution in North America.",
  "trapeze":
    "English rock band formed in Wolverhampton in 1969. Long-running lineup historically featured Glenn Hughes (bass/vocals, b. 1951, who left in 1973 to join Deep Purple), Mel Galley (guitar/vocals, 1948-2008), and Dave Holland (drums, 1948-2018). Distinguished by their fusion of hard rock with funk and soul influences.\n\nReleased five studio albums between *Trapeze* (1970) and *Hot Wire* (1974). Critical peak: *Medusa* (1970) and *You Are the Music... We're Just the Band* (1972). Mel Galley subsequently joined Whitesnake; Dave Holland joined Judas Priest.",
  "traveling-wilburys":
    "Anglo-American rock supergroup formed in 1988. Lineup: George Harrison (1943-2001), Bob Dylan (b. 1941), Roy Orbison (1936-1988), Tom Petty (1950-2017), and Jeff Lynne (b. 1947). Each member adopted a \"Wilbury\" alias (Nelson, Lucky, Lefty, Charlie T. Jr., and Otis, respectively).\n\nReleased two studio albums: *Traveling Wilburys Vol. 1* (1988, 3x platinum, featuring \"Handle with Care\" and \"End of the Line\") and *Traveling Wilburys Vol. 3* (1990, after Orbison's December 1988 death from a heart attack). Won the 1990 Grammy for Best Rock Performance by a Duo or Group with Vocal for the first album.",
  "travis-tritt":
    "American country singer-songwriter born James Travis Tritt on February 9, 1963, in Marietta, Georgia. Distinguished by his fusion of Southern rock and outlaw-country influences with mainstream country.\n\nReleased 11 studio albums between *Country Club* (1990) and *Set in Stone* (2021). Commercial peak: *It's All About to Change* (1991), *T-r-o-u-b-l-e* (1992), and *Greatest Hits: From the Beginning* (1995). Two Grammy Awards. Member of the Grand Ole Opry since 1992.",
  "tree":
    "American hardcore band formed in Boston in 1988. Long-running lineup centered on Dave Tree (vocals/guitar). Distinguished by their fusion of hardcore with heavy metal and progressive influences.\n\nReleased four studio albums between *Plant a Tree or Die!!* (1992) and *Plays the Year of the Rat* (2000). Released primarily on independent labels. The band has been intermittently active in subsequent decades.",
  "triple-fast-action":
    "American power pop band formed in Chicago in 1992. Long-running lineup centered on Wes Kidd (vocals/guitar). Distinguished by their melodic power-pop style drawing on Cheap Trick and the Replacements.\n\nReleased two studio albums: *Broadcaster* (1994) and *Cattlemen Don't* (1997). Released on Capitol Records during their commercial peak. The band dissolved in 1998; Kidd has subsequently pursued music management.",
  "trixter":
    "American glam metal band formed in Paramus, New Jersey in 1983. Long-running lineup: Pete Loran (vocals), Steve Brown (guitar), P.J. Farley (bass), and Mark \"Gus\" Scott (drums). Distinguished by their late arrival to the glam-metal scene — their self-titled debut emerged in 1990, just as the genre was being eclipsed by grunge.\n\nReleased four studio albums between *Trixter* (1990) and *Human Era* (2012). Commercial peak: *Trixter* (gold-certified, featuring \"Give It to Me Good\" and \"One in a Million\"). Steve Brown has subsequently played with Def Leppard as a touring guitarist.",
  "twisted-sister":
    "American glam metal band formed in Ho-Ho-Kus, New Jersey in 1972. Long-running classic lineup: Dee Snider (vocals, b. 1955), Jay Jay French (guitar, b. 1952), Eddie Ojeda (guitar), Mark Mendoza (bass), and A.J. Pero (drums, 1959-2015). Distinguished by their over-the-top glam-metal visual aesthetic and Snider's outspoken role during the 1985 PMRC senate hearings on music censorship.\n\nReleased seven studio albums between *Under the Blade* (1982) and *A Twisted Christmas* (2006). Commercial peak: *Stay Hungry* (1984, 3x platinum, featuring \"We're Not Gonna Take It\" and \"I Wanna Rock\"). The band reunited 2003-2016 and has been on permanent hiatus since A.J. Pero's 2015 death.",
  "twiztid":
    "American hip-hop / horrorcore duo formed in Detroit in 1997. Lineup: Jamie Madrox (Jamie Spaniolo) and Monoxide Child (Paul Methric). Affiliated with Insane Clown Posse's Psychopathic Records (1997-2012) before founding their own Majik Ninja Entertainment label in 2014.\n\nReleased over a dozen studio albums between *Mostasteless* (1997) and *Welcome to Our House* (2024). Part of the broader Juggalo subculture associated with Insane Clown Posse and the Gathering of the Juggalos festival.",
  "uk":
    "British progressive rock supergroup formed in London in 1977 (officially U.K.). Lineup: John Wetton (vocals/bass, formerly of King Crimson and Roxy Music, 1949-2017), Eddie Jobson (keyboards/violin, formerly of Roxy Music and Frank Zappa's band), Bill Bruford (drums, formerly of Yes and King Crimson), and Allan Holdsworth (guitar, 1946-2017). Holdsworth and Bruford left after the first album, replaced by drummer Terry Bozzio (formerly of Frank Zappa's band).\n\nReleased two studio albums during their original run: *U.K.* (1978) and *Danger Money* (1979). The band split in 1980; reunited in 2011 with Wetton, Jobson, and various supporting musicians. Wetton died in 2017 of colon cancer.",
  "ugly-kid-joe":
    "American rock band formed in Isla Vista, California in 1989. Long-running lineup centered on Whitfield Crane (vocals). Distinguished by their satirical name (chosen to mock the era's prettyboy glam-metal bands) and their late-arrival commercial peak as glam metal collapsed.\n\nReleased five studio albums between *As Ugly as They Wanna Be* (1991) and *Rad Wings of Destiny* (2022). Commercial peak: *America's Least Wanted* (1992, multi-platinum, featuring \"Everything About You\" and their cover of Harry Chapin's \"Cat's in the Cradle\"). Reunited in 2010 after a long hiatus.",
  "uk-subs":
    "English punk rock band formed in Tooting, London in 1976. Long-running lineup centered on Charlie Harper (vocals, b. April 25, 1944). One of the longest-running first-wave UK punk bands; Harper has remained the only constant member through dozens of lineup changes.\n\nReleased over 25 studio albums between *Another Kind of Blues* (1979) and *Reverse Engineering* (2022). Critical peak: their first four LPs, *Another Kind of Blues*, *Brand New Age* (1980), *Crash Course* (1980, live), and *Diminished Responsibility* (1981). Harper announced an alphabetical series of 26 albums in the 1980s and completed it in 2022.",
};

async function main() {
  const dryRun = process.argv.includes("--dry-run");
  const force = process.argv.includes("--force");
  const { containers } = await import("../lib/cosmos");
  const { getStoredArtist } = await import("../lib/artists");

  let written = 0;
  let skipped = 0;
  let missing = 0;

  for (const [slug, description] of Object.entries(DESCRIPTIONS)) {
    const existing = await getStoredArtist(slug);
    if (!existing) {
      console.log(`✗ ${slug}: no stored doc found`);
      missing += 1;
      continue;
    }
    if (existing.description && !force) {
      console.log(`↷ ${slug}: already has description — skipping`);
      skipped += 1;
      continue;
    }
    if (dryRun) {
      console.log(`◌ ${slug}: would write ${description.length} chars`);
      written += 1;
      continue;
    }
    const updated = {
      ...existing,
      description,
      updatedAt: new Date().toISOString(),
    };
    await containers.artists.item(slug, slug).replace(updated);
    console.log(`✓ ${slug}: ${description.length} chars`);
    written += 1;
  }

  console.log(`\nDone. written=${written} skipped=${skipped} missing=${missing}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
