import { config as loadEnv } from "dotenv";
loadEnv({ path: ".env.local" });

const DESCRIPTIONS: Record<string, string> = {
  "vovod":
    "Same artist as Voivod — different setlist.fm/MusicBrainz credit variation. Canadian progressive metal band formed in Jonquière, Quebec in 1982. Lineup historically centered on Michel \"Away\" Langevin (drums) and the late Denis \"Piggy\" D'Amour (guitar). Distinguished by their dissonant, chord-based riffing, sci-fi concept albums, and Away's distinctive comic-book artwork.\n\nFifteen studio albums between *War and Pain* (1984) and *Synchro Anarchy* (2022). Critical peak: *Killing Technology* (1987), *Dimension Hatröss* (1988), and *Nothingface* (1989, featuring a cover of Pink Floyd's \"Astronomy Domine\"). D'Amour died in 2005 of colon cancer; the band continued with Daniel \"Chewy\" Mongrain on guitar. *Synchro Anarchy* won the 2023 Juno Award for Metal/Hard Music Album of the Year.",
  "jason-the-scorchers":
    "American country-rock band formed in Nashville in 1981 (originally as Jason and the Nashville Scorchers). Long-running lineup centered on Jason Ringenberg (vocals) and Warner E. Hodges (guitar). Pioneers of the cowpunk genre, fusing hardcore punk energy with traditional country songwriting and instrumentation.\n\nReleased *Fervor* (1983, EP) and *Lost & Found* (1985), both highly influential on the alt-country movement that emerged a decade later. Subsequent albums include *Still Standing* (1986), *A Blazing Grace* (1995), and *Halcyon Times* (2010). The band has been intermittently active; Ringenberg continues to tour as a solo artist.",
  "jd-pinkus":
    "American bassist and multi-instrumentalist born Jeffrey Dean Pinkus on August 1, 1965. Long-running member of the Butthole Surfers (1985-present) and Honky. Has also performed and recorded with Daddy Longhead, the Melvins, the Reverend Horton Heat, and Pus.\n\nReleased solo albums including *Fungus Shui* (2017) and *Grow a Pair!* (2022), the latter a banjo-focused outing exploring his interest in old-time Americana. Resides in Texas.",
  "jeff-austin":
    "American mandolinist and singer-songwriter born November 22, 1974, in Wonder Lake, Illinois; died June 24, 2019. Co-founding member of the bluegrass-jam band Yonder Mountain String Band (1998-2014). Distinguished by his propulsive, jam-influenced mandolin playing.\n\nAfter leaving Yonder Mountain in 2014, he led the Jeff Austin Band and released *The Simple Truth* (2015). Died at age 44 from complications related to alcoholism and addiction.",
  "jeff-bates":
    "American country singer-songwriter born September 19, 1963, in Bunker Hill, Mississippi. RCA Records signing whose deep baritone drew frequent comparisons to Conway Twitty.\n\nReleased four studio albums between *Rainbow Man* (2003, featuring the top-10 \"The Love Song\") and *Me and Conway* (2013). Best-known singles include \"Long, Slow Kisses\" (2004) and \"No Shame\" (2005). Continues to tour and record independently.",
  "jeff-buckley":
    "American singer-songwriter and guitarist born November 17, 1966, in Anaheim, California; died May 29, 1997. Son of folk singer Tim Buckley. Distinguished by a multi-octave vocal range and a unique melding of folk, rock, soul, jazz, and qawwali influences.\n\nReleased only one full studio album during his lifetime: *Grace* (1994), which received widespread critical acclaim and grew into a posthumous classic. His recording of Leonard Cohen's \"Hallelujah\" has become the definitive version for many listeners. Died at age 30 in a swimming accident in the Wolf River while working on his second album, *My Sweetheart the Drunk* (released posthumously in 1998 as *Sketches for My Sweetheart the Drunk*).",
  "jeff-lynnes-elo":
    "Touring and recording project led by Jeff Lynne, founder of Electric Light Orchestra. Adopted the \"Jeff Lynne's ELO\" branding starting around 2014 to distinguish the project from earlier ELO-affiliated touring acts.\n\nReleased *Alone in the Universe* (2015) and *From Out of Nowhere* (2019) under the Jeff Lynne's ELO banner. The 2024 tour was announced as the project's final outing. Lynne is also a celebrated producer (the Traveling Wilburys, George Harrison's *Cloud Nine*, Tom Petty's *Full Moon Fever* and *Into the Great Wide Open*).",
  "jerry-cantrell":
    "American guitarist, vocalist, and songwriter born March 18, 1966, in Tacoma, Washington. Co-founding member, lead guitarist, and primary songwriter for Alice in Chains (1987-present). Distinguished by his sludgy, harmonized riffing and his vocal harmonies with the late Layne Staley.\n\nReleased four solo albums alongside his Alice in Chains work: *Boggy Depot* (1998), *Degradation Trip* (2002), *Brighten* (2021), and *I Want Blood* (2024). His solo work draws on classic rock and country influences less prominent in Alice in Chains material.",
  "jess-and-the-ancient-ones":
    "Finnish occult rock band formed in Kuopio in 2010. Lineup centered on vocalist Jasmin \"Jess\" Saarela. Style draws on 1970s psychedelic rock, doom, and proto-metal, with lyrical themes oriented around mysticism and esoterica.\n\nFour studio albums between *Jess and the Ancient Ones* (2012) and *Vertigo* (2023). Critical peak: *Second Psychedelic Coming: The Aquarius Tapes* (2015) and *The Horse and Other Weird Tales* (2017). Released on Svart Records.",
  "jewel":
    "American singer-songwriter born Jewel Kilcher on May 23, 1974, in Payson, Utah. Raised on a homestead in Homer, Alaska. Among the best-selling debut artists of the 1990s, with *Pieces of You* (1995) eventually selling over 12 million copies in the US.\n\nReleased 12 studio albums spanning folk-pop, country, lullaby, and Christmas genres. Best-known singles include \"Who Will Save Your Soul,\" \"You Were Meant for Me,\" and \"Foolish Games.\" A two-time New York Times bestselling author (*A Night Without Armor* poetry collection, 1998; memoir *Never Broken*, 2015).",
  "jim-donovan-sun-king-warriors":
    "American rock band led by Jim Donovan, former drummer for Pittsburgh rock band Rusted Root (1990-2005). Donovan handles vocals, percussion, and guitar; the project blends roots rock, world music influences, and meditative drumming.\n\nReleased *Show Your Light* (2019). Donovan is also active as a meditation teacher and author of *Rhythm Recovery* (2024). Based in western Pennsylvania.",
  "jim-steinman":
    "American songwriter, composer, and producer born Jim Schultz on November 1, 1947, in Hyde Park, New York; died April 19, 2021. Best known for his collaborative work with Meat Loaf (*Bat Out of Hell*, 1977; *Bat Out of Hell II: Back into Hell*, 1993).\n\nWrote and produced major hits for Bonnie Tyler (\"Total Eclipse of the Heart,\" 1983), Air Supply (\"Making Love Out of Nothing at All,\" 1983), and Celine Dion (\"It's All Coming Back to Me Now,\" 1996). The 1981 solo album *Bad for Good* was originally intended as the Meat Loaf follow-up to *Bat Out of Hell*. The stage musical *Bat Out of Hell: The Musical* premiered in 2017. Died at age 73 of kidney failure.",
  "jimi-hendrix-experience":
    "British-American rock band formed in London in 1966 by guitarist Jimi Hendrix (American, b. November 27, 1942; d. September 18, 1970), bassist Noel Redding (British, b. 1945; d. 2003), and drummer Mitch Mitchell (British, b. 1946; d. 2008). Among the most influential rock bands of the 1960s, transforming the role of the electric guitar in popular music.\n\nThree studio albums in two years: *Are You Experienced* (1967), *Axis: Bold as Love* (1967), and *Electric Ladyland* (1968). The group dissolved in mid-1969 amid tensions between Hendrix and Redding. Hendrix performed at Woodstock in August 1969 with the Gypsy Sun and Rainbows band, but a brief 1970 Experience reunion (with Billy Cox on bass) was cut short by Hendrix's death from barbiturate-related asphyxiation. Inducted into the Rock and Roll Hall of Fame in 1992.",
  "jimmies-chicken-shack":
    "American alternative rock band formed in Annapolis, Maryland in 1990. Long-running lineup centered on vocalist Jimi Haha (born Jimi Davies). Style draws on funk-influenced post-grunge and ska-influenced alternative rock.\n\nFour studio albums between *Pushing the Salmanilla Envelope* (1997) and *Fail Forward Fall* (2004), with a long gap before *Triangulating the Yellow Diamond* (2022). Best-known single: \"High\" (1997). Continues to perform in the mid-Atlantic region.",
  "joan-baez":
    "American folk singer, songwriter, and activist born January 9, 1941, in Staten Island, New York. Among the most influential folk performers of the 1960s, with a soprano voice and a six-decade-plus catalog spanning English folk ballads, American protest songs, Latin American material, and original compositions.\n\nReleased over 30 studio albums starting with *Joan Baez* (1960). Best-known recordings include \"Diamonds & Rust\" (1975), her cover of \"The Night They Drove Old Dixie Down\" (1971), and her interpretations of Bob Dylan material. Inducted into the Rock and Roll Hall of Fame in 2017. Retired from touring in 2019.",
  "joan-osborne":
    "American singer-songwriter born July 8, 1962, in Anchorage, Kentucky. Blue-eyed-soul-influenced vocalist whose major-label debut *Relish* (1995) sold over four million copies in the US and featured the Grammy-nominated single \"One of Us.\"\n\nReleased nine studio albums between *Relish* and *Trouble and Strife* (2020), including the Dylan-cover album *Songs of Bob Dylan* (2017). Toured with the surviving members of the Grateful Dead as part of the Dead in 2003. Continues to record and tour.",
  "joo-gilberto":
    "Same artist as João Gilberto — variant character encoding. Brazilian singer, guitarist, and songwriter born João Gilberto Prado Pereira de Oliveira on June 10, 1931, in Juazeiro, Bahia; died July 6, 2019. Architect of the bossa nova style and one of the most influential figures in 20th-century Brazilian music.\n\nReleased the foundational *Chega de Saudade* (1959), establishing the gentle vocal phrasing and syncopated nylon-string guitar pattern that defined bossa nova. The Stan Getz collaboration *Getz/Gilberto* (1964) introduced bossa nova to a global audience and won the Grammy for Album of the Year (1965); the album includes \"The Girl from Ipanema,\" sung by his then-wife Astrud Gilberto. Continued recording into the 2000s.",
  "job-for-a-cowboy":
    "American death metal band formed in Glendale, Arizona in 2003. Long-running lineup centered on vocalist Jonny Davy. Began as a deathcore act before shifting toward technical/progressive death metal across their catalog.\n\nFour studio albums between *Genesis* (2007) and *Sun Eater* (2014), with the comeback *Moon Healer* (2024) following a decade-long studio gap. Released on Metal Blade Records.",
  "joe-jacksons-jumpin-jive":
    "Side project of English singer-songwriter Joe Jackson (b. 1954). The 1981 album *Jumpin' Jive* paid tribute to the jump blues and swing era of the late 1930s and early 1940s, including covers of Cab Calloway, Louis Jordan, and Lester Young material.\n\nJackson assembled a horn-heavy band for the album, which marked a sharp stylistic detour from his new-wave-era work (*Look Sharp!*, 1979). The project briefly toured before Jackson returned to original material with *Night and Day* (1982).",
  "joe-nuxhall":
    "American baseball player and broadcaster born July 30, 1928, in Hamilton, Ohio; died November 15, 2007. Famous for being the youngest player in Major League Baseball history (15 years, 316 days, June 10, 1944, for the Cincinnati Reds). Subsequently a 16-year MLB pitcher and a beloved Cincinnati Reds radio broadcaster (1967-2007).\n\nThe Joe Nuxhall recordings in record collections typically refer to spoken-word baseball albums or compilation appearances rather than music recordings in the traditional sense.",
  "joe-satriani":
    "American guitarist born July 15, 1956, in Westbury, New York. Among the most commercially successful instrumental rock guitarists, with over 10 million albums sold worldwide. Distinguished by his fluent legato technique and his role as guitar teacher to Steve Vai, Kirk Hammett, Larry LaLonde, Alex Skolnick, and many others.\n\nReleased 19 studio albums starting with *Not of This Earth* (1986). Critical and commercial peak: *Surfing with the Alien* (1987), one of the few instrumental rock albums to achieve platinum certification. Founded the G3 instrumental rock touring concept (1996-present) and joined the supergroup Chickenfoot with Sammy Hagar and Michael Anthony (2008-2017).",
  "joe-walsh":
    "American guitarist, singer, and songwriter born November 20, 1947, in Wichita, Kansas. Member of the James Gang (1968-1971), the Eagles (1975-1980, 1994-present), and Barnstorm (1972-1974). Distinguished by his slide-guitar technique and his dry, self-deprecating sense of humor.\n\nReleased over a dozen solo albums between *Barnstorm* (1972) and *Analog Man* (2012). Best-known solo single: \"Life's Been Good\" (1978). Joined the Eagles for *Hotel California* (1976), contributing the title-track guitar solo. Inducted into the Rock and Roll Hall of Fame as a member of the Eagles in 1998.",
  "joey-mcintyre":
    "American singer, actor, and dancer born December 31, 1972, in Needham, Massachusetts. Youngest member of the boy band New Kids on the Block (1985-1994, 2007-present).\n\nReleased six solo studio albums between *Stay the Same* (1999) and *Bring it Home* (2024). Best-known solo single: \"Stay the Same\" (1999). Continues to perform with New Kids on the Block and to record solo material.",
  "john-barry":
    "British film composer, conductor, and arranger born John Barry Prendergast on November 3, 1933, in York; died January 30, 2011. Best known for composing 11 James Bond film scores between *Dr. No* (1962, arranged) and *The Living Daylights* (1987), establishing the iconic \"James Bond Theme\" arrangement.\n\nWon five Academy Awards: *Born Free* (1966, two awards), *The Lion in Winter* (1968), *Out of Africa* (1985), and *Dances with Wolves* (1990). Composed over 100 film and television scores. Awarded the OBE in 1999.",
  "john-mellencamp":
    "American singer-songwriter born October 7, 1951, in Seymour, Indiana. Performed under the names Johnny Cougar, John Cougar, John Cougar Mellencamp, and finally John Mellencamp. Distinguished by heartland-rock songwriting drawing on small-town American life.\n\nReleased over 25 studio albums starting with *Chestnut Street Incident* (1976). Commercial peak: *American Fool* (1982, featuring \"Jack & Diane\" and \"Hurts So Good\"), *Uh-Huh* (1983), and *Scarecrow* (1985). Co-founded Farm Aid with Willie Nelson and Neil Young in 1985. Inducted into the Rock and Roll Hall of Fame in 2008.",
  "john-sebastian":
    "American singer-songwriter and multi-instrumentalist born March 17, 1944, in Greenwich Village, New York. Co-founding member, lead vocalist, and primary songwriter for the Lovin' Spoonful (1965-1968). Distinguished by his good-time folk-rock songwriting and autoharp playing.\n\nReleased six solo studio albums starting with *John B. Sebastian* (1970). Best-known solo single: \"Welcome Back\" (1976), the theme song from the sitcom *Welcome Back, Kotter* and his only #1 hit. Inducted into the Rock and Roll Hall of Fame as a member of the Lovin' Spoonful in 2000.",
  "john-wesley-harding":
    "Stage name of English singer-songwriter Wesley Stace, born October 22, 1965, in Hastings, East Sussex. Adopted the stage name (a reference to the 1968 Bob Dylan album) for his musical career starting in the late 1980s; uses his birth name for his novel-writing career.\n\nReleased over a dozen studio albums between *Here Comes the Groom* (1990) and *Pleased and Thank You* (2020). Author of four novels including *Misfortune* (2005) and *Charles Jessold, Considered as a Murderer* (2011). Hosts the Cabinet of Wonders variety show in New York.",
  "johnny-cash-and-tennessee-two":
    "Same artist as Johnny Cash and the Tennessee Two — credit variation. Johnny Cash's original backing duo: Luther Perkins (electric guitar, 1928-1968) and Marshall Grant (upright bass, 1928-2011). The trio recorded for Sun Records (1955-1958) and later Columbia (from 1958), establishing the spare \"boom-chicka-boom\" rhythm that defined Cash's early sound.\n\nKey Sun Records sessions yielded \"Cry! Cry! Cry!\" (1955), \"Folsom Prison Blues\" (1955), \"I Walk the Line\" (1956), and \"Big River\" (1958). The duo expanded to the Tennessee Three with the addition of drummer W.S. Holland in 1960.",
  "johnny-cash-and-the-tennessee-two":
    "Johnny Cash's original backing duo: Luther Perkins (electric guitar, 1928-1968) and Marshall Grant (upright bass, 1928-2011). The trio recorded for Sun Records (1955-1958) and later Columbia (from 1958), establishing the spare \"boom-chicka-boom\" rhythm that defined Cash's early sound.\n\nKey Sun Records sessions yielded \"Cry! Cry! Cry!\" (1955), \"Folsom Prison Blues\" (1955), \"I Walk the Line\" (1956), and \"Big River\" (1958). Perkins died in a house fire in 1968; the duo expanded to the Tennessee Three with the addition of drummer W.S. Holland in 1960 and continued with Bob Wootton replacing Perkins on guitar.",
  "johnny-pate":
    "American jazz bassist, arranger, and composer born John W. Pate on December 5, 1923, in Chicago Heights, Illinois; died December 21, 2024. Best known as the arranger for Curtis Mayfield and the Impressions during their 1960s peak (\"People Get Ready,\" \"It's All Right\").\n\nReleased jazz albums under his own name including *Swingin' Flute* (1958). As a composer scored blaxploitation films including *Shaft in Africa* (1973) and *Bucktown* (1975). Active in Chicago studio work for decades.",
  "johnny-rivers":
    "American singer, songwriter, and guitarist born John Henry Ramistella on November 7, 1942, in New York City; raised in Baton Rouge, Louisiana. Adopted the stage name on the advice of Alan Freed. Distinguished by his electrified covers of folk and R&B material, recorded live in many cases at the Whisky a Go Go in Los Angeles.\n\nReleased over 25 studio albums. Best-known singles include \"Memphis\" (1964, a Chuck Berry cover), \"Mountain of Love\" (1964), \"Secret Agent Man\" (1966), \"Poor Side of Town\" (1966, his only #1), and \"Swayin' to the Music (Slow Dancin')\" (1977). Continues to perform.",
  "judy-mowatt":
    "Jamaican reggae singer born January 1, 1952, in Gordon Town, Jamaica. Member of the I Threes (with Rita Marley and Marcia Griffiths), Bob Marley and the Wailers' backing vocal trio from 1974 until Marley's death in 1981.\n\nReleased solo albums including *Black Woman* (1979, the first solo reggae album by a female artist to receive widespread international attention) and *Working Wonders* (1985), the latter earning a Grammy nomination — the first for a female reggae artist. Converted to Christianity in the 1990s and has primarily released gospel material since.",
  "julien-k":
    "American electronic rock band formed in Huntington Beach, California in 2003. Originally a side project of Orgy members Ryan Shuck (vocals) and Amir Derakh (guitar/programming), expanding to a full band with bassist Anthony \"Fu\" Valcic (later replaced) and drummer Frank Zummo (later of Sum 41).\n\nReleased *Death to Analog* (2009), *We're Here With You* (2012), and *California Noir* trilogy (2016-2019). The band has worked extensively with Linkin Park's Chester Bennington in his Dead by Sunrise side project (2009 album *Out of Ashes*).",
  "junior-wells":
    "American blues vocalist and harmonica player born Amos Wells Blakemore Jr. on December 9, 1934, in Memphis, Tennessee; died January 15, 1998. Long associated with guitarist Buddy Guy. Apprenticed in Chicago with Muddy Waters and Tampa Red.\n\nReleased the influential *Hoodoo Man Blues* (1965, the first Chicago blues album recorded specifically for the LP format) with Buddy Guy on guitar. Subsequent classics include *It's My Life, Baby!* (1966) and *Coming at You* (1968). Toured extensively with the Rolling Stones in 1970 and continued performing until shortly before his death from lymphoma.",
  "junior-wells-chicago-blues-band":
    "Junior Wells's working band for the landmark *Hoodoo Man Blues* (Delmark Records, 1965). The lineup included Junior Wells (vocals/harmonica), Buddy Guy (guitar, credited as \"Friendly Chap\" due to contractual issues with Chess Records), Jack Myers (bass), and Bill Warren (drums).\n\nThe album was the first Chicago blues LP recorded explicitly as an album rather than as a singles collection, and its sound has been widely cited as foundational to the modern Chicago blues sound.",
  "jurassic-5":
    "American hip-hop group formed in Los Angeles in 1993. Lineup: Chali 2na, Akil, Zaakir, and Mark 7even on vocals, with Cut Chemist and DJ Nu-Mark on production/turntables. Distinguished by their old-school four-MC approach and crate-digging production aesthetic.\n\nFour studio albums between *Jurassic 5* (1998) and *Feedback* (2006). Critical peak: *Quality Control* (2000) and *Power in Numbers* (2002). The group disbanded in 2007 and reunited for several tours starting in 2013.",
  "karas-flowers":
    "American pop-rock band formed in Los Angeles in 1994 by high-school friends Adam Levine (vocals/guitar), Jesse Carmichael (guitar/keyboards), Mickey Madden (bass), and Ryan Dusick (drums). Released the album *We Like Digging?* (1995, self-released) and *The Fourth World* (1997, Reprise) before being dropped by Reprise.\n\nThe band reformed with guitarist James Valentine in 2001, changing their name to Maroon 5 and signing to Octone Records. *Songs About Jane* (2002) launched the renamed group's commercial breakthrough.",
  "karl-hendricks-trio":
    "American indie rock band formed in Pittsburgh in 1991 by Karl Hendricks (vocals/guitar, 1970-2017). Style draws on lo-fi indie rock and noisy guitar-driven songwriting comparable to Built to Spill and the Silver Jews.\n\nReleased seven studio albums between *Buick Electra* (1992) and *The Adult Section* (2001). Subsequent work was released as the Karl Hendricks Rock Band. Hendricks died at age 46 in 2017 of throat cancer. His record store, Sound Cat Records, remains a Pittsburgh fixture under new ownership.",
  "keb-mo":
    "American blues guitarist and singer-songwriter born Kevin Roosevelt Moore on October 3, 1951, in Compton, California. Distinguished by his country-blues fingerpicking style and his contemporary songwriting drawing on classic Delta blues forms.\n\nReleased over 15 studio albums starting with *Keb' Mo'* (1994). Five Grammy Awards including Best Contemporary Blues Album for *Keb' Mo'* (1997), *Slow Down* (1999), *Keep It Simple* (2005), *Oklahoma* (2020), and *Good to Be...* (2023). Played Robert Johnson in the documentary *Can't You Hear the Wind Howl?* (1997).",
  "kelsy-karter-the-heroines":
    "American rock band led by New Zealand-born vocalist Kelsy Karter (born Kelsy Karter Smith, c. 1991). Style draws on glam rock, classic rock, and 1970s-influenced power-pop.\n\nReleased *Missing Person* (2022) and *The Coming of Age* (2024). Earned brief viral attention in 2019 for a publicity stunt involving a tattoo of Harry Styles's face, which the artist later confirmed was a temporary tattoo.",
  "kenny-g":
    "American saxophonist born Kenneth Bruce Gorelick on June 5, 1956, in Seattle, Washington. Among the best-selling instrumental musicians in history, with estimated worldwide sales of 75 million-plus units. The dominant figure in smooth jazz from the late 1980s onward.\n\nReleased over a dozen studio albums starting with *Kenny G* (1982). Commercial peak: *Duotones* (1986, featuring \"Songbird\"), *Silhouette* (1988), *Breathless* (1992, the best-selling instrumental album of all time at over 15 million US copies), and *Miracles: The Holiday Album* (1994). Won the Guinness World Record in 1997 for the longest sustained note on a saxophone (45 minutes 47 seconds, using circular breathing).",
  "kerry-livgren":
    "American guitarist, keyboardist, and songwriter born September 18, 1949, in Topeka, Kansas. Founding member and primary songwriter for Kansas (1973-1983, 1990-1991), responsible for the band's progressive-rock-meets-heartland-rock signature material including \"Carry On Wayward Son\" and \"Dust in the Wind.\"\n\nReleased solo albums starting with *Seeds of Change* (1980, featuring Ronnie James Dio on vocals). Converted to Christianity in 1979 and his subsequent solo work increasingly explored Christian themes. Suffered a stroke in 2009 that limited his playing; continues to write and produce.",
  "kid-n-play":
    "American hip-hop duo formed in New York City in 1986. Lineup: Christopher \"Kid\" Reid (vocals, known for his high-top fade haircut) and Christopher \"Play\" Martin (vocals). Distinguished by their family-friendly, dance-oriented hip-hop and their crossover into film with the *House Party* franchise (1990-1994).\n\nThree studio albums between *2 Hype* (1988) and *Face the Nation* (1991). Best-known singles include \"Rollin' with Kid 'N Play\" (1988), \"Gittin' Funky\" (1989), and \"Ain't Gonna Hurt Nobody\" (1990). The duo also starred in an NBC Saturday-morning cartoon series (1990-1991).",
  "kid-rock":
    "American singer-songwriter born Robert James Ritchie on January 17, 1971, in Romeo, Michigan. Distinguished by genre-blending material combining hip-hop, hard rock, country, and Southern rock.\n\nReleased 12 studio albums starting with *Grits Sandwiches for Breakfast* (1990). Commercial peak: *Devil Without a Cause* (1998, diamond-certified, featuring \"Bawitdaba\" and \"Cowboy\") and *Rock n Roll Jesus* (2007, featuring \"All Summer Long\"). Has become increasingly politically active in the 2010s and 2020s, frequently aligning with conservative causes.",
  "kid606":
    "American electronic musician born Miguel Manuel De Pedro on November 21, 1979, in Caracas, Venezuela; raised in San Diego. Style draws on glitch, breakcore, IDM, and digital hardcore.\n\nReleased over 20 studio albums starting with *Don't Sweat the Technics* (1998). Critical peak: *Down with the Scene* (2000), *PS I Love You* (2000), and *Pretty Girls Make Raves* (2006). Founder of the Tigerbeat6 record label, which released material by Cex, Lesser, and Numbers among others.",
  "kilgore":
    "American metal band formed in Worcester, Massachusetts in 1995 (originally as Kilgore Smudge). Long-running lineup centered on Jay Berndt (vocals). Style draws on groove metal and hardcore-influenced heavy metal in the vein of Pantera and Sepultura.\n\nThree studio albums between *A Search for Reason* (1998) and *Blue Collar Solitude* (2001). Toured with bands including Slayer and Sevendust. The band dissolved in 2001 but reunited intermittently afterward.",
  "king-crimson":
    "English progressive rock band formed in London in 1968 by Robert Fripp (guitar) and Ian McDonald (multi-instrumentalist). Distinguished by their constantly evolving lineup (over 20 members across their history) and stylistic restlessness, ranging from symphonic prog to jazz fusion to industrial-leaning rock.\n\nReleased 13 studio albums between *In the Court of the Crimson King* (1969) and *The Power to Believe* (2003). Critical peaks across multiple eras: the original (*In the Court of the Crimson King*), the mid-1970s lineup with John Wetton and Bill Bruford (*Larks' Tongues in Aspic*, 1973; *Red*, 1974), and the 1980s lineup with Adrian Belew and Tony Levin (*Discipline*, 1981). The band ended touring in 2021; Fripp remains the only constant member across their history.",
  "kip-winger":
    "American singer, bassist, and composer born Charles Frederick Kip Winger on June 21, 1961, in Denver, Colorado. Co-founding member, lead vocalist, bassist, and primary songwriter for Winger (1987-present). Distinguished by formal classical training and his current dual career as a contemporary classical composer.\n\nReleased three solo albums between *This Conversation Seems Like a Dream* (1997) and *Songs from the Ocean Floor* (2014). Composed *Conversations With Nijinsky* (2016) and *C. F. Kip Winger: Ghosts* (2024) for the San Francisco Ballet and other classical ensembles, receiving a 2017 Grammy nomination for the former.",
  "la-guns":
    "American hard rock band formed in Los Angeles in 1983 by guitarist Tracii Guns. Original lineup briefly included Axl Rose before his departure to co-found Guns N' Roses (which took its name partly from L.A. Guns). Long-running lineup eventually centered on Tracii Guns and vocalist Phil Lewis.\n\nReleased over a dozen studio albums starting with *L.A. Guns* (1988). Commercial peak: *Cocked & Loaded* (1989, featuring the ballad \"The Ballad of Jayne\"). The band has frequently split into competing lineups led by Guns and Lewis respectively before reuniting in 2017.",
  "les-stitches":
    "American punk rock band formed in Manhattan in 1992 (officially L.E.S. Stitches, for Lower East Side). Long-running lineup centered on guitarist/vocalist Mick Stitch and bassist/vocalist J Boy. Style draws on 1970s glam and punk, including New York Dolls and Hanoi Rocks influences.\n\nReleased *Tonight! Tonight!* (1997) and *Last Punk Standing* (2009). Spent considerable time touring during the late-1990s punk-rock revival.",
  "la-bouche":
    "German-American Eurodance duo formed in Frankfurt in 1992. Lineup: American vocalist Melanie Thornton (1967-2001) and American rapper Lane McCray. Style typifies the early/mid-1990s Eurodance sound — uptempo synthesizer production, female-led pop vocals, and male rap verses.\n\nTwo studio albums between *Sweet Dreams* (1995, multi-platinum, featuring the title track and \"Be My Lover\") and *S.O.S.* (1998). Thornton left the duo in 2000 to pursue a solo career and died in the Crossair Flight 3597 crash in November 2001. McCray continues the project with various replacement vocalists.",
  "larry-the-cable-guy":
    "American stand-up comedian, actor, and country music singer born Daniel Lawrence Whitney on February 17, 1963, in Pawnee City, Nebraska. Performs in character as a Southern blue-collar everyman whose catchphrase is \"Git-R-Done.\" Member of the Blue Collar Comedy Tour with Jeff Foxworthy, Bill Engvall, and Ron White (2000-2003).\n\nReleased a series of stand-up comedy albums (some with country-music elements) starting with *Lord, I Apologize* (2001). Voiced Mater in the *Cars* film franchise (2006-present).",
  "laura-cantrell":
    "American country and folk singer born March 17, 1967, in Nashville, Tennessee. Longtime DJ for the WFMU radio program *The Radio Thrift Shop* (1993-2005). Distinguished by her thoughtful interpretations of vintage country and original songwriting in a similar idiom.\n\nReleased five studio albums between *Not the Tremblin' Kind* (2000) and *No Way There From Here* (2014). Late John Peel called her debut \"my favorite record of the last 10 years and possibly my life.\" Continues to perform and to DJ occasionally.",
  "lauryn-hill":
    "American singer, songwriter, and rapper born May 26, 1975, in East Orange, New Jersey. Member of the Fugees (1992-1997, occasional reunions). One of the most acclaimed solo debuts in hip-hop history with *The Miseducation of Lauryn Hill* (1998).\n\n*The Miseducation of Lauryn Hill* sold over 19 million copies worldwide and won five Grammy Awards including Album of the Year and Best New Artist (1999); Hill became the first woman to win five Grammys in a single night. Released only one further full-length, the live *MTV Unplugged No. 2.0* (2002). Continues to tour intermittently; an album-length follow-up has been long-promised but never released.",
  "leahy":
    "Canadian Celtic music ensemble of siblings from Lakefield, Ontario. The Leahy family includes 11 children, of whom 8 became founding members of the touring band. The lineup has shifted over time as some siblings departed and others joined.\n\nReleased six studio albums between *Leahy* (1997) and *In All Things: A Celtic Christmas* (2014). The 1997 self-titled debut won three Juno Awards. Continues to tour through Canada, the US, and the UK.",
  "lemonheads":
    "American alternative rock band formed in Boston in 1986. Long-running lineup centered on Evan Dando (vocals/guitar). Began as a hardcore-influenced punk band before shifting toward power-pop and college-rock starting around 1990.\n\nReleased 10 studio albums between *Hate Your Friends* (1987) and *Love Chord* (2025). Commercial peak: *It's a Shame About Ray* (1992) and *Come On Feel the Lemonheads* (1993). Best-known singles: \"Mrs. Robinson\" (1992, a cover) and \"Into Your Arms\" (1993). The 2025 release marks the first new Lemonheads studio material since *Varshons 2* (2019).",
  "lenny-kravitz":
    "American singer, songwriter, and multi-instrumentalist born Leonard Albert Kravitz on May 26, 1964, in New York City. Distinguished by his retro-rock production aesthetic drawing on Hendrix, Stevie Wonder, and Led Zeppelin influences, and by his typically performing all instruments on his recordings.\n\nReleased 12 studio albums starting with *Let Love Rule* (1989). Commercial peak: *Are You Gonna Go My Way* (1993), *Mama Said* (1991), and *5* (1998, featuring \"Fly Away\"). Four consecutive Best Male Rock Vocal Performance Grammys (1999-2002), a record in that category.",
  "leslie-west":
    "American guitarist, vocalist, and songwriter born Leslie Weinstein on October 22, 1945, in Forest Hills, New York; died December 23, 2020. Co-founding member of Mountain (1969-1971, 1973-1985, intermittent reunions) and the West, Bruce and Laing supergroup with Jack Bruce and Corky Laing (1972-1974). Distinguished by his big-toned blues-rock guitar style.\n\nReleased over a dozen solo studio albums between *Mountain* (1969, a Felix Pappalardi production credited as a Leslie West solo album that effectively launched the Mountain band) and *Soundcheck* (2015). Best-known recording: \"Mississippi Queen\" (1970, with Mountain). Had his right leg amputated below the knee in 2011 due to complications from diabetes. Died at age 75 of a heart attack.",
  "lets-go-bowling":
    "American third-wave ska band formed in Fresno, California in 1986. Among the longest-running American ska bands. Style draws on traditional ska and rocksteady more than the punk-ska hybrid common in the 1990s third-wave revival.\n\nReleased five studio albums between *Music to Bowl By* (1991) and *Stretch a Mile* (2024). Toured with bands including the Skatalites, the Toasters, and the Mighty Mighty Bosstones.",
  "letlive":
    "American post-hardcore band formed in Inglewood, California in 2002 (officially stylized letlive., with the trailing period). Long-running lineup centered on vocalist Jason Aalon Butler. Distinguished by Butler's incendiary stage presence and lyrics frequently engaging racial and social themes.\n\nFour studio albums between *Speak Like You Talk* (2005) and *If I'm the Devil...* (2016). Critical peak: *Fake History* (2010) and *The Blackest Beautiful* (2013). The band went on hiatus in 2017; Butler has since led Fever 333.",
  "letters-to-cleo":
    "American power-pop band formed in Boston in 1990. Long-running lineup centered on Kay Hanley (vocals) and Greg McKenna (guitar). Distinguished by Hanley's bright pop vocals and the band's appearance in the 1999 teen comedy *10 Things I Hate About You*.\n\nFour studio albums between *Aurora Gory Alice* (1993) and *Go!* (1997), with reunion EPs starting in 2016. Best-known single: \"Here & Now\" (1994, featured on the *Melrose Place* soundtrack). Hanley has also done extensive voice work for *Doc McStuffins* and other Disney productions.",
  "link-wray-the-raymen":
    "Link Wray's longtime backing band, formed in 1958 around Wray (guitar, b. 1929, d. 2005), brother Vernon Wray (vocals/rhythm guitar), brother Doug Wray (drums), and Shorty Horton (bass). Wray's distorted, power-chord-driven instrumental \"Rumble\" (1958) was famously banned by some radio stations for allegedly inciting juvenile delinquency despite having no lyrics.\n\nThe Raymen backed Wray throughout the late 1950s and 1960s on Cadence, Epic, and Swan Records. Subsequent classics include \"Rawhide\" (1959), \"Jack the Ripper\" (1960), and the title-track instrumental from *Big City After Dark* (1959). Wray's power-chord approach is widely credited as foundational to heavy rock, garage rock, and punk.",
  "lit":
    "American rock band formed in Fullerton, California in 1988 (originally as Razzle). Lineup: brothers A. Jay Popoff (vocals) and Jeremy Popoff (guitar), Kevin Baldes (bass), and various drummers (Allen Shellenberger died of brain cancer in 2009; he was replaced by Nathan Walker).\n\nFour studio albums starting with *Tripping the Light Fantastic* (1997). Commercial peak: *A Place in the Sun* (1999, multi-platinum, featuring \"My Own Worst Enemy\"). Has shifted increasingly toward country-rock on later releases.",
  "little-anthony-the-imperials":
    "American R&B and doo-wop group formed in Brooklyn in 1957. Lineup historically centered on Jerome Anthony \"Little Anthony\" Gourdine (vocals, b. January 8, 1941). Distinguished by Gourdine's distinctive high tenor lead.\n\nReleased numerous singles starting with \"Tears on My Pillow\" (1958). Best-known hits include \"Shimmy, Shimmy, Ko-Ko-Bop\" (1959), \"Goin' Out of My Head\" (1964), and \"Hurt So Bad\" (1965). Inducted into the Rock and Roll Hall of Fame in 2009 and the Vocal Group Hall of Fame in 2001.",
  "living-sacrifice":
    "American metal band formed in Little Rock, Arkansas in 1989. Long-running lineup centered on Bruce Fitzhugh (vocals/guitar). Began as a thrash metal band and shifted toward death metal and then groove metal/metalcore across their career. A Christian-affiliated act.\n\nNine studio albums between *Living Sacrifice* (1991) and *Ghost Thief* (2013), with the comeback *Through The Storm* (2024) following an 11-year studio gap. Critical peak: *Reborn* (1997) and *The Hammering Process* (2000).",
  "liz-phair":
    "American singer-songwriter born April 17, 1967, in New Haven, Connecticut. Raised in Winnetka, Illinois. Distinguished by frank, sexually explicit lyrics and a lo-fi, double-tracked vocal aesthetic on her early work.\n\nReleased seven studio albums starting with *Exile in Guyville* (1993), a song-by-song response to the Rolling Stones' *Exile on Main St.* and one of the most acclaimed indie-rock debuts of the 1990s. Subsequent peaks: *Whip-Smart* (1994) and *whitechocolatespaceegg* (1998). The 2003 self-titled album marked a polarizing pivot toward mainstream pop-rock. Returned with *Soberish* (2021).",
  "local-h":
    "American rock band formed in Zion, Illinois in 1987. Long-running duo of Scott Lucas (vocals/guitar/bass — performed simultaneously via a modified guitar with bass pickup) and a series of drummers (currently Ryan Harding). Distinguished by their two-piece power format and Lucas's unique bass/guitar setup.\n\nNine studio albums between *Ham Fisted* (1995) and *Lifers* (2020). Commercial peak: *As Good as Dead* (1996, featuring \"Bound for the Floor\"). Continues to tour extensively.",
  "london-festival-orchestra":
    "British studio orchestra used primarily for soundtrack recordings and pops/classical crossover albums. The London Festival Orchestra has been credited on numerous film scores, exotica albums, and easy-listening recordings since the 1950s.\n\nNot to be confused with the unrelated London Festival Orchestra founded in 1983 by Ross Pople (which focuses on traditional classical repertoire). The studio name has been used as a credit by various British orchestral session collectives.",
  "lonnie-mack":
    "American blues guitarist and vocalist born Lonnie McIntosh on July 18, 1941, in Aurora, Indiana; died April 21, 2016. Pioneer of the lead-guitar instrumental style; his 1963 recording of \"Memphis\" (a Chuck Berry cover) is widely cited as one of the first lead-guitar instrumental hits, influencing Stevie Ray Vaughan and Eric Clapton among many others.\n\nReleased over a dozen studio albums starting with *The Wham of That Memphis Man!* (1963). Subsequent peaks: *Strike Like Lightning* (1985, produced by Stevie Ray Vaughan). Continued to perform until shortly before his death from natural causes at age 74.",
  "lords-of-acid":
    "Belgian electronic body music and acid house group formed in Antwerp in 1988. Long-running lineup centered on Maurice \"Praga Khan\" Engelen. Distinguished by sexually explicit lyrics and album artwork. Founding member of the broader Antwerp-based Praga Khan / Digital Poodle production circle.\n\nReleased seven studio albums between *Lust* (1991) and *Pretty in Kink* (2018). Best-known tracks include \"I Sit on Acid\" (1988) and \"Pussy\" (1997). Multiple vocalists have led the group over the decades, including Ruth McArdle, Deborah Ostrega, and Marieke Bresseleers.",
  "los-lobos":
    "American rock band formed in East Los Angeles in 1973. Long-running lineup: David Hidalgo (vocals/guitar/accordion), Cesar Rosas (vocals/guitar), Conrad Lozano (bass), Louie Pérez (drums/guitar), and Steve Berlin (saxophone/keyboards, since 1984). Distinguished by their fluent integration of Tex-Mex, traditional Mexican music, Tejano, blues, country, and rock.\n\nOver 15 studio albums between *Los Lobos del Este de Los Angeles* (1978) and *Native Sons* (2021). Commercial peak: the *La Bamba* soundtrack (1987, featuring the band's #1 cover of Ritchie Valens's title track). Critical peaks: *How Will the Wolf Survive?* (1984), *By the Light of the Moon* (1987), and *Kiko* (1992). Three Grammy Awards.",
  "louie-bellson-orchestra":
    "Big band led by American jazz drummer Luigi Paulino Alfredo Francesco Antonio Balassoni, known professionally as Louie Bellson (1924-2009). Distinguished by being among the first to feature the double bass drum kit and by Bellson's role as composer of works including \"Skin Deep\" (1952) and \"The Hawk Talks\" (1951).\n\nBellson led various big-band formations under his own name throughout his career while also playing in the orchestras of Duke Ellington, Tommy Dorsey, and Harry James. Multiple Grammy nominations across his catalog.",
  "love":
    "American rock band formed in Los Angeles in 1965. Long-running lineup centered on Arthur Lee (vocals/guitar, 1945-2006). Bryan MacLean (guitar/vocals, 1946-1998) contributed prominently to the early albums. Distinguished by their stylistic restlessness — folk-rock, psychedelia, garage rock, and orchestrated pop across their catalog.\n\nSeven studio albums between *Love* (1966) and *Reel to Real* (1974). Critical peak: *Forever Changes* (1967), widely regarded as one of the greatest albums of the 1960s but commercially unsuccessful at the time. Lee was incarcerated 1996-2001 on a firearms conviction; reunited Love briefly thereafter. Died in 2006 of acute myeloid leukemia.",
  "lovehate":
    "American hard rock band formed in Los Angeles in 1985. Long-running lineup centered on Jizzy Pearl (vocals). Distinguished by their late-arrival to the LA hard-rock scene and a darker tone compared to most Sunset Strip contemporaries.\n\nFive studio albums between *Blackout in the Red Room* (1990) and *Crucified* (2010). The Sony major-label debut was well-received critically but commercially modest. Pearl has also led L.A. Guns and Ratt at various points.",
  "ludacris":
    "American rapper, actor, and entrepreneur born Christopher Brian Bridges on September 11, 1977, in Champaign, Illinois; raised in Atlanta. Distinguished by his rapid-fire delivery, comic punch lines, and prominent role in the Southern hip-hop explosion of the early 2000s.\n\nReleased 11 studio albums starting with *Incognegro* (2000, independent). Commercial peak: *Back for the First Time* (2000, Def Jam reissue of *Incognegro*), *Word of Mouf* (2001), *Chicken-N-Beer* (2003), and *Release Therapy* (2006, Grammy for Best Rap Album). Co-founded Disturbing tha Peace Records. Co-starred in the *Fast & Furious* franchise (2003-present) as Tej Parker.",
  "lukas-nelson-promise-of-the-real":
    "American country rock band formed in Hawaii in 2008. Lineup: Lukas Nelson (vocals/guitar, son of Willie Nelson, b. December 25, 1988), Anthony LoGerfo (drums), Corey McCormick (bass), and Logan Metz (keyboards). Distinguished by their close working relationship with Neil Young, including a long stint as his touring band (2014-2019) and contributions to *The Monsanto Years* (2015) and *Earth* (2016).\n\nReleased seven studio albums between *Promise of the Real* (2010) and *American Romance* (2025). Lukas Nelson co-produced the Bradley Cooper / Lady Gaga *A Star Is Born* soundtrack (2018) and appears in the film as a member of Cooper's backing band.",
  "luther-ingram":
    "American R&B singer-songwriter born Luther Thomas Ingram on November 30, 1937, in Jackson, Tennessee; died March 19, 2007. Best known for the deep-soul hit \"(If Loving You Is Wrong) I Don't Want to Be Right\" (1972).\n\nReleased six studio albums between *I've Been Here All the Time* (1972) and *Let's Steal Away to the Hideaway* (1976). \"(If Loving You Is Wrong)\" topped the R&B charts for four weeks and crossed over to #3 on the Billboard Hot 100. The song has been covered by Millie Jackson, Barbara Mandrell, Rod Stewart, and many others. Died at age 69 of complications from a long illness.",
  "machine-head":
    "American groove metal band formed in Oakland, California in 1991. Long-running lineup centered on Robb Flynn (vocals/guitar, formerly of Vio-lence). Distinguished by their thrash-metal-meets-groove approach and their longevity through the late-1990s and 2000s metalcore and nu-metal pivots.\n\nNine studio albums between *Burn My Eyes* (1994) and *Of Kingdom and Crown* (2022). Critical peak: *Burn My Eyes* (1994, one of the best-selling thrash-era debuts) and *The Blackening* (2007). Frequent lineup changes; Flynn is the only constant member.",
  "macy-gray":
    "American singer, songwriter, and actress born Natalie Renée McIntyre on September 6, 1967, in Canton, Ohio. Distinguished by her raspy, distinctive voice (sometimes compared to Billie Holiday) and by her crossover R&B-rock-soul style.\n\nReleased 10 studio albums starting with *On How Life Is* (1999, featuring the international hit \"I Try\"). Won the 2001 Grammy for Best Female Pop Vocal Performance for \"I Try.\" Has continued to record and tour extensively while building a parallel acting career (*Training Day*, 2001; *Spider-Man*, 2002; *The Paperboy*, 2012).",
  "man-will-surrender":
    "American Christian rock band formed in Tampa, Florida in the early 2000s. Long-running lineup centered on vocalist David Marian. Style draws on emo and post-hardcore. Released material primarily on Floodgate Records.\n\nReleased the self-titled debut *Man Will Surrender* (2003). The band has been intermittently active.",
  "manhole":
    "American hardcore/metal band formed in Los Angeles in 1989, fronted by vocalist Tairrie B (born Theresa Allen, b. 1965), formerly a Ruthless Records-signed rapper. The band later changed its name to Tura Satana (1998) after the actress, due to a UK band of the same name.\n\nReleased *All Is Not Well* (1996, Noise Records). Style draws on early nu-metal and hardcore. Tairrie B subsequently founded My Ruin in 1999 with her husband Mick Murphy.",
  "marc-cohn":
    "American singer-songwriter born July 5, 1959, in Cleveland, Ohio. Best known for the Grammy-winning \"Walking in Memphis\" (1991).\n\nReleased six studio albums between *Marc Cohn* (1991) and *Careful What You Dream: Lost Songs and Rarities* (2017). \"Walking in Memphis\" earned Cohn the 1992 Grammy for Best New Artist. Survived a 2005 attempted carjacking in Denver in which he was shot in the head; he made a full recovery and resumed touring.",
  "margo-price":
    "American country singer-songwriter born April 15, 1983, in Aledo, Illinois; based in Nashville. Distinguished by classic-country songwriting influences combined with autobiographical lyrics and a willingness to engage political themes.\n\nReleased four studio albums between *Midwest Farmer's Daughter* (2016, Jack White's Third Man Records) and *Strays II* (2024). Subsequent peaks: *All American Made* (2017), *That's How Rumors Get Started* (2020), and *Strays* (2023). Author of the 2022 memoir *Maybe We'll Make It*.",
  "mark-crozer-and-the-rels":
    "British rock band led by Mark Crozer, former member of the Jesus and Mary Chain (2006-2008 touring lineup). Crozer is also known for writing the WWE wrestler Bray Wyatt's entrance theme \"Live in Fear\" (2014).\n\nReleased *Sad Songs and Other Ways to Die* (2014) and *Pulled From the Wreckage* (2017). The Rels include various session and touring musicians on the recordings.",
  "mark-daly":
    "Irish singer-songwriter and guitarist (b. early 1990s, Cork). Best known as the guitarist for the Cork-based rock band Bonham (later renamed The Stunning) and for solo work drawing on classic rock and singer-songwriter influences.\n\nReleased the EP *Mark Daly EP* and the album *Vagabond* (2017). Has performed extensively in Irish and UK venues.",
  "mark-mcgrath":
    "American singer and television personality born March 15, 1968, in Hartford, Connecticut. Lead vocalist for Sugar Ray (1986-present). Distinguished by the late-1990s commercial peak of Sugar Ray and his subsequent role as a TV host on *Extra* (2008-2009) and *Don't Forget the Lyrics!* (2010).\n\nMcGrath has also performed as a solo artist on package tours featuring 1990s-2000s acts and has done extensive voice work and reality-TV appearances.",
  "marty-brennaman":
    "American baseball broadcaster born July 28, 1942, in Portsmouth, Virginia. Long-running radio play-by-play announcer for the Cincinnati Reds (1974-2019), succeeding Al Michaels. Famous for his signature \"And this one belongs to the Reds!\" home-victory call.\n\nThe Marty Brennaman recordings typically refer to compilation albums of his broadcast highlights from Reds games rather than music recordings in the traditional sense. Inducted into the National Baseball Hall of Fame (Ford C. Frick Award) in 2000.",
  "mary-wilson":
    "American singer born March 6, 1944, in Greenville, Mississippi; died February 8, 2021. Co-founding member of the Supremes (1959-1977), the longest-tenured member alongside Diana Ross and Florence Ballard.\n\nReleased solo albums including *Mary Wilson* (1979, Motown) and *Walk the Line* (1992). Co-authored the bestselling memoirs *Dreamgirl: My Life as a Supreme* (1986) and *Supreme Faith* (1990). Inducted into the Rock and Roll Hall of Fame as a member of the Supremes in 1988. Died at age 76 of hypertensive atherosclerotic cardiovascular disease.",
  "matchbox-twenty":
    "American rock band formed in Orlando, Florida in 1995. Long-running lineup: Rob Thomas (vocals), Kyle Cook (guitar), Paul Doucette (drums/guitar), Brian Yale (bass), and Adam Gaynor (guitar, until 2005). Distinguished by their adult-contemporary-leaning rock songwriting and Thomas's distinctive vocal style.\n\nFive studio albums between *Yourself or Someone Like You* (1996) and *Where the Light Goes* (2023). Commercial peak: *Yourself or Someone Like You* (diamond-certified, featuring \"Push,\" \"3AM,\" \"Real World,\" and \"Back 2 Good\") and *Mad Season* (2000, featuring \"Bent\" and \"If You're Gone\"). Thomas has also released solo albums during the band's hiatuses.",
  "maximum-penalty":
    "American hardcore band formed in New York City in 1988. Long-running lineup centered on vocalist Jimmy Williams. Among the longest-running NYHC bands, with a style drawing on the late-1980s NYHC sound (Agnostic Front, Sick of It All) and metallic hardcore.\n\nReleased four studio albums between *East Side Story* (1995) and *Life and Times* (2010). The band continues to perform intermittently in the New York hardcore scene.",
  "mc-hammer":
    "American rapper and dancer born Stanley Kirk Burrell on March 30, 1962, in Oakland, California. Acquired his stage name during a stint as an Oakland Athletics batboy due to his resemblance to Hammerin' Hank Aaron. Distinguished by his high-energy stage shows, parachute pants, and crossover commercial success that briefly made him the best-selling rapper of the early 1990s.\n\nReleased 10 studio albums starting with *Feel My Power* (1986). Commercial peak: *Please Hammer, Don't Hurt 'Em* (1990, diamond-certified, featuring \"U Can't Touch This\" and \"Pray\") — the first hip-hop album to be certified diamond. Filed for bankruptcy in 1996. Became an ordained minister in the late 1990s and continues to perform.",
  "mc-lars":
    "American rapper born Andrew Robert Nielsen on August 6, 1982, in Berkeley, California. Pioneer of the \"post-punk laptop rap\" or \"lit-hop\" genre, fusing hip-hop with pop-punk and emo influences and literary references (frequent songs about Edgar Allan Poe, Hemingway, *Hamlet*, etc.).\n\nReleased over a dozen studio albums starting with *The Laptop EP* (2004). Best-known tracks include \"Download This Song\" (2006) and \"This Gigantic Robot Kills\" (2009, featuring MC Frontalot). Tours extensively on the Warped Tour circuit and college campuses.",
  "mc5":
    "American rock band formed in Lincoln Park, Michigan in 1964. Long-running lineup: Rob Tyner (vocals, 1944-1991), Wayne Kramer (guitar, 1948-2024), Fred \"Sonic\" Smith (guitar, 1948-1994), Michael Davis (bass, 1943-2012), and Dennis Thompson (drums, 1948-2024). Distinguished by their proto-punk intensity and political activism, including association with John Sinclair's White Panther Party.\n\nThree studio albums during their original run: *Kick Out the Jams* (1969, recorded live), *Back in the USA* (1970), and *High Time* (1971). Critical peak: *Kick Out the Jams*, widely cited as foundational to punk rock. The band dissolved in 1972; all five original members died between 1991 and 2024. Inducted into the Rock and Roll Hall of Fame in 2024 (the same year Kramer and Thompson died).",
  "meatmen":
    "American hardcore punk band formed in Lansing, Michigan in 1980. Long-running lineup centered on Tesco Vee (born Bob Vermeulen, vocals). Distinguished by deliberately offensive humor in their lyrics — frequently homophobic, racist, and scatological satire intended as transgressive comedy.\n\nReleased seven studio albums between *We're the Meatmen... And You Suck!* (1983) and *Savage Sagas* (2014). Vee also founded *Touch and Go* fanzine and the early Touch and Go Records imprint (later sold to Corey Rusk, who built it into the influential indie label).",
  "meltbanana":
    "Japanese noise rock band formed in Tokyo in 1992 (officially stylized Melt-Banana). Long-running duo of Yasuko Onuki (vocals) and Ichirou Agata (guitar). Distinguished by Onuki's high-pitched yelping vocals and Agata's heavily-processed guitar work.\n\nNine studio albums between *Speak Squeak Creak* (1994) and *3+5* (2024, with new touring drummer Dani Hyde). Critical peak: *Charlie* (2003) and *Bambi's Dilemma* (2007). Frequent international touring partners include Tortoise, Mr. Bungle, and the Boredoms.",
  "melvins":
    "American rock band formed in Montesano, Washington in 1983. Long-running core: Buzz Osborne (vocals/guitar) and Dale Crover (drums). Distinguished by their genre-restless approach spanning sludge metal, hardcore, noise rock, and avant-garde. Major influence on grunge (particularly Nirvana — Kurt Cobain was an early roadie).\n\nOver 25 studio albums between *Gluey Porch Treatments* (1987) and *Tarantula Heart* (2024). Critical peaks across multiple eras: *Houdini* (1993, produced partly by Cobain), *Stoner Witch* (1994), and *(A) Senile Animal* (2006, the first of several with Big Business members in the lineup). One of the most prolific and consistently active bands in American underground rock.",
  "memphis-may-fire":
    "American metalcore band formed in Dallas, Texas in 2006. Long-running lineup centered on Matty Mullins (vocals, joined 2008). Style draws on contemporary metalcore with prominent clean vocals and electronic elements.\n\nSeven studio albums between *Sleepwalking* (2009) and *Remade in Misery* (2022). Commercial peak: *Challenger* (2012), *Unconditional* (2014), and *This Light I Hold* (2016). Signed to Rise Records.",
  "mercyful-fate":
    "Danish heavy metal band formed in Copenhagen in 1981. Long-running lineup centered on King Diamond (vocals) and Hank Shermann (guitar). Distinguished by King Diamond's operatic falsetto, occult lyrical themes, and complex twin-guitar arrangements. Foundational influence on black metal (cited as an inspiration by Mayhem, Emperor, Watain, and many others).\n\nFive studio albums during their two major runs: *Melissa* (1983) and *Don't Break the Oath* (1984) initially, then *In the Shadows* (1993), *Time* (1994), *Into the Unknown* (1996), *Dead Again* (1998), and *9* (1999). Reformed in 2020; a new studio album has been long-promised.",
  "meshell-ndegeocello":
    "American singer, bassist, and songwriter born Michelle Lynn Johnson on August 29, 1968, in West Berlin, Germany; raised in Washington, D.C. (Officially stylized meshell ndegeocello, lowercase.) Distinguished by genre-spanning work across funk, jazz, soul, hip-hop, and R&B.\n\nReleased 13 studio albums between *Plantation Lullabies* (1993) and *No More Water: The Gospel of James Baldwin* (2024). Critical peaks: *Peace Beyond Passion* (1996), *Bitter* (1999), and *Comet, Come to Me* (2014). Won the 2024 Grammy for Best Alternative Jazz Album for *The Omnichord Real Book* (2023).",
  "miami-sound-machine":
    "American Latin pop band formed in Miami in 1975 (originally as the Miami Latin Boys). Renamed Miami Sound Machine after Gloria Estefan (then Gloria Fajardo) joined as vocalist. Long-running core: Gloria Estefan (vocals), Emilio Estefan (percussion/producer), and Kiki Garcia (drums). Foundational to the international crossover success of Latin pop in the 1980s.\n\nReleased 12 studio albums between *Renacer* (1977) and *Cuts Both Ways* (1989), the latter increasingly credited as Gloria Estefan and Miami Sound Machine. Commercial peak: *Primitive Love* (1985, featuring \"Conga,\" \"Bad Boy,\" and \"Words Get in the Way\"). The group was renamed Gloria Estefan and Miami Sound Machine starting with *Let It Loose* (1987), then simply Gloria Estefan from *Cuts Both Ways* onward.",
};

async function main() {
  const dryRun = process.argv.includes("--dry-run");
  const force = process.argv.includes("--force");
  const { containers } = await import("../lib/cosmos");
  const { getStoredArtist } = await import("../lib/artists");

  let written = 0;
  let skipped = 0;
  let missing = 0;

  for (const [slug, description] of Object.entries(DESCRIPTIONS)) {
    const existing = await getStoredArtist(slug);
    if (!existing) {
      console.log(`✗ ${slug}: no stored doc found`);
      missing += 1;
      continue;
    }
    if (existing.description && !force) {
      console.log(`↷ ${slug}: already has description — skipping`);
      skipped += 1;
      continue;
    }
    if (dryRun) {
      console.log(`◌ ${slug}: would write ${description.length} chars`);
      written += 1;
      continue;
    }
    const updated = {
      ...existing,
      description,
      updatedAt: new Date().toISOString(),
    };
    await containers.artists.item(slug, slug).replace(updated);
    console.log(`✓ ${slug}: ${description.length} chars`);
    written += 1;
  }

  console.log(`\nDone. written=${written} skipped=${skipped} missing=${missing}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
