import { config as loadEnv } from "dotenv";
loadEnv({ path: ".env.local" });

const DESCRIPTIONS: Record<string, string> = {
  "nine-inch-nails":
    "American industrial rock project formed in Cleveland in 1988 by Trent Reznor. Reznor is the band's sole continuous creative force; touring lineups have varied widely. Foundational to the development of mainstream industrial rock alongside Ministry, KMFDM, and Skinny Puppy.\n\nTen studio albums starting with *Pretty Hate Machine* (1989). Critical peak: *The Downward Spiral* (1994, one of the best-selling industrial albums of all time) and *The Fragile* (1999, a double album that debuted at #1). Reznor has since pursued an extensive parallel film-scoring career with Atticus Ross (winning Oscars for *The Social Network* and *Soul*). Inducted into the Rock and Roll Hall of Fame in 2020.",
  "nirvana":
    "American rock band formed in Aberdeen, Washington in 1987 by Kurt Cobain (vocals/guitar) and Krist Novoselic (bass). Dave Grohl joined as drummer in 1990, completing the classic lineup. Foundational to the early-1990s grunge movement; the band's commercial breakthrough launched alternative rock into the mainstream.\n\nThree studio albums: *Bleach* (1989), *Nevermind* (1991, multi-platinum and spawning \"Smells Like Teen Spirit\"), and *In Utero* (1993). Cobain died by suicide in April 1994, ending the band. The posthumous *MTV Unplugged in New York* (1994) won the Grammy for Best Alternative Music Performance. Inducted into the Rock and Roll Hall of Fame in 2014.",
  "operation-ivy":
    "American ska-punk band formed in Berkeley, California in 1987 by Tim Armstrong (vocals/guitar) and Matt Freeman (bass). Lineup completed by Jesse Michaels (vocals) and Dave Mello (drums). Foundational to the East Bay punk scene; Lookout! Records initially formed around the band.\n\nReleased one studio album: *Energy* (1989), plus the *Hectic* EP (1988). The band dissolved in May 1989 just as *Energy* was about to be released. Armstrong and Freeman went on to form Rancid; Michaels later led Common Rider. The band's influence on the ska-punk and skate-punk revivals of the 1990s was substantial.",
  "orange-goblin":
    "English stoner doom band formed in London in 1995. Long-running lineup: Ben Ward (vocals), Joe Hoare (guitar), Martyn Millard (bass), and Chris Turner (drums, since 2004). Style draws on Black Sabbath, classic doom, biker rock, and NWOBHM.\n\nTen studio albums starting with *Frequencies from Planet Ten* (1997). Best-known releases include *Time Travelling Blues* (1998), *Coup de Grace* (2002), and *A Eulogy for the Damned* (2012). Released primarily on Rise Above Records and Candlelight. The band has been continuously active since 1995.",
  "our-lady-peace":
    "Canadian rock band formed in Toronto in 1992. Long-running lineup: Raine Maida (vocals), Duncan Coutts (bass, since 1995), and various guitarists and drummers — Steve Mazur joined on guitar in 2002. Foundational to the late-1990s Canadian alternative-rock scene.\n\nNine studio albums starting with *Naveed* (1994). Commercial peak: *Clumsy* (1997, multi-platinum) and *Happiness... Is Not a Fish That You Can Catch* (1999). The 2002 album *Gravity* marked their breakthrough in the US. Continuously active; Maida has also released solo material.",
  "over-the-rhine":
    "American folk-rock duo formed in Cincinnati in 1989 by Karin Bergquist (vocals) and Linford Detweiler (multi-instrumentalist). The duo are married and have collaborated continuously since formation. Initial lineup included other members; the band became a primary duo by the early 2000s.\n\nReleased 16 studio albums starting with *Til We Have Faces* (1991). Best-known releases include *Good Dog Bad Dog* (1996), *Films for Radio* (2001), and *Drunkard's Prayer* (2005). Released primarily on independent labels; the duo's Nowhere Else Festival has drawn fans to their southwestern Ohio farm property each summer since 2014.",
  "overcome":
    "American Christian hardcore band formed in West Palm Beach, Florida in 1992. Long-running lineup centered on guitarist Jason Stinson. Associated with the 1990s metallic-hardcore scene alongside Earth Crisis and Hatebreed.\n\nFour studio albums starting with *Don't Lose Faith in Me* (1993). Best-known releases include *Blessed Are the Persecuted* (1994), *Reality* (1999), and *The Life of Death* (2003). Released primarily on Tooth & Nail and Solid State Records.",
  "pat-benatar":
    "American singer born Patricia Mae Andrzejewski on January 10, 1953, in Brooklyn, New York. Long-running musical and personal partnership with husband Neil Giraldo (guitar/producer). Among the most commercially successful rock vocalists of the early 1980s, with four Grammy Awards for Best Female Rock Vocal Performance (1980-1983).\n\nTwelve studio albums starting with *In the Heat of the Night* (1979). Commercial peak: *Crimes of Passion* (1980, featuring \"Hit Me with Your Best Shot\"), *Precious Time* (1981, featuring \"Fire and Ice\"), and *Get Nervous* (1982). Subsequent releases include *Tropico* (1984, featuring \"We Belong\") and *Wide Awake in Dreamland* (1988, featuring \"All Fired Up\"). Inducted into the Rock and Roll Hall of Fame in 2022.",
  "peter-frampton":
    "English-American rock musician born April 22, 1950, in Beckenham, Kent. First gained prominence as a member of the Herd (1966-1969) and Humble Pie (1969-1971) before launching a solo career. Distinguished by his pioneering use of the talk box (\"Show Me the Way,\" \"Do You Feel Like We Do\").\n\nReleased 18 solo studio albums starting with *Wind of Change* (1972). Commercial peak: *Frampton Comes Alive!* (1976), one of the best-selling live albums of all time at over 8 million US copies sold. Subsequent peaks include *I'm in You* (1977) and a long late-career stretch as a respected session guitarist. Released *Frampton Forgets the Words* (2021), an instrumental covers album, despite a diagnosis of inclusion body myositis.",
  "pixies":
    "American alternative rock band formed in Boston in 1986. Original lineup: Black Francis (vocals/guitar, born Charles Thompson), Joey Santiago (guitar), Kim Deal (bass/vocals, 1986-2013), and David Lovering (drums). Foundational to the development of alternative rock; cited as a primary influence by Kurt Cobain on Nirvana's sound.\n\nFive studio albums in the original era between *Surfer Rosa* (1988) and *Trompe le Monde* (1991). Critical peak: *Doolittle* (1989, featuring \"Here Comes Your Man\" and \"Monkey Gone to Heaven\"). The band split in 1993 and reunited in 2004 with extensive touring; Deal departed again in 2013. Subsequent albums *Indie Cindy* (2014), *Head Carrier* (2016), and others have featured Paz Lenchantin on bass.",
  "prince-and-the-revolution":
    "American funk-rock band led by Prince (1958-2016) from 1979 to 1986. The Revolution backing band included Wendy Melvoin (guitar/vocals), Lisa Coleman (keyboards/vocals), Brown Mark (bass), Bobby Z. (drums), and Matt Fink (keyboards) at its classic-era peak.\n\nReleased three studio albums under the Prince and the Revolution name: *Purple Rain* (1984), *Around the World in a Day* (1985), and *Parade* (1986). *Purple Rain* sold over 25 million copies and won the Academy Award for Best Original Song Score for the accompanying film. Prince disbanded the Revolution in 1986; surviving members have toured under the Revolution name since 2012.",
  "queen":
    "English rock band formed in London in 1970. Lineup: Freddie Mercury (vocals, 1970-1991, died), Brian May (guitar), Roger Taylor (drums), and John Deacon (bass, 1971-1997). One of the most commercially successful rock bands in history, with estimated worldwide sales over 250 million units.\n\nFifteen studio albums between *Queen* (1973) and *Made in Heaven* (1995, with Mercury's last vocal sessions). Commercial peak: *A Night at the Opera* (1975, featuring \"Bohemian Rhapsody\"), *News of the World* (1977, featuring \"We Will Rock You\" and \"We Are the Champions\"), and *The Game* (1980). Mercury died of AIDS-related complications in November 1991. The band has toured since 2004 with Paul Rodgers and Adam Lambert as guest vocalists. Inducted into the Rock and Roll Hall of Fame in 2001.",
  "quiet-riot":
    "American hard rock band formed in Los Angeles in 1973 by guitarist Randy Rhoads (1973-1979, joined Ozzy Osbourne, died 1982) and bassist Kelly Garni. Vocalist Kevin DuBrow (died 2007) joined in 1975 and was the band's identifying voice. Frankie Banali (drums, 1980-2020) defined the classic lineup.\n\nThirteen studio albums between *Quiet Riot* (1977) and *Hollywood Cowboys* (2019). Commercial peak: *Metal Health* (1983), the first heavy metal album to reach #1 on the Billboard 200, featuring \"Cum on Feel the Noize\" (a Slade cover). DuBrow died of a cocaine overdose in 2007; Banali died of pancreatic cancer in 2020. The band has continued with Jizzy Pearl on vocals and various lineups.",
  "red-five":
    "American power-pop band formed in Pittsburgh, Pennsylvania in 1995. Lineup: Christine Donald (vocals/bass), Brian Foughty (guitar), and Tony Reali (drums). Distinguished by their melodic punk-pop hooks and female-led vocals.\n\nTwo studio albums: *Flash* (1996) and *Tracks of My Tears* (1998). Released on Interscope Records. The band toured with Foo Fighters and Hum during their commercial peak before dissolving in the late 1990s.",
  "ric-ocasek":
    "American singer-songwriter, guitarist, and producer (born Richard Theodore Otcasek, 1944-2019). Best known as the lead vocalist of The Cars (1976-1988, 2010-2019). Pursued a parallel solo recording and music production career.\n\nReleased seven solo studio albums starting with *Beatitude* (1982). As a producer, worked with Weezer (*Blue Album*, 1994; *Green Album*, 2001; *Everything Will Be Alright in the End*, 2014), Bad Brains, Bad Religion, Hole, No Doubt, and Guided by Voices, among others. Ocasek died of cardiovascular disease in September 2019. Inducted into the Rock and Roll Hall of Fame with the Cars in 2018.",
  "rick-james":
    "American singer-songwriter and producer (1948-2004). Born James Ambrose Johnson Jr. in Buffalo, New York. Distinguished by his self-described \"punk-funk\" sound — a fusion of funk, R&B, and rock with deliberately provocative stage persona.\n\nReleased ten studio albums starting with *Come Get It!* (1978). Commercial peak: *Street Songs* (1981), which sold over 3 million copies on the strength of \"Super Freak\" and \"Give It to Me Baby.\" Subsequent peaks include *Throwin' Down* (1982) and *Glow* (1985). His 1985 production of Eddie Murphy's \"Party All the Time\" became a top-10 hit. The 2004 sketch \"Charlie Murphy's True Hollywood Stories\" on *Chappelle's Show* introduced him to a new generation. Died of heart failure in August 2004.",
  "ricky-skaggs":
    "American country and bluegrass musician born July 18, 1954, in Cordell, Kentucky. First gained prominence as a member of Emmylou Harris's Hot Band (1977-1980) before launching a solo career.\n\nReleased over 20 studio albums spanning country and bluegrass between *That's It!* (1975) and *Brand New Strings* (2004) onward. Commercial peak: *Highways & Heartaches* (1982, featuring \"Heartbroke\") and *Don't Cheat in Our Hometown* (1983). Returned to traditional bluegrass with *Bluegrass Rules!* (1997), winning 15 Grammy Awards. Inducted into the Country Music Hall of Fame in 2018.",
  "robert-palmer":
    "English singer-songwriter (1949-2003). First gained prominence as a member of the Power Station (1985, with members of Duran Duran) before launching a successful solo career. Distinguished by his eclectic style — touching R&B, rock, blues, jazz, and reggae — and his iconic MTV-era visual presentation.\n\nReleased 14 studio albums between *Sneakin' Sally Through the Alley* (1974) and *Drive* (2003). Commercial peak: *Riptide* (1985, featuring \"Addicted to Love\" — the iconic music video featured a band of identically-dressed mannequin-styled women) and *Heavy Nova* (1988, featuring \"Simply Irresistible\"). Died of a heart attack in September 2003.",
  "rocket-from-the-crypt":
    "American rock band formed in San Diego in 1989. Long-running lineup: John Reis (vocals/guitar), Andy Stamets (guitar), Petey X (bass), JC2000 (saxophone), Apollo 9 (saxophone), and various drummers. Distinguished by their matching uniforms, horn-driven garage-punk, and visual aesthetic.\n\nSeven studio albums between *Paint as a Fragrance* (1991) and *Live from Camp X-Ray* (2002). Commercial peak: *Scream, Dracula, Scream!* (1995, featuring \"On a Rope\") and *RFTC* (1998). Disbanded in 2005 and reunited in 2011. Reis has also led Drive Like Jehu, Hot Snakes, the Sultans, and the Night Marchers.",
  "rolling-stones":
    "Same artist as the previously described The Rolling Stones — different Discogs spelling variant. English rock band formed in London in 1962. Long-running classic lineup: Mick Jagger (vocals), Keith Richards (guitar), Charlie Watts (drums, 1963-2021, died), and various bassists and second guitarists. Among the most commercially successful and influential rock bands in history.\n\nReleased 31 studio albums starting with the 1964 self-titled debut. Often cited as the \"greatest rock and roll band in the world.\" Charlie Watts died in 2021; Steve Jordan has been the band's primary drummer since. *Hackney Diamonds* (2023) was their first studio album of original material in 18 years. Inducted into the Rock and Roll Hall of Fame in 1989.",
  "roy-orbison":
    "American singer-songwriter (1936-1988). Born in Vernon, Texas. Distinguished by his operatic three-octave vocal range, dramatic ballads, and signature dark glasses (originally worn after he accidentally left his clear glasses on a plane).\n\nReleased over 20 studio albums between *Lonely and Blue* (1961) and the posthumous *Mystery Girl* (1989). Career peak: \"Only the Lonely,\" \"In Dreams,\" \"Crying,\" and \"Oh, Pretty Woman\" — all top-10 hits between 1960 and 1964. Career-revival second act came with the Traveling Wilburys (with George Harrison, Bob Dylan, Jeff Lynne, and Tom Petty) in 1988. Died of a heart attack in December 1988. Inducted into the Rock and Roll Hall of Fame in 1987.",
  "royal-crown-revue":
    "American swing-revival band formed in Los Angeles in 1989. Long-running lineup: Eddie Nichols (vocals), James Achor (guitar), Mando Dorame (saxophone), Bill Ungerman (saxophone), Veikko Lepisto (bass), and Daniel Glass (drums). Considered foundational to the 1990s swing-revival movement alongside Cherry Poppin' Daddies and the Brian Setzer Orchestra.\n\nFive studio albums between *Kings of Gangster Bop* (1991) and *Walk on Fire* (2017). Best-known release: *Mugzy's Move* (1996), featured on the soundtrack of *The Mask* (1994). The band appeared in films and TV programs throughout the swing-revival peak.",
  "sarah-mclachlan":
    "Canadian singer-songwriter born January 28, 1968, in Halifax, Nova Scotia. Founded the touring festival Lilith Fair (1997-1999), featuring exclusively female solo artists and women-led bands — a defining event of late-1990s alternative pop. Three Grammy Awards across her career.\n\nReleased nine studio albums starting with *Touch* (1988). Commercial peak: *Fumbling Towards Ecstasy* (1993), *Surfacing* (1997, featuring \"Building a Mystery\" and \"Adia\"), and *Afterglow* (2003). Released the holiday album *Wintersong* (2006), which became one of the best-selling Christmas albums of the 2000s.",
  "sevendust":
    "American rock band formed in Atlanta in 1994. Lineup: Lajon Witherspoon (vocals), Clint Lowery (guitar, 1994-2004, 2008-present), John Connolly (guitar), Vince Hornsby (bass), and Morgan Rose (drums). Often associated with the late-1990s nu-metal wave despite the band's more melodic, soul-influenced approach.\n\nFourteen studio albums between the 1997 self-titled debut and *Truth Killer* (2023). Commercial peak: *Home* (1999), *Animosity* (2001), and *Seasons* (2003). Released primarily on TVT and 7Bros. Records (the band's own label). Continuously active.",
  "shades-apart":
    "American melodic hardcore band formed in Westfield, New Jersey in 1989. Lineup: Mark Anderson (vocals), Kevin Lally (bass), and Chris Howard (drums) — Mark Anderson is also the band's guitarist. Style draws on hardcore punk, post-hardcore, and emo.\n\nFive studio albums between *Shades Apart* (1989) and *Sonic Boom* (2002). Best-known releases include *Save It* (1995), *Eyewitness* (1999), and *Sonic Boom* (2002). Released primarily on Revelation Records, Universal, and Wind-Up.",
  "slade":
    "English rock band formed in Wolverhampton in 1966. Classic lineup: Noddy Holder (vocals/guitar), Dave Hill (guitar), Jim Lea (bass), and Don Powell (drums). Distinguished by their deliberately misspelled song titles, working-class appeal, and chart dominance in early-1970s UK glam rock.\n\nFifteen studio albums between *Beginnings* (1969) and *Keep Your Hands Off My Power Supply* (1984). Commercial peak in the UK: six #1 singles between 1971 and 1973, including \"Coz I Luv You,\" \"Take Me Bak 'Ome,\" \"Mama Weer All Crazee Now,\" \"Cum On Feel the Noize,\" and \"Merry Xmas Everybody\" (1973). The 1983-84 comeback as \"Slade II\" produced US hits \"Run Runaway\" and \"My Oh My.\"",
  "sleep":
    "American doom metal band formed in San Jose, California in 1990 by Matt Pike (guitar), Al Cisneros (bass/vocals), and Chris Hakius (drums, 1990-2011, replaced by Jason Roeder in 2018). Pioneers of stoner doom alongside Kyuss.\n\nFour studio albums: *Volume One* (1991), *Sleep's Holy Mountain* (1992), *Dopesmoker* (2003, originally recorded 1998-1999), and *The Sciences* (2018, a surprise 4/20 release with no advance promotion). The hour-long single-track *Dopesmoker* (originally rejected by London Records as too uncommercial) has become a definitive stoner-doom touchstone. Pike has also led High on Fire.",
  "snapcase":
    "American post-hardcore band formed in Buffalo, New York in 1991. Long-running lineup: Daryl Taberski (vocals), Frank Vicario (guitar), and various rhythm sections. Considered foundational to the late-1990s post-hardcore scene alongside Refused and At the Drive-In.\n\nSix studio albums between *Comatose* (1993) and *Bright Flashes* (2003). Best-known releases include *Lookinglasself* (1993), *Progression Through Unlearning* (1997), and *Designs for Automotion* (2000). Released primarily on Victory Records during the label's late-1990s hardcore peak.",
  "social-distortion":
    "American rock band formed in Fullerton, California in 1978 by vocalist/guitarist Mike Ness — the band's only continuous member. Long-running classic lineup also included guitarist Dennis Danell (1978-2000, died 2000), bassist John Maurer (1984-2004), and drummer Charlie Quintana (2010-2018, died 2018).\n\nSeven studio albums starting with *Mommy's Little Monster* (1983). Commercial peak: *Social Distortion* (1990, featuring \"Story of My Life\" and \"Ball and Chain\"), *Somewhere Between Heaven and Hell* (1992), and *White Light, White Heat, White Trash* (1996). Distinguished by their fusion of punk, rockabilly, and country influences. Danell died of a brain aneurysm in 2000.",
  "soul-asylum":
    "American rock band formed in Minneapolis in 1981 (originally as Loud Fast Rules). Long-running lineup: Dave Pirner (vocals/guitar), Dan Murphy (guitar, 1981-2012), Karl Mueller (bass, 1981-2005, died 2005), and various drummers. Initially associated with the early-1980s Minneapolis hardcore scene alongside Hüsker Dü and the Replacements.\n\nEleven studio albums starting with *Say What You Will...* (1984). Commercial breakthrough came with their seventh album *Grave Dancers Union* (1992), featuring \"Runaway Train\" (which won the Grammy for Best Rock Song). Mueller died of throat cancer in 2005; the band continued and released *Hurry Up and Wait* (2020) and *Slowly but Shirley* (2024).",
  "soulfly":
    "American heavy metal band formed in Phoenix in 1997 by Max Cavalera after his departure from Sepultura. Cavalera is the band's only continuous member; the lineup has rotated frequently around him. Distinguished by the fusion of Brazilian rhythmic traditions, world music, and heavy metal that Cavalera pioneered with Sepultura.\n\nTwelve studio albums starting with the 1998 self-titled debut. Best-known releases include *Primitive* (2000), *Conquer* (2008), and *Archangel* (2015). The band has frequently been described as a continuation of Cavalera's Sepultura work. Cavalera also fronts Cavalera Conspiracy with his brother Iggor.",
  "soundgarden":
    "American rock band formed in Seattle in 1984. Lineup: Chris Cornell (vocals, 1984-1997, 2010-2017, died 2017), Kim Thayil (guitar), and Matt Cameron (drums, 1986-1997, 2010-2017). Bassist Ben Shepherd joined in 1990, replacing Hiro Yamamoto. Foundational to the grunge wave alongside Nirvana, Pearl Jam, and Alice in Chains; the first grunge act signed to a major label (A&M, 1989).\n\nSix studio albums between *Ultramega OK* (1988) and *King Animal* (2012). Commercial peak: *Badmotorfinger* (1991), *Superunknown* (1994, featuring \"Black Hole Sun\"), and *Down on the Upside* (1996). The band split in 1997 and reunited in 2010. Cornell died by suicide in May 2017, ending the band again.",
  "stabbing-westward":
    "American industrial rock band formed in Macomb, Illinois in 1985. Long-running lineup: Christopher Hall (vocals), Walter Flakus (keyboards), and various rhythm sections. Style draws on industrial rock, alternative rock, and synth-pop.\n\nFive studio albums between *Ungod* (1994) and *Wasteland* (2022). Best-known releases include *Wither Blister Burn + Peel* (1996) and *Darkest Days* (1998). Disbanded in 2002 and reunited in 2016. *Chasing Ghosts* (2022) was their first studio album in 21 years.",
  "steve-miller-band":
    "American rock band formed in San Francisco in 1966 by Steve Miller (vocals/guitar) — the band's only continuous member. Distinguished by the fusion of blues, psychedelic rock, and pop hooks that defined the band's classic 1970s commercial peak.\n\nReleased 18 studio albums starting with *Children of the Future* (1968). Commercial peak: *The Joker* (1973), *Fly Like an Eagle* (1976), and *Book of Dreams* (1977). The latter two albums combined sold over 12 million copies in the US. Inducted into the Rock and Roll Hall of Fame in 2016, though Miller's controversial acceptance speech criticized the institution's gender imbalance.",
  "stevie-nicks":
    "American singer-songwriter born May 26, 1948, in Phoenix, Arizona. First gained prominence as a member of Fleetwood Mac (1975-present). Pursued a successful parallel solo career starting with *Bella Donna* (1981).\n\nReleased eight solo studio albums between *Bella Donna* (1981) and *In Your Dreams* (2011). Commercial peak: *Bella Donna* and *The Wild Heart* (1983). Notable solo singles include \"Edge of Seventeen,\" \"Stop Draggin' My Heart Around\" (with Tom Petty), and \"Stand Back.\" Inducted into the Rock and Roll Hall of Fame twice — with Fleetwood Mac (1998) and as a solo artist (2019), making her the first woman to receive a double induction.",
  "sting":
    "English musician born Gordon Sumner on October 2, 1951, in Wallsend, England. First gained prominence as vocalist/bassist of the Police (1977-1986). Launched a successful solo career after the Police disbanded.\n\nReleased 15 solo studio albums between *The Dream of the Blue Turtles* (1985) and *The Bridge* (2021). Commercial peak: *Nothing Like the Sun* (1987), *The Soul Cages* (1991), and *Ten Summoner's Tales* (1993, featuring \"If I Ever Lose My Faith in You\" and \"Fields of Gold\"). Seventeen Grammy Awards. Inducted into the Rock and Roll Hall of Fame with the Police in 2003.",
  "strife":
    "American hardcore band formed in Los Angeles in 1991. Long-running lineup centered on vocalist Rick Rodney. Associated with the 1990s straightedge hardcore scene.\n\nThree studio albums in the original era: *One Truth* (1994), *In This Defiance* (1997), and *Angermeans* (2001). Subsequent releases include *Witness a Rebirth* (2012). Released primarily on Victory Records during the label's late-1990s hardcore peak.",
  "superchunk":
    "American indie rock band formed in Chapel Hill, North Carolina in 1989. Lineup: Mac McCaughan (vocals/guitar), Laura Ballance (bass), Jim Wilbur (guitar, since 1989), and various drummers — Jon Wurster joined in 1991 and remained. McCaughan and Ballance co-founded the influential indie label Merge Records in 1989.\n\nTwelve studio albums starting with *Superchunk* (1990). Best-known releases include *No Pocky for Kitty* (1991), *Foolish* (1994), *Here's Where the Strings Come In* (1995), and *Majesty Shredding* (2010). Ballance retired from touring in 2013 due to hyperacusis; Jason Narducy handles bass on tour. The band has been continuously active.",
  "supertramp":
    "English rock band formed in London in 1969. Long-running classic lineup: Roger Hodgson (vocals/keyboards, 1969-1983), Rick Davies (vocals/keyboards), John Helliwell (saxophone, 1973-present), Dougie Thomson (bass, 1972-1988), and Bob Siebenberg (drums, 1973-present). Distinguished by Davies and Hodgson's contrasting vocal styles.\n\nTen studio albums starting with *Supertramp* (1970). Commercial peak: *Crime of the Century* (1974), *Breakfast in America* (1979, featuring \"The Logical Song,\" \"Take the Long Way Home,\" and the title track — over 20 million copies sold), and *...Famous Last Words...* (1982). Hodgson departed in 1983. Davies has led the band intermittently since.",
  "system-of-a-down":
    "American rock band formed in Glendale, California in 1994 by four members of Armenian descent: Serj Tankian (vocals), Daron Malakian (guitar/vocals), Shavo Odadjian (bass), and John Dolmayan (drums, since 1997). Distinguished by their fusion of heavy metal, Middle Eastern melodies, and politically charged lyrics — particularly addressing the Armenian Genocide.\n\nFive studio albums in the original 1994-2005 era. Commercial peak: *Toxicity* (2001, multi-platinum, featuring \"Chop Suey!\" and \"Aerials\") and the simultaneously-released double albums *Mezmerize* and *Hypnotize* (2005). The band has not released a studio album since *Hypnotize*, though they released two 2020 singles in support of Armenia during the Nagorno-Karabakh war.",
  "teen-idols":
    "American pop-punk band formed in Nashville in 1995. Long-running lineup: Heather (Iceboy) Vance (vocals/bass), Kenny Vance (vocals/guitar, the husband of Heather), and Phillip Hill (drums). Closely associated with the Honest Don's Records (Fat Wreck Chords subsidiary) catalog.\n\nFive studio albums starting with *Pucker Up!* (1996). Best-known releases include the self-titled second album (1998) and *Full Leather Jacket* (1999). Released primarily on Honest Don's. The band has been on extended hiatus since the early 2000s.",
  "tesla":
    "American hard rock band formed in Sacramento, California in 1982 (originally as City Kidd). Long-running lineup: Jeff Keith (vocals), Frank Hannon (guitar), Tommy Skeoch (guitar, 1984-2006, 2008-2009), Brian Wheat (bass), and Troy Luccketta (drums). Often distinguished from glam-metal peers by their more straightforward blues-rock approach.\n\nEight studio albums starting with *Mechanical Resonance* (1986). Commercial peak: *The Great Radio Controversy* (1989, featuring \"Love Song\") and *Five Man Acoustical Jam* (1990), an early-MTV-Unplugged-era live acoustic album. The band split in 1996, reunited in 2000, and has continued recording and touring.",
  "testament":
    "American thrash metal band formed in Berkeley, California in 1983 (originally as Legacy). Long-running lineup centered on Eric Peterson (guitar) and Chuck Billy (vocals, since 1986, replacing Steve Souza). Considered a foundational \"second tier\" thrash band — emerging slightly after the \"Big Four\" but with comparable influence on the genre.\n\nThirteen studio albums starting with *The Legacy* (1987). Best-known releases include *The New Order* (1988), *Practice What You Preach* (1989), and *The Gathering* (1999). Chuck Billy was diagnosed with germ cell cancer in 2001; he beat it and the band has continued. Released *Titans of Creation* (2020) and *Para Bellum* (2025).",
  "tha-alkaholiks":
    "American hip-hop group formed in Los Angeles in 1991. Lineup: J-Ro (James Robinson), Tash (Rico Smith), and DJ E-Swift (Eric Brooks). Associated with the West Coast underground hip-hop scene of the 1990s, with King Tee as an early mentor and frequent collaborator.\n\nFour studio albums between *21 & Over* (1993) and *Firewater* (2006). Best-known releases include *Coast II Coast* (1995) and *Likwidation* (1997). Released primarily on Loud and Loud/RCA. The group has been on extended hiatus while members pursue solo work.",
  "the-alan-parsons-live-project":
    "Touring band led by English producer and musician Alan Parsons. Parsons launched the Alan Parsons Project in 1975 with Eric Woolfson as a studio-only collaboration; after Woolfson's 2009 death, Parsons reorganized the touring entity as the Alan Parsons Live Project.\n\nThe Project's studio catalog spans 11 albums between *Tales of Mystery and Imagination* (1976) and *The Time Machine* (1999). Commercial peak: *The Turn of a Friendly Card* (1980) and *Eye in the Sky* (1982, featuring the title track). The live project has continued touring with Parsons as the centerpiece since the original Project's dissolution.",
  "the-allman-brothers-band":
    "American Southern rock band formed in Jacksonville, Florida in 1969 by brothers Duane Allman (guitar, died 1971) and Gregg Allman (vocals/keyboards, died 2017). Original lineup also included Dickey Betts (guitar, died 2024), Berry Oakley (bass, died 1972), Butch Trucks (drums, died 2017), and Jaimoe (drums).\n\nTwelve studio albums between *The Allman Brothers Band* (1969) and *Hittin' the Note* (2003). Critical peak: *At Fillmore East* (1971), one of the best-selling live albums of all time. Two of the original six members — Duane Allman and Berry Oakley — died in motorcycle accidents in 1971 and 1972 respectively, just three blocks apart from each other. Inducted into the Rock and Roll Hall of Fame in 1995.",
  "the-black-dahlia-murder":
    "American melodic death metal band formed in Waterford, Michigan in 2001. Long-running lineup centered on Brian Eschbach (guitar) and the late Trevor Strnad (vocals, 2001-2022, died). The band's name references the 1947 Black Dahlia murder case.\n\nNine studio albums starting with *Unhallowed* (2003). Best-known releases include *Miasma* (2005), *Nocturnal* (2007), and *Verminous* (2020). Trevor Strnad died by suicide in May 2022; the band continued with Eschbach taking over vocals and released *Servitude* (2024).",
  "the-del-fuegos":
    "American rock band formed in Boston in 1980. Lineup: Dan Zanes (vocals/guitar), Warren Zanes (guitar/vocals, his brother), Tom Lloyd (bass, 1980-1986), and Brent \"Woody\" Giessmann (drums, died 2021). Style draws on roots rock, country, and bar-band rock and roll.\n\nFour studio albums between *The Longest Day* (1984) and *Smoking in the Fields* (1989). Best-known releases include *Boston, Mass.* (1985) and *Stand Up* (1987). Dan Zanes has pursued a successful subsequent career as a children's music recording artist.",
  "the-neal-morse-band":
    "American progressive rock band formed in 2014 by Neal Morse (vocals/keyboards/guitar), Mike Portnoy (drums, formerly of Dream Theater), Randy George (bass), Eric Gillette (guitar/vocals), and Bill Hubauer (keyboards/vocals). Continues Morse's long-running collaboration with Portnoy that began with Transatlantic in the late 1990s.\n\nFive studio albums between *The Grand Experiment* (2015) and *Innocence & Danger* (2021). Best-known releases include *The Similitude of a Dream* (2016) and *The Great Adventure* (2019), both ambitious double-LP concept works. Morse has also led Spock's Beard, Transatlantic, and various solo and Christian-rock projects.",
  "the-rolling-stones":
    "Same artist as the previously described Rolling Stones — different Discogs spelling variant. English rock band formed in London in 1962. Long-running classic lineup: Mick Jagger (vocals), Keith Richards (guitar), Charlie Watts (drums, 1963-2021, died), and various bassists and second guitarists. Among the most commercially successful and influential rock bands in history.\n\nReleased 31 studio albums starting with the 1964 self-titled debut. Often cited as the \"greatest rock and roll band in the world.\" Charlie Watts died in 2021; Steve Jordan has been the band's primary drummer since. *Hackney Diamonds* (2023) was their first studio album of original material in 18 years. Inducted into the Rock and Roll Hall of Fame in 1989.",
  "the-smashing-pumpkins":
    "American rock band formed in Chicago in 1988 by Billy Corgan (vocals/guitar) and James Iha (guitar). Original lineup also included D'arcy Wretzky (bass, 1988-1999) and Jimmy Chamberlin (drums, 1988-1996, 1999-2009, 2015-present). Among the central acts of 1990s alternative rock.\n\nThirteen studio albums starting with *Gish* (1991). Commercial peak: *Siamese Dream* (1993) and *Mellon Collie and the Infinite Sadness* (1995), the band's only #1 album — a double album that has sold over 10 million copies in the US. The band dissolved in 2000, reformed as a Corgan-led project in 2006, and reunited the original lineup (minus Wretzky) in 2018.",
  "the-toasters":
    "American ska band formed in New York City in 1981 by Robert \"Bucket\" Hingley. Considered one of the foundational acts of the American ska revival; Hingley founded Moon Ska Records (later Megalith Records) and signed many of the era's third-wave ska acts.\n\nReleased over a dozen studio albums starting with *Skaboom!* (1987). Best-known releases include *This Gun for Hire* (1990) and *Don't Let the Bastards Grind You Down* (1996). The band has cycled through many members over its 40-plus years, with Hingley the only constant. The 2008 documentary *Together* chronicled the band's history.",
  "the-urge":
    "American funk-rock band formed in St. Louis in 1987. Lineup: Steve Ewing (vocals), Bill Reiter (saxophone/keyboards), John Pessoni (drums), Matt Kwiatkowski (bass), and Karl Grable (guitar). Style fuses ska, funk, reggae, and rock.\n\nFive studio albums between *Magically Delicious* (1992) and *Make It Real* (2014). Commercial peak: *Master of Styles* (1998, featuring \"Jump Right In\"). Released primarily on Epic and EastWest Records. Ewing has also pursued a solo career.",
  "the-vandals":
    "American punk rock band formed in Huntington Beach, California in 1980. Long-running lineup since 1989: Dave Quackenbush (vocals), Warren Fitzgerald (guitar), Joe Escalante (bass), and Josh Freese (drums, since 1989). Escalante also operates Kung Fu Records, which has released material by Tsunami Bomb, the Ataris, the Living End, and others.\n\nTen studio albums starting with *Peace Thru Vandalism* (1982). Best-known releases include *Hitler Bad, Vandals Good* (1998), *Look What I Almost Stepped In...* (2000), and the popular Christmas-themed *Oi to the World!* (1996) — covered by No Doubt the following year. Drummer Josh Freese has played in dozens of major rock bands including Devo, Sting, Foo Fighters, and Nine Inch Nails.",
  "the-ventures":
    "American instrumental rock band formed in Tacoma, Washington in 1958 by Don Wilson (rhythm guitar, died 2022) and Bob Bogle (lead guitar/bass, died 2009). Among the best-selling instrumental rock acts in history, with over 100 million albums sold worldwide — particularly massive in Japan.\n\nReleased over 250 albums spanning surf rock, pop covers, soundtracks, and original material. Best-known recordings include \"Walk, Don't Run\" (1960), \"Perfidia\" (1960), and the theme to *Hawaii Five-O* (1968). The band has continued in various configurations into the 2020s. Inducted into the Rock and Roll Hall of Fame in 2008.",
  "three-dog-night":
    "American rock band formed in Los Angeles in 1967. Three-vocalist lineup: Danny Hutton, Cory Wells (died 2015), and Chuck Negron. Distinguished by their ability to make hits out of material written by other songwriters — including Randy Newman, Hoyt Axton, Laura Nyro, Russ Ballard, and Harry Nilsson.\n\nEleven studio albums between *Three Dog Night* (1968) and *Coming Down Your Way* (1975). Commercial peak: 21 consecutive top-40 singles between 1969 and 1975, including \"Joy to the World\" (1971), \"Mama Told Me (Not to Come),\" \"One,\" \"Black and White,\" and \"An Old Fashioned Love Song.\" Negron departed in 1985; the surviving original members continued. Wells died in 2015.",
  "todd-rundgren":
    "American singer-songwriter, multi-instrumentalist, and producer born June 22, 1948, in Upper Darby, Pennsylvania. First gained prominence as a member of Nazz (1967-1970), then launched a long-running solo career. Also led the band Utopia (1973-1986, 2018-present).\n\nReleased over 25 solo studio albums between *Runt* (1970) and *Space Force* (2022). Commercial peak: *Something/Anything?* (1972) and *A Wizard, a True Star* (1973). As a producer, worked with Meat Loaf (*Bat Out of Hell*, 1977), the New York Dolls, Patti Smith, Hall & Oates, XTC, Cheap Trick, and Grand Funk Railroad. Inducted into the Rock and Roll Hall of Fame in 2021.",
  "tony-bennett":
    "American singer (1926-2023). Born Anthony Dominick Benedetto in Astoria, Queens, New York. Career spanning over 75 years across traditional pop, swing, and jazz. Among the most popular American vocalists of his generation; experienced a notable second commercial peak in the 1990s alongside younger collaborators.\n\nReleased over 70 studio albums between *Cloud 7* (1955) and *Love for Sale* (2021, with Lady Gaga). Commercial peak in his original era: \"I Left My Heart in San Francisco\" (1962). Late-career second act: *MTV Unplugged* (1994), *Duets: An American Classic* (2006), and the two-volume Lady Gaga collaboration *Cheek to Cheek* (2014) and *Love for Sale* (2021). Twenty Grammy Awards. Diagnosed with Alzheimer's disease in 2016, performed his final concert in 2021. Died July 2023.",
  "tori-amos":
    "American singer-songwriter and pianist born August 22, 1963, in Newton, North Carolina. First gained prominence as a member of the synth-pop band Y Kant Tori Read (1988) before launching a solo career as a confessional piano-driven singer-songwriter.\n\nReleased 16 studio albums between *Little Earthquakes* (1992) and *Ocean to Ocean* (2021). Critical peak: *Little Earthquakes*, *Under the Pink* (1994), *Boys for Pele* (1996), and *From the Choirgirl Hotel* (1998). Co-founded RAINN (Rape, Abuse & Incest National Network) in 1994.",
  "transsiberian-orchestra":
    "American progressive metal/orchestral rock band formed in 1996 by Paul O'Neill, Robert Kinkel, Jon Oliva (of Savatage), and Al Pitrelli. Distinguished by their fusion of progressive metal, classical music, and rock-opera storytelling — typically built around Christmas-themed concept albums.\n\nSix studio albums starting with *Christmas Eve and Other Stories* (1996, multi-platinum). Subsequent releases: *The Christmas Attic* (1998), *Beethoven's Last Night* (2000), *The Lost Christmas Eve* (2004), *Night Castle* (2009), and *Letters from the Labyrinth* (2015). The band's annual Christmas tour has become one of the highest-grossing touring concerts in the world. O'Neill died of an accidental overdose in 2017.",
  "triumph":
    "Canadian hard rock power trio formed in Mississauga, Ontario in 1975 by guitarist Rik Emmett, drummer Gil Moore, and bassist Mike Levine. Distinguished by Emmett's high-tenor vocals (alternating lead duties with Moore) and elaborate stage productions during their commercial peak.\n\nEight studio albums between *Triumph* (1976) and *Surveillance* (1987). Commercial peak: *Allied Forces* (1981, featuring \"Magic Power\" and \"Fight the Good Fight\"), *Never Surrender* (1983), and *Thunder Seven* (1984). Emmett departed in 1988 for a solo career; the band has reunited for select live appearances.",
  "trivium":
    "American heavy metal band formed in Orlando, Florida in 1999. Long-running lineup: Matt Heafy (vocals/guitar), Corey Beaulieu (guitar), Paolo Gregoletto (bass, since 2004), and various drummers — Alex Bent has been the drummer since 2016. Among the leading 21st-century US metal acts, often credited with influencing both metalcore and traditional heavy metal revivals.\n\nTen studio albums starting with *Ember to Inferno* (2003). Commercial peak: *Ascendancy* (2005), *The Crusade* (2006), *Shogun* (2008), and *In Waves* (2011). The band has been continuously active since 1999.",
  "turmoil":
    "American hardcore band formed in Philadelphia in 1990. Long-running lineup centered on vocalist Jon Gula. Associated with the metallic-hardcore wave of the late 1990s alongside Strife, Earth Crisis, and Hatebreed.\n\nFour studio albums starting with *Process of...* (1996). Best-known release: *The Process of...* and *Anchor* (1999). Released primarily on Century Media. The band disbanded in 2000 and has reunited occasionally for live performances.",
  "ufo":
    "English hard rock band formed in London in 1969. Long-running lineup centered on Phil Mogg (vocals, 1969-2022) and Andy Parker (drums). Other key members included guitarist Michael Schenker (1973-1978, 1993-2003) — whose tenure defined the band's commercial peak — and bassist Pete Way (1969-1982).\n\nTwenty-two studio albums between *UFO 1* (1970) and *Salentino Cuts* (2017). Commercial peak: *Phenomenon* (1974), *Force It* (1975), *Lights Out* (1977), and the live *Strangers in the Night* (1979). Mogg retired in 2022 after the band's farewell tour; UFO is no longer a touring entity.",
  "vision-of-disorder":
    "American hardcore band formed in Long Island, New York in 1992. Long-running lineup: Tim Williams (vocals), Mike Kennedy (guitar), Matt Baumbach (guitar), Mike Fleischmann (bass), and Brendon Cohen (drums). Considered foundational to the metalcore movement alongside Earth Crisis and Hatebreed.\n\nFive studio albums between the 1996 self-titled debut and *The Cursed Remain Cursed* (2012). Best-known releases include *Imprint* (1998) and *From Bliss to Devastation* (2001). The band disbanded in 2002 and reunited in 2008. Williams has also led Bloodsimple and various other projects.",
  "walter-carlos":
    "American composer and pianist born Walter Carlos in 1939 in Pawtucket, Rhode Island. Released early albums under \"Walter Carlos\" before her 1972 gender transition and subsequent reissue/continued release under the name Wendy Carlos. Pioneering figure in electronic music; the 1968 album *Switched-On Bach* was a landmark moment in popularizing synthesized music.\n\nReleased a dozen albums spanning electronic classical, ambient, and film scores. Key works include *Switched-On Bach* (1968), *The Well-Tempered Synthesizer* (1969), *Sonic Seasonings* (1972), and scores for *A Clockwork Orange* (1971), *The Shining* (1980, partially used), and *Tron* (1982). Earlier releases now typically reissued under the Wendy Carlos name; the Walter Carlos credit appears on original-era pressings.",
  "warrant":
    "American glam metal band formed in Hollywood in 1984. Lineup: Jani Lane (vocals, 1984-1993, 2004-2008, died 2011), Joey Allen (guitar), Erik Turner (guitar), Jerry Dixon (bass), and Steven Sweet (drums). Among the most commercially successful Sunset Strip glam-metal acts of the late 1980s.\n\nSix studio albums starting with *Dirty Rotten Filthy Stinking Rich* (1989). Commercial peak: *Cherry Pie* (1990, multi-platinum, featuring the title track) and *Dog Eat Dog* (1992). Lane departed in 1993 (replaced by Jaime St. James for *Belly to Belly*, 1996) and rejoined intermittently before his 2011 death from alcohol poisoning. Robert Mason has been the band's vocalist since 2008.",
};

async function main() {
  const dryRun = process.argv.includes("--dry-run");
  const force = process.argv.includes("--force");
  const { containers } = await import("../lib/cosmos");
  const { getStoredArtist } = await import("../lib/artists");

  let written = 0;
  let skipped = 0;
  let missing = 0;

  for (const [slug, description] of Object.entries(DESCRIPTIONS)) {
    const existing = await getStoredArtist(slug);
    if (!existing) {
      console.log(`✗ ${slug}: no stored doc found`);
      missing += 1;
      continue;
    }
    if (existing.description && !force) {
      console.log(`↷ ${slug}: already has description — skipping`);
      skipped += 1;
      continue;
    }
    if (dryRun) {
      console.log(`◌ ${slug}: would write ${description.length} chars`);
      written += 1;
      continue;
    }
    const updated = {
      ...existing,
      description,
      updatedAt: new Date().toISOString(),
    };
    await containers.artists.item(slug, slug).replace(updated);
    console.log(`✓ ${slug}: ${description.length} chars`);
    written += 1;
  }

  console.log(`\nDone. written=${written} skipped=${skipped} missing=${missing}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
