import { config as loadEnv } from "dotenv";
loadEnv({ path: ".env.local" });

const DESCRIPTIONS: Record<string, string> = {
  "heart":
    "American rock band formed in Seattle in 1973. Sisters Ann Wilson (vocals) and Nancy Wilson (guitar/vocals) have been the band's only continuous members. Other key members included Howard Leese (guitar, 1975-1995), Roger Fisher (guitar, 1975-1979), and Michael Derosier (drums, 1975-1982).\n\nSixteen studio albums starting with *Dreamboat Annie* (1975). Early '70s success with \"Magic Man,\" \"Crazy on You,\" and \"Barracuda.\" The 1985 self-titled album marked a commercial second act on Capitol with \"What About Love,\" \"Never,\" and \"These Dreams\" (their first #1). Inducted into the Rock and Roll Hall of Fame in 2013.",
  "insane-clown-posse":
    "American hip-hop duo formed in Detroit in 1989 by Violent J (Joseph Bruce) and Shaggy 2 Dope (Joseph Utsler). Known for their face paint, horror-themed lyrics, and the dedicated subculture of \"Juggalo\" fans. The annual Gathering of the Juggalos festival has run since 2000.\n\nEighteen studio albums under the \"Joker's Cards\" concept series and beyond. Best-known releases include *The Great Milenko* (1997), *The Amazing Jeckel Brothers* (1999), and *The Wraith: Shangri-La* (2002). The duo also runs Psychopathic Records, which has released material by Twiztid, Boondox, and others.",
  "jefferson-starship":
    "American rock band formed in San Francisco in 1974, evolved from the earlier Jefferson Airplane. Long-running lineup centered on founding guitarist Paul Kantner (1974-1984, 1992-2016, died 2016), with various vocalists including Grace Slick, Marty Balin, and Mickey Thomas.\n\nActive in three primary eras: rock-oriented 1974-1984 (*Red Octopus*, 1975; *Spitfire*, 1976), pop-oriented Starship (1985-1989, *Knee Deep in the Hoopla*, 1985), and the Kantner-led Jefferson Starship reunion (1992-2016). Eleven studio albums under the Jefferson Starship name. Inducted into the Rock and Roll Hall of Fame in 1996 (as Jefferson Airplane).",
  "jimmy-buffett":
    "American singer-songwriter (1946-2023). Best known for his \"Gulf and Western\" style — a fusion of country, folk-rock, and Caribbean music — and the cultural phenomenon of \"Parrotheads,\" his devoted fan community. The 1977 single \"Margaritaville\" became a defining song.\n\nReleased over 30 studio albums starting with *Down to Earth* (1970). Built a substantial business empire — Margaritaville Holdings — encompassing restaurants, hotels, and consumer products. Buffett died in September 2023; *Equal Strain on All Parts* (2023) was released two months later.",
  "limp-bizkit":
    "American rap rock band formed in Jacksonville, Florida in 1994. Lineup: Fred Durst (vocals), Wes Borland (guitar), Sam Rivers (bass), John Otto (drums), and DJ Lethal. Borland departed twice (2001-2004 and 2003-2009) before stabilizing.\n\nTheir second album *Significant Other* (1999) sold over 16 million copies worldwide. *Chocolate Starfish and the Hot Dog Flavored Water* (2000) debuted at #1 with first-week US sales of over 1 million. After a long commercial decline through the 2000s, the band released *Still Sucks* (2021) on their own Suretone label. Six studio albums total.",
  "mtley-cre":
    "American glam metal band formed in Los Angeles in 1981. Classic lineup: Vince Neil (vocals), Nikki Sixx (bass), Mick Mars (guitar), and Tommy Lee (drums). The band has rarely deviated from this lineup — except for John Corabi (vocals, 1992-1996) and the 2022 retirement of Mick Mars due to ankylosing spondylitis.\n\nNine studio albums between 1981 and 2008. Commercial peak: *Theatre of Pain* (1985), *Girls, Girls, Girls* (1987), and *Dr. Feelgood* (1989, their only #1 album). Bassist Nikki Sixx's *The Heroin Diaries* (2007) and the band's autobiography *The Dirt* (2001, later a Netflix film) chronicled the band's substance-abuse history. The 2014 \"final tour\" was reversed when the band returned to touring in 2019.",
  "mxpx":
    "American punk rock band formed in Bremerton, Washington in 1992 (originally as Magnified Plaid). Long-running lineup: Mike Herrera (vocals/bass), Tom Wisniewski (guitar), and Yuri Ruley (drums). Initially associated with the Christian punk scene; their style spans skate punk, pop-punk, and melodic hardcore.\n\nEleven studio albums between *Pokinatcha* (1994) and *MxPx* (2018). Commercial peak years on A&M Records produced *Slowly Going the Way of the Buffalo* (1998) and *The Ever Passing Moment* (2000). Released later albums independently. Continuously active.",
  "night-ranger":
    "American hard rock band formed in San Francisco in 1979. Long-running lineup centered on Jack Blades (vocals/bass) and Brad Gillis (guitar). Other longtime members include Kelly Keagy (vocals/drums) and Joel Hoekstra (guitar, 2008-2014). Mainstream success during the MTV-era hard rock peak.\n\nTwelve studio albums starting with *Dawn Patrol* (1982). Best-known singles include \"Sister Christian\" and \"(You Can Still) Rock in America\" from *Midnight Madness* (1983). Blades later co-founded the supergroup Damn Yankees (1989-1996) alongside Ted Nugent and Styx's Tommy Shaw.",
  "pink-floyd":
    "English rock band formed in London in 1965. Original lineup: Syd Barrett (vocals/guitar, 1965-1968), Roger Waters (bass/vocals), Richard Wright (keyboards), Nick Mason (drums), and David Gilmour (guitar/vocals, joined 1968 replacing Barrett). One of the best-selling music artists of all time, with over 250 million units sold worldwide.\n\nFifteen studio albums between 1967 and 2014. Commercial peaks include *The Dark Side of the Moon* (1973), which has charted on Billboard for over 950 weeks, *Wish You Were Here* (1975), and the rock opera *The Wall* (1979). Roger Waters departed in 1985 in acrimony; the band continued under Gilmour with *A Momentary Lapse of Reason* (1987) and *The Division Bell* (1994). Wright died in 2008. Inducted into the Rock and Roll Hall of Fame in 1996.",
  "prince":
    "American singer, songwriter, multi-instrumentalist, and producer (1958-2016). Born Prince Rogers Nelson in Minneapolis, Minnesota. One of the most prolific and influential musicians of the late 20th century; instrumental in shaping funk, R&B, pop, and rock.\n\nReleased 39 studio albums during his lifetime, plus posthumous material from his \"Vault\" of unreleased recordings. Commercial peak: *1999* (1982), the *Purple Rain* film and soundtrack (1984), *Around the World in a Day* (1985), and *Sign o' the Times* (1987). Founded NPG (New Power Generation) as his backing band in 1990. Inducted into the Rock and Roll Hall of Fame in 2004.",
  "queens-of-the-stone-age":
    "American rock band formed in Palm Desert, California in 1996 by guitarist/vocalist Josh Homme (formerly of Kyuss). The band's lineup has rotated frequently around Homme; longtime contributors include Troy Van Leeuwen (guitar, 2002-present), Michael Shuman (bass, 2007-present), and Jon Theodore (drums, 2013-present).\n\nEight studio albums including *Rated R* (2000), *Songs for the Deaf* (2002, featuring Dave Grohl on drums), *Lullabies to Paralyze* (2005), *...Like Clockwork* (2013), and *Villains* (2017). Mark Lanegan (Screaming Trees) and Nick Oliveri were notable past members. The band has been a key vehicle for the broader \"Desert Sessions\" project Homme runs.",
  "rem":
    "American rock band formed in Athens, Georgia in 1980. Classic lineup: Michael Stipe (vocals), Peter Buck (guitar), Mike Mills (bass/vocals), and Bill Berry (drums, 1980-1997). Foundational to the development of alternative rock and college radio in the 1980s before crossing to mainstream success in the 1990s.\n\nFifteen studio albums between *Murmur* (1983) and *Collapse into Now* (2011). Commercial peak: *Out of Time* (1991), *Automatic for the People* (1992), and *Monster* (1994). Berry retired in 1997 after a brain aneurysm; the band continued as a trio. R.E.M. formally disbanded in 2011. Inducted into the Rock and Roll Hall of Fame in 2007.",
  "robin-trower":
    "English rock guitarist and singer born March 9, 1945, in Catford, London. Initially gained prominence as guitarist in Procol Harum (1967-1971) before launching a solo career. Distinguished by his blues-rock-meets-psychedelia approach and Hendrix-influenced lead playing.\n\nReleased over 20 studio albums starting with *Twice Removed from Yesterday* (1973). Commercial peak: *Bridge of Sighs* (1974), considered his masterwork. Longtime vocalist James Dewar (1973-1983) shaped the band's classic-era sound. Trower has continued to record and tour into the 2020s.",
  "rod-stewart":
    "Scottish-English singer-songwriter born January 10, 1945, in London. First gained prominence as vocalist for the Jeff Beck Group (1967-1969) and Faces (1969-1975) before launching his commercially dominant solo career.\n\nReleased over 30 solo studio albums between *An Old Raincoat Won't Ever Let You Down* (1969) and *Swing Fever* (2024). Commercial peak years spanning soft rock, disco-pop, and adult contemporary include *Every Picture Tells a Story* (1971), *A Night on the Town* (1976), *Foot Loose & Fancy Free* (1977), and the *Great American Songbook* series (2002-2010). Inducted into the Rock and Roll Hall of Fame twice — as a solo artist (1994) and as a member of Faces (2012).",
  "santana":
    "American rock band formed in San Francisco in 1966. Guitarist Carlos Santana is the band's only continuous member. Pioneers of the fusion of rock with Latin and African rhythms. The band's 1969 Woodstock performance was a breakthrough moment.\n\nReleased 26 studio albums between *Santana* (1969) and *Sentient* (2023). Early peak: *Abraxas* (1970), *Santana III* (1971), and *Caravanserai* (1972). The 1999 comeback album *Supernatural* sold over 30 million copies worldwide and produced \"Smooth\" (a #1 single featuring Rob Thomas of Matchbox Twenty). Inducted into the Rock and Roll Hall of Fame in 1998.",
  "slaughter":
    "American glam metal band formed in Las Vegas in 1988 by vocalist Mark Slaughter and bassist Dana Strum after the death of their previous singer Vinnie Vincent (formerly of KISS). The band emerged at the tail end of the LA hair-metal boom.\n\nTheir 1990 debut *Stick It to Ya* sold over 2 million copies on the strength of \"Up All Night\" and \"Fly to the Angels.\" Subsequent releases (*The Wild Life*, 1992; *Fear No Evil*, 1995; *Revolution*, 1997) did not match the breakthrough; the grunge era effectively ended the band's commercial momentum. Five studio albums total. The band has performed periodic reunion tours.",
  "subhumans":
    "English anarcho-punk band formed in Trowbridge, Wiltshire in 1980. Lineup: Dick Lucas (vocals), Bruce Treasure (guitar), Phil Bryant (bass), and Trotsky (drums). Distinguished by political lyrics and a more melodic approach than the contemporary UK82 hardcore scene.\n\nSix studio albums starting with *The Day the Country Died* (1983). Other key releases include *From the Cradle to the Grave* (1984) and *Worlds Apart* (1985). Lucas also fronts Citizen Fish, a related anarcho-ska-punk band. After a 1985 breakup, the Subhumans reunited in 1991 and have remained active.",
  "the-atomic-bitchwax":
    "American stoner rock band formed in Neptune, New Jersey in 1992 by guitarist Ed Mundell (also of Monster Magnet at the time). Long-running lineup also includes bassist/vocalist Chris Kosnik and drummer Bob Pantella. Style typified by extended instrumental passages and improvisational elements.\n\nSix studio albums between 1999 and 2017, including the self-titled debut (1999), *II* (2000), and *Force Field* (2017). Mundell departed in 2008 to focus on Monster Magnet; replaced by Finn Ryan and later Garrett Sweeny. Active continuously.",
  "the-clarks":
    "American rock band formed in Indiana, Pennsylvania in 1986. Lineup: Scott Blasey (vocals), Dave Minarik (drums), Robert James (bass), and Greg Joseph (guitar/bass). Held a long-running cult following in Pittsburgh and western Pennsylvania despite limited national exposure.\n\nEight studio albums between 1988 and 2019, including *I'll Tell You What, Man...* (1988), *Let It Go* (1994), and *Restless Days* (2002). The band's regional touring schedule and stable lineup over decades made them a fixture of the Mid-Atlantic college-rock circuit.",
  "the-time":
    "American funk band formed in Minneapolis in 1981 by Prince and Morris Day. Original lineup: Day (vocals), Jesse Johnson (guitar), Terry Lewis (bass), Jimmy Jam (keyboards), Monte Moir (keyboards), and Jellybean Johnson (drums). Prince produced and wrote most of the band's early material.\n\nFour studio albums in the original run: *The Time* (1981), *What Time Is It?* (1982), *Ice Cream Castle* (1984), and *Pandemonium* (1990). Jam and Lewis launched a successful production career after departing the band in 1983; they became one of the most successful R&B production teams of the 1980s and '90s. The band reunited in 2008 as the Original 7ven.",
  "unwritten-law":
    "American punk rock band formed in San Diego in 1990. Lineup: Scott Russo (vocals), Steve Morris (guitar), Wade Youman (drums), John Bell (bass). Style spans melodic hardcore, pop-punk, and post-hardcore.\n\nSeven studio albums starting with *Blue Room* (1994). Commercial peak: *Elva* (2002, featuring \"Seein' Red\"). Subsequent releases include *Here's to the Mourning* (2005) and *The Hum Goes On Forever* (2011). The band has cycled through frequent lineup changes around Russo, who has been the only continuous member.",
  "voivod":
    "Canadian heavy metal band formed in Jonquière, Quebec in 1982. Original lineup: Snake (Denis Bélanger, vocals), Piggy (Denis D'Amour, guitar, died 2005), Blacky (Jean-Yves Thériault, bass), and Away (Michel Langevin, drums). The band's style evolved from speed metal into a uniquely progressive, dissonant approach that influenced extreme metal broadly.\n\nFifteen studio albums starting with *War and Pain* (1984). Critical peaks include *Killing Technology* (1987), *Dimension Hatröss* (1988), and *Nothingface* (1989, featuring a cover of Pink Floyd's \"Astronomy Domine\"). Piggy died of colorectal cancer in 2005; the band continued with archived guitar parts and new guitarist Daniel Mongrain (2008-present).",
  "wasp":
    "American heavy metal band formed in Los Angeles in 1982 by vocalist/bassist Blackie Lawless. Long associated with the controversies that fueled the 1985 PMRC Senate hearings on rock-music labeling. Known for their over-the-top stage presentation in the early 1980s.\n\nSixteen studio albums starting with the self-titled 1984 debut. Commercial peak: *The Last Command* (1985), *Inside the Electric Circus* (1986), and the concept album *The Crimson Idol* (1992). Lawless has been the only continuous member through frequent lineup changes.",
  "weather-report":
    "American jazz fusion band formed in New York City in 1970 by keyboardist Joe Zawinul (formerly of Miles Davis's electric-era ensembles) and saxophonist Wayne Shorter. Long-running rhythm section over the band's history included Alphonse Mouzon, Eric Gravatt, Chester Thompson, Peter Erskine (drums), and bassists Miroslav Vitous, Alphonso Johnson, and famously Jaco Pastorius (1976-1981).\n\nFifteen studio albums between 1971 and 1986. Commercial peak: *Heavy Weather* (1977), featuring \"Birdland\" — later widely covered. Other significant releases include *Mysterious Traveller* (1974), *Black Market* (1976), and *Mr. Gone* (1978). The band dissolved in 1986. Zawinul died in 2007; Shorter died in 2023.",
  "alice-in-chains":
    "American rock band formed in Seattle in 1987. Original lineup: Layne Staley (vocals, 1987-2002), Jerry Cantrell (guitar/vocals), Mike Starr (bass, 1987-1993), and Sean Kinney (drums). Often associated with the early-1990s grunge wave despite the band's heavier metal-influenced approach.\n\nTheir first three albums — *Facelift* (1990), *Dirt* (1992), and the self-titled third album (1995) — sold a combined 12 million-plus copies in the US. Staley died of an overdose in 2002. The band reunited in 2005 with vocalist William DuVall and has released three subsequent albums: *Black Gives Way to Blue* (2009), *The Devil Put Dinosaurs Here* (2013), and *Rainier Fog* (2018).",
  "anal-cunt":
    "American grindcore band formed in Newton, Massachusetts in 1988 by Seth Putnam (vocals, died 2011). Known for deliberately offensive lyrics, extremely short song lengths (often under 30 seconds), and minimal instrumentation. Frequently censored their name to \"AxCx\" in promotional contexts.\n\nEight studio albums and over 30 EPs/splits starting with *Everyone Should Be Killed* (1994). The band's controversial humor and Putnam's frequent provocations defined their reception. Putnam died in 2011 of a heart attack; the band has been formally dissolved since.",
  "bad-brains":
    "American hardcore band formed in Washington, D.C. in 1976 (originally as Mind Power, a jazz-fusion group). Lineup: H.R. (Paul D. Hudson, vocals), Dr. Know (Gary Miller, guitar), Darryl Jenifer (bass), and Earl Hudson (drums). Pioneers of hardcore punk; their fusion of hardcore with reggae and Rastafarian spirituality was influential on subsequent post-hardcore and crossover bands.\n\nEight studio albums starting with the 1982 self-titled debut. Best-known releases include *I Against I* (1986) and *Quickness* (1989). H.R.'s mental health issues caused recurring band instability; he has cycled in and out of the lineup multiple times. Recent reunion shows have continued into the 2020s.",
  "bad-company":
    "English-American hard rock supergroup formed in 1973. Founding lineup: Paul Rodgers (vocals, formerly of Free), Mick Ralphs (guitar, formerly of Mott the Hoople), Boz Burrell (bass, formerly of King Crimson), and Simon Kirke (drums, formerly of Free). Considered one of the foundational arena-rock acts of the 1970s.\n\nSix studio albums in the original Rodgers era (1974-1982): *Bad Company* (1974), *Straight Shooter* (1975), *Run with the Pack* (1976), *Burnin' Sky* (1977), *Desolation Angels* (1979), and *Rough Diamonds* (1982). The band continued with Brian Howe (1986-1994) and Robert Hart (1994-1998) as vocalists. Inducted into the Rock and Roll Hall of Fame in 2025.",
  "black-mountain":
    "Canadian psychedelic rock band formed in Vancouver in 2004 by Stephen McBean (vocals/guitar). Long-running lineup also included Amber Webber (vocals, 2004-2016), Matt Camirand (bass), Joshua Wells (drums), and Jeremy Schmidt (keyboards). Style draws on 1970s heavy psych, prog, and stoner rock.\n\nFive studio albums between 2005 and 2019, including the self-titled debut (2005), *In the Future* (2008), *Wilderness Heart* (2010), and *IV* (2016). Webber departed in 2016; subsequent lineups have continued as a McBean-led project.",
  "blink182":
    "American rock band formed in Poway, California in 1992. Classic lineup: Mark Hoppus (vocals/bass), Tom DeLonge (vocals/guitar, 1992-2015, 2022-present), and Travis Barker (drums, 1998-present, replacing Scott Raynor). Among the most commercially successful pop-punk bands of the late 1990s and 2000s.\n\nNine studio albums including *Enema of the State* (1999, multi-platinum), *Take Off Your Pants and Jacket* (2001), and the self-titled experimental fifth album (2003). DeLonge departed in 2005 (followed by a 2009-2015 reunion) before another extended absence and 2022 return. Matt Skiba (of Alkaline Trio) filled DeLonge's spot from 2015 to 2022.",
  "brian-setzer":
    "American guitarist and vocalist born April 10, 1959, in Massapequa, New York. First gained prominence as vocalist/guitarist for the Stray Cats. Following the band's 1984 breakup, he pursued solo projects and founded the Brian Setzer Orchestra.\n\nReleased over 15 solo studio albums and Orchestra albums starting with *The Knife Feels Like Justice* (1986). The Brian Setzer Orchestra's 1998 cover of \"Jump, Jive an' Wail\" rejuvenated his commercial profile during the late-1990s swing revival. The orchestra's *Boogie Woogie Christmas* (2002) became a perennial holiday album. Continues to record and tour.",
  "brothers-keeper":
    "American hardcore band formed in Erie, Pennsylvania in 1993. Long-running lineup centered on guitarist John Wylie. The band has been associated with the underground straightedge and Christian hardcore scenes.\n\nFive studio albums starting with their self-titled debut (1995). Best-known releases include *The Reality of Sentiment* (1998), *Last Straw* (2000), and *We Were Made for Spectacular Things* (2005). Released primarily on Trustkill, Solid State, and Resurrection A.D.",
  "dance-hall-crashers":
    "American ska-punk band formed in Berkeley, California in 1989 by Operation Ivy alumni Tim Armstrong and Matt Freeman (both before Rancid). Vocalists Karina Denike and Elyse Rogers anchored the band's long-running classic lineup, with Armstrong and Freeman departing early to form Rancid.\n\nFive studio albums between 1989 and 2002, including *Lockjaw* (1995), *Honey, I'm Homely!* (1997), and *Purr* (1999). Released primarily on (510) Records and MCA. Active intermittently since 2002.",
  "david-lee-roth":
    "American singer and entertainer born October 10, 1954, in Bloomington, Indiana. First gained prominence as the original vocalist for Van Halen (1974-1985, 2007-2020) before launching a solo career during his first departure from the band.\n\nReleased five solo studio albums between 1986 and 2003. Commercial peak: *Eat 'Em and Smile* (1986), which featured guitarist Steve Vai. Subsequent solo work — *Skyscraper* (1988), *A Little Ain't Enough* (1991), *Your Filthy Little Mouth* (1994) — did not match the early peak. After his second Van Halen tenure ended in 2020, Roth has pursued various solo touring and visual-art projects.",
  "dog-eat-dog":
    "American rap rock band formed in Bergenfield, New Jersey in 1990. Lineup centered on John Connor (vocals), Dave Neabore (bass), and Sean Kilkenny (guitar). Style fused hardcore punk, hip-hop, and ska.\n\nFive studio albums starting with *Warrant* EP (1993) and *All Boro Kings* (1994). The single \"No Fronts\" from *All Boro Kings* gained widespread MTV rotation. Subsequent releases include *Play Games* (1996), *Amped* (1999), and *Walk With Me* (2006). The band has performed intermittent reunion tours, particularly in Europe where they retain a strong fan base.",
  "donnie-iris":
    "American rock singer born February 28, 1943, in Ellwood City, Pennsylvania. First gained prominence as vocalist for The Jaggerz (\"The Rapper,\" 1970) before launching a solo career with the Cruisers band as backing musicians.\n\nReleased eleven studio albums starting with *Back on the Streets* (1980). Best-known single: \"Ah! Leah!\" (1980). Subsequent releases include *King Cool* (1981), *The High and the Mighty* (1982), and *Fortune 410* (1983). The Cruisers — Mark Avsec (keyboards), Marty Lee (guitar), Albritton McClain (bass, later Paul Goll), and Kevin Valentine (drums) — have remained largely consistent. Iris continues to perform regionally in the Pittsburgh area.",
  "down-by-law":
    "American punk rock band formed in Los Angeles in 1989 by Dave Smalley (vocals, formerly of Dag Nasty, DYS, and ALL). Long-running lineup around Smalley with various guitarists, bassists, and drummers.\n\nNine studio albums including the self-titled debut (1991), *Punkrockacademyfightsong* (1994), *All Scratched Up!* (1996), and *Last of the Sharpshooters* (1997). Released primarily on Epitaph during the label's mid-1990s peak. The band has remained active in some form since 1989.",
  "dream-theater":
    "American progressive metal band formed in Boston in 1985 (originally as Majesty) by John Petrucci (guitar), John Myung (bass), and Mike Portnoy (drums, 1985-2010, 2023-present). The classic lineup also includes James LaBrie (vocals, since 1991) and Jordan Rudess (keyboards, since 1999).\n\nFifteen studio albums starting with *When Dream and Day Unite* (1989). Best-known releases include *Images and Words* (1992, featuring \"Pull Me Under\"), *Metropolis Pt. 2: Scenes from a Memory* (1999), and *Octavarium* (2005). Mike Portnoy departed in 2010 and rejoined in 2023.",
  "dwight-yoakam":
    "American country singer-songwriter, guitarist, and actor born October 23, 1956, in Pikeville, Kentucky. Associated with the \"Bakersfield sound\" revival of the 1980s, drawing on Buck Owens and Merle Haggard as primary influences.\n\nReleased over 15 studio albums starting with *Guitars, Cadillacs, Etc., Etc.* (1986). Commercial peak: *Hillbilly Deluxe* (1987), *Buenas Noches from a Lonely Room* (1988), *If There Was a Way* (1990), and *This Time* (1993). Notable acting roles include *Sling Blade* (1996), *Panic Room* (2002), and *Crank* (2006).",
  "eagles":
    "American rock band formed in Los Angeles in 1971. Original lineup: Glenn Frey (vocals/guitar), Don Henley (vocals/drums), Bernie Leadon (guitar/vocals), and Randy Meisner (bass/vocals). Joe Walsh joined in 1975 replacing Leadon; Timothy B. Schmit replaced Meisner in 1977.\n\nSeven studio albums during the original 1971-1980 run plus the long-delayed *Long Road Out of Eden* (2007). *Their Greatest Hits 1971-1975* (1976) sold over 38 million copies in the US — one of the best-selling albums of all time. Frey died in 2016. The band has continued to tour with Frey's son Deacon Frey and country singer Vince Gill. Inducted into the Rock and Roll Hall of Fame in 1998.",
  "eddie-money":
    "American singer-songwriter (1949-2019). Born Edward Mahoney in Brooklyn, New York; briefly served as a NYPD officer before pursuing music. His blue-collar rock persona and Bay Area-honed sound made him a 1970s-1980s AOR mainstay.\n\nEleven studio albums between *Eddie Money* (1977) and *Eddie Money Christmas* (2018). Commercial peak singles: \"Two Tickets to Paradise,\" \"Baby Hold On,\" \"Shakin',\" and the 1986 comeback \"Take Me Home Tonight\" (a duet with Ronnie Spector). Money died of esophageal cancer in 2019, shortly after the AXS TV reality series *Real Money* aired.",
  "elvis":
    "Elvis Presley (1935-1977). American singer, musician, and actor born in Tupelo, Mississippi. Widely regarded as the most popular and influential American musician of the 20th century — a foundational figure in rock and roll, rockabilly, gospel, and country crossover. Often referred to simply as \"Elvis\" or \"the King.\"\n\nReleased 24 studio albums during his lifetime, plus dozens of compilation, soundtrack, and live albums. Initial commercial breakthrough on Sun Records (1954) and RCA (1955 onward). Major career arcs include his 1968 \"Comeback Special\" return after a decade of mostly soundtrack work, and the Las Vegas residency era (1969-1977). Inducted into the Rock and Roll Hall of Fame in 1986.",
  "elvis-costello-the-imposters":
    "English rock band, formed in 2001 as Elvis Costello's primary backing band after the dissolution of the Attractions. Lineup: Costello (vocals/guitar), Steve Nieve (keyboards), Davey Faragher (bass), and Pete Thomas (drums). Two of the three Imposters (Nieve, Thomas) were previously Attractions; Faragher replaced original Attractions bassist Bruce Thomas.\n\nSix studio albums under the Costello & Imposters banner including *When I Was Cruel* (2002), *The Delivery Man* (2004), *Momofuku* (2008), and *Hey Clockface* (2020). Costello has used the band for a substantial portion of his post-2001 output, including extensive touring.",
  "fleetwood-mac":
    "British-American rock band formed in London in 1967. The band has had many lineups; the most commercially successful version (1975-present) features Mick Fleetwood (drums), John McVie (bass), Christine McVie (keyboards/vocals, 1970-1998, 2014-2022), Lindsey Buckingham (guitar/vocals, 1975-1987, 1997-2018), and Stevie Nicks (vocals, 1975-present).\n\nEighteen studio albums total. The lineup's debut, *Fleetwood Mac* (1975), and follow-up *Rumours* (1977) made the band into one of the best-selling acts of all time — *Rumours* alone has sold over 40 million copies worldwide. Christine McVie died in 2022. Inducted into the Rock and Roll Hall of Fame in 1998.",
  "foreigner":
    "American-British rock band formed in New York City in 1976 by Mick Jones (guitar) and Ian McDonald (multi-instrumentalist, formerly of King Crimson). Vocalist Lou Gramm fronted the band from 1976 to 2003; Kelly Hansen has been the band's vocalist since 2005.\n\nNine studio albums between *Foreigner* (1977) and *Can't Slow Down* (2009). Commercial peak: *Foreigner* (1977), *Double Vision* (1978), *Head Games* (1979), *4* (1981), and *Agent Provocateur* (1984, featuring \"I Want to Know What Love Is\"). Inducted into the Rock and Roll Hall of Fame in 2024.",
  "g-love-special-sauce":
    "American band formed in Philadelphia in 1992 by Garrett Dutton (G. Love, vocals/guitar/harmonica). Long-running lineup also includes Jeffrey \"the Houseman\" Clemens (drums) and Jim \"Jazz\" Prescott (bass, 1992-2003). Style combines blues, hip-hop, folk, and rock.\n\nEleven studio albums starting with the self-titled debut (1994). Best-known releases include *Coast to Coast Motel* (1995), *Yeah, It's That Easy* (1997), and *The Hustle* (2004). Released primarily on OKeh and Brushfire Records. Continues to tour.",
  "gorilla-biscuits":
    "American hardcore band formed in New York City in 1986. Lineup: Civ (Anthony Civarelli, vocals), Walter Schreifels (guitar, later of Quicksand), Arthur Smilios (bass), Luke Abbey (drums), and Alex Brown (guitar/vocals, 1988-1990). Foundational to the \"youth crew\" hardcore scene alongside Youth of Today and Judge.\n\nTwo studio releases in the band's original 1986-1991 run: the *Gorilla Biscuits* EP (1988) and the LP *Start Today* (1989). Schreifels and Civ went on to form Quicksand and Civ, respectively. The band has performed periodic reunion shows since 2005 and continues to tour intermittently.",
  "joe-jackson":
    "English musician born David Ian Jackson in 1954. Initially associated with the British new wave scene; subsequent career has spanned jazz, classical, swing, and pop with frequent stylistic shifts.\n\nReleased over 20 studio albums starting with *Look Sharp!* (1979). Commercial peak years 1979-1984: *I'm the Man* (1979), *Night and Day* (1982, including \"Steppin' Out\"), and *Body and Soul* (1984). Subsequent work includes the symphonic *Symphony No. 1* (1999) and the genre-spanning *Volume 4* (2003).",
  "johnny-cash":
    "American singer-songwriter (1932-2003). Born in Kingsland, Arkansas. Among the most influential American musicians of the 20th century, with a career spanning country, rock and roll, rockabilly, blues, folk, and gospel. Often referred to as \"the Man in Black\" for his trademark stage attire.\n\nReleased 97 studio albums between *Johnny Cash with His Hot and Blue Guitar* (1957) and his posthumous *American VI: Ain't No Grave* (2010). Career peak releases include the prison concert albums *At Folsom Prison* (1968) and *At San Quentin* (1969), and the Rick Rubin-produced *American Recordings* series (1994-2010). Inducted into the Country Music Hall of Fame (1980), the Songwriters Hall of Fame (1977), and the Rock and Roll Hall of Fame (1992).",
  "life-of-agony":
    "American alternative metal band formed in Brooklyn, New York in 1989. Lineup: Mina Caputo (vocals; previously credited as Keith Caputo prior to her 2011 gender transition), Joey Z. (Joseph Zampella, guitar), Alan Robert (bass), and various drummers.\n\nSix studio albums starting with *River Runs Red* (1993), which became a cult favorite in the 1990s alternative metal scene. Subsequent releases include *Ugly* (1995), *Soul Searching Sun* (1997), and *A Place Where There's No More Pain* (2017). The band broke up in 1999, reunited in 2003, broke up again, and reunited a second time in 2014.",
  "lionel-richie":
    "American singer-songwriter and producer born June 20, 1949, in Tuskegee, Alabama. First gained prominence as lead vocalist and primary songwriter for the Commodores (1968-1980) before launching a solo career.\n\nTen solo studio albums starting with the self-titled 1982 debut. Commercial peak: *Can't Slow Down* (1983, multi-platinum, featuring \"All Night Long (All Night)\" and \"Hello\") and *Dancing on the Ceiling* (1986). Subsequent career has included extensive touring, a 2018-present judging role on *American Idol*, and continued chart appearances. Inducted into the Songwriters Hall of Fame in 1994.",
  "little-feat":
    "American rock band formed in Los Angeles in 1969 by Lowell George (vocals/slide guitar, 1969-1979) and Bill Payne (keyboards/vocals). Other long-running members include Sam Clayton (percussion/vocals), Kenny Gradney (bass), Paul Barrere (guitar, 1972-2019, died 2019), and Richie Hayward (drums, 1969-2009, died 2010).\n\nReleased 16 studio albums between *Little Feat* (1971) and *Sam's Place* (2024). Critical peak: *Dixie Chicken* (1973), *Feats Don't Fail Me Now* (1974), *The Last Record Album* (1975), and *Time Loves a Hero* (1977). The band broke up after George's 1979 death from a heart attack and reformed in 1987 with new members.",
  "luscious-jackson":
    "American band formed in New York City in 1991. Lineup: Jill Cunniff (vocals/bass), Gabby Glaser (vocals/guitar), Kate Schellenbach (drums, also formerly of the Beastie Boys), and Vivian Trimble (keyboards, 1991-1998). Style fused hip-hop, indie rock, funk, and soul.\n\nThree studio albums and an EP between 1992 and 1999, including *Natural Ingredients* (1994), *Fever In Fever Out* (1996, featuring \"Naked Eye\"), and *Electric Honey* (1999). Released primarily on the Beastie Boys' Grand Royal label. The band reunited in 2011 to record *Magic Hour* (2013), a children's album.",
  "lynyrd-skynyrd":
    "American Southern rock band formed in Jacksonville, Florida in 1964. Original lineup: Ronnie Van Zant (vocals, 1964-1977, died), Gary Rossington (guitar, 1964-2023, died), Allen Collins (guitar, 1964-1990, died), Larry Junstrom (bass), and Bob Burns (drums). The band's 1977 plane crash killed Van Zant, Steve Gaines (guitar), and Cassie Gaines (vocals), ending the original era.\n\nFive studio albums in the original era (1973-1977), including *Pronounced 'Lĕh-'nérd 'Skin-'nérd* (1973, featuring \"Free Bird\"), *Second Helping* (1974, featuring \"Sweet Home Alabama\"), and *Street Survivors* (1977, released three days before the crash). The band reformed in 1987 with Van Zant's brother Johnny Van Zant as vocalist; eight subsequent studio albums. Rossington died in 2023, ending the run of original founding members. Inducted into the Rock and Roll Hall of Fame in 2006.",
  "marilyn-manson":
    "American rock singer (born Brian Hugh Warner, 1969). The eponymous band has had multiple lineups built around Manson; longest-tenured collaborator was Twiggy Ramirez (Jeordie White, 1993-2002, 2008-2017). Distinguished by deliberately provocative theatrical performances, lyrics, and album artwork.\n\nEleven studio albums starting with *Portrait of an American Family* (1994). Commercial peak: *Antichrist Superstar* (1996), *Mechanical Animals* (1998), and *Holy Wood (In the Shadow of the Valley of Death)* (2000) — the band's \"Triptych.\" Manson has been involved in significant legal controversy since 2021, with multiple sexual assault and abuse allegations against him.",
  "marky-ramone-and-the-intruders":
    "American punk rock band led by Marky Ramone (Marc Bell), drummer of the Ramones from 1978 to 1996 (in two stretches). Lineup also typically includes vocalist Ben Trokan and various guitarists/bassists.\n\nThree studio albums between 1996 and 2000: *Marky Ramone and the Intruders* (1996), *The Answer to Your Problems?* (1999), and *Pop Punk World* (2000). Marky Ramone has subsequently led several other tribute and post-Ramones touring projects, including Marky Ramone's Blitzkrieg.",
  "megadeth":
    "American thrash metal band formed in Los Angeles in 1983 by guitarist/vocalist Dave Mustaine after his firing from Metallica. Long-running lineup centered on Mustaine and bassist David Ellefson (1983-2002, 2010-2021). One of the \"Big Four\" thrash bands alongside Metallica, Anthrax, and Slayer.\n\nSixteen studio albums starting with *Killing Is My Business... and Business Is Good!* (1985). Commercial peak: *Peace Sells... but Who's Buying?* (1986), *Rust in Peace* (1990), *Countdown to Extinction* (1992), and *Youthanasia* (1994). Mustaine has been treated for throat cancer (2019); the band has continued to record and tour.",
  "monster-magnet":
    "American stoner rock band formed in Red Bank, New Jersey in 1989 by Dave Wyndorf (vocals/guitar). Long-running lineup also includes Phil Caivano (guitar) and Bob Pantella (drums). Style draws on 1970s heavy psych, sci-fi pulp imagery, and proto-metal.\n\nEleven studio albums starting with *Spine of God* (1991). Commercial peak: *Powertrip* (1998, featuring \"Space Lord\"). Wyndorf's heroin addiction caused a 2006 overdose that nearly killed him; the band has continued with subsequent releases through *A Better Dystopia* (2021), a covers album.",
  "motrhead":
    "English rock band formed in London in 1975 by Lemmy Kilmister (vocals/bass, died 2015). The classic lineup of Lemmy with Fast Eddie Clarke (guitar, 1976-1982) and Phil \"Philthy Animal\" Taylor (drums, 1975-1984, 1987-1992) defined the band's primary 1979-1981 commercial peak. Influential on both heavy metal and hardcore punk.\n\nTwenty-two studio albums between *Motörhead* (1977) and *Bad Magic* (2015). Critical peaks include *Overkill* (1979), *Bomber* (1979), and *Ace of Spades* (1980). Lemmy died of cancer in December 2015 days after his 70th birthday; the band has been formally dissolved since.",
  "mustard-plug":
    "American ska-punk band formed in Grand Rapids, Michigan in 1991. Long-running lineup centered on vocalist Dave Kirchgessner. Style typified by horns, danceable rhythms, and pop-punk songcraft.\n\nSeven studio albums starting with *Big Daddy Multitude* (1993). Best-known releases include *Evildoers Beware!* (1997) and *Pray for Mojo* (1999). Released primarily on Hopeless Records during the late-1990s third-wave ska revival.",
  "oingo-boingo":
    "American new wave band formed in Los Angeles in 1979 by composer Danny Elfman, evolved from the earlier performance-art group the Mystic Knights of the Oingo Boingo. Lineup also included Steve Bartek (guitar), John Avila (bass, from 1984), and a long-running brass section.\n\nEight studio albums between 1981 and 1994. Commercial breakthrough single \"Weird Science\" from the 1985 film of the same name. Other notable releases: *Only a Lad* (1981), *Good for Your Soul* (1983), *Dead Man's Party* (1985), and *Boi-Ngo* (1987). Elfman transitioned to a major film-scoring career starting with Tim Burton's *Pee-wee's Big Adventure* (1985), eventually dissolving the band in 1995.",
  "overkill":
    "American thrash metal band formed in Old Bridge, New Jersey in 1980. Long-running lineup centered on vocalist Bobby \"Blitz\" Ellsworth and bassist D.D. Verni (both with the band since formation). Considered foundational to the East Coast thrash scene alongside Anthrax.\n\nTwenty studio albums starting with *Feel the Fire* (1985). Best-known releases include *Taking Over* (1987), *The Years of Decay* (1989), *Horrorscope* (1991), and *Ironbound* (2010). Active continuously since 1980 — exceptionally consistent for the genre.",
  "paul-simon":
    "American singer-songwriter born October 13, 1941, in Newark, New Jersey. First gained prominence in the folk-rock duo Simon & Garfunkel (1956-1970) before launching a successful solo career.\n\nReleased 14 solo studio albums between *The Paul Simon Songbook* (1965) and *Seven Psalms* (2023). Commercial peak: *There Goes Rhymin' Simon* (1973), *Still Crazy After All These Years* (1975), and the Grammy-winning *Graceland* (1986) — the latter notably bringing South African musicians to international prominence during the apartheid-era cultural boycott. Inducted into the Rock and Roll Hall of Fame twice (1990 with Simon & Garfunkel, 2001 as a solo artist).",
  "pretenders":
    "English-American rock band formed in Hereford, England in 1978 by American expatriate Chrissie Hynde (vocals/guitar). Original lineup included James Honeyman-Scott (guitar, 1978-1982, died), Pete Farndon (bass, 1978-1982, died), and Martin Chambers (drums). Both Honeyman-Scott and Farndon died of drug-related causes in 1982 and 1983 respectively.\n\nEleven studio albums starting with *Pretenders* (1979). Commercial peak: *Pretenders II* (1981) and *Learning to Crawl* (1984, featuring \"Back on the Chain Gang\" and \"Middle of the Road\"). The band has continued through frequent lineup changes around Hynde, who remains the only continuous member. Inducted into the Rock and Roll Hall of Fame in 2005.",
  "primus":
    "American rock band formed in El Sobrante, California in 1984 by bassist/vocalist Les Claypool. Classic lineup includes Larry \"Ler\" LaLonde (guitar) and various drummers — most notably Tim \"Herb\" Alexander (1989-1996, 2003-2010, 2013-2023) and Brain Mantia (1996-2003, 2010-2013). Distinguished by Claypool's virtuosic bass playing and the band's idiosyncratic, often satirical songwriting.\n\nNine studio albums starting with *Frizzle Fry* (1990). Commercial peak: *Sailing the Seas of Cheese* (1991), *Pork Soda* (1993), and *Tales from the Punchbowl* (1995). Claypool composed the *South Park* TV theme (1997). Continuously active in some form since 1984.",
  "public-enemy":
    "American hip-hop group formed in Roosevelt, New York in 1985. Original lineup: Chuck D (Carlton Ridenhour, vocals), Flavor Flav (William Drayton, vocals/hype man), Professor Griff (Richard Griffin, \"Minister of Information\"), and the Bomb Squad production team (Hank Shocklee, Eric Sadler, Keith Shocklee). One of the most politically influential acts in hip-hop history.\n\nFifteen studio albums starting with *Yo! Bum Rush the Show* (1987). Critical peak: *It Takes a Nation of Millions to Hold Us Back* (1988) and *Fear of a Black Planet* (1990). Notable for sample-heavy \"wall of noise\" production and Chuck D's pointed political commentary. Inducted into the Rock and Roll Hall of Fame in 2013.",
  "ratt":
    "American glam metal band formed in San Diego in 1976 (originally as Mickey Ratt). Classic lineup: Stephen Pearcy (vocals), Warren DeMartini (guitar), Robbin Crosby (guitar, 1981-1990, died 2002), Juan Croucier (bass), and Bobby Blotzer (drums).\n\nTheir 1984 debut *Out of the Cellar* sold over 3 million copies in the US on the strength of \"Round and Round.\" Subsequent releases: *Invasion of Your Privacy* (1985), *Dancing Undercover* (1986), *Reach for the Sky* (1988), and *Detonator* (1990). Crosby died of AIDS-related causes in 2002. The band has reunited and split multiple times since the late 1990s.",
  "savatage":
    "American progressive metal band formed in Tarpon Springs, Florida in 1979 by brothers Jon Oliva (vocals/keyboards) and Criss Oliva (guitar). Criss died in a car accident in 1993; Jon has continued the band intermittently with various lineups.\n\nEleven studio albums starting with *Sirens* (1983). Critical peak: the rock operas produced by Paul O'Neill — *Hall of the Mountain King* (1987), *Gutter Ballet* (1989), *Streets: A Rock Opera* (1991), and *Dead Winter Dead* (1995). The band's 1995 release of \"Christmas Eve (Sarajevo 12/24)\" eventually became the foundation of Paul O'Neill's Trans-Siberian Orchestra project.",
};

async function main() {
  const dryRun = process.argv.includes("--dry-run");
  const force = process.argv.includes("--force");
  const { containers } = await import("../lib/cosmos");
  const { getStoredArtist } = await import("../lib/artists");

  let written = 0;
  let skipped = 0;
  let missing = 0;

  for (const [slug, description] of Object.entries(DESCRIPTIONS)) {
    const existing = await getStoredArtist(slug);
    if (!existing) {
      console.log(`✗ ${slug}: no stored doc found`);
      missing += 1;
      continue;
    }
    if (existing.description && !force) {
      console.log(`↷ ${slug}: already has description — skipping`);
      skipped += 1;
      continue;
    }
    if (dryRun) {
      console.log(`◌ ${slug}: would write ${description.length} chars`);
      written += 1;
      continue;
    }
    const updated = {
      ...existing,
      description,
      updatedAt: new Date().toISOString(),
    };
    await containers.artists.item(slug, slug).replace(updated);
    console.log(`✓ ${slug}: ${description.length} chars`);
    written += 1;
  }

  console.log(`\nDone. written=${written} skipped=${skipped} missing=${missing}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
