import { config as loadEnv } from "dotenv";
loadEnv({ path: ".env.local" });

const DESCRIPTIONS: Record<string, string> = {
  "days-of-the-new":
    "American rock band formed in Charlestown, Indiana in 1995 by Travis Meeks (vocals/guitar). Style draws on acoustic-driven post-grunge and alternative rock.\n\nThree studio albums between *Days of the New* (1997, multi-platinum, featuring \"Touch, Peel and Stand\" and \"Shelf in the Room\") and *Days of the New III* (2001). The original lineup (Meeks, Todd Whitener, Jesse Vest, Matt Taul) departed after the debut to form Tantric; Meeks has continued under the Days of the New name with rotating personnel. His public struggles with substance abuse have been documented in *Intervention* (2009).",
  "death":
    "American death metal band formed in Altamonte Springs, Florida in 1984 by Chuck Schuldiner (vocals/guitar, 1967-2001). Foundational to the development of death metal as a genre; widely cited as one of the originating acts alongside Possessed and Morbid Angel. Schuldiner is the only continuous member.\n\nSeven studio albums between *Scream Bloody Gore* (1987) and *The Sound of Perseverance* (1998). Critical peak: *Human* (1991), *Individual Thought Patterns* (1993), and *Symbolic* (1995). Schuldiner died of brain cancer in December 2001 at age 34; the band has remained dissolved. The 2003 archival album *Live in L.A.* and various retrospective collections have continued his legacy.",
  "dee-gees":
    "Side project of Foo Fighters performing Bee Gees disco covers. Released as a Foo Fighters EP, *Hail Satin* (2021, a Record Store Day exclusive). The album also includes live versions of *Medicine at Midnight* songs.\n\nThe project's existence — and its tongue-in-cheek name — emerged from Dave Grohl's lifelong love of disco-era Bee Gees. The 2024 album *Where the Pyramid Meets the Eye* (under the Dee Gees name) was a follow-up release.",
  "deke-dickerson":
    "American guitarist and singer born in Columbia, Missouri. Specialist in rockabilly, hillbilly, Western swing, and rhythm-and-blues revivalism. Has worked extensively with vintage instruments and amplifiers — particularly Mosrite guitars and the rare \"double-neck\" configuration.\n\nReleased over a dozen studio albums starting with *Number One Hit Record* (1998). Frequently collaborates with vintage country and rockabilly artists; has produced and engineered for various roots-music projects. Active continuously since the mid-1990s.",
  "del-mccoury":
    "American bluegrass musician born February 1, 1939, in Bakersville, North Carolina. Long-running bandleader of the Del McCoury Band, with sons Ronnie McCoury (mandolin) and Rob McCoury (banjo) as core members. Among the most acclaimed traditional bluegrass artists of the late 20th and early 21st centuries.\n\nReleased over 20 albums starting with *Del McCoury Sings Bluegrass* (1968). Career-defining acts include over 30 IBMA Awards (more than any other artist) and the 1996 album *The Cold Hard Facts*. Frequently collaborates across genre lines — with Steve Earle (*The Mountain*, 1999) and Bruce Hornsby, among others. Inducted into the Grand Ole Opry in 2003.",
  "del-tha-funke-homosapien":
    "American rapper born Teren Delvon Jones on August 12, 1972, in Oakland, California. Cousin of Ice Cube; first gained prominence through Cube's Lench Mob Records. Member of the Hieroglyphics collective along with Casual, Souls of Mischief, and others.\n\nReleased seven studio albums starting with *I Wish My Brother George Was Here* (1991, featuring \"Mistadobalina\"). Best-known releases include *No Need for Alarm* (1993), *Both Sides of the Brain* (2000), and *Eleventh Hour* (2008). Also a member of the Damon Albarn-led virtual band Gorillaz on the singles \"Clint Eastwood\" (2001) and \"Rock the House\" (2001).",
  "dennis-brown":
    "Jamaican reggae singer (1957-1999). Born in Kingston. Often called \"the Crown Prince of Reggae.\" Began his recording career at age 11 with Studio One; widely considered one of the most influential reggae vocalists ever.\n\nReleased over 75 studio albums between *No Man Is an Island* (1969) and the posthumous *Death Before Dishonor* (2000). Critical peak: *Wolves and Leopards* (1977), *Visions* (1978), and *Joseph's Coat of Many Colours* (1978). Bob Marley reportedly cited Brown as his favorite singer. Died from respiratory failure related to long-term cocaine addiction.",
  "derek-and-the-dominos":
    "English-American blues-rock supergroup formed in 1970 by Eric Clapton (vocals/guitar), Bobby Whitlock (vocals/keyboards), Carl Radle (bass, died 1980), and Jim Gordon (drums, died 2023). Guitarist Duane Allman (of the Allman Brothers Band) contributed extensively to the band's only studio album but was never an official member.\n\nReleased one studio album: the double LP *Layla and Other Assorted Love Songs* (1970). Best-known song: \"Layla,\" written by Clapton about Pattie Boyd (then George Harrison's wife, later Clapton's). The band dissolved in 1971 after substance-abuse-related fractures and the death of Duane Allman in 1971.",
  "desmond-dekker":
    "Jamaican singer (1941-2006). Born Desmond Adolphus Dacres in Saint Andrew, Jamaica. Among the most internationally successful ska and rocksteady artists of the late 1960s.\n\nReleased over 20 studio albums between *007 (Shanty Town)* (1967) and *Halfway to Paradise* (1999). Best-known single: \"Israelites\" (1968), the first Jamaican-recorded song to top the UK Singles Chart and the first reggae song to reach the top 10 on the Billboard Hot 100. Other significant hits: \"007 (Shanty Town),\" \"It Mek,\" and \"Sing a Little Song.\"",
  "desmond-dekker-the-aces":
    "Jamaican vocal group fronted by Desmond Dekker (1941-2006). The Aces — comprising brothers Wilson James, Easton Barrington Howard, and Patrick Johnson — provided harmony vocals behind Dekker on most of his late-1960s commercial peak. The group was credited as \"Desmond Dekker & The Aces\" on many of the original Pyramid and Beverley's recordings.\n\nThe collaboration produced \"Israelites,\" \"007 (Shanty Town),\" and many other ska and rocksteady classics. Dekker continued as a solo artist after the Aces' departure in 1969.",
  "despair":
    "American hardcore band formed in Cleveland in 1995. Style draws on metallic hardcore and post-hardcore.\n\nReleased two studio albums in their brief original run: *Self-Titled* (1996) and *History of Hate* (1998). Released primarily on Trustkill and Watchmaker Records. The band has been inactive since the late 1990s.",
  "destinys-child":
    "American R&B group formed in Houston in 1990 (originally as Girl's Tyme). Best-known lineup: Beyoncé Knowles, Kelly Rowland, and Michelle Williams. Earlier lineups included LaTavia Roberson and LeToya Luckett (1997-2000), whose departures from the group during *The Writing's on the Wall* sessions led to high-profile legal disputes.\n\nFive studio albums between *Destiny's Child* (1998) and *Destiny Fulfilled* (2004). Commercial peak: *The Writing's on the Wall* (1999, featuring \"Bills, Bills, Bills,\" \"Say My Name,\" and \"Jumpin', Jumpin'\") and *Survivor* (2001, featuring \"Independent Women, Part I,\" \"Survivor,\" and \"Bootylicious\"). Disbanded in 2006 after the *Destiny Fulfilled... and Lovin' It* tour. Beyoncé has become one of the most commercially successful solo artists of the 21st century.",
  "dethlehem":
    "American comedy metal band formed in Pittsburgh in 2005. Distinguished by their over-the-top medieval-fantasy lyrical content, costumed live performances, and tongue-in-cheek take on Dungeons & Dragons-style narrative metal.\n\nReleased multiple studio albums starting with *Tales of the Brave* (2010). The band has performed extensively at gaming and tabletop conventions; their material frequently references RPG mechanics, dungeon crawls, and fantasy-novel tropes.",
  "diamond-rio":
    "American country band formed in Nashville in 1989. Long-running lineup: Marty Roe (vocals), Gene Johnson (mandolin/vocals), Jimmy Olander (guitar), Brian Prout (drums), Dan Truman (keyboards), and Dana Williams (bass). All six members have been continuous since formation — exceptionally rare for any band over a 35-plus year span.\n\nReleased nine studio albums between *Diamond Rio* (1991) and *I Made It* (2016). Commercial peak: the debut album (whose first single \"Meet in the Middle\" was the first single by a country group to debut at #1) and *Diamond Rio's Greatest Hits* (1997). Six Vocal Group of the Year wins at the Country Music Association awards.",
  "dickies":
    "Same artist as The Dickies — different Discogs/setlist.fm credit variation. American punk band formed in San Fernando Valley, California in 1977 by guitarist Stan Lee and vocalist Leonard Graves Phillips. Notable for their rapid tempos, bubblegum-pop melodies, and steady stream of cover songs. Phillips died in 2024.",
  "diddy":
    "American rapper, record producer, and entrepreneur born Sean John Combs on November 4, 1969, in Harlem, New York. Has performed and recorded under multiple stage names including Puff Daddy (1996-2001), P. Diddy (2001-2005), and Diddy (2005-present, though he announced in 2017 a return to \"Love\" before reverting).\n\nFounded Bad Boy Records in 1993, which signed the Notorious B.I.G., Mase, 112, Faith Evans, and many others. Released six studio albums starting with *No Way Out* (1997, multi-platinum, featuring \"I'll Be Missing You\" with Faith Evans and 112). Three Grammy Awards. Faces ongoing federal criminal proceedings and civil lawsuits beginning in 2024.",
  "diesel-boy":
    "American pop-punk band formed in San Francisco in 1995. Long-running lineup centered on vocalist/guitarist Adam Doll. Style draws on melodic pop-punk and skate-punk.\n\nFour studio albums between *Cock Rock* (1996) and *Sofa King Cool* (2003). Released primarily on Honest Don's Records (a Fat Wreck Chords subsidiary). Best-known release: *Venus Envy* (1999). The band has been inactive since the early 2000s.",
  "dillinger-four":
    "American punk rock band formed in Minneapolis in 1994. Long-running lineup: Patrick \"Paddy\" Costello (vocals/bass), Erik Funk (vocals/guitar), Bill Morrisette (drums, 1994-1998), Lane Pederson (drums, since 1998), and Billy Morrisette/Dan Adriaens (guitar). Distinguished by their politically charged lyrics and high-tempo melodic hardcore approach.\n\nFour studio albums between *Midwestern Songs of the Americas* (1998) and *Civil War* (2008). Released primarily on Fat Wreck Chords and Hopeless Records. The band releases material at a deliberately slow pace; *Civil War* has been their most recent album for over 16 years.",
  "dion":
    "American singer and songwriter born Dion DiMucci on July 18, 1939, in The Bronx, New York. First gained prominence as the lead vocalist of Dion and the Belmonts (1957-1960), then launched a long solo career. One of the few popular pre-Beatles American teen idols to remain commercially viable into the 1960s and beyond.\n\nReleased over 40 studio albums in his solo career, starting with *Alone with Dion* (1960). Best-known singles include \"Runaround Sue\" (1961), \"The Wanderer\" (1961), \"Ruby Baby\" (1963), and the late-1960s comeback \"Abraham, Martin and John\" (1968). Inducted into the Rock and Roll Hall of Fame in 1989. Continues to release blues-oriented material into the 2020s.",
  "dire-straits":
    "English rock band formed in Deptford, London in 1977. Lineup centered on Mark Knopfler (vocals/lead guitar). Other key members included his brother David Knopfler (rhythm guitar, 1977-1980), John Illsley (bass), Pick Withers (drums, 1977-1982), and Alan Clark (keyboards, since 1980). Distinguished by Knopfler's fingerpicked Stratocaster technique and the band's blues-influenced rock approach.\n\nSix studio albums between *Dire Straits* (1978) and *On Every Street* (1991). Commercial peak: *Brothers in Arms* (1985), which sold over 30 million copies worldwide on the strength of \"Money for Nothing\" and \"Walk of Life.\" The band dissolved in 1995; Knopfler has pursued a successful solo career since. Inducted into the Rock and Roll Hall of Fame in 2018.",
  "disciple":
    "American Christian rock band formed in Knoxville, Tennessee in 1992. Long-running lineup centered on Kevin Young (vocals). Other members have rotated over the band's 30-plus-year history.\n\nTwelve studio albums between *What Was I Thinking* (1995) and *By God* (2022). Commercial peak: the self-titled fifth album (2005) and *Southern Hospitality* (2008). Released primarily on Slain, INO, and Tooth & Nail Records.",
  "disturbed":
    "American rock band formed in Chicago in 1994 (originally as Brawl). Lineup: David Draiman (vocals), Dan Donegan (guitar), John Moyer (bass, since 2003), and Mike Wengren (drums). One of the most commercially successful American rock acts of the 2000s.\n\nEight studio albums starting with *The Sickness* (2000, multi-platinum, featuring \"Down with the Sickness\"). Subsequent peaks: *Believe* (2002), *Ten Thousand Fists* (2005), and *Indestructible* (2008) — all #1 albums on the Billboard 200. The band took a hiatus from 2011 to 2015 before returning with *Immortalized* (2015). Their 2015 cover of Simon & Garfunkel's \"The Sound of Silence\" became a viral hit.",
  "doc-severinsen":
    "American jazz trumpeter and bandleader born Carl Hilding Severinsen on July 7, 1927, in Arlington, Oregon. Best known as the long-running bandleader of *The Tonight Show Band* during Johnny Carson's tenure on the NBC program (1967-1992).\n\nReleased dozens of albums between the 1960s and 2010s. Known for his flamboyant on-air wardrobe and the friendly bantering relationship with Carson. Won the 1986 Grammy for Best Jazz Instrumental Performance, Big Band. Continues to perform with various ensembles at venues including the Royal Conservatory of Music in Mexico.",
  "doctor-smoke":
    "American doom-metal band formed in Cleveland in 2011. Lineup: Matt Tluchowski (vocals/guitar), Steve Lindner (guitar), Jeff Curtis (bass), and Brent Suchy (drums). Style draws on traditional doom, NWOBHM, and stoner rock.\n\nTwo studio albums: *The Witching Hour* (2014) and *Dreamers and the Dead* (2018). Released on Cruz del Sur Music. The band has been intermittently active.",
  "don-henley":
    "American singer, songwriter, and drummer born July 22, 1947, in Gilmer, Texas. Best known as a co-founder, drummer, and vocalist of the Eagles (1971-1980, 1994-present). Pursued a successful parallel solo career after the Eagles' 1980 dissolution.\n\nFive solo studio albums between *I Can't Stand Still* (1982) and *Cass County* (2015). Commercial peak: *Building the Perfect Beast* (1984, featuring \"The Boys of Summer\" and \"All She Wants to Do Is Dance\") and *The End of the Innocence* (1989). Eight Grammy Awards across solo and Eagles work. Co-founded the Walden Woods Project in 1990 to preserve Henry David Thoreau's eponymous Massachusetts woodland.",
  "dont-panic":
    "American post-hardcore band associated with the late-1990s/early-2000s Christian punk scene. Style draws on post-hardcore and pop-punk. Limited national exposure outside the Tooth & Nail / Solid State Records-adjacent Christian-music underground.",
  "down-to-the-bone":
    "British acid jazz / smooth jazz band formed in London in 1996 by Stuart Wade. Long-running lineup with rotating session musicians. Style fuses smooth jazz, acid jazz, funk, soul, and R&B.\n\nReleased over a dozen studio albums starting with *From Manhattan to Staten* (1996). Best-known releases include *Urban Grooves* (1998), *Cellar Funk* (2002), and *Spread the Word* (2007). Particularly popular on the US smooth-jazz radio circuit through the 2000s.",
  "dr-dre":
    "American rapper, record producer, and entrepreneur born Andre Romelle Young on February 18, 1965, in Compton, California. Among the most influential figures in hip-hop production history. Former member of N.W.A (1986-1991); co-founded Death Row Records (1991) and Aftermath Entertainment (1996).\n\nReleased three studio albums: *The Chronic* (1992), *2001* (1999), and *Compton* (2015). *The Chronic* is widely regarded as foundational to G-funk and one of the most influential hip-hop albums ever. As a producer, has shaped careers including Snoop Dogg, Eminem, 50 Cent, Kendrick Lamar, and others. Co-founded Beats Electronics (sold to Apple in 2014 for $3 billion). Six Grammy Awards. Inducted into the Rock and Roll Hall of Fame with N.W.A in 2016.",
  "drain-sth":
    "Swedish all-female alternative metal band formed in Stockholm in 1993. Lineup: Maria Sjöholm (vocals), Flavia Canel (guitar), Anna Kjellberg (bass), and Martina Axén (drums). The \"STH\" in the name distinguished them from the unrelated American band Drain.\n\nTwo studio albums: *Horror Wrestling* (1996) and *Freaks of Nature* (1999). Best-known release: *Freaks of Nature*, which featured a cover of Black Sabbath's \"Black Sabbath.\" The band dissolved in 2000.",
  "dream-widow":
    "American heavy metal band formed in 2022 as a side project of Dave Grohl (Foo Fighters). The name and concept emerged from the 2022 horror film *Studio 666* (in which Foo Fighters play themselves and encounter a fictional 1990s metal band called Dream Widow).\n\nReleased one studio album: the self-titled debut (2022), credited entirely to Grohl on all instruments and vocals. Style is significantly heavier than Foo Fighters output, drawing on classic doom metal and 1990s alternative metal influences.",
  "driver-eight":
    "American rock band formed in the late 1990s, named after the R.E.M. song of the same name. Limited public information available; appears to be a regional alt-rock act.",
  "drowning-pool":
    "American rock band formed in Dallas in 1996. Multiple vocalists during the band's career: Dave Williams (1996-2002, died 2002), Jason \"Gong\" Jones (2002-2005), Ryan McCombs (2005-2011), and Jasen Moreno (since 2012). Long-running lineup also includes C.J. Pierce (guitar), Stevie Benton (bass), and Mike Luce (drums).\n\nSeven studio albums starting with *Sinner* (2001, multi-platinum, featuring \"Bodies\" — a song that became deeply controversial for its inclusion in interrogation playlists at Guantanamo Bay). Williams died of cardiomyopathy in 2002 at age 30. Subsequent releases include *Desensitized* (2004) and *Resilience* (2013).",
  "eyc":
    "American R&B vocal group formed in Los Angeles in 1992. Lineup: Marc Wood, Trey Parker (not the *South Park* co-creator), Dave Loeffler, and Damon Sharpe. The name was an acronym for \"Express Yourself Clearly.\"\n\nReleased one studio album: *Express Yourself* (1993). Best-known single: \"Feelin' Alright\" (1993). The group was unable to repeat their initial commercial momentum and dissolved by the mid-1990s.",
  "eddie-cochran":
    "American singer, songwriter, and guitarist (1938-1960). Born in Albert Lea, Minnesota. Among the most influential early figures in rockabilly and rock and roll; his three-chord arrangements and use of overdubbing influenced subsequent generations of rock players from the Beatles to the Sex Pistols.\n\nReleased one studio album during his lifetime: *Singin' to My Baby* (1957). Posthumous compilations have collected his prolific singles work. Best-known songs include \"Summertime Blues,\" \"C'mon Everybody,\" \"Twenty Flight Rock,\" and \"Three Steps to Heaven\" (a UK #1 released posthumously). Died in a car crash on April 17, 1960, at age 21 — the same accident severely injured Gene Vincent. Inducted into the Rock and Roll Hall of Fame in 1987.",
  "eddy-grant":
    "Guyanese-British singer-songwriter born March 5, 1948, in Plaisance, British Guiana. First gained prominence as a member of the Equals (1965-1971, featuring his own hit \"Baby, Come Back\") before launching a successful solo career.\n\nReleased over a dozen solo studio albums between *Message Man* (1977) and *Reparation* (2008). Commercial peak: *Killer on the Rampage* (1982, featuring the international hit \"Electric Avenue\") and *Going for Broke* (1984, featuring \"Romancing the Stone\"). Pioneered ringbang — a fusion of Caribbean rhythms — and built the Coach House Studio in Barbados.",
  "edgar-winter":
    "American musician born December 28, 1946, in Beaumont, Texas. Younger brother of guitarist Johnny Winter (both are albinos). Multi-instrumentalist particularly known for his work on keyboards, saxophone, and percussion.\n\nReleased over a dozen studio albums starting with *Entrance* (1970). Commercial peak: *They Only Come Out at Night* (1972, multi-platinum, featuring the instrumental hit \"Frankenstein\" and \"Free Ride\") with the Edgar Winter Group. Subsequent releases include *Shock Treatment* (1974) and *The Edgar Winter Album* (1979).",
  "elastica":
    "English rock band formed in London in 1992 by Justine Frischmann (vocals/guitar, ex-Suede). Other founding members: Donna Matthews (guitar/vocals), Annie Holland (bass), and Justin Welch (drums). Distinguished by their punk and post-punk influences during the Britpop era.\n\nTwo studio albums: *Elastica* (1995, which set a UK chart record for fastest-selling debut album at the time) and *The Menace* (2000). Best-known singles include \"Connection\" and \"Stutter.\" The first album was marred by lawsuits over similarities to songs by Wire and the Stranglers; both were settled. The band dissolved in 2001.",
  "electric-citizen":
    "American rock band formed in Cincinnati in 2009. Lineup: Laura Dolan (vocals), Ross Dolan (guitar, her husband), Nick Vogelpohl (bass), and various drummers. Style draws on 1970s heavy psych, doom, and proto-metal.\n\nFour studio albums: *Sateen* (2014), *Higher Time* (2016), *Helltown* (2018), and *Helltown* (2018 reissue). Released primarily on RidingEasy Records. The band has been a fixture at retro-rock festivals.",
  "elliot-easton":
    "American guitarist born December 18, 1953, in Brooklyn, New York. Best known as the lead guitarist of The Cars (1976-1988, 2010-2019). Known for his concise, melodic, instantly-identifiable lead guitar work — particularly on hits like \"Just What I Needed,\" \"Best Friend's Girl,\" and \"Drive.\"\n\nReleased two solo studio albums: *Change No Change* (1985) and *...And* (2024, the 2024 album released over 40 years later). Also worked as a member of Creedence Clearwater Revisited (a touring offshoot of CCR), the New Cars (a Todd Rundgren-fronted Cars touring lineup), and Tiki Gods (an instrumental surf-rock project). Inducted into the Rock and Roll Hall of Fame with the Cars in 2018.",
  "elliott-smith":
    "American singer-songwriter (1969-2003). Born in Omaha, Nebraska. First gained prominence as a member of Heatmiser (1991-1996), then launched a successful solo career. Distinguished by his hushed vocal style, intricate fingerpicked acoustic arrangements, and lyrically frank treatment of depression and addiction.\n\nReleased six studio albums in his lifetime, between *Roman Candle* (1994) and *Figure 8* (2000). The posthumous *From a Basement on the Hill* (2004) was assembled by collaborators from his unfinished sessions. Critical peak: *Either/Or* (1997) and *XO* (1998). Nominated for an Academy Award for \"Miss Misery\" from the *Good Will Hunting* soundtrack (1997). Died from two stab wounds to the chest in October 2003; the death has been variously ruled a suicide and a possible homicide.",
  "emerson-lake-palmer":
    "English progressive rock supergroup formed in 1970. Trio of Keith Emerson (keyboards, 1944-2016), Greg Lake (vocals/bass/guitar, 1947-2016), and Carl Palmer (drums). Emerson and Palmer previously played in the Nice and Atomic Rooster respectively; Lake came from King Crimson.\n\nTen studio albums starting with *Emerson, Lake & Palmer* (1970). Commercial peak: *Tarkus* (1971), *Pictures at an Exhibition* (1971, adapted from Modest Mussorgsky's classical suite), *Trilogy* (1972), and *Brain Salad Surgery* (1973, featuring the 30-minute \"Karn Evil 9\"). Emerson and Lake both died in 2016 — Emerson by suicide in March, Lake of cancer in December.",
  "eminem":
    "American rapper, songwriter, and record producer born Marshall Bruce Mathers III on October 17, 1972, in St. Joseph, Missouri. Discovered by Dr. Dre in 1997; their collaboration became one of the most commercially successful in hip-hop history.\n\nReleased twelve studio albums between *Infinite* (1996) and *The Death of Slim Shady (Coup de Grâce)* (2024). Commercial peak: *The Slim Shady LP* (1999), *The Marshall Mathers LP* (2000, which sold over 21 million copies worldwide), *The Eminem Show* (2002), and *Encore* (2004). Won the 2003 Academy Award for Best Original Song (\"Lose Yourself\" from *8 Mile*). Among the best-selling music artists in history with over 200 million units sold.",
  "end":
    "Hardcore band formed in the early 2000s, often stylized as \"end.\" with lowercase letters and period. Limited public documentation; appears to be a regional act tied to the Pittsburgh or broader Northeast US hardcore scenes.",
  "erasure":
    "English synth-pop duo formed in London in 1985 by Vince Clarke (synthesizers/songwriter, formerly of Depeche Mode and Yazoo) and Andy Bell (vocals). One of the longest-running and most consistent acts in the synth-pop genre.\n\nReleased over 20 studio albums starting with *Wonderland* (1986). Commercial peak: *The Innocents* (1988, featuring \"A Little Respect\" and \"Chains of Love\"), *Wild!* (1989), and *Chorus* (1991). The 1992 EP *Abba-esque* — covers of four ABBA songs — became their highest-charting UK release. Continues to record and tour into the 2020s.",
  "europe":
    "Swedish rock band formed in Upplands Väsby in 1979. Long-running lineup: Joey Tempest (vocals), John Norum (guitar, 1979-1986, 2003-present), John Levén (bass), Mic Michaeli (keyboards, since 1984), and Ian Haugland (drums, since 1984).\n\nEleven studio albums between *Europe* (1983) and *Walk the Earth* (2017). Commercial peak: *The Final Countdown* (1986, multi-platinum, featuring the iconic title track) and *Out of This World* (1988). The band split in 1992 and reunited in 2003. The title track of *The Final Countdown* has become a sports-stadium and rock-radio standard.",
  "eurythmics":
    "British synth-pop duo formed in 1980 by Annie Lennox (vocals) and Dave Stewart (instruments/songwriter). The duo formed after their previous band, the Tourists, dissolved in 1980. Among the most commercially successful synth-pop acts of the early-to-mid 1980s.\n\nEight studio albums between *In the Garden* (1981) and *Peace* (1999). Commercial peak: *Sweet Dreams (Are Made of This)* (1983, featuring the iconic title track) and *Touch* (1983, featuring \"Here Comes the Rain Again\"). The duo split in 1990; both pursued solo work, with Lennox achieving substantial commercial success as a solo artist. Inducted into the Rock and Roll Hall of Fame in 2022.",
  "eve-6":
    "American rock band formed in La Crescenta, California in 1995. Long-running lineup: Max Collins (vocals/bass), Jon Siebels (guitar, 1995-2007, 2011-present), and Tony Fagenson (drums, 1995-2007, 2011-2020). The band's name references the *X-Files* character \"Eve 6.\"\n\nFour studio albums starting with *Eve 6* (1998). Commercial peak: *Eve 6* (multi-platinum, featuring \"Inside Out\" and \"Leech\") and *Horrorscope* (2000, featuring \"Here's to the Night\"). The band split in 2004 and reunited in 2011. Collins has been an outspoken voice on social media in the 2020s.",
  "everclear":
    "American rock band formed in Portland, Oregon in 1991. Long-running lineup centered on Art Alexakis (vocals/guitar). Other members have rotated frequently; bassist Craig Montoya and drummer Greg Eklund defined the band's classic 1995-2003 era.\n\nTen studio albums starting with *World of Noise* (1993). Commercial peak: *Sparkle and Fade* (1995, multi-platinum, featuring \"Santa Monica\") and *So Much for the Afterglow* (1997, featuring \"I Will Buy You a New Life\" and \"Father of Mine\"). Continues to record and tour with various lineups.",
  "everdown":
    "American hardcore band formed in the mid-1990s. Style draws on metallic hardcore and emo. Limited public information available; appears to be a regional act tied to the late-1990s Christian hardcore scene.",
  "expos":
    "American freestyle/dance-pop trio formed in Miami in 1984. Best-known lineup: Jeanette Jurado, Ann Curless, and Gioia Bruno. Initial vocalists included Sandee Casanas, Laurie Miller, and Alé Lorenzo.\n\nThree studio albums between *Exposure* (1987) and *Exposé* (1992). Commercial peak: *Exposure* (1987), which sold over 3 million copies on the strength of four top-10 singles including \"Come Go with Me,\" \"Point of No Return,\" \"Let Me Be the One,\" and the #1 hit \"Seasons Change.\" The group reformed in 2003 with the classic lineup.",
  "extreme":
    "American rock band formed in Boston in 1985. Long-running lineup: Gary Cherone (vocals), Nuno Bettencourt (guitar), Pat Badger (bass), and various drummers. Cherone briefly fronted Van Halen (1996-1999) during the Extreme hiatus.\n\nSix studio albums starting with *Extreme* (1989). Commercial peak: *Pornograffitti* (1990, featuring \"More Than Words\" and \"Hole Hearted\") and *III Sides to Every Story* (1992). The band split in 1996 and reunited in 2004. Released *Six* (2023), their first studio album in 15 years.",
  "fahrenheit-451":
    "American hardcore band formed in Cleveland in 1995. Long-running lineup centered on vocalist Dan Yemin (later of Lifetime, Kid Dynamite, and Paint It Black). Style draws on metallic hardcore and emotional hardcore.\n\nOne studio album: the self-titled debut (1996). Released on Indecision Records. Yemin's subsequent projects have been more influential; Fahrenheit 451 has been long inactive.",
  "falco":
    "Austrian musician (1957-1998). Born Johann \"Hans\" Hölzel in Vienna. Among the best-known Austrian artists ever to have international commercial success. Distinguished by his fusion of pop, rock, hip-hop, and German-language lyrics.\n\nReleased seven studio albums between *Einzelhaft* (1982) and the posthumous *Verdammt wir leben noch* (1999). Commercial peak: *Falco 3* (1985), which featured \"Rock Me Amadeus\" — the first German-language single to top the Billboard Hot 100 (in 1986) and the first to reach #1 in the UK. Falco died in a car accident in the Dominican Republic in February 1998.",
  "fastbacks":
    "American pop-punk band formed in Seattle in 1979. Long-running lineup: Kim Warnick (vocals/bass, 1979-2001), Lulu Gargiulo (guitar/vocals, 1979-2001), Kurt Bloch (guitar, since 1979), and various drummers — Mike Musburger and Mike Stewart were the most consistent.\n\nNine studio albums between *Every Day Is Saturday* (1985) and *The Question Is No* (1999). The band toured with Pearl Jam in the mid-1990s, gaining a substantial post-grunge audience. Released primarily on Sub Pop, Lookout!, and various smaller indie labels. The band has performed sporadic reunion shows since 2001.",
  "faster-pussycat":
    "American glam metal band formed in Los Angeles in 1986. Long-running lineup centered on Taime Downe (vocals). Other key members included Brent Muscat (guitar, 1986-2001), Greg Steele (guitar, 1986-1992, 2001-2007), Eric Stacy (bass, 1986-1993), and Mark Michals (drums, 1986-1993).\n\nFour studio albums starting with *Faster Pussycat* (1987). Best-known release: *Wake Me When It's Over* (1989, featuring \"House of Pain\"). The band shifted toward industrial rock after their late-1990s reunion. Downe has remained at the helm through frequent lineup changes.",
  "fastway":
    "English-Irish hard rock band formed in London in 1982 by guitarist \"Fast\" Eddie Clarke (formerly of Motörhead) and bassist Pete Way (formerly of UFO). Vocalist Dave King (formerly of Flogging Molly, born 1962) joined in 1983.\n\nFour studio albums in the original era between *Fastway* (1983) and *On Target* (1988). The band has reformed periodically; King left in 1986 to pursue what would become Flogging Molly. Eddie Clarke died in 2018; Pete Way died in 2020.",
  "fifth-harmony":
    "American girl group formed via the second season of *The X Factor (USA)* in 2012. Original lineup: Ally Brooke, Normani Kordei, Dinah Jane, Lauren Jauregui, and Camila Cabello (departed in 2016). Brought together as solo contestants and reassembled by judge Simon Cowell.\n\nThree studio albums: *Reflection* (2015), *7/27* (2016), and *Fifth Harmony* (2017). Best-known singles include \"Worth It\" (with Kid Ink), \"Work from Home\" (with Ty Dolla Sign), and \"Down\" (with Gucci Mane). Cabello's departure in late 2016 led to legal disputes; she has since become a successful solo artist. The remaining members began indefinite hiatus in 2018.",
  "fiji-mariners":
    "American jam band side project of Aquarium Rescue Unit members Bruce Hampton, Jeff Sipe, and Oteil Burbridge. Active briefly in the late 1990s, primarily as a touring entity that explored more electronics-influenced material than ARU.\n\nReleased two studio albums: *Fiji Mariners* (1997) and *Fiji* (1999). The project was put on hold as Burbridge joined the Allman Brothers Band in 1997.",
  "filter":
    "American rock band formed in Cleveland in 1993 by Richard Patrick (vocals, formerly the touring guitarist for Nine Inch Nails) and Brian Liesegang (multi-instrumentalist, 1993-1997). Patrick has been the band's only continuous member since the original duo split.\n\nNine studio albums between *Short Bus* (1995) and *The Algorithm* (2023). Best-known releases include *Short Bus* (featuring \"Hey Man, Nice Shot\") and *Title of Record* (1999, featuring \"Take a Picture\"). Liesegang and Patrick have collaborated occasionally since the 1997 split. The band has been continuously active with rotating supporting musicians.",
  "fine-young-cannibals":
    "English rock band formed in Birmingham in 1984. Lineup: Roland Gift (vocals), Andy Cox (guitar), and David Steele (bass). Cox and Steele were previously the rhythm section of The Beat. Distinguished by Gift's distinctive falsetto and the band's fusion of pop, rock, and R&B.\n\nTwo studio albums: *Fine Young Cannibals* (1985) and *The Raw & the Cooked* (1989). The 1989 follow-up sold over 4 million copies in the US and produced two #1 singles, \"She Drives Me Crazy\" and \"Good Thing.\" The band has been inactive since the early 1990s.",
  "firehouse":
    "American rock band formed in Charlotte, North Carolina in 1984 (originally as White Heat). Lineup: C.J. Snare (vocals, died 2024), Bill Leverty (guitar), Perry Richardson (bass, 1984-2000), and Michael Foster (drums). Brand of melodic hard rock that arrived in the late 1980s just as grunge was about to displace it.\n\nSix studio albums starting with the self-titled 1990 debut. Commercial peak: *FireHouse* (1990, double-platinum, featuring \"Don't Treat Me Bad\" and \"Love of a Lifetime\") and *Hold Your Fire* (1992). The band won the 1992 American Music Award for Best New Heavy Metal Band. Snare died in April 2024.",
  "flashpoint":
    "American hardcore band associated with the late-1990s/early-2000s metallic hardcore scene. Released material on Trustkill or similar genre-focused indie labels. Limited public documentation; appears to be a regional Northeast US act.",
  "flatt-scruggs":
    "American bluegrass duo of Lester Flatt (vocals/guitar, 1914-1979) and Earl Scruggs (banjo, 1924-2012). Active from 1948 to 1969. Foundational to the development of bluegrass alongside Bill Monroe — particularly Scruggs's three-finger banjo picking style.\n\nReleased dozens of albums in their two-decade partnership. Best-known recordings include \"Foggy Mountain Breakdown\" (used in the 1967 film *Bonnie and Clyde*) and \"The Ballad of Jed Clampett\" (the theme song to *The Beverly Hillbillies*, a #1 country hit in 1962). The duo split in 1969 over creative differences. Both members were inducted into the Country Music Hall of Fame (1985) and the International Bluegrass Music Hall of Fame.",
  "flotsam-and-jetsam":
    "American thrash metal band formed in Phoenix in 1981. Long-running lineup centered on Eric A.K. Knutson (vocals) and Michael Gilbert (guitar). The band's most famous former member is bassist Jason Newsted, who joined Metallica in 1986 after Cliff Burton's death.\n\nFourteen studio albums between *Doomsday for the Deceiver* (1986) and *I Am the Weapon* (2024). Best-known releases include *Doomsday for the Deceiver*, *No Place for Disgrace* (1988), and *When the Storm Comes Down* (1990). The band has been continuously active since 1981 despite many lineup changes.",
  "fluf":
    "American power-pop band formed in San Diego in 1991 by O (Otis Barthoulameu, vocals/guitar). Other long-running members include Mike Andrew (bass) and various drummers.\n\nSix studio albums between *Waikiki* (1992) and *Some Were Looking for Light Bulbs* (2001). Released primarily on Headhunter, Cargo, and Big Wheel Recreation. The band has been on extended hiatus since the early 2000s.",
  "fluffy":
    "English punk rock band formed in London in 1994. Lineup: Amanda Rootes (vocals/guitar), Bridget Jones (guitar, no relation to the literary character), Helen Storer (bass), and Angie Adams (drums). All-female lineup associated with the late-Britpop alternative scene.\n\nReleased one studio album: *Black Eye* (1996). Best-known single: \"Husband\" (1996). The band toured with the Foo Fighters and the Sex Pistols' reunion tour before dissolving in 1997.",
  "fourplay":
    "American smooth jazz supergroup formed in 1990. Lineup: Bob James (keyboards), Lee Ritenour (guitar, 1990-1997), Larry Carlton (guitar, 1997-2009), Chuck Loeb (guitar, 2010-2017, died 2017), Nathan East (bass), and Harvey Mason (drums). One of the most commercially successful smooth-jazz acts of the 1990s and 2000s.\n\nReleased twelve studio albums between *Fourplay* (1991) and *Silver* (2015). Best-known releases include *Fourplay* (1991), *Between the Sheets* (1993), and *Elixir* (1995). The band has been on hiatus since Loeb's 2017 death.",
  "frampton-brothers":
    "American duo of brothers Owen Frampton (guitar/vocals) and Ben Frampton (bass/vocals). The brothers are the sons of Peter Frampton (the British rock guitarist).\n\nReleased one EP and various singles in the late 2010s and early 2020s. Performs primarily in the indie rock and acoustic singer-songwriter space; Owen has also worked as a touring guitarist with his father.",
  "frank":
    "Limited public information available; appears to be an obscure independent project tied to a specific local or regional music scene.",
  "frank-zappa":
    "American musician, composer, and bandleader (1940-1993). Born in Baltimore. Among the most prolific and stylistically diverse American musicians of the 20th century. His output spans rock, jazz fusion, orchestral composition, doo-wop parody, and electronic music. Highly outspoken on political and free-speech issues throughout his career.\n\nReleased over 60 studio albums during his lifetime starting with the Mothers of Invention's *Freak Out!* (1966). The Zappa Family Trust has continued posthumous releases, bringing the total to over 100. Critical peak: *Hot Rats* (1969), *Apostrophe (')* (1974), *One Size Fits All* (1975), *Joe's Garage* Acts I-III (1979), and the orchestral *London Symphony Orchestra Vol. 1* (1983). Died of prostate cancer in December 1993. Inducted into the Rock and Roll Hall of Fame in 1995.",
  "frankie-goes-to-hollywood":
    "English synth-pop band formed in Liverpool in 1980. Lineup: Holly Johnson (vocals), Paul Rutherford (vocals/dancer), Brian Nash (guitar), Mark O'Toole (bass), and Peter Gill (drums). Among the most commercially successful UK acts of the mid-1980s.\n\nTwo studio albums: *Welcome to the Pleasuredome* (1984) and *Liverpool* (1986). The 1984 debut produced three consecutive UK #1 singles — \"Relax,\" \"Two Tribes,\" and the title track — a feat only previously achieved by Gerry and the Pacemakers in 1963. The band split in 1987 after legal disputes with producer Trevor Horn.",
  "frankie-valli":
    "American singer born Francesco Stephen Castelluccio on May 3, 1934, in Newark, New Jersey. Best known as the lead vocalist of the Four Seasons (1960-present, intermittent). Pursued a parallel solo career starting in 1967.\n\nReleased over a dozen solo studio albums. Commercial peak: \"Can't Take My Eyes Off You\" (1967), \"My Eyes Adored You\" (1974), \"Swearin' to God\" (1975), and \"Grease\" (1978, the theme song to the film). Inducted into the Rock and Roll Hall of Fame with the Four Seasons in 1990. The 2005 Broadway musical *Jersey Boys* chronicled the Four Seasons' story and became a long-running theatrical hit.",
  "franz-ferdinand":
    "Scottish rock band formed in Glasgow in 2002. Lineup: Alex Kapranos (vocals/guitar), Bob Hardy (bass), Nick McCarthy (guitar/keyboards, 2002-2016), Paul Thomson (drums, 2002-2021), and Julian Corrie (keyboards, since 2017). Distinguished by their angular, danceable post-punk-revival sound during the early-2000s indie rock wave.\n\nSix studio albums starting with *Franz Ferdinand* (2004, featuring \"Take Me Out\" and \"This Fire\"). The debut won the 2004 Mercury Prize. Subsequent releases include *You Could Have It So Much Better* (2005), *Tonight: Franz Ferdinand* (2009), and *Always Ascending* (2018).",
  "free-kitten":
    "American indie rock supergroup formed in 1992. Original lineup: Kim Gordon (bass/vocals, of Sonic Youth), Julie Cafritz (guitar, of Pussy Galore), and Mark Ibold (bass, of Pavement). Yoshimi P-We (drums, of Boredoms) joined in 1993.\n\nFour studio albums between *Call Now* (1992) and *Inherit* (2008). Released primarily on Wiiija and Ecstatic Peace! (Thurston Moore's label). The band has been on extended hiatus since the late 2000s.",
  "frenzal-rhomb":
    "Australian punk rock band formed in Sydney in 1992. Long-running lineup: Jay Whalley (vocals/guitar), Lex Feltham (bass), and Gordy Forman (drums, since 2002). Distinguished by political satire and Australian-specific cultural commentary.\n\nReleased ten studio albums starting with *Once a Jolly Swagman, Always a Jolly Swagman* (1996). Best-known releases include *Meet the Family* (1997), *A Man's Not a Camel* (1999), and *Smoko at the Pet Food Factory* (2011). Released primarily on Shock Records and Fat Wreck Chords.",
  "front-242":
    "Belgian electronic body music (EBM) band formed in Aarschot in 1981. Long-running lineup: Daniel Bressanutti (samples/programming), Patrick Codenys (keyboards), Jean-Luc De Meyer (vocals), and Richard 23 (vocals/percussion). Pioneers of EBM; their term \"electronic body music\" was first used by Kraftwerk but defined by Front 242.\n\nNine studio albums between *Geography* (1982) and *Pulse* (2003). Critical peak: *Front by Front* (1988, featuring \"Headhunter\") and *Tyranny (For You)* (1991). The band has been performing live concerts intermittently into the 2020s.",
};

async function main() {
  const dryRun = process.argv.includes("--dry-run");
  const force = process.argv.includes("--force");
  const { containers } = await import("../lib/cosmos");
  const { getStoredArtist } = await import("../lib/artists");

  let written = 0;
  let skipped = 0;
  let missing = 0;

  for (const [slug, description] of Object.entries(DESCRIPTIONS)) {
    const existing = await getStoredArtist(slug);
    if (!existing) {
      console.log(`✗ ${slug}: no stored doc found`);
      missing += 1;
      continue;
    }
    if (existing.description && !force) {
      console.log(`↷ ${slug}: already has description — skipping`);
      skipped += 1;
      continue;
    }
    if (dryRun) {
      console.log(`◌ ${slug}: would write ${description.length} chars`);
      written += 1;
      continue;
    }
    const updated = {
      ...existing,
      description,
      updatedAt: new Date().toISOString(),
    };
    await containers.artists.item(slug, slug).replace(updated);
    console.log(`✓ ${slug}: ${description.length} chars`);
    written += 1;
  }

  console.log(`\nDone. written=${written} skipped=${skipped} missing=${missing}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
