import { config as loadEnv } from "dotenv";
loadEnv({ path: ".env.local" });

const DESCRIPTIONS: Record<string, string> = {
  "rdgldgrn":
    "American rock band formed in Sterling, Virginia in 2008 (officially stylized RDGLDGRN, pronounced \"red gold green,\" after the colors associated with Rastafarianism and African pride). Trio: Marcus Parham (vocals/guitar), Pierre Desrosiers (bass), and Andrei Busuioceanu (drums). Distinguished by their fusion of go-go, indie rock, and hip-hop.\n\nReleased *Red Gold Green* (2013, produced by Dave Grohl, who also played drums on the record) and *Red Gold Green 2* (2017). The band has been intermittently active in the Washington, D.C. independent scene.",
  "rebuke":
    "Generic artist credit used by multiple acts; the Rebuke (3) Discogs disambiguation refers to the Swedish techno producer Rebuke (born Phil Anderson). Anderson is associated with Drumcode Records and the broader techno scene anchored around Adam Beyer.\n\nReleased a series of singles and EPs in the late 2010s and early 2020s including the widely-played \"Along Came Polly.\" Primarily a singles and DJ-set artist rather than an album act.",
  "red-hot-chili-peppers":
    "American rock band formed in Los Angeles in 1983. Long-running classic lineup: Anthony Kiedis (vocals), Flea (bass), Chad Smith (drums, joined 1988), and John Frusciante (guitar, intermittent membership 1988-1992, 1998-2009, 2019-present). Original guitarist Hillel Slovak died in 1988 of a heroin overdose. Distinguished by their fusion of funk, punk, and arena rock and by Flea's slap-bass-driven groove.\n\nReleased 13 studio albums between *The Red Hot Chili Peppers* (1984) and *Return of the Dream Canteen* (2022). Commercial peak: *Blood Sugar Sex Magik* (1991, featuring \"Under the Bridge\" and \"Give It Away\"), *Californication* (1999), and *By the Way* (2002). Six Grammy Awards. Inducted into the Rock and Roll Hall of Fame in 2012.",
  "redman":
    "American rapper born Reginald Noble on April 17, 1970, in Newark, New Jersey. Member of the Def Squad with EPMD and Keith Murray, and of Method Man & Redman with Method Man. Distinguished by his comic delivery, frequent marijuana-themed lyrics, and his association with the De La Soul / Native Tongues / Def Jam continuum.\n\nReleased nine studio albums starting with *Whut? Thee Album* (1992). Critical peak: *Dare Iz a Darkside* (1994) and *Muddy Waters* (1996). Co-recorded *Blackout!* (1999) and *Blackout! 2* (2009) with Method Man. Co-starred in the films *How High* (2001) and *How High 2* (2019).",
  "republica":
    "British electronic rock band formed in London in 1994. Lineup historically centered on Saffron (vocals) and Tim Dorney (keyboards, formerly of Flowered Up). Distinguished by Saffron's confrontational vocal style and the band's hybrid of dance music with rock guitars.\n\nReleased two studio albums: *Republica* (1996, featuring \"Ready to Go\") and *Speed Ballads* (1998). The band has been intermittently active in the 2000s and 2010s.",
  "rev-theory":
    "American rock band formed in Boston in 2002 (originally as Revelation Theory). Long-running lineup centered on Rich Luzzi (vocals). Distinguished by their post-grunge / alternative metal style and the wrestling-entrance-music staple \"Voices\" (2008), used by WWE wrestler Randy Orton.\n\nReleased five studio albums between *Truth Is Currency* (2005) and *Take 'Em Out* (2016). Commercial peak: *Light It Up* (2008). Continues to perform on the active-rock-radio circuit.",
  "rev-horton-heat":
    "American psychobilly band formed in Dallas, Texas in 1985 (officially the Reverend Horton Heat). Long-running lineup centered on Jim Heath (vocals/guitar, the \"Reverend Horton Heat\") and Jimbo Wallace (upright bass, since 1989). Distinguished by Heath's virtuoso rockabilly guitar playing and high-octane live shows.\n\nReleased 12 studio albums between *Smoke 'Em If You Got 'Em* (1991) and *Whole New Life* (2018). Commercial peak: *Liquor in the Front* (1994) and *It's Martini Time* (1996). One of the most consistent live acts in modern Americana/roots music.",
  "rick-springfield":
    "Australian-American singer-songwriter, guitarist, and actor born Richard Lewis Springthorpe on August 23, 1949, in Sydney, Australia. Distinguished by his dual careers as a rock musician and as a soap-opera actor (*General Hospital*, 1981-1983, 2005-present in recurring roles).\n\nReleased over 20 studio albums starting with *Beginnings* (1972). Commercial peak: *Working Class Dog* (1981, featuring the #1 \"Jessie's Girl\") and *Success Hasn't Spoiled Me Yet* (1982). Won the 1982 Grammy for Best Male Rock Vocal Performance for \"Jessie's Girl.\" Continues to tour and record.",
  "ricky-skaggs-and-kentucky-thunder":
    "American bluegrass band led by Ricky Skaggs (b. July 18, 1954, Cordell, Kentucky), the long-running country/bluegrass star who had been a member of Ralph Stanley's Clinch Mountain Boys and Emmylou Harris's Hot Band before launching his country solo career in the 1980s. Skaggs returned to bluegrass full-time in 1997.\n\nKentucky Thunder has backed Skaggs on his bluegrass recordings since 1997. Won the Grammy for Best Bluegrass Album multiple times including *Bluegrass Rules!* (1997), *Soldier of the Cross* (1999), *History of the Future* (2001), and *Live at the Charleston Music Hall* (2003). Inducted into the Country Music Hall of Fame in 2018.",
  "rob-zombie":
    "American singer, songwriter, and filmmaker born Robert Bartleh Cummings on January 12, 1965, in Haverhill, Massachusetts. Founding lead vocalist for White Zombie (1985-1998) before launching his solo career. Distinguished by horror-movie aesthetics and his parallel career as a horror-film writer/director (*House of 1000 Corpses*, 2003; *The Devil's Rejects*, 2005; *Halloween*, 2007).\n\nReleased eight solo studio albums between *Hellbilly Deluxe* (1998, featuring \"Dragula\" and \"Living Dead Girl\") and *The Lunar Injection Kool Aid Eclipse Conspiracy* (2021). Older brother of Powerman 5000's Spider One.",
  "robert-bradleys-blackwater-surprise":
    "American blues/rock band formed in Detroit in 1995. Led by blind blues singer-songwriter Robert Bradley (1951-2021) and originally backed by members of the band Hank Hill (Andrew Nehra and Chris Bukowski on guitars, and Jeff Fowlkes on drums). Distinguished by Bradley's gospel-rooted vocals and the band's roots-rock backing.\n\nReleased three studio albums between *Robert Bradley's Blackwater Surprise* (1996) and *New Ground* (2003). Bradley died in 2021 of complications from COVID-19.",
  "robert-cray":
    "American blues guitarist and singer-songwriter born August 1, 1953, in Columbus, Georgia; raised in multiple US Army base locations. Distinguished by his smooth contemporary-blues style fusing R&B, soul, and traditional Chicago blues.\n\nReleased over 20 studio albums starting with *Who's Been Talkin'* (1980). Commercial breakthrough: *Strong Persuader* (1986, featuring \"Smoking Gun\"). Five Grammy Awards across his catalog. Inducted into the Blues Hall of Fame in 2011. Continues to tour with the Robert Cray Band.",
  "robert-plant":
    "English singer-songwriter born August 20, 1948, in West Bromwich, Staffordshire. Lead vocalist of Led Zeppelin (1968-1980). Distinguished by his banshee-wail vocals on the Zeppelin catalog and his subsequent stylistic restlessness across folk, blues, world music, and electronica in his solo work.\n\nReleased 11 solo studio albums starting with *Pictures at Eleven* (1982). Subsequent peaks: *Now and Zen* (1988), *Mighty ReArranger* (2005), and the collaborations *Raising Sand* (2007, with Alison Krauss; six Grammy Awards including Album of the Year) and *Raise the Roof* (2021, with Krauss). Inducted into the Rock and Roll Hall of Fame as a member of Led Zeppelin in 1995.",
  "rockets":
    "American rock band formed in Detroit in 1972. Lineup historically centered on Jim McCarty (guitar, formerly of Mitch Ryder's band) and Johnny \"Bee\" Badanjek (drums). Distinguished by their long association with the Detroit hard-rock scene and their mid-1970s arena-rock sound.\n\nReleased seven studio albums between *Love Transfusion* (1977) and *Rocket Roll* (1982). Best-known recording: \"Oh Well\" (1979, a Fleetwood Mac cover). Frequently confused with the unrelated Italian disco band the Rockets active in the same period.",
  "rodney-crowell":
    "American country singer-songwriter born August 7, 1950, in Houston, Texas. Member of Emmylou Harris's Hot Band (1975-1977). Distinguished by his literate songwriting and his long-running role as one of the most respected songwriters in country music.\n\nReleased 15 studio albums between *Ain't Living Long Like This* (1978) and *The Chicago Sessions* (2023). Commercial peak: *Diamonds & Dirt* (1988), which produced five consecutive #1 country singles. Co-produced his ex-wife Rosanne Cash's commercial peak. Two Grammy Awards.",
  "rodney-dangerfield":
    "American stand-up comedian and actor born Jacob Cohen on November 22, 1921, in Babylon, New York; died October 5, 2004. Defined by his \"I get no respect\" persona and his characteristic neck-tugging delivery. Founder of Dangerfield's comedy club in New York (1969-2020), which gave early breaks to Tim Allen, Jerry Seinfeld, Adam Sandler, Roseanne Barr, and many others.\n\nReleased numerous comedy albums starting with *The Loser* (1966). Won the 1981 Grammy for Best Comedy Recording for *No Respect* (1980). Co-starred in the films *Caddyshack* (1980), *Easy Money* (1983), *Back to School* (1986), and *Natural Born Killers* (1994). Died at age 82 of surgery complications.",
  "roger-daltrey":
    "English singer-songwriter born March 1, 1944, in Hammersmith, London. Founding lead vocalist of the Who (1964-present). Distinguished by his powerful voice and stage presence, including the iconic microphone-cord twirling.\n\nReleased nine solo studio albums between *Daltrey* (1973) and *As Long as I Have You* (2018). The solo work has emphasized roots-rock and singer-songwriter material distinct from the Who's catalog. Has also pursued an acting career including the title role in Ken Russell's *Tommy* (1975). Inducted into the Rock and Roll Hall of Fame as a member of the Who in 1990.",
  "ronnie-montrose":
    "American guitarist born November 29, 1947, in San Francisco; died March 3, 2012. Founding member of Montrose (1973-1976), the band that launched Sammy Hagar's career. Subsequently founded Gamma (1979-1983) and recorded extensively as a session and solo guitarist.\n\nReleased over a dozen solo studio albums between *Open Fire* (1978) and *10x10* (2017, completed posthumously). Worked as a session guitarist with Edgar Winter, the Beau Brummels, and Van Morrison among many others. Died at age 64 by suicide following a long battle with prostate cancer and depression.",
  "rooney":
    "American rock band formed in Los Angeles in 1999. Long-running lineup centered on Robert Schwartzman (vocals/guitar, brother of actor Jason Schwartzman, son of Talia Shire, nephew of Francis Ford Coppola). Distinguished by their power-pop-meets-classic-rock sound drawing on Big Star, the Cars, and Cheap Trick.\n\nReleased five studio albums between *Rooney* (2003) and *Washed Away* (2016). Toured with the Strokes during their early-2000s commercial peak. Schwartzman has subsequently pursued film directing including *Dreamland* (2016).",
  "rosco-martinez":
    "Generic stage name with limited public documentation. Multiple performers have credited material as Rosco Martinez across folk, Latin, and rock scenes. The most likely reference is the Texas-based Latin/Tejano performer of the early 2000s.\n\nWithout further context the specific Rosco Martinez referenced in a typical setlist or record credit cannot be conclusively identified.",
  "rosie-flores":
    "American singer-songwriter and guitarist born September 10, 1950, in San Antonio, Texas. Distinguished by her honky-tonk-meets-rockabilly style and her long-running role as a champion of female rockabilly history (her *Rockabilly Filly* project with Wanda Jackson and Janis Martin reactivated their careers in the 1990s).\n\nReleased over 15 studio albums between *Rosie* (1980, with the Screamers) and *Working Girl's Guitar* (2012). Member of the Honky Tonk Quartet alongside Dave Alvin, Lucinda Williams, and others. Continues to tour and record.",
  "royal-thunder":
    "American hard rock band formed in Atlanta in 2004. Long-running lineup centered on Mlny Parsonz (vocals/bass). Distinguished by their fusion of doom metal, classic rock, and Southern rock and Parsonz's distinctive bluesy vocals.\n\nFour studio albums between *Royal Thunder* (2010, EP) and *Rebuilding the Mountain* (2024). Critical peak: *CVI* (2012, Relapse Records) and *Crooked Doors* (2015).",
  "run-dmc":
    "Same artist as Run-D.M.C. — credit variation. American hip-hop group formed in Hollis, Queens in 1981. Lineup: Joseph \"Run\" Simmons, Darryl \"D.M.C.\" McDaniels, and Jason \"Jam Master Jay\" Mizell (1965-2002). Among the most influential acts in hip-hop history; bridged the early-1980s underground hip-hop scene with the mainstream commercial breakthrough of the genre.\n\nReleased seven studio albums between *Run-D.M.C.* (1984) and *Crown Royal* (2001). Commercial peak: *Raising Hell* (1986, featuring \"Walk This Way\" with Aerosmith, the first hip-hop single to reach the top five of the Billboard Hot 100). Jam Master Jay was murdered in his Queens recording studio in 2002. Inducted into the Rock and Roll Hall of Fame in 2009.",
  "rundmc":
    "Same artist as Run-D.M.C. — credit variation. American hip-hop group formed in Hollis, Queens in 1981. Lineup: Joseph \"Run\" Simmons, Darryl \"D.M.C.\" McDaniels, and Jason \"Jam Master Jay\" Mizell (1965-2002). Among the most influential acts in hip-hop history; bridged the early-1980s underground hip-hop scene with the mainstream commercial breakthrough of the genre.\n\nReleased seven studio albums between *Run-D.M.C.* (1984) and *Crown Royal* (2001). Commercial peak: *Raising Hell* (1986, featuring \"Walk This Way\" with Aerosmith). Inducted into the Rock and Roll Hall of Fame in 2009.",
  "rx-bandits":
    "American rock band formed in Seal Beach, California in 1995. Long-running lineup centered on Matt Embree (vocals/guitar). Began as a ska-punk band and progressively shifted toward progressive rock and experimental rock across their catalog.\n\nReleased seven studio albums between *Those Damn Bandits* (1997) and *Gemini, Her Majesty* (2022). Critical peak: *...And the Battle Begun* (2006) and *Mandala* (2009). Released primarily on Drive-Thru Records and Mash Down Babylon.",
  "sod":
    "American crossover thrash band formed in New York City in 1985 (officially S.O.D., for Stormtroopers of Death). Lineup: Billy Milano (vocals), Scott Ian (guitar, Anthrax), Dan Lilker (bass, Anthrax/Nuclear Assault), and Charlie Benante (drums, Anthrax). The band was assembled as a side project during downtime in Anthrax's *Spreading the Disease* sessions.\n\nReleased *Speak English or Die* (1985), widely credited as foundational to the crossover thrash genre bridging hardcore punk and thrash metal. Reunited intermittently for *Bigger Than the Devil* (1999) and live appearances. Milano subsequently led the related band M.O.D.",
  "sabaton":
    "Swedish power metal band formed in Falun in 1999. Long-running lineup centered on Joakim Brodén (vocals, keyboards). Distinguished by their lyrics focused almost exclusively on historical military conflicts and figures.\n\nReleased 11 studio albums between *Primo Victoria* (2005) and *The War to End All Wars* (2022). Commercial peak: *The Art of War* (2008, about Sun Tzu's text), *Heroes* (2014), *The Last Stand* (2016), and *The Great War* (2019). Operates the Sabaton History Channel on YouTube with historian Indy Neidell.",
  "saga":
    "Canadian progressive rock band formed in Oakville, Ontario in 1977. Long-running lineup centered on Michael Sadler (vocals) and Jim Crichton (bass). Distinguished by their melodic, keyboard-driven progressive rock with strong pop sensibilities.\n\nReleased over 20 studio albums between *Saga* (1978) and *Symmetry* (2021). Commercial peak: *Worlds Apart* (1981, featuring \"On the Loose\" and \"Wind Him Up\"). Particularly popular in Germany and Canada.",
  "saint-asonia":
    "Canadian-American rock band formed in 2015. Lineup includes Adam Gontier (vocals, formerly of Three Days Grace), Mike Mushok (guitar, Staind), Cale Gontier (bass, cousin of Adam), and various drummers. Distinguished by combining members of two major early-2000s post-grunge bands.\n\nReleased two studio albums and an EP between *Saint Asonia* (2015) and *Introvert / Extrovert* (2024). The band is essentially a touring/recording vehicle for Gontier post-Three Days Grace.",
  "saliva":
    "American rock band formed in Memphis, Tennessee in 1996. Long-running lineup historically centered on Josey Scott (vocals, until 2011, returned 2024) and Wayne Swinny (guitar, 1971-2023). Distinguished by their hybrid hip-hop-influenced post-grunge / nu-metal style.\n\nReleased 10 studio albums between *Saliva* (1997) and *Revelation* (2023). Commercial peak: *Every Six Seconds* (2001, featuring \"Click Click Boom\" and \"Your Disease\") and *Back into Your System* (2002, featuring the Nickelback collaboration \"Always\"). Wayne Swinny died of a brain hemorrhage in 2023.",
  "saltnpepa":
    "American hip-hop group formed in New York City in 1985 (officially Salt-N-Pepa). Lineup: Cheryl \"Salt\" James, Sandra \"Pepa\" Denton, and DJ Spinderella (born Deidra Roper, joined 1987). Among the first commercially successful female hip-hop acts and pioneers of female hip-hop's pop crossover.\n\nReleased five studio albums between *Hot, Cool & Vicious* (1986) and *Brand New* (1997). Best-known recordings include \"Push It\" (1986), \"Let's Talk About Sex\" (1991), \"Shoop\" (1993), and \"Whatta Man\" (1993, with En Vogue). Won the 1995 Grammy for Best Rap Performance by a Duo or Group for \"None of Your Business.\"",
  "sara-evans":
    "American country singer-songwriter born February 5, 1971, in Boonville, Missouri. Distinguished by her clear, traditional country vocals and her continued advocacy for traditional country aesthetics during the 2000s pop-country dominance.\n\nReleased nine studio albums between *Three Chords and the Truth* (1997) and *Copy That* (2020). Commercial peak: *Born to Fly* (2000, multi-platinum, featuring the title track) and *Restless* (2003). Three #1 country singles including \"Suds in the Bucket\" (2004) and \"A Real Fine Place to Start\" (2005).",
  "save-ferris":
    "American ska-punk band formed in Orange County, California in 1996. Long-running lineup centered on Monique Powell (vocals). The band's name references the *Ferris Bueller's Day Off* (1986) refrain.\n\nReleased *It Means Everything* (1997) and *Modified* (1999) during their original run, plus the EP *Checkered Past* (2017) following a Powell-led reunion. Best-known recording: the band's cover of Dexys Midnight Runners' \"Come On Eileen\" (1997).",
  "sawyer-brown":
    "American country band formed in 1981. Long-running lineup centered on Mark Miller (vocals) and Gregg \"Hobie\" Hubbard (keyboards). Won the 1984 *Star Search* national talent competition, launching the band's recording contract with Capitol Records.\n\nReleased over 20 studio albums between *Sawyer Brown* (1985) and *Travelin' Band* (2022). Commercial peak: *The Boys Are Back* (1989), *Buick* (1991), and *Cafe on the Corner* (1992). Notable for their relentless touring schedule (200-plus shows per year for over three decades).",
  "scandal":
    "American rock band formed in New York City in 1981. Long-running lineup centered on Patty Smyth (vocals). Distinguished by their pop-rock sound and Smyth's gritty vocals.\n\nReleased one studio album and one EP during their original run: *Scandal* (1982, EP, featuring \"Goodbye to You\") and *Warrior* (1984, featuring \"The Warrior\" — a #7 Billboard Hot 100 hit). Patty Smyth pursued a solo career thereafter. Scandal has reunited occasionally for tours.",
  "scott-weiland":
    "American singer-songwriter born Scott Richard Kline on October 27, 1967, in San Jose, California; died December 3, 2015. Lead vocalist for Stone Temple Pilots (1989-2013) and Velvet Revolver (2003-2008). Distinguished by his charismatic vocals and well-documented public struggles with addiction.\n\nReleased two solo studio albums: *12 Bar Blues* (1998) and *\"Happy\" in Galoshes* (2008), plus the Christmas album *The Most Wonderful Time of the Year* (2011). Died at age 48 of an accidental drug overdose on his tour bus.",
  "scrawl":
    "American indie rock band formed in Columbus, Ohio in 1985. Long-running lineup: Marcy Mays (vocals/guitar), Sue Harshe (bass/vocals), and various drummers. Distinguished by their all-female lineup and direct, melodic indie-rock songwriting in the vein of contemporary acts like the Breeders and the Throwing Muses.\n\nReleased six studio albums between *Plus, Also, Too* (1986) and *Nature Film* (1998). Released primarily on Rough Trade and Simple Machines. The band has been on indefinite hiatus since the early 2000s.",
  "screeching-weasel":
    "American pop-punk band formed in Prospect Heights, Illinois in 1986. Long-running lineup centered on Ben Weasel (vocals, born Ben Foster). Distinguished by their Ramones-influenced pop-punk songwriting and Weasel's polarizing public persona.\n\nReleased over a dozen studio albums between *Screeching Weasel* (1987) and *Some Freaks of Atavism* (2022). Critical peak: *My Brain Hurts* (1991), *Anthem for a New Tomorrow* (1993), and *How to Make Enemies and Irritate People* (1994). Weasel's public outbursts have repeatedly led to lineup turmoil and reunion-tour cancellations.",
  "scritti-politti":
    "British band formed in Leeds in 1977. Long-running lineup centered on Green Gartside (vocals/guitar/songwriter). Style shifted from post-punk (their early Rough Trade era) to glossy synth-pop (their commercial-peak Virgin Records era of the mid-1980s).\n\nReleased five studio albums between *Songs to Remember* (1982) and *White Bread Black Beer* (2006). Commercial peak: *Cupid & Psyche 85* (1985, featuring \"Wood Beez\" and \"The Word Girl\") and *Provision* (1988). Gartside collaborated with Miles Davis on \"Oh Patti (Don't Feel Sorry for Loverboy)\" (1988), Davis's last guest appearance.",
  "seaweed":
    "American post-hardcore band formed in Tacoma, Washington in 1989. Long-running lineup centered on Aaron Stauffer (vocals). Distinguished by their melodic-hardcore approach drawing on Hüsker Dü and Dinosaur Jr.\n\nReleased six studio albums between *Despised* (1991) and *Actions and Indications* (1995). Released on Sub Pop and (briefly) Hollywood Records. The band has been intermittently active since the late 1990s.",
  "sebastian-bach":
    "Canadian singer-songwriter born Sebastian Philip Bierk on April 3, 1968, in Freeport, Bahamas; raised in Peterborough, Ontario. Founding lead vocalist for Skid Row (1986-1996). Distinguished by his powerful high-range vocals during the late-1980s/early-1990s commercial peak of glam metal.\n\nReleased five solo studio albums between *Bring 'Em Bach Alive!* (1999) and *Child Within the Man* (2024). Notable solo album: *Angel Down* (2007, featuring Axl Rose guest vocals). Has pursued an acting career including stage runs in *Jekyll & Hyde* (2000-2001) and *The Rocky Horror Show* (2001-2002) on Broadway.",
  "semisonic":
    "American rock band formed in Minneapolis in 1995. Lineup: Dan Wilson (vocals/guitar), John Munson (bass), and Jacob Slichter (drums). Distinguished by Wilson's literate songwriting; he has subsequently become a major Nashville/LA songwriter for hire (co-writing Adele's \"Someone Like You,\" the Dixie Chicks' \"Not Ready to Make Nice,\" and others).\n\nReleased four studio albums between *Great Divide* (1996) and *Little Bit of Sun* (2023). Commercial peak: *Feeling Strangely Fine* (1998, featuring the ubiquitous \"Closing Time\"). The band reunited in 2017 after a long hiatus.",
  "sense-field":
    "American indie rock band formed in Los Angeles in 1990. Long-running lineup centered on Jon Bunch (vocals, 1970-2016). Distinguished by their melodic, emotionally direct post-hardcore in the vein of Sunny Day Real Estate and Mineral.\n\nReleased five studio albums between *Killed for Less* (1994) and *Living Outside* (2003). Best-known recording: \"Save Yourself\" (2001), featured on the *Smallville* (2002) season-one DVD release. Bunch died in 2016 in his sleep at age 45.",
  "set-it-off":
    "American rock band formed in Tampa, Florida in 2008. Lineup: Cody Carson (vocals), Zach DeWall (guitar/bass), and Maxx Danziger (drums). Distinguished by their pop-punk-meets-symphonic-rock sound and Carson's stage presence as a frontman who studied music theory at the University of South Florida.\n\nReleased five studio albums between *Cinematics* (2012) and *Skeleton* (2023). Best-known single: \"Wolf in Sheep's Clothing\" (2014).",
  "shadows-fall":
    "American metalcore band formed in Springfield, Massachusetts in 1996. Long-running lineup centered on Brian Fair (vocals, joined 1999). Distinguished by their fusion of melodic metalcore with thrash metal and their long-running role as one of the bands in the early-2000s \"New Wave of American Heavy Metal.\"\n\nReleased seven studio albums between *Somber Eyes to the Sky* (2000) and *Fire from the Sky* (2012). Critical peak: *The Art of Balance* (2002) and *The War Within* (2004). On hiatus since 2014.",
  "shakin-pyramids":
    "Scottish rockabilly band formed in Glasgow in 1980. Lineup: Davie Duncan (vocals), Nick Clark (guitar), and Jim Paris (upright bass). Distinguished by their acoustic-led rockabilly style during the early-1980s UK rockabilly revival.\n\nReleased two studio albums during their original run: *Skin 'Em Up* (1981) and *Celts and Cobras* (1982). The band dissolved in 1983 but reunited intermittently in subsequent decades.",
  "shania-twain":
    "Canadian singer-songwriter born Eilleen Regina Edwards on August 28, 1965, in Windsor, Ontario; raised in Timmins. Adopted the stage name \"Shania\" (an Ojibwe word) in 1991. Distinguished by her crossover country-pop sound (largely shaped by producer/then-husband Robert John \"Mutt\" Lange) and her role in expanding country music's commercial reach in the mid-to-late 1990s.\n\nReleased six studio albums between *Shania Twain* (1993) and *Queen of Me* (2023). Commercial peak: *The Woman in Me* (1995), *Come On Over* (1997, the best-selling album by a female artist in any genre at over 40 million copies worldwide), and *Up!* (2002). Five Grammy Awards. Suffered Lyme disease-related dysphonia in 2003-2004 that required vocal rehabilitation and surgery.",
  "sheila-e":
    "American singer, songwriter, drummer, and percussionist born Sheila Cecilia Escovedo on December 12, 1957, in Oakland, California. Daughter of percussionist Pete Escovedo. Distinguished by her virtuoso percussion work and her long-running collaboration with Prince (1984-1989, 2011-2016).\n\nReleased seven studio albums between *The Glamorous Life* (1984, featuring the title-track hit) and *Iconic* (2013). Commercial peak: *The Glamorous Life* and *Romance 1600* (1985, featuring \"A Love Bizarre\" with Prince). Has worked extensively as a session percussionist for artists ranging from Lionel Richie to Beyoncé.",
  "silverstein":
    "Canadian post-hardcore band formed in Burlington, Ontario in 2000. Long-running lineup centered on Shane Told (vocals). Among the longest-running bands in the post-hardcore/emo scene of the early 2000s.\n\nReleased 11 studio albums between *When Broken Is Easily Fixed* (2003) and *Pink Moon* (2024). Critical peak: *Discovering the Waterfront* (2005) and *Arrivals & Departures* (2007). Released primarily on Victory Records and (more recently) UNFD.",
  "sinad-lohan":
    "Irish singer-songwriter born Sinéad Lohan on August 9, 1971, in Cork. Distinguished by her acoustic folk-rock style and her late-1990s commercial peak on Interscope/Grapevine Records.\n\nReleased two studio albums: *Who Do You Think I Am* (1995) and *No Mermaid* (1998). Best-known recording: \"No Mermaid\" (1998). Withdrew from the music industry in the early 2000s and has not released new material since.",
  "six-feet-deep":
    "American Christian hardcore band formed in Akron, Ohio in 1992. Long-running lineup centered on Bobby Bostick (vocals). Distinguished by their metalcore-influenced Christian hardcore style.\n\nReleased four studio albums between *Struggle* (1994) and *We Will Conquer* (1996). Released primarily on REX Records. The band has been intermittently active and re-emerged in the 2010s with new material.",
  "sixpence-none-the-richer":
    "American Christian rock band formed in New Braunfels, Texas in 1992. Long-running lineup centered on Leigh Nash (vocals) and Matt Slocum (guitar/cello/songwriter). The band's name comes from a passage in C.S. Lewis's *Mere Christianity*. Distinguished by their dreamy, harmony-rich indie-pop style.\n\nReleased six studio albums between *The Fatherless and the Widow* (1994) and *Strange Conversation* (2019). Commercial peak: *Sixpence None the Richer* (1997, eventually multi-platinum after the 1998 reissue, featuring the international #1 \"Kiss Me\" and the Crowded House cover \"Don't Dream It's Over\").",
  "skankin-pickle":
    "American ska-punk band formed in San Jose, California in 1989. Long-running lineup featured Mike Park (saxophone/vocals, founder of Asian Man Records) and Lynette Knackstedt (guitar). Distinguished by their hyperactive third-wave ska style and Park's political and Asian-American advocacy lyrics.\n\nReleased four studio albums between *Skafunkrastapunk* (1991) and *The Green Album* (1996). Park founded Asian Man Records (1996), which has released material by Less Than Jake, the Lawrence Arms, the Queers, and many others. The band dissolved in 1996.",
  "skarhead":
    "American hardcore band formed in New York City in 1994. Long-running lineup centered on Lord Ezec (vocals, born Daniel Singer). Distinguished by their fusion of hardcore with hip-hop and their association with the broader NYHC scene.\n\nReleased four studio albums between *Drugs, Money, Sex* (1998) and *Vintage* (2014). Members have overlapped with the parallel band Madball and the NYHC scene generally.",
  "skillet":
    "American Christian rock band formed in Memphis, Tennessee in 1996. Long-running lineup centered on married couple John Cooper (vocals/bass) and Korey Cooper (rhythm guitar/keyboards), plus Seth Morrison (lead guitar) and Jen Ledger (drums/vocals). Among the most commercially successful Christian rock acts of the 2000s and 2010s.\n\nReleased 11 studio albums between *Skillet* (1996) and *Revolution* (2024). Commercial peak: *Awake* (2009, double-platinum, featuring \"Monster\" and \"Hero\") and *Rise* (2013).",
  "skunk-anansie":
    "British rock band formed in London in 1994. Long-running lineup: Skin (vocals, born Deborah Anne Dyer, b. 1967), Cass Lewis (bass), Ace (guitar), and Mark Richardson (drums). Distinguished by Skin's powerful vocals and the band's fusion of hard rock with politically charged lyrics.\n\nReleased seven studio albums between *Paranoid & Sunburnt* (1995) and *The Painful Truth* (2024). Commercial peak: *Stoosh* (1996) and *Post Orgasmic Chill* (1999). Headlined the Glastonbury Festival in 1999, making Skin one of the first Black female frontwomen to headline the festival.",
  "sleeping-with-sirens":
    "American post-hardcore band formed in Orlando, Florida in 2009. Long-running lineup centered on Kellin Quinn (vocals). Distinguished by Quinn's high-tenor vocals and the band's role as one of the prominent post-hardcore/emo-revival acts of the early 2010s.\n\nReleased seven studio albums between *With Ears to See and Eyes to Hear* (2010) and *Complete Collapse* (2022). Commercial peak: *Feel* (2013) and *Madness* (2015). Quinn has frequently collaborated with Pierce the Veil's Vic Fuentes.",
  "slipknot":
    "American heavy metal band formed in Des Moines, Iowa in 1995. Nine-member ensemble notable for performing in matching jumpsuits and individualized masks. Long-running lineup historically centered on Corey Taylor (vocals), Shawn \"Clown\" Crahan (percussion), Jim Root (guitar), and Mick Thomson (guitar). Founding bassist Paul Gray (1972-2010) and drummer Joey Jordison (1975-2021) both died young.\n\nReleased seven studio albums between *Slipknot* (1999) and *The End, So Far* (2022). Commercial peak: *Iowa* (2001), *Vol. 3: (The Subliminal Verses)* (2004, Grammy for Best Metal Performance for \"Before I Forget\"), and *.5: The Gray Chapter* (2014, the first after Gray's death). One of the most commercially successful heavy metal bands of the 21st century.",
  "sloppy-seconds":
    "American punk rock band formed in Indianapolis in 1985. Long-running lineup centered on B.A. (vocals, born Brett Buchanan). Distinguished by their Ramones-influenced pop-punk style and explicitly trashy/B-movie lyrical themes.\n\nReleased five studio albums between *Destroyed* (1989) and *Endless Bummer* (2008). Released primarily on Taang! Records during their commercial peak. The band has remained intermittently active.",
  "sly-the-family-stone":
    "American funk band formed in San Francisco in 1966. Lineup originally: Sly Stone (vocals/keyboards, born Sylvester Stewart, b. March 15, 1943, d. June 9, 2025), Freddie Stone (guitar/vocals), Larry Graham (bass, 1968-1972, originator of slap bass), Cynthia Robinson (trumpet, 1944-2015), Rose Stone (keyboards/vocals), Jerry Martini (saxophone), and Greg Errico (drums). The first major rock/funk band to feature racially mixed and gender-mixed personnel.\n\nReleased seven studio albums between *A Whole New Thing* (1967) and *Heard Ya Missed Me, Well I'm Back* (1976). Critical and commercial peaks: *Stand!* (1969), *There's a Riot Goin' On* (1971), and *Fresh* (1973). Performed at Woodstock in 1969 with what became one of the festival's most iconic sets. Inducted into the Rock and Roll Hall of Fame in 1993. Sly Stone died in 2025.",
  "smokey-robinson":
    "American singer-songwriter born William Robinson Jr. on February 19, 1940, in Detroit. Founding lead vocalist of the Miracles (1955-1972) and Vice President of Motown Records (1961-1988). Bob Dylan reportedly called him \"America's greatest living poet.\"\n\nReleased over 25 solo studio albums between *Smokey* (1973) and *Gasms* (2023). Wrote and co-wrote major Motown hits including \"My Girl,\" \"The Way You Do the Things You Do,\" \"My Guy,\" \"Get Ready,\" and dozens more for the Temptations, Marvin Gaye, Mary Wells, and the Miracles. Inducted into the Rock and Roll Hall of Fame in 1987. Kennedy Center Honoree in 2006.",
  "snoop-dogg":
    "American rapper, songwriter, and media personality born Calvin Cordozar Broadus Jr. on October 20, 1971, in Long Beach, California. Discovered by Dr. Dre and featured prominently on Dre's *The Chronic* (1992) before launching his solo career. Distinguished by his laid-back delivery and his decades-long evolution from G-Funk hardcore rapper to mainstream entertainment fixture.\n\nReleased 20 studio albums starting with *Doggystyle* (1993, the first hip-hop debut album to enter the Billboard 200 at #1). Subsequent peaks: *Tha Doggfather* (1996), *No Limit Top Dogg* (1999), and *R&G (Rhythm & Gangsta): The Masterpiece* (2004). Has hosted the 2024 Olympic torch relay coverage with Kevin Hart, the live-streaming coverage of the 2024 Paris Games for NBC, and many other mainstream productions.",
  "snot":
    "American nu-metal band formed in Santa Barbara, California in 1995. Long-running lineup centered on Lynn Strait (vocals, 1968-1998). Distinguished by their fusion of nu-metal, funk, and punk influences.\n\nReleased *Get Some* (1997, Geffen). Strait died in a car accident in December 1998 along with his dog Dobbs. The 2000 tribute album *Strait Up* features various nu-metal vocalists (Corey Taylor, Jonathan Davis, Serj Tankian, etc.) performing unfinished songs from the band's planned second album.",
  "spahn-ranch":
    "American industrial/electronic band formed in Los Angeles in 1992. Long-running lineup centered on Athan Maroulis (vocals). The band's name references the California ranch where Charles Manson's \"family\" lived in 1969. Distinguished by their dark electronic/industrial style drawing on EBM and goth-industrial.\n\nReleased five studio albums between *Collateral Damage* (1992) and *The Beautiful Fallen* (2000). Released primarily on Cleopatra Records. Maroulis subsequently led Black Tape for a Blue Girl and NoiseFloor.",
  "spandau-ballet":
    "British new wave band formed in London in 1979. Long-running lineup: Tony Hadley (vocals), Gary Kemp (guitar/keyboards), Martin Kemp (bass), Steve Norman (saxophone/percussion), and John Keeble (drums). Among the defining bands of the New Romantic movement of the early 1980s.\n\nReleased seven studio albums between *Journeys to Glory* (1981) and *Once More* (2009). Commercial peak: *True* (1983, featuring the international #1 title track and \"Gold\"). The Kemp brothers also pursued acting careers, including the leading roles in the Kray twins biopic *The Krays* (1990).",
  "spice-girls":
    "British pop group formed in London in 1994. Lineup: Victoria Beckham (Posh, b. 1974), Mel B (Scary, b. 1975), Emma Bunton (Baby, b. 1976), Mel C (Sporty, b. 1974), and Geri Halliwell (Ginger, b. 1972). Architects of the \"girl power\" pop phenomenon of the late 1990s.\n\nReleased three studio albums between *Spice* (1996, the best-selling album by a female group of all time at over 23 million copies) and *Forever* (2000). Best-known recordings include \"Wannabe\" (1996), \"Say You'll Be There\" (1996), and \"Spice Up Your Life\" (1997). Reunited briefly in 2007-2008 and again in 2019 (without Victoria Beckham).",
  "sponge":
    "American rock band formed in Detroit in 1991. Long-running lineup centered on Vinnie Dombroski (vocals). Distinguished by their post-grunge / alternative rock style drawing on Detroit's hard-rock heritage.\n\nReleased nine studio albums between *Rotting Piñata* (1994) and *Lavatorium* (2024). Commercial peak: *Rotting Piñata* (gold-certified, featuring \"Plowed\" and \"Molly (Sixteen Candles)\") and *Wax Ecstatic* (1996).",
  "spring-heeled-jack":
    "American ska-punk band formed in New Haven, Connecticut in 1991 (full name: Spring Heeled Jack USA, to distinguish from a UK band of the same name). Distinguished by their bright, horn-heavy third-wave ska style.\n\nReleased two studio albums: *Static World View* (1996) and *Songs From Suburbia* (1998). Member Tyler Jones subsequently joined the Pilfers. The band has reunited for occasional shows since the early 2000s.",
  "stan-getz":
    "American jazz saxophonist born February 2, 1927, in Philadelphia; died June 6, 1991. Distinguished by his cool-toned, lyrical tenor saxophone style and his central role in introducing bossa nova to American audiences.\n\nReleased over 100 albums across his career. Critical and commercial peaks: *Focus* (1961, with arrangements by Eddie Sauter), *Jazz Samba* (1962, with Charlie Byrd, featuring \"Desafinado\"), and *Getz/Gilberto* (1964, with João and Astrud Gilberto and Antônio Carlos Jobim, featuring \"The Girl from Ipanema,\" winning the 1965 Grammy for Album of the Year). Multiple Grammy Awards across his catalog.",
  "standards":
    "American instrumental rock band formed in Los Angeles in 2014 (officially stylized standards, lowercase). Duo of Marcos Mena (guitar) and Marcello Bardi (drums). Distinguished by their twinkly, math-rock-meets-pop guitar style drawing on TTNG and American Football.\n\nReleased *Fruit Town* (2018) and *Mood Swing!* (2021). Built a substantial following via the YouTube live-session and Spotify algorithmic discovery scenes for instrumental math rock.",
  "staticx":
    "American industrial metal band formed in Los Angeles in 1994 (officially Static-X). Long-running lineup historically centered on Wayne Static (1965-2014, vocals/guitar). Distinguished by their \"evil disco\" style (Static's term) — combining nu-metal with industrial dance rhythms.\n\nReleased seven studio albums between *Wisconsin Death Trip* (1999) and *Project: Regeneration Vol. 2* (2024). Wayne Static died in 2014 of mixed-substance toxicity. The band re-formed in 2019 with the original lineup minus Static, performing with a masked vocalist (\"Xer0\") and incorporating posthumous Wayne Static vocal tracks.",
  "stavesacre":
    "American Christian post-hardcore band formed in Orange County, California in 1993. Long-running lineup centered on Mark Salomon (vocals, formerly of the Crucified). Distinguished by their melodic post-hardcore style drawing on Quicksand and Sense Field.\n\nReleased six studio albums between *Friction* (1995) and *How to Live with a Curse* (2007). Released on Tooth & Nail and Lakeshore Records. The band has been intermittently active.",
  "steely-dan":
    "American rock band formed in New York City in 1971 as a duo of Walter Becker (bass/guitar/songwriter, 1950-2017) and Donald Fagen (vocals/keyboards/songwriter, b. 1948). Distinguished by their jazz-influenced rock arrangements, perfectionist studio approach, and famously demanding session-musician auditions.\n\nReleased nine studio albums between *Can't Buy a Thrill* (1972) and *Everything Must Go* (2003). Critical and commercial peaks: *Pretzel Logic* (1974), *Katy Lied* (1975), *Aja* (1977), and *Gaucho* (1980). Won the 2001 Grammy for Album of the Year for *Two Against Nature* (2000), the band's first studio album in 20 years. Inducted into the Rock and Roll Hall of Fame in 2001. Becker died in 2017; Fagen continues to tour under the Steely Dan name.",
  "steppenwolf":
    "Canadian-American rock band formed in Los Angeles in 1967. Long-running lineup historically centered on John Kay (vocals/guitar, b. 1944). Distinguished by their hard-rock blueprint and Kay's gravelly vocals.\n\nReleased over a dozen studio albums between *Steppenwolf* (1968) and *Rise & Shine* (1990). Best-known recordings: \"Born to Be Wild\" (1968, used in *Easy Rider*) and \"Magic Carpet Ride\" (1968). \"Born to Be Wild\" introduced the phrase \"heavy metal thunder\" to popular music vocabulary; the term \"heavy metal\" as a music-genre descriptor traces partly to this lyric.",
  "steve-augeri":
    "American singer born June 30, 1959, in Brooklyn, New York. Lead vocalist for Journey (1998-2006), replacing Steve Perry, before being replaced by Arnel Pineda. Distinguished by his Perry-like tenor that allowed Journey to continue touring the classic catalog.\n\nPrior to Journey, Augeri sang for Tall Stories (1988-1991) and Tyketto (1995-1996). Has subsequently led a solo touring band and the Steve Augeri Band, performing Journey-era material and his earlier work.",
  "steve-martin":
    "American comedian, actor, writer, and musician born August 14, 1945, in Waco, Texas. Among the most influential stand-up comedians of the 1970s before pivoting to film (*The Jerk*, 1979; *Planes, Trains and Automobiles*, 1987; *Father of the Bride*, 1991, etc.). Also a virtuoso bluegrass banjoist who has released several albums of original instrumental music.\n\nReleased the stand-up comedy albums *Let's Get Small* (1977, Grammy winner) and *A Wild and Crazy Guy* (1978, Grammy winner). Subsequent bluegrass releases include *The Crow: New Songs for the Five-String Banjo* (2009, Grammy winner) and the collaborations with the Steep Canyon Rangers (2011-2018). Co-stars in the Hulu mystery-comedy *Only Murders in the Building* (2021-present).",
  "steve-morse-band":
    "American instrumental rock band formed in 1984 by guitarist Steve Morse (b. July 28, 1954, Hamilton, Ohio), formerly of the Dixie Dregs and later a member of Deep Purple (1994-2022) and Flying Colors. Distinguished by Morse's fluent integration of country, jazz, classical, and rock styles into virtuoso instrumental compositions.\n\nReleased eight studio albums between *The Introduction* (1984) and *Outstanding in Their Field* (2009). Morse stepped back from Deep Purple in 2022 to focus on caring for his wife during a long illness; she died in 2022.",
  "steve-vai":
    "American guitarist born Steven Siro Vai on June 6, 1960, in Carle Place, New York. Studied under Joe Satriani. Member of Frank Zappa's band (1980-1983), Alcatrazz (1985), and David Lee Roth's solo band (1985-1989) before launching his solo career. Distinguished by his virtuoso technique and his use of seven-string guitars (Ibanez Universe, his signature model, was one of the first commercial seven-strings).\n\nReleased over a dozen studio albums between *Flex-Able* (1984) and *Inviolate* (2022). Commercial peak: *Passion and Warfare* (1990). Three Grammy Awards. Continues to tour internationally.",
  "stevie-ray-vaughan-and-double-trouble":
    "American blues-rock band formed in Austin, Texas in 1978. Lineup: Stevie Ray Vaughan (vocals/guitar, 1954-1990), Tommy Shannon (bass), Chris Layton (drums), and Reese Wynans (keyboards, joined 1985). Distinguished by Vaughan's virtuoso lead guitar work fusing Hendrix-style rock with Albert King-style blues.\n\nReleased five studio albums between *Texas Flood* (1983) and *In Step* (1989). Critical and commercial peaks: *Texas Flood*, *Couldn't Stand the Weather* (1984), and *In Step* (Grammy-winning). Vaughan died on August 27, 1990, in a helicopter crash following a concert in East Troy, Wisconsin (along with three Eric Clapton tour personnel). Inducted into the Rock and Roll Hall of Fame in 2015.",
  "stiff-little-fingers":
    "Northern Irish punk rock band formed in Belfast in 1977. Long-running lineup historically centered on Jake Burns (vocals/guitar). Distinguished by their politically charged lyrics directly addressing the Northern Ireland Troubles.\n\nReleased 11 studio albums between *Inflammable Material* (1979) and *No Going Back* (2014). The 1979 debut was the first independently released album to reach the UK Top 20 (#14). Critical peaks: *Inflammable Material* and *Nobody's Heroes* (1980). The band has been continuously touring since their 1987 reunion.",
  "stone-horses":
    "American rock band based in Brooklyn, New York. Active in the 2010s and 2020s indie-rock and Americana scenes. Lineup historically centered on songwriter Jed Hughes.\n\nLimited public documentation; primarily known among regional fans and active in the New York singer-songwriter and Americana scenes. The band has performed in support of regional touring artists and released material independently.",
  "streisand":
    "Same artist as Barbra Streisand — credit variation. American singer, actress, filmmaker, and songwriter born April 24, 1942, in Brooklyn, New York. Among the best-selling music artists of all time, with estimated worldwide sales of 150 million-plus units, and one of the most acclaimed performers in American popular culture.\n\nReleased over 35 studio albums starting with *The Barbra Streisand Album* (1963). The only artist to have a #1 album in seven consecutive decades on the Billboard 200 (1960s through 2020s). Won two Academy Awards (Best Actress for *Funny Girl*, 1969; Best Original Song for \"Evergreen\" from *A Star Is Born*, 1977). Memoir *My Name Is Barbra* (2023). The 1991 *Highlights from Just for the Record* compilation contains an exhaustive career retrospective.",
  "strongarm":
    "American Christian hardcore band formed in Florida in 1990. Long-running lineup centered on Nate Crocker (drums) and various vocalists. Distinguished by their metallic Christian hardcore style and their role as a foundational band for the early Solid State Records (Tooth & Nail's heavy-music imprint).\n\nReleased three studio albums between *Atonement* (1995) and *Advent of a Miracle* (1998). Members went on to form As Friends Rust and Further Seems Forever (whose initial lineup featured Chris Carrabba pre-Dashboard Confessional).",
  "strung-out":
    "American punk rock band formed in Simi Valley, California in 1989. Long-running lineup centered on Jason Cruz (vocals), Jake Kiley (guitar), and Rob Ramos (guitar). Distinguished by their fusion of melodic skate-punk with thrash-metal influences.\n\nReleased 11 studio albums between *Another Day in Paradise* (1994) and *Dead Rebellion* (2024). Critical peak: *Twisted by Design* (1998), *An American Paradox* (2002), and *Blackhawks Over Los Angeles* (2007). Released primarily on Fat Wreck Chords.",
  "stryper":
    "American Christian metal band formed in Orange County, California in 1983. Long-running lineup: Michael Sweet (vocals/guitar), Robert Sweet (drums, his brother), Oz Fox (guitar), and Tim Gaines (bass, until 2017). Distinguished by their yellow-and-black striped visual aesthetic and their explicit Christian evangelism — they would throw Bibles into the audience at every show.\n\nReleased over a dozen studio albums between *Yellow and Black Attack* (1984) and *When We Were Kings* (2024). Commercial peak: *To Hell with the Devil* (1986, platinum, featuring \"Calling on You\" and \"Honestly\"). The first overtly Christian band to achieve sustained mainstream metal success.",
  "stuck-mojo":
    "American rap-metal band formed in Atlanta in 1989. Long-running lineup centered on Rich Ward (guitar) and various vocalists (most prominently Bonz from 1991-2000 and 2006-2009). Distinguished by their fusion of Southern metal with hip-hop and their role as one of the early rap-rock crossover acts.\n\nReleased seven studio albums between *Snappin' Necks* (1995) and *The Great Revival* (2008). Ward also leads Fozzy with WWE wrestler Chris Jericho.",
  "styx":
    "American rock band formed in Chicago in 1972. Long-running lineup historically centered on Dennis DeYoung (vocals/keyboards, until 1999), Tommy Shaw (vocals/guitar, since 1975), and James \"JY\" Young (guitar/vocals). Distinguished by their fusion of progressive rock with arena rock and their multiple-lead-vocalist approach.\n\nReleased 17 studio albums between *Styx* (1972) and *Crash of the Crown* (2021). Commercial peak: *The Grand Illusion* (1977), *Pieces of Eight* (1978), *Cornerstone* (1979, featuring \"Babe\"), and *Paradise Theatre* (1981, featuring \"The Best of Times\"). The 1983 rock opera *Kilroy Was Here* (featuring \"Mr. Roboto\") split the band internally and led to their initial breakup in 1984.",
  "sugar-hill-gang":
    "American hip-hop group formed in Englewood, New Jersey in 1979. Lineup: Big Bank Hank (Henry Jackson, 1956-2014), Wonder Mike (Michael Wright), and Master Gee (Guy O'Brien). Among the very first hip-hop groups to achieve commercial success.\n\n\"Rapper's Delight\" (1979), an 11-minute-plus single built on Chic's \"Good Times\" bassline, was the first hip-hop single to reach the US Top 40 and the first to be widely heard outside of the New York metropolitan area. The group released three subsequent studio albums but never approached \"Rapper's Delight\" commercially. Inducted into the Hip Hop Hall of Fame in 1999.",
  "sugar-minott":
    "Jamaican reggae singer born Lincoln Barrington Minott on May 25, 1956, in Kingston, Jamaica; died July 10, 2010. Influential dancehall and lovers-rock vocalist. Founded the Youth Promotion sound system and label in the late 1970s, mentoring artists including Garnett Silk, Tenor Saw, and Yami Bolo.\n\nReleased over 50 studio albums between *Live Loving* (1978) and *Sugar Minott Goes Pop* (2010). Best-known recordings: \"Good Thing Going (We've Got a Good Thing Going)\" (1981, a UK Top 5 hit) and \"Vanity\" (1983). Died at age 54 of heart-related illness.",
  "sugar-ray":
    "American rock band formed in Newport Beach, California in 1986. Long-running lineup centered on Mark McGrath (vocals). Began as a funk-metal band before pivoting to a brightly pop-oriented sound on *Floored* (1997).\n\nReleased eight studio albums between *Lemonade and Brownies* (1995) and *Little Yachty* (2019). Commercial peak: *Floored* (1997, featuring the breakthrough \"Fly\"), *14:59* (1999, featuring \"Every Morning\" and \"Someday\"), and *Sugar Ray* (2001). McGrath has since hosted *Extra* and various reality TV productions.",
  "super-guitar-bros":
    "American instrumental duo of fingerstyle guitarists Eric Calderone and Sam Griffin. Distinguished by their virtuoso fingerstyle covers of video-game and pop music, primarily distributed via YouTube.\n\nReleased *World of Warcraft* (2019) and several other album-length tribute releases. Primarily a streaming/YouTube-native act rather than a touring band.",
  "susan-tedeschi":
    "American blues and soul guitarist and singer-songwriter born November 9, 1970, in Boston, Massachusetts. Married to Derek Trucks (member of the Allman Brothers Band) since 2001; together they lead the Tedeschi Trucks Band (2010-present).\n\nReleased six solo studio albums between *Better Days* (1995) and *Back to the River* (2008) before largely transitioning to Tedeschi Trucks Band work. Six Grammy nominations as a solo artist; Tedeschi Trucks Band won the 2012 Grammy for Best Blues Album for *Revelator*.",
  "sweet":
    "British glam-rock band formed in London in 1968 (originally as the Sweetshop). Classic lineup: Brian Connolly (vocals, 1945-1997), Steve Priest (bass/vocals, 1948-2020), Andy Scott (guitar/vocals), and Mick Tucker (drums, 1947-2002). Distinguished by their string of Chinn-Chapman bubblegum-pop singles in the early 1970s before pivoting to harder-rock material.\n\nReleased over a dozen studio albums between *Funny How Sweet Co-Co Can Be* (1971) and *Isolation Boulevard* (2021). Best-known recordings: \"Little Willy\" (1972), \"Block Buster!\" (1973), \"The Ballroom Blitz\" (1973), \"Fox on the Run\" (1975), and \"Love Is Like Oxygen\" (1978). Competing Brian Connolly's Sweet and Andy Scott's Sweet lineups coexisted in the late 1980s and 1990s.",
  "switchblade-symphony":
    "American gothic rock duo formed in San Francisco in 1989. Lineup: Tina Root (vocals) and Susan Wallace (keyboards). Distinguished by their fairy-tale-meets-darkwave gothic style with prominent classical and harpsichord-style keyboard textures.\n\nReleased three studio albums between *Serpentine Gallery* (1995) and *The Three Calamities* (1999) before splitting in 1999. Root subsequently led Tre Lux and continues to record.",
  "t-rex":
    "British rock band formed in London in 1967 (originally as Tyrannosaurus Rex). Long-running lineup historically centered on Marc Bolan (vocals/guitar, 1947-1977) and Mickey Finn (percussion, 1947-2003). The defining band of the British glam rock movement.\n\nReleased 11 studio albums between *My People Were Fair and Had Sky in Their Hair... But Now They're Content to Wear Stars on Their Brows* (1968) and *Dandy in the Underworld* (1977). Commercial peak: *Electric Warrior* (1971, featuring \"Get It On (Bang a Gong)\" and \"Jeepster\") and *The Slider* (1972). Bolan died in a car accident in 1977 at age 29 (two weeks short of his 30th birthday).",
  "tsol":
    "American punk rock band formed in Long Beach, California in 1978 (officially T.S.O.L., for True Sounds of Liberty). Long-running lineup historically centered on Jack Grisham (vocals). Stylistically restless across hardcore punk (early years), gothic-influenced punk (*Dance with Me*, 1981), glam metal (mid-1980s), and a return to hardcore/punk (1990s reunion onward).\n\nReleased over a dozen studio albums between *Dance with Me* (1981) and *Set the Hook* (2024). Critical peak: *Dance with Me*. The Grisham-led TSOL split in the mid-1980s and a competing lineup continued under the TSOL name; Grisham reclaimed the band in the late 1990s.",
  "talib-kweli":
    "American rapper born Talib Kweli Greene on October 3, 1975, in Brooklyn, New York. Member of Black Star with Mos Def (Yasiin Bey) and Reflection Eternal with Hi-Tek. Distinguished by his dense, literate lyricism and his association with the late-1990s conscious hip-hop movement.\n\nReleased eight solo studio albums between *Quality* (2002) and *Liberation 2* (2022, with Madlib). Critical peak: *Quality*, *The Beautiful Struggle* (2004), and *Eardrum* (2007). Co-founded the Javotti Media label/publishing house.",
  "tatyana-ali":
    "American actress and singer born January 24, 1979, in Brooklyn, New York. Best known for playing Ashley Banks on the sitcom *The Fresh Prince of Bel-Air* (1990-1996). Briefly pursued a recording career during the late 1990s.\n\nReleased one studio album: *Kiss the Sky* (1998, MJJ Music / Epic). Best-known recording: \"Daydreamin'\" (1998), produced by Will Smith and Poke & Tone. Has subsequently focused on her acting and producing career.",
  "tears-for-fears":
    "British new wave band formed in Bath, Somerset in 1981. Long-running duo of Roland Orzabal (vocals/guitar) and Curt Smith (vocals/bass), with various supporting musicians. Distinguished by their cerebral synth-pop drawing on Arthur Janov's primal-therapy texts (the band's name comes from a phrase in Janov's *Prisoners of Pain*).\n\nReleased seven studio albums between *The Hurting* (1983) and *The Tipping Point* (2022). Commercial peak: *Songs from the Big Chair* (1985, featuring \"Everybody Wants to Rule the World,\" \"Shout,\" and \"Head Over Heels\") and *The Seeds of Love* (1989). Reunited in 2000 after a long split.",
  "ten-years-after":
    "British blues-rock band formed in Nottingham in 1966. Long-running lineup historically centered on Alvin Lee (vocals/guitar, 1944-2013). Distinguished by Lee's lightning-fast lead guitar work and his iconic performance of \"I'm Going Home\" at the original 1969 Woodstock festival.\n\nReleased 12 studio albums between *Ten Years After* (1967) and *Naturally Live* (2018). Commercial peak: *Cricklewood Green* (1970), *Watt* (1970), *A Space in Time* (1971, featuring \"I'd Love to Change the World\"), and *Rock & Roll Music to the World* (1972). Alvin Lee left the band in 1974 and intermittently reunited; he died in 2013 of unforeseen complications during a routine surgery.",
  "terry-taylor":
    "American Christian rock singer-songwriter and producer born November 24, 1950, in Sacramento, California. Frontman of Daniel Amos (1974-present), the Swirling Eddies (1986-present), and the Lost Dogs (1991-present); also founder of Christian-themed children's-music project Tinker Tunes.\n\nReleased solo albums starting with *Knowledge & Innocence* (1986). Has produced extensively for Christian rock artists including the Choir, Adam Again, and the Lost Dogs. Founded the Stunt Records label.",
  "the-4-seasons":
    "Same artist as the Four Seasons — credit variation. American rock band formed in Newark, New Jersey in 1960. Original lineup: Frankie Valli (vocals, b. 1934), Bob Gaudio (keyboards/vocals/songwriter, b. 1942), Tommy DeVito (guitar/vocals, 1928-2020), and Nick Massi (bass/vocals, 1927-2000). Distinguished by Valli's extreme falsetto and Gaudio's prolific hit songwriting.\n\nReleased over 25 studio albums starting with *Sherry & 11 Others* (1962). Commercial peak: a string of mid-1960s hits including \"Sherry,\" \"Big Girls Don't Cry,\" \"Walk Like a Man,\" \"Rag Doll,\" and \"Dawn (Go Away).\" Resurfaced in the 1970s with \"Who Loves You\" (1975) and \"December, 1963 (Oh, What a Night)\" (1975). The 2005 Broadway musical *Jersey Boys* dramatized the band's history. Inducted into the Rock and Roll Hall of Fame in 1990.",
  "the-alan-parsons-project":
    "British progressive rock band formed in London in 1975. Duo of producer/engineer Alan Parsons (b. December 20, 1948; engineered Pink Floyd's *The Dark Side of the Moon*) and songwriter/keyboardist Eric Woolfson (1945-2009). Distinguished by their conceptual albums and use of rotating session vocalists rather than a fixed frontman.\n\nReleased 11 studio albums between *Tales of Mystery and Imagination* (1976, based on Edgar Allan Poe) and *Gaudi* (1987). Commercial peak: *I Robot* (1977, based on Isaac Asimov's stories), *The Turn of a Friendly Card* (1980), and *Eye in the Sky* (1982, featuring the title-track hit). The Parsons-led project officially ended in 1990; Parsons continues to tour as \"The Alan Parsons Live Project.\"",
};

async function main() {
  const dryRun = process.argv.includes("--dry-run");
  const force = process.argv.includes("--force");
  const { containers } = await import("../lib/cosmos");
  const { getStoredArtist } = await import("../lib/artists");

  let written = 0;
  let skipped = 0;
  let missing = 0;

  for (const [slug, description] of Object.entries(DESCRIPTIONS)) {
    const existing = await getStoredArtist(slug);
    if (!existing) {
      console.log(`✗ ${slug}: no stored doc found`);
      missing += 1;
      continue;
    }
    if (existing.description && !force) {
      console.log(`↷ ${slug}: already has description — skipping`);
      skipped += 1;
      continue;
    }
    if (dryRun) {
      console.log(`◌ ${slug}: would write ${description.length} chars`);
      written += 1;
      continue;
    }
    const updated = {
      ...existing,
      description,
      updatedAt: new Date().toISOString(),
    };
    await containers.artists.item(slug, slug).replace(updated);
    console.log(`✓ ${slug}: ${description.length} chars`);
    written += 1;
  }

  console.log(`\nDone. written=${written} skipped=${skipped} missing=${missing}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
