import { config as loadEnv } from "dotenv";
loadEnv({ path: ".env.local" });

const DESCRIPTIONS: Record<string, string> = {
  "yngwie-j-malmsteen":
    "Swedish guitarist born June 30, 1963, in Stockholm. Foundational figure in neoclassical metal — a subgenre that fuses heavy metal with the harmonic and melodic language of European classical music, particularly Bach, Vivaldi, and Paganini. Frequently cited as one of the most technically influential guitarists of the 1980s.\n\nReleased over 20 studio albums, primarily under the band name Rising Force, starting with *Rising Force* (1984). Commercial peak: *Marching Out* (1985), *Trilogy* (1986), and *Odyssey* (1988, his most commercial album, featuring vocalist Joe Lynn Turner). Continues to record and tour as a solo guitarist with revolving rhythm sections.",
  "yngwie-j-malmsteens-rising-force":
    "Same artist as Yngwie J. Malmsteen — the \"Rising Force\" band name is the credit Malmsteen uses on his studio albums as a nod to his 1984 debut. Backing musicians have rotated throughout the band's history; key vocalists have included Jeff Scott Soto, Mark Boals, Joe Lynn Turner, and Tim \"Ripper\" Owens.\n\nThe Rising Force discography effectively constitutes Yngwie's solo work — over 20 albums starting with the instrumental debut *Rising Force* (1984) and continuing through *Parabellum* (2021). Style centers on Malmsteen's neoclassical shred guitar playing.",
  "zebrahead":
    "American rap-rock band formed in Orange County, California in 1996. Long-running lineup: Ali Tabatabaee (vocals), Matty Lewis (vocals/guitar, since 2004), Greg Bergdorf (guitar, 1996-2011), Ben Osmundson (bass), and Ed Udhus (drums). Style fuses pop-punk, hip-hop, and ska.\n\nTwelve studio albums starting with *Waste of Mind* (1998). Commercial peak: *Playmate of the Year* (2000) and *MFZB* (2003). Particularly popular in Japan, where the band's late-period albums (*HelloApocalypse*, 2017; *I'll Be Your Ghost*, 2025) have charted strongly.",
  "question-mark-the-mysterians":
    "American garage rock band formed in Saginaw, Michigan in 1962 by Mexican-American teenage cousins. Lineup: ? (Question Mark, Rudy Martinez, vocals), Frank Lugo (bass), Frank Rodriguez (organ), Robert Martinez (drums, replaced by Eddie Serrato in 1964), and Bobby Balderrama (guitar).\n\nBest known for the 1966 #1 single \"96 Tears,\" a garage-rock standard that remains one of the most-covered songs of the era. Released two studio albums in the original run: *96 Tears* (1966) and *Action* (1967). The band has reunited periodically since the 1980s, often with the original members.",
  "the-mysterians":
    "Same artist as ? & The Mysterians — different Discogs/setlist.fm credit variation. American garage rock band formed in Saginaw, Michigan in 1962. Best known for the 1966 #1 single \"96 Tears.\" Released two studio albums in the original run: *96 Tears* (1966) and *Action* (1967). The band has reunited periodically since the 1980s.",
  "bald-bill-hagan-and-his-trocaderons":
    "Late-1950s/early-1960s American novelty band associated with burlesque-house instrumental music. The \"Music for a Strip Tease Party\" album series — distributed by Somerset Records and similar budget labels — is the most-circulated artifact of their output, frequently traded among crate-diggers and curio collectors.",
  "22-jacks":
    "American punk rock band formed in Los Angeles in 1995. Side project of Joe Sib (vocals, also of Wax). Style draws on pop-punk, melodic hardcore, and the broader mid-1990s SoCal scene.\n\nThree studio albums between *Overserved* (1995) and *Going North* (2000). Released primarily on Side One Dummy Records, which Sib co-founded in 1996 — the label has gone on to release material by Flogging Molly, the Mighty Mighty Bosstones, and Gogol Bordello.",
  "2cellos":
    "Croatian cello duo of Luka Šulić and Stjepan Hauser, formed in 2011. Distinguished by their genre-fluid approach — rock, pop, classical, and film scores performed entirely on cellos. Sometimes referred to as \"the Cello Guys.\"\n\nReleased six studio albums between the 2011 self-titled debut and *Dedicated* (2021). Best-known recordings include their viral 2011 YouTube cover of Michael Jackson's \"Smooth Criminal\" (which led to Elton John signing them as his touring opening act) and the long-running *Dedicated* album. The duo announced an indefinite pause in 2022.",
  "30footfall":
    "American punk rock band formed in Houston, Texas in 1992. Long-running lineup centered on Butch Klotz (vocals/bass). Style draws on melodic hardcore, ska-punk, and pop-punk.\n\nSix studio albums between *Speed of Sound* (1996) and *Now That I Don't Have a Driver's License* (2010). Released primarily on Nitro Records, the label co-founded by Dexter Holland of the Offspring. Active continuously since formation.",
  "98":
    "98 Degrees — American boy band formed in Los Angeles in 1996. Lineup: Nick Lachey, Drew Lachey (brothers), Jeff Timmons, and Justin Jeffre. Distinguished from contemporary boy bands by writing portions of their own material and avoiding the Lou Pearlman / Backstreet Boys / NSYNC management pipeline.\n\nFour studio albums in the original run: *98 Degrees* (1997), *98 Degrees and Rising* (1998), *Revelation* (2000), and the Christmas album *This Christmas* (1999). Best-known singles include \"Because of You,\" \"The Hardest Thing,\" \"I Do (Cherish You),\" and \"Thank God I Found You\" (with Mariah Carey). Reunited in 2012 and have continued touring intermittently.",
  "aaron-carter":
    "American singer (1987-2022). Born in Tampa, Florida. Younger brother of Nick Carter of the Backstreet Boys. Launched his solo career at age nine and was a defining teen-pop figure of the late 1990s and early 2000s.\n\nReleased five studio albums between *Aaron Carter* (1997) and *Love* (2018). Commercial peak: *Aaron's Party (Come Get It)* (2000, featuring the title track and \"I Want Candy\") and *Oh Aaron* (2001). Adult career marked by substance abuse, mental-health struggles, and legal issues. Died from drowning in November 2022 at age 34.",
  "abba":
    "Swedish pop group formed in Stockholm in 1972. Lineup: Agnetha Fältskog, Björn Ulvaeus, Benny Andersson, and Anni-Frid \"Frida\" Lyngstad. The name is an acronym of the members' first initials. Among the most commercially successful pop acts in history, with estimated worldwide sales exceeding 380 million units.\n\nNine studio albums between *Ring Ring* (1973) and *Voyage* (2021, their first new album in 40 years). Commercial peak: *Arrival* (1976), *The Album* (1977), and *Voulez-Vous* (1979). Won the 1974 Eurovision Song Contest with \"Waterloo,\" launching their international career. The 2008 jukebox musical and film *Mamma Mia!* introduced their catalog to a new generation. Inducted into the Rock and Roll Hall of Fame in 2010.",
  "abby-the-spoon-lady":
    "American street musician based in Asheville, North Carolina. Born Abigail Roberts. Plays the spoons as a primary instrument; performs traditional Appalachian folk and old-time music, often in collaboration with banjo player Chris Rodrigues. Active on the busking circuit since approximately 2007.\n\nReleased several studio albums of street recordings and traditional folk material. Built a substantial YouTube following through busking videos shot in downtown Asheville. Has been a recurring presence at folk and bluegrass festivals across the eastern US.",
  "accept":
    "German heavy metal band formed in Solingen in 1976. Long-running lineup centered on guitarist Wolf Hoffmann. Vocalists: Udo Dirkschneider (1976-1987, 1992-1996, 2005) and Mark Tornillo (since 2009). One of the foundational European heavy metal bands.\n\nSixteen studio albums starting with *Accept* (1979). Commercial peak: *Restless and Wild* (1982), *Balls to the Wall* (1983, featuring the title track), and *Metal Heart* (1985). Dirkschneider departed permanently in 2005 to focus on his own band U.D.O. Accept resumed in 2009 with new vocalist Mark Tornillo and have released seven subsequent albums.",
  "adolf-satan":
    "American grindcore band formed in Boston in 2000. Lineup: Steve Austin (vocals, also of Today Is the Day), Cory Saavedra (guitar), Mark Bouchard (bass), and Tad Kubler (drums, later of the Hold Steady). Style fuses grindcore, sludge metal, and noise rock.\n\nReleased one studio album: the self-titled debut (2003). Active briefly between 2000 and 2003 as a side project of the participants' primary bands.",
  "adrenalin-od":
    "American hardcore punk band formed in New Jersey in 1981. Lineup: Paul Richard (vocals), Jim Foster (guitar), Jack Steeples (bass), and Dave Scott (drums). Distinguished by their sense of humor and willingness to incorporate elements of surf, ska, and reggae into hardcore's three-chord framework.\n\nFour studio albums between *The Wacky Hi-Jinks of...* (1984) and *Ishtar* (1990). Best-known release: *Cruising with Elvis in Bigfoot's UFO* (1988). The band briefly reunited in the 2010s.",
  "afi":
    "American rock band formed in Ukiah, California in 1991. Long-running lineup: Davey Havok (vocals), Jade Puget (guitar, since 1998), Hunter Burgan (bass, since 1997), and Adam Carson (drums). Style evolved from hardcore punk through horror punk into post-hardcore and gothic alternative rock.\n\nEleven studio albums starting with *Answer That and Stay Fashionable* (1995). Commercial peak: *Sing the Sorrow* (2003, featuring \"Girl's Not Grey\") and *Decemberunderground* (2006, the band's only #1 album, featuring \"Miss Murder\"). Continuously active.",
  "against-me":
    "American punk rock band formed in Gainesville, Florida in 1997 by Laura Jane Grace (vocals/guitar; she came out as a trans woman in 2012, having previously performed under her birth name). Long-running lineup also includes James Bowman (guitar) and various rhythm sections — Atom Willard joined on drums in 2013.\n\nSeven studio albums starting with *Against Me!* (1997). Commercial peak: *New Wave* (2007), *Transgender Dysphoria Blues* (2014, addressing Grace's transition), and *Shape Shift with Me* (2016). Grace also pursues solo work and the side project Laura Jane Grace and the Devouring Mothers.",
  "agnostic-front":
    "American hardcore band formed in New York City in 1980. Long-running lineup centered on Roger Miret (vocals) and Vinnie Stigma (guitar). Among the foundational acts of New York hardcore (NYHC) alongside Bad Brains and Cro-Mags.\n\nTwelve studio albums starting with *Victim in Pain* (1984). Best-known releases include *Cause for Alarm* (1986) and *Liberty and Justice for...* (1987). Continuously active in some form since 1980, with Stigma the only continuous member through multiple lineup changes.",
  "aimee-mann":
    "American singer-songwriter born September 8, 1960, in Richmond, Virginia. First gained prominence as bassist/vocalist of 'Til Tuesday (1982-1990), best known for \"Voices Carry.\" Launched a successful solo career after the band's dissolution.\n\nReleased ten solo studio albums between *Whatever* (1993) and *Queens of the Summer Hotel* (2021). Critical peak: *Bachelor No. 2 or, the Last Remains of the Dodo* (2000) and the *Magnolia* (1999) soundtrack, which she largely composed and performed. The song \"Save Me\" from the *Magnolia* soundtrack was nominated for an Academy Award. Two-time Grammy winner.",
  "alan-dawson":
    "American jazz drummer (1929-1996). Born in Marietta, Pennsylvania, raised in Boston. Among the most respected jazz drummer-educators of the 20th century; taught at Berklee College of Music from 1957 to 1974, where his students included Tony Williams, Vinnie Colaiuta, Steve Smith, and Terri Lyne Carrington.\n\nMost prominently associated with the Dave Brubeck Quartet (1968-1974), replacing the long-tenured Joe Morello. Also performed and recorded with Sonny Rollins, Hank Mobley, and Lionel Hampton, among many others. Released several recordings as a leader; primarily known as a sideman and educator.",
  "alanis-morissette":
    "Canadian-American singer-songwriter born June 1, 1974, in Ottawa, Canada. Initial Canadian teen-pop releases (1991-1992) preceded her global commercial breakthrough as an alternative-rock artist in 1995.\n\nReleased nine studio albums starting with *Alanis* (1991). Commercial peak: *Jagged Little Pill* (1995), which sold over 33 million copies worldwide on the strength of \"You Oughta Know,\" \"Hand in My Pocket,\" \"Ironic,\" and \"You Learn.\" Subsequent peaks include *Supposed Former Infatuation Junkie* (1998). Eight Grammy Awards. *Jagged Little Pill* was adapted into a Broadway musical that opened in 2019.",
  "albert-lee":
    "English guitarist born December 21, 1943, in Herefordshire. Considered one of the most influential country and rockabilly guitarists in history — known for his hybrid-picking technique and Telecaster mastery. Worked extensively as both a sideman and bandleader.\n\nReleased over a dozen solo studio albums starting with *Hiding* (1979). As a sideman, performed and recorded with Emmylou Harris (Hot Band, 1974-1978), the Crickets, Eric Clapton (1978-1984), Ricky Skaggs, Bill Wyman's Rhythm Kings, and many others. Two Grammy Awards.",
  "alkaline-trio":
    "American punk rock band formed in Chicago in 1996. Lineup: Matt Skiba (vocals/guitar), Dan Andriano (vocals/bass), and various drummers — Derek Grant has been the drummer since 2002. Distinguished by dark/macabre lyrical themes set against melodic pop-punk songcraft.\n\nTen studio albums starting with *Goddamnit* (1998). Best-known releases include *From Here to Infirmary* (2001), *Good Mourning* (2003), *Crimson* (2005), and *Agony & Irony* (2008). Skiba briefly replaced Tom DeLonge in blink-182 (2015-2022) without leaving Alkaline Trio.",
  "all-that-remains":
    "American metalcore band formed in Springfield, Massachusetts in 1998. Long-running lineup: Phil Labonte (vocals), Mike Martin (guitar, since 2007), various bassists, and drummers Jason Costa (since 2011). Original guitarist Oli Herbert co-founded the band; he died of accidental drowning in 2018.\n\nNine studio albums between *Behind Silence and Solitude* (2002) and *Antifragile* (2024). Commercial peak: *The Fall of Ideals* (2006), *Overcome* (2008, featuring \"Two Weeks\"), and *For We Are Many* (2010). The band has been a consistent touring presence in the 2000s and 2010s American metalcore scene.",
  "ammonia":
    "Australian alternative rock band formed in Perth in 1993. Lineup: Dave Johnstone (vocals/guitar), Allan Balmont (drums, died 2017), and Simon Hensworth (bass). Distinguished by their punk-influenced indie-rock approach and minor commercial success in the late-1990s Australian alternative scene.\n\nTwo studio albums: *Mint 400* (1995, the title song was a top-20 Australian hit) and *Eleventh Avenue* (1997). The band dissolved in 1998 amid label conflicts and personal disputes. Balmont died of cancer in 2017.",
  "amon-amarth":
    "Swedish death metal band formed in Tumba in 1992. Long-running lineup: Johan Hegg (vocals), Olavi Mikkonen (guitar), Johan Söderberg (guitar), Ted Lundström (bass), and various drummers — Jocke Wallgren has been the drummer since 2016. Distinguished by Viking-themed lyrics and melodic death metal arrangements.\n\nTwelve studio albums between *Once Sent from the Golden Hall* (1998) and *The Great Heathen Army* (2022). Commercial peak: *Twilight of the Thunder God* (2008), *Surtur Rising* (2011), and *Jomsviking* (2016). The band has been a consistent fixture on European metal festivals; their elaborate stage productions include Viking longboats and other thematic props.",
  "amy-winehouse":
    "English singer-songwriter (1983-2011). Born in Southgate, London. Distinguished by her contralto vocal range and the fusion of jazz, soul, R&B, and reggae that defined her two studio albums.\n\nReleased two studio albums during her lifetime: *Frank* (2003) and *Back to Black* (2006, produced by Mark Ronson and Salaam Remi). *Back to Black* sold over 16 million copies worldwide and won six Grammy Awards in 2008, including Record of the Year (\"Rehab\"), Song of the Year, and Best Pop Vocal Album. Winehouse died of alcohol poisoning in July 2011 at age 27, joining the so-called \"27 Club\" of musicians who died at that age.",
  "andrew-lloyd-webber-tim-rice":
    "British songwriting partnership of composer Andrew Lloyd Webber (born 1948) and lyricist Tim Rice (born 1944). Active as a primary partnership between 1965 and 1980, with periodic later collaborations. Their three major works together effectively reshaped the modern stage musical.\n\nKey collaborations: *Joseph and the Amazing Technicolor Dreamcoat* (1968), *Jesus Christ Superstar* (1970), and *Evita* (1976). The original concept albums for the latter two — released before any stage production — were commercially successful in their own right. Both partners have since pursued separate composing/lyric-writing careers with frequent collaborations (Lloyd Webber with Don Black and Glenn Slater; Rice with Alan Menken, Elton John, and others).",
  "andrew-wk":
    "American singer-songwriter and motivational speaker born Andrew Wilkes-Krier on May 9, 1979, in Stanford, California. Distinguished by a relentlessly positive party-rock persona; his lyrics, public statements, and even motivational speeches consistently center the celebration of partying.\n\nReleased eight studio albums between *I Get Wet* (2001) and *The Wolves* (2024). Best-known releases include *I Get Wet* (2001, featuring \"Party Hard\") and the late-career *You're Not Alone* (2018). Has also hosted *The Andrew W.K. Show* (MTV2, 2003) and the *American Hangover* podcast.",
  "anti-heros":
    "American Oi! punk band formed in Atlanta in 1984. Long-running lineup: Mark Noah (vocals), Joe Winograd (guitar), and various rhythm sections. Distinguished by their working-class, skinhead-adjacent aesthetic and US-Oi! associations.\n\nFour studio albums starting with *That's Right!* (1987). Best-known releases include *Don't Tread on Me* (1989) and *Underneath the Underground* (1995). Released primarily on Link Records and GMM Records. The band has been intermittently active since the early 2000s.",
  "antonio-carlos-jobim":
    "Brazilian composer and pianist (1927-1994). Born in Rio de Janeiro. Among the most influential figures in 20th-century Brazilian music; widely credited as the primary composer in the development of bossa nova alongside lyricist Vinicius de Moraes and guitarist João Gilberto.\n\nReleased over 30 studio albums between *The Composer of Desafinado, Plays* (1963) and *Antonio Brasileiro* (1994). Best-known compositions include \"The Girl from Ipanema,\" \"Desafinado,\" \"Corcovado,\" and \"Wave\" — all jazz and pop standards covered by hundreds of artists. The 1964 album *Getz/Gilberto* (with Stan Getz and João/Astrud Gilberto) won Album of the Year at the 1965 Grammy Awards.",
  "apartment-26":
    "American industrial rock band formed in 1998. Co-founded by guitarist Louie Pastore (later of the Crystal Method) and vocalist Biff Butler (the son of Black Sabbath's Geezer Butler). Style fused industrial rock, electronics, and alternative metal.\n\nTwo studio albums: *Hallucinating* (2000) and *Music for the Massive* (2003). The band toured extensively with Black Sabbath, Korn, and System of a Down in the early 2000s but did not break through commercially. Inactive since the mid-2000s.",
  "apollonia":
    "American singer, dancer, and actress born Patricia Kotero on August 2, 1959, in Santa Monica, California. Best known as the female lead of the 1984 Prince film *Purple Rain* and as the lead singer of the Prince-created girl group Apollonia 6 (the successor to Vanity 6).\n\nReleased one studio album with Apollonia 6: *Apollonia 6* (1984), featuring \"Sex Shooter.\" Pursued an acting career through the 1980s and early 1990s. Continues to perform occasionally and operates motivational-speaking enterprises.",
  "aquarium-rescue-unit":
    "American jam band formed in Athens, Georgia in 1989 by Bruce Hampton (vocals/guitar, died 2017). The classic lineup included Jeff Sipe (drums), Oteil Burbridge (bass), Jimmy Herring (guitar), Matt Mundy (mandolin), and Count M'Butu (percussion). Considered foundational to the Southern jam-band scene that produced Widespread Panic, Phish, and others.\n\nThree studio albums between *Aquarium Rescue Unit* (1992) and *In a Perfect World* (1994). Hampton died on stage at his 70th birthday concert in 2017, just minutes after performing. Surviving members went on to dozens of significant projects including the Allman Brothers Band, Phil Lesh and Friends, Dead & Company, and Widespread Panic.",
  "ar-the-rockin-ricochettes":
    "American rockabilly revival act, active in the early-1980s rockabilly scene. The \"Rock On & Carl's Rockabilly Roll\" 7\" single (1982) is the most-circulated artifact of their output. Obscure outside of dedicated rockabilly-revival collectors.",
  "arch-enemy":
    "Swedish melodic death metal band formed in Halmstad in 1995 by guitarist Michael Amott. Vocalists: Johan Liiva (1995-2000), Angela Gossow (2000-2014), and Alissa White-Gluz (since 2014). The band's vocalist change to a woman in 2000 — and again in 2014 — was notable in a male-dominated genre.\n\nEleven studio albums starting with *Black Earth* (1996). Commercial peak: *Wages of Sin* (2001), *Anthems of Rebellion* (2003), and *Doomsday Machine* (2005). Amott's brother Christopher Amott has been in and out of the band on second guitar.",
  "architects":
    "English metalcore band formed in Brighton in 2004. Long-running lineup centered on Sam Carter (vocals, since 2007) and Dan Searle (drums). Guitarist Tom Searle (Dan's twin brother) was the band's primary songwriter until his 2016 death from cancer.\n\nEleven studio albums between *Nightmares* (2006) and *The Sky, the Earth & All Between* (2025). Commercial peak: *Lost Forever // Lost Together* (2014), *All Our Gods Have Abandoned Us* (2016, the last album Tom Searle wrote), and *Holy Hell* (2018, addressing Tom's death). The band has continued with Josh Middleton on guitar.",
  "arlo-guthrie":
    "American folk singer-songwriter born July 10, 1947, in Coney Island, New York. Son of Woody Guthrie. Distinguished by his story-song approach — the most famous example being the 18-minute \"Alice's Restaurant Massacree\" (1967), an anti-Vietnam-War talking-blues epic that became a Thanksgiving radio tradition.\n\nReleased over 20 studio albums starting with *Alice's Restaurant* (1967). Other key releases include *Running Down the Road* (1969), *Hobo's Lullaby* (1972, featuring his hit cover of Steve Goodman's \"City of New Orleans\"), and *Last of the Brooklyn Cowboys* (1973). Officially retired from touring in 2020 due to health issues.",
  "arrested-development":
    "American hip-hop group formed in Atlanta in 1988. Original lineup: Speech (Todd Thomas, vocals), Aerle Taree (vocals), Headliner (Tim Barnwell, DJ), Rasa Don (drums), Montsho Eshe (dancer/vocals), and Baba Oje (spiritual elder). Among the foundational acts of alternative hip-hop alongside De La Soul and A Tribe Called Quest.\n\nNine studio albums between *3 Years, 5 Months and 2 Days in the Life Of...* (1992) and *Don't Fight Your Demons* (2020). Commercial breakthrough: the debut album sold over 5 million copies and produced the Grammy-winning singles \"Tennessee\" and \"People Everyday.\" Won the 1993 Grammy for Best New Artist — the first hip-hop act to do so.",
  "assorted-jelly-beans":
    "American punk rock band formed in Riverside, California in 1990. Long-running lineup centered on Brian Sheerin (vocals/guitar). Closely associated with Kung Fu Records, the label founded by the Vandals' Joe Escalante.\n\nThree studio albums between *Assorted Jelly Beans* (1996) and *Strung Out* (1999). Released primarily on Kung Fu Records and Big Deal. The band has been intermittently active since the early 2000s.",
  "audioslave":
    "American rock supergroup formed in Los Angeles in 2001 by Chris Cornell (vocals, formerly of Soundgarden, died 2017) and the three remaining members of Rage Against the Machine — Tom Morello (guitar), Tim Commerford (bass), and Brad Wilk (drums) — after Zack de la Rocha's 2000 departure.\n\nThree studio albums: *Audioslave* (2002), *Out of Exile* (2005), and *Revelations* (2006). All three reached #1 on the US rock chart. The band dissolved in 2007 when Cornell returned to a reunited Soundgarden and the other three reunited with de la Rocha as Rage Against the Machine. A single 2017 reunion performance preceded Cornell's death by months.",
  "august-burns-red":
    "American metalcore band formed in Lancaster, Pennsylvania in 2003. Long-running lineup: Jake Luhrs (vocals, since 2006), JB Brubaker (guitar), Brent Rambler (guitar), Dustin Davidson (bass), and Matt Greiner (drums). Distinguished by their technical approach and Christian-aligned lyrical content.\n\nNine studio albums starting with *Thrill Seeker* (2005). Commercial peak: *Constellations* (2009), *Leveler* (2011), *Rescue & Restore* (2013), and *Found in Far Away Places* (2015). The 2017 album *Phantom Anthem* was the band's first to be nominated for a Grammy.",
  "avenged-sevenfold":
    "American heavy metal band formed in Huntington Beach, California in 1999. Long-running lineup: M. Shadows (Matt Sanders, vocals), Synyster Gates (Brian Haner Jr., guitar), Zacky Vengeance (Zachary Baker, guitar), and Johnny Christ (bass). Original drummer The Rev (James Sullivan) died of an accidental overdose in 2009; Brooks Wackerman has been the band's drummer since 2015.\n\nEight studio albums starting with *Sounding the Seventh Trumpet* (2001). Commercial peak: *City of Evil* (2005, featuring \"Bat Country\"), the self-titled fifth album (2007), *Nightmare* (2010, written after The Rev's death), and *Hail to the King* (2013). Released the experimental *Life Is but a Dream...* in 2023.",
  "be-taylor-group":
    "American rock band led by B.E. Taylor (William Berton Edward Taylor, 1953-2016). The Pittsburgh-area band gained regional success in the early 1980s before B.E. Taylor transitioned to a long-running Christmas-concert career.\n\nThe B.E. Taylor Group's primary release was *Innermission* (1984), featuring the moderate hit \"Vitamin L.\" The band continued to release material into the 1990s under the B.E. Taylor Group and B.E. Taylor names. Taylor died of brain cancer in 2016; tribute concerts featuring his backing band have continued.",
  "babes-in-toyland":
    "American rock band formed in Minneapolis in 1987. Lineup: Kat Bjelland (vocals/guitar), Lori Barbero (drums), and various bassists — Maureen Herman was the longest-serving (1992-1997, 2014-2015). Foundational to the riot grrrl movement, although Bjelland generally rejected the label.\n\nThree studio albums: *Spanking Machine* (1990), *Fontanelle* (1992), and *Nemesisters* (1995). Best-known releases include *To Mother* (1991) and the major-label debut *Fontanelle* (produced by Lee Ranaldo of Sonic Youth). The band dissolved in 2001 and reunited in 2014-2015. Bjelland co-founded Babes in Toyland and the earlier band Pagan Babies with Courtney Love, who took the name briefly before forming Hole.",
  "baby-gopal":
    "American alternative rock band formed in the mid-1990s. Style draws on indie rock, post-grunge, and alternative pop. Limited national exposure; primarily regional act associated with the Mid-Atlantic college-radio circuit of the late 1990s and early 2000s.",
  "bachman-turner-overdrive":
    "Canadian rock band formed in Winnipeg in 1973. Original lineup: Randy Bachman (vocals/guitar, formerly of the Guess Who), Robbie Bachman (drums, his brother), Fred Turner (vocals/bass), and Tim Bachman (guitar, also Randy's brother). The band's name is often abbreviated as BTO.\n\nEight studio albums between *Bachman-Turner Overdrive* (1973) and *Bachman-Turner Overdrive II* (1973), continuing through *Rock n' Roll Nights* (1979). Commercial peak: *Not Fragile* (1974, featuring the #1 single \"You Ain't Seen Nothing Yet\") and *Four Wheel Drive* (1975). The band has reunited periodically with various lineups since.",
  "bastille":
    "English rock band formed in London in 2010. Lineup: Dan Smith (vocals), Will Farquarson (bass/guitar), Kyle Simmons (keyboards), and Chris \"Woody\" Wood (drums). Distinguished by Smith's high tenor and the band's combination of synth-pop, alternative rock, and orchestral textures.\n\nFive studio albums between *Bad Blood* (2013) and *& (Ampersand)* (2024). Commercial peak: *Bad Blood* (featuring \"Pompeii,\" one of the best-selling UK singles of 2013) and *Wild World* (2016). The band has remained active continuously since formation.",
  "beck-bogert-appice":
    "English-American hard rock supergroup formed in 1972. Trio of Jeff Beck (guitar/vocals, formerly of the Yardbirds), Tim Bogert (bass/vocals, formerly of Vanilla Fudge and Cactus), and Carmine Appice (drums/vocals, also of Vanilla Fudge and Cactus). Beck had attempted to form a band with Bogert and Appice as early as 1969 before they joined Cactus.\n\nReleased one studio album: the self-titled debut (1973), featuring a cover of Stevie Wonder's \"Superstition\" (which Wonder had originally written for Beck). The trio dissolved in 1974 amid creative differences. Beck pursued a more jazz-fusion-oriented solo career thereafter.",
  "bee-gees":
    "Australian-English pop group formed in Manchester, England in 1958 by brothers Barry Gibb (vocals/guitar), Robin Gibb (vocals, died 2012), and Maurice Gibb (vocals/bass, died 2003). Among the best-selling musical acts in history, with estimated worldwide sales exceeding 220 million units.\n\nTwenty-two studio albums between *The Bee Gees Sing and Play 14 Barry Gibb Songs* (1965) and *This Is Where I Came In* (2001). Career peaks include their 1960s ballad era (*Bee Gees' 1st*, 1967), their disco peak via the *Saturday Night Fever* soundtrack (1977, with the singles \"Stayin' Alive,\" \"How Deep Is Your Love,\" and \"Night Fever\"), and their late-career second act starting with *E.S.P.* (1987). Inducted into the Rock and Roll Hall of Fame in 1997.",
  "behemoth":
    "Polish extreme metal band formed in Gdańsk in 1991. Long-running lineup centered on Nergal (Adam Darski, vocals/guitar). The band's style evolved from black metal in the 1990s into a death metal-black metal hybrid by the late 2000s.\n\nTwelve studio albums starting with *Sventevith (Storming Near the Baltic)* (1995). Commercial peak: *Demigod* (2004), *The Apostasy* (2007), and *The Satanist* (2014). Nergal survived leukemia in 2010; the subsequent album *The Satanist* was widely regarded as a creative peak following his recovery.",
  "bla-fleck-and-the-flecktones":
    "American fusion band formed in 1988 by banjo virtuoso Béla Fleck. Lineup: Fleck (banjo), Howard Levy (harmonica/keyboards, 1988-1992, 2009-2011), Victor Wooten (bass), and Roy \"Future Man\" Wooten (drums/Synthaxe Drumitar). Wooten's brother is also a virtuoso bassist.\n\nTwelve studio albums between *Béla Fleck and the Flecktones* (1990) and *Rocket Science* (2011, reuniting the original four-member lineup). Fifteen Grammy Awards across the band's career. Style fuses bluegrass, jazz, funk, and world music; Fleck has pursued numerous parallel projects with Edgar Meyer, Chick Corea, and others.",
  "belly":
    "American alternative rock band formed in Providence, Rhode Island in 1991 by Tanya Donelly (vocals/guitar, formerly of Throwing Muses and the Breeders). Lineup also included Tom Gorman (guitar), Chris Gorman (drums), and Fred Abong (bass, 1991-1993, replaced by Gail Greenwood).\n\nThree studio albums between *Star* (1993) and *Dove* (2018). *Star* sold over 1 million copies in the US on the strength of \"Feed the Tree\" and \"Gepetto.\" The band split in 1996 and reunited in 2016 for the *Dove* album and accompanying tour.",
  "ben-folds-five":
    "American rock trio formed in Chapel Hill, North Carolina in 1993 by Ben Folds (vocals/piano), Robert Sledge (bass/vocals), and Darren Jessee (drums/vocals). Distinguished by Folds's prominent piano playing and the absence of a guitar — Folds described the band as \"punk rock for sissies.\"\n\nFour studio albums between *Ben Folds Five* (1995) and *The Sound of the Life of the Mind* (2012). Commercial peak: *Whatever and Ever Amen* (1997, featuring \"Brick\"). The band dissolved in 2000; Folds pursued a successful solo career before the trio reunited in 2011 for *The Sound of the Life of the Mind*.",
  "ben-harper-the-innocent-criminals":
    "American rock band led by singer-songwriter and guitarist Ben Harper (born October 28, 1969, in Pomona, California). The Innocent Criminals backing band has been Harper's primary touring and recording unit since 1995. Long-running members include Juan Nelson (bass, died 2021), Oliver Charles (drums), and Leon Mobley (percussion).\n\nReleased ten studio albums between *Welcome to the Cruel World* (1994) and *Bloodline Maintenance* (2022). Best-known releases include *Burn to Shine* (1999), *Diamonds on the Inside* (2003), and *Both Sides of the Gun* (2006). Harper has also pursued projects with Ellen Harper (his mother), Charlie Musselwhite, and the band Relentless7.",
  "berlin":
    "American synth-pop band formed in Orange County, California in 1979. Long-running lineup centered on Terri Nunn (vocals) and John Crawford (bass). Other key members included David Diamond (keyboards) and Rick Olsen (guitar).\n\nFive studio albums between *Pleasure Victim* (1982) and *Animal* (2013). Commercial peak: *Love Life* (1984), the soundtrack single \"Take My Breath Away\" from *Top Gun* (1986, which won the Academy Award for Best Original Song), and *Count Three & Pray* (1986). The band dissolved in 1987 and reformed under Nunn in the late 1990s.",
  "big-d-and-the-kids-table":
    "American ska-punk band formed in Boston in 1995. Long-running lineup centered on David McWane (vocals). Distinguished by the band's incorporation of traditional ska and rocksteady alongside punk-influenced material.\n\nNine studio albums starting with *Shot by Lammi* (1997). Best-known releases include *Strictly Rude* (2007), *Fluent in Stroll* (2009), and *Stomp* (2013). Released primarily on Side One Dummy Records.",
  "big-head-todd-and-the-monsters":
    "American rock band formed in Boulder, Colorado in 1986. Long-running lineup: Todd Park Mohr (vocals/guitar), Brian Nevin (drums), and Rob Squires (bass) — all members since formation. Style draws on blues-rock, alternative rock, and Americana.\n\nTwelve studio albums between *Another Mayberry* (1989) and *New World Arisin'* (2017). Commercial peak: *Sister Sweetly* (1993, multi-platinum, featuring \"Bittersweet\") and *Strategem* (1994). The band has been continuously active since formation and tours regularly.",
  "big-mountain":
    "American reggae band formed in San Diego in 1986. Long-running lineup: Quino McWhinney (vocals), Lance Rhodes (drums), and various other members. Considered one of the best-known American reggae acts to emerge alongside Sublime in the late 1980s and early 1990s.\n\nReleased multiple studio albums starting with *Wake Up* (1992). Commercial peak: their 1994 reggae cover of Peter Frampton's \"Baby, I Love Your Way,\" featured on the *Reality Bites* soundtrack. Subsequent releases include *Resistance* (1995) and *Free Up* (1997). The band has continued to tour and record sporadically.",
  "bigwig":
    "American punk rock band formed in Kearny, New Jersey in 1995. Long-running lineup: Tom Petta (vocals/guitar), Joshua Brown (guitar), Dan Brown (bass, his brother), and various drummers. Closely associated with Kung Fu Records and the late-1990s skate-punk scene.\n\nThree studio albums between *Unmerry Melodies* (1997) and *Stay Asleep* (2005). Best-known releases include *Invitation to Tragedy* (2001), which featured the single \"Sore Loser.\"",
  "bill-wyman":
    "English bassist born William George Perks on October 24, 1936, in Lewisham, London. The original bassist for the Rolling Stones (1962-1993). Left the band to pursue solo and side projects, becoming one of the few high-profile rock musicians to retire from a successful band by choice.\n\nReleased multiple solo studio albums starting with *Monkey Grip* (1974). Formed Bill Wyman's Rhythm Kings (1997-present), a revolving-membership blues and R&B revue. Inducted into the Rock and Roll Hall of Fame with the Rolling Stones in 1989.",
  "billie-myers":
    "British singer-songwriter born December 12, 1971, in Coventry, England. Best known for the 1997 single \"Kiss the Rain,\" a top-20 hit in multiple countries from her debut album.\n\nReleased three studio albums: *Growing, Pains* (1997), *Vertigo* (2000), and *Tea & Sympathy* (2008). Subsequent releases have been independent EPs and singles. Pursued a parallel acting career in the 2000s.",
  "billy-ocean":
    "Trinidadian-British singer born Leslie Sebastian Charles on January 21, 1950, in Fyzabad, Trinidad. Among the most commercially successful Black British performers of the 1980s.\n\nReleased eleven studio albums between *Billy Ocean* (1976) and *One World* (2020). Commercial peak: *Suddenly* (1984, featuring \"Caribbean Queen (No More Love on the Run)\") and *Love Zone* (1986, featuring \"There'll Be Sad Songs (To Make You Cry)\" and \"When the Going Gets Tough, the Tough Get Going\"). Won the 1985 Grammy for Best Male R&B Vocal Performance.",
  "black-lab":
    "American alternative rock band formed in San Francisco in 1994 by Paul Durham (vocals/guitar). Other members have rotated; Durham is the only continuous member.\n\nReleased seven studio albums between *Your Body Above Me* (1997) and *See the Sun* (2018). Best-known release: the single \"Time Ago\" from *Your Body Above Me*. Has placed music in numerous film and television soundtracks, including *Spider-Man 2* (2004) and the TV series *Roswell*.",
  "black-star":
    "American hip-hop duo of Mos Def (Yasiin Bey) and Talib Kweli, formed in Brooklyn in 1997. Both members were prominent figures in the late-1990s alternative hip-hop scene; the duo's name references the Marcus Garvey-founded shipping company.\n\nTwo studio albums: *Mos Def & Talib Kweli Are Black Star* (1998) and *No Fear of Time* (2022, released exclusively on Luminary podcast platform). The 1998 debut became a critical landmark of underground hip-hop. Both members have continued extensive solo careers.",
  "black-veil-brides":
    "American rock band formed in Cincinnati in 2006. Lineup: Andy Biersack (vocals), Jake Pitts (guitar), Jinxx (guitar/violin), Ashley Purdy (bass, 2009-2020), and Christian \"CC\" Coma (drums). Distinguished by their theatrical glam-meets-emo presentation, drawing visual references from Mötley Crüe and KISS.\n\nSeven studio albums starting with *We Stitch These Wounds* (2010). Commercial peak: *Set the World on Fire* (2011), *Wretched and Divine: The Story of the Wild Ones* (2013), and the self-titled fourth album (2014). Biersack also pursues a solo career as Andy Black.",
  "blackberry-smoke":
    "American Southern rock band formed in Atlanta in 2000. Lineup: Charlie Starr (vocals/guitar), Paul Jackson (guitar), Brit Turner (drums, died 2024), Richard Turner (bass, his brother), and Brandon Still (keyboards, since 2009). Style draws on Southern rock, country, and Allman Brothers-style guitar interplay.\n\nEight studio albums starting with *Bad Luck Ain't No Crime* (2003). Best-known releases include *The Whippoorwill* (2012), *Find a Light* (2018), and *You Hear Georgia* (2021). The band has been continuously active since formation. Drummer Brit Turner died in March 2024.",
  "blaster-the-rocketman":
    "American ska-punk band associated with the late-1990s Christian punk scene. Style draws on third-wave ska, pop-punk, and horn-driven punk rock. Limited national exposure outside the Tooth & Nail Records-adjacent Christian-music scene.\n\nReleased multiple studio albums in the late 1990s and early 2000s. Best-known release: *The Monster Who Ate Jesus* (1998).",
  "blessid-union-of-souls":
    "American pop-rock band formed in Cincinnati in 1993 by Eliot Sloan (vocals). Long-running lineup also included C.P. Roth (keyboards) and Jeff Pence (guitar).\n\nReleased six studio albums between *Home* (1995) and *Closer to the Edge* (2017). Commercial peak: *Home* (1995, featuring the top-10 single \"I Believe\") and *Blessid Union of Souls* (1997, featuring \"I Wanna Be There\" and \"Light in Your Eyes\"). The band has continued to record and tour intermittently.",
  "blessthefall":
    "American metalcore band formed in Phoenix in 2004. Long-running lineup: Beau Bokan (vocals, since 2008), Eric Lambert (guitar), Jared Warth (bass), and various drummers. Original vocalist Craig Mabbitt was fired in 2008 (later forming Escape the Fate).\n\nSix studio albums between *His Last Walk* (2007) and *Hard Feelings* (2018). Best-known releases include *Witness* (2009) and *Awakening* (2011, featuring \"Promised Ones\"). Released primarily on Fearless Records.",
  "blood-for-blood":
    "American hardcore band formed in Boston in 1994. Long-running lineup centered on guitarist Erick \"Buddha\" Medina (died 2007) and vocalist Rob \"Lingo\" Lind. Style fused hardcore punk with metal and blue-collar working-class imagery.\n\nFour studio albums between *Spit My Last Breath* (1997) and *Outlaw Anthems* (2002). Best-known releases include *Revenge on Society* (1998) and *Livin' in Exile* (2000). Medina's 2007 death ended the band; surviving members have performed periodic memorial shows.",
  "bloodhound-gang":
    "American comedy rock band formed in Trappe, Pennsylvania in 1988. Long-running lineup: Jimmy Pop (Jimmy Franks, vocals), Lupus Thunder (guitar), Evil Jared Hasselhoff (bass), and various other members. Distinguished by deliberately juvenile, scatological, and offensive lyrics.\n\nFive studio albums between *Use Your Fingers* (1995) and *Hard-Off!* (2015). Commercial peak: *Hooray for Boobies* (1999, featuring the international hit \"The Bad Touch\"). The band has been on extended hiatus since the mid-2010s.",
  "bloodline":
    "American rock band formed in 1994 by sons of famous musicians: Joe Bonamassa (guitar, son of Joe Bonamassa Sr.), Erin Davis (drums, son of Miles Davis), Berry Oakley Jr. (bass, son of Berry Oakley of the Allman Brothers), Lou Segreti (vocals, son of label exec/manager Stevie Sands), and Waylon Krieger (guitar, son of the Doors' Robby Krieger).\n\nReleased one studio album: the self-titled debut (1994). The band dissolved shortly after; Bonamassa launched a successful solo blues-rock career that has become one of the most commercially successful in modern blues.",
  "blue-yster-cult":
    "American rock band formed in Stony Brook, New York in 1967. Long-running classic lineup: Eric Bloom (vocals/guitar/keyboards), Buck Dharma (Donald Roeser, guitar/vocals), Allen Lanier (guitar/keyboards, died 2013), Joe Bouchard (bass/vocals, 1969-1986), and Albert Bouchard (drums/vocals, 1967-1981). Often credited as one of the originators of heavy metal alongside Black Sabbath and Deep Purple.\n\nFifteen studio albums between *Blue Öyster Cult* (1972) and *Ghost Stories* (2024). Best-known releases include *Agents of Fortune* (1976, featuring \"(Don't Fear) The Reaper\"), *Spectres* (1977), and *Fire of Unknown Origin* (1981). The band has been continuously active since formation despite many lineup changes.",
};

async function main() {
  const dryRun = process.argv.includes("--dry-run");
  const force = process.argv.includes("--force");
  const { containers } = await import("../lib/cosmos");
  const { getStoredArtist } = await import("../lib/artists");

  let written = 0;
  let skipped = 0;
  let missing = 0;

  for (const [slug, description] of Object.entries(DESCRIPTIONS)) {
    const existing = await getStoredArtist(slug);
    if (!existing) {
      console.log(`✗ ${slug}: no stored doc found`);
      missing += 1;
      continue;
    }
    if (existing.description && !force) {
      console.log(`↷ ${slug}: already has description — skipping`);
      skipped += 1;
      continue;
    }
    if (dryRun) {
      console.log(`◌ ${slug}: would write ${description.length} chars`);
      written += 1;
      continue;
    }
    const updated = {
      ...existing,
      description,
      updatedAt: new Date().toISOString(),
    };
    await containers.artists.item(slug, slug).replace(updated);
    console.log(`✓ ${slug}: ${description.length} chars`);
    written += 1;
  }

  console.log(`\nDone. written=${written} skipped=${skipped} missing=${missing}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
