import { config as loadEnv } from "dotenv";
loadEnv({ path: ".env.local" });

const DESCRIPTIONS: Record<string, string> = {
  "michael-bolton":
    "American singer-songwriter born Michael Bolotin on February 26, 1953, in New Haven, Connecticut. Began his career as a hard-rock vocalist with the bands Blackjack (1979-1980) and a solo career under his birth name before reinventing himself as an adult-contemporary balladeer in the late 1980s.\n\nReleased over a dozen studio albums. Commercial peak: *Soul Provider* (1989, featuring \"How Am I Supposed to Live Without You\") and *Time, Love & Tenderness* (1991, featuring \"When a Man Loves a Woman\"). Two Grammy Awards for Best Pop Male Vocal Performance. Has continued to record adult-contemporary, swing, and Italian-language albums.",
  "michael-viners-incredible-bongo-band":
    "American studio group assembled by music executive Michael Viner (1944-2009) in 1972. Best known for the heavily-sampled instrumental \"Apache\" (1973), whose drum break has been used in hundreds of hip-hop tracks since its rediscovery by DJ Kool Herc and the early Bronx hip-hop DJs of the mid-1970s.\n\nReleased two studio albums: *Bongo Rock* (1973) and *The Return of the Incredible Bongo Band* (1974). The break from \"Apache\" is among the most-sampled drum breaks in recorded music history. Drummer Jim Gordon and percussionist King Errisson were the principal players.",
  "mickey-hart":
    "American percussionist born September 11, 1943, in Brooklyn, New York. Member of the Grateful Dead (1967-1971, 1974-1995). After the Dead, has explored world percussion and ethnomusicology, frequently collaborating with the Smithsonian Folkways archive.\n\nReleased numerous solo albums starting with *Rolling Thunder* (1972). Won three Grammy Awards including Best World Music Album for *Planet Drum* (1991), the first Grammy in that category. Has performed in subsequent Grateful Dead-related projects including The Other Ones, The Dead, and Dead & Company. Inducted into the Rock and Roll Hall of Fame as a member of the Grateful Dead in 1994.",
  "mike-ness":
    "American singer-songwriter and guitarist born Michael James Ness on April 3, 1962, in Lynn, Massachusetts. Founding member, lead vocalist, and primary songwriter for Social Distortion (1978-present). Distinguished by his country-influenced punk songwriting and his rockabilly-meets-punk-rock visual aesthetic.\n\nReleased two solo studio albums: *Cheating at Solitaire* (1999) and *Under the Influences* (1999), the latter a covers album. Underwent treatment for tonsil cancer in 2024. Continues to lead Social Distortion.",
  "mike-patton":
    "American singer, songwriter, and composer born January 27, 1968, in Eureka, California. Lead vocalist for Faith No More (1989-1998, 2009-present), Mr. Bungle (1985-2000, 2019-present), Tomahawk, Fantômas, and many other projects. Among the most stylistically versatile vocalists in modern rock — comfortable across heavy metal, funk, jazz, lounge, and experimental music.\n\nOver 40 albums across his various projects. Co-founder of the Ipecac Recordings label (1999, with Greg Werckman). His six-octave vocal range and aggressive use of extended vocal techniques (screams, growls, falsetto, scatting) have influenced a generation of singers.",
  "mike-watt-the-black-gang":
    "Touring band led by American bassist Mike Watt (b. December 20, 1957, Portsmouth, Virginia), formerly of Minutemen and fIREHOSE. The Black Gang accompanied Watt on his 1995 solo album *Ball-Hog or Tugboat?* tour, with a lineup including Nels Cline (guitar) and Stephen Hodges (drums).\n\nWatt subsequently led various other touring configurations including the Pair of Pliers, the Secondmen, and the Missingmen. He also joined the Stooges in 2003 for their reunion lineup. Active in the broader Los Angeles improvisational and punk scenes.",
  "miles-davis":
    "American jazz trumpeter, bandleader, and composer born May 26, 1926, in Alton, Illinois; died September 28, 1991. Among the most influential figures in 20th-century music; instrumental in multiple jazz revolutions including bebop, cool jazz, hard bop, modal jazz, and jazz fusion.\n\nReleased over 50 studio albums. Landmark releases: *Birth of the Cool* (1957, compiled from 1949-1950 sessions), *Kind of Blue* (1959, the best-selling jazz album of all time), *Sketches of Spain* (1960), *In a Silent Way* (1969), *Bitches Brew* (1970), and *Tutu* (1986). His bands launched the careers of John Coltrane, Cannonball Adderley, Herbie Hancock, Wayne Shorter, Chick Corea, John McLaughlin, and many others. Inducted into the Rock and Roll Hall of Fame in 2006.",
  "milli-vanilli":
    "German-French R&B duo formed in Munich in 1988. Lineup: Fab Morvan (b. 1966) and Rob Pilatus (1965-1998), neither of whom actually sang on the recordings credited to them. The actual vocals were performed by uncredited session singers John Davis, Brad Howell, and Charles Shaw.\n\nReleased *All or Nothing* (1988, retitled *Girl You Know It's True* for the US market). Won the 1990 Grammy for Best New Artist, which was revoked later that year after the lip-sync deception was revealed — the only Grammy ever rescinded. Pilatus died of a drug overdose in 1998 at age 32.",
  "mindy-smith":
    "American country and folk singer-songwriter born July 27, 1972, in Long Island, New York; based in Nashville. Distinguished by her crystalline soprano and acoustic-driven songwriting.\n\nReleased four studio albums between *One Moment More* (2004, featuring the title track and her acclaimed cover of Dolly Parton's \"Jolene\") and *Mindy Smith* (2012). Dolly Parton sang on the *One Moment More* recording of \"Jolene.\"",
  "miri-benari":
    "Israeli-American violinist born November 4, 1978, in Tel Aviv. Distinguished by her work bridging classical violin technique with hip-hop and R&B production, frequently collaborating with Kanye West, Wyclef Jean, Jay-Z, and Alicia Keys.\n\nReleased *The Song of the Promised Land* (2005) and *Artists Series* (2007). Won a Grammy as featured violinist on Kanye West's \"Jesus Walks\" (2004). Has performed at the United Nations, the Vatican, and the Apollo Theater.",
  "moby":
    "American musician, songwriter, and producer born Richard Melville Hall on September 11, 1965, in New York City. Distinguished by his eclectic electronic music drawing on house, ambient, breakbeat, and downtempo influences and frequent vegetarian/animal-rights advocacy.\n\nReleased over a dozen studio albums starting with *Moby* (1992). Commercial peak: *Play* (1999, a sleeper hit that eventually sold over 12 million copies worldwide, every track licensed for film/TV/advertising). Subsequent peaks: *18* (2002) and *Hotel* (2005). Released the autobiographical *Porcelain* (2016) and *Then It Fell Apart* (2019).",
  "mojo-nixon":
    "American psychobilly singer-songwriter born Neill Kirby McMillan Jr. on August 2, 1957, in Chapel Hill, North Carolina; died February 7, 2024. Distinguished by his irreverent novelty songs and his long-running role as a SiriusXM DJ on the Outlaw Country channel.\n\nReleased 11 studio albums (often with washboard player Skid Roper) between *Mojo Nixon & Skid Roper* (1985) and *Whiskey Rebellion* (2009). Best-known songs include \"Elvis Is Everywhere\" (1987), \"Don Henley Must Die\" (1990), and \"Burn Down the Malls\" (1989). Died at age 66 of a cardiac event while on the Outlaw Country Cruise.",
  "monica":
    "American R&B singer born Monica Denise Arnold on October 24, 1980, in College Park, Georgia. Distinguished by her smooth contralto and her long-running career stretching from her 1995 debut to the present.\n\nReleased nine studio albums starting with *Miss Thang* (1995). Commercial peak: *The Boy Is Mine* (1998, featuring the Brandy duet title track, which topped the Billboard Hot 100 for 13 weeks). Three Grammy Awards including Best R&B Performance by a Duo or Group for \"The Boy Is Mine\" (1999).",
  "monster-voodoo-machine":
    "Canadian industrial metal band formed in Toronto in 1989. Long-running lineup centered on Adam Sewell (vocals/programming). Style draws on industrial metal in the vein of Ministry, Pitchshifter, and Fear Factory.\n\nReleased three studio albums between *Suffersystem* (1993) and *Defcon Zero* (2009). Toured extensively in the 1990s including support slots for Sepultura and KMFDM. The band has been intermittently active.",
  "monty-python":
    "British comedy troupe formed in 1969. Lineup: Graham Chapman (1941-1989), John Cleese (b. 1939), Terry Gilliam (b. 1940), Eric Idle (b. 1943), Terry Jones (1942-2020), and Michael Palin (b. 1943). Best known for the TV series *Monty Python's Flying Circus* (BBC, 1969-1974) and the films *And Now for Something Completely Different* (1971), *Monty Python and the Holy Grail* (1975), *Life of Brian* (1979), and *The Meaning of Life* (1983).\n\nReleased numerous comedy albums including *Monty Python's Previous Record* (1972), *Matching Tie and Handkerchief* (1973), and *Live at Drury Lane* (1974). Eric Idle wrote and composed the stage musical *Spamalot* (2005, Tony Award for Best Musical), adapting *Holy Grail* for Broadway. The troupe reunited briefly in 2014 for the *Monty Python Live (Mostly)* O2 Arena shows.",
  "moon-zappa":
    "American actress and writer born Moon Unit Zappa on September 28, 1967, in New York City. Eldest child of Frank and Gail Zappa. Best known for her 1982 vocal performance on her father's hit single \"Valley Girl,\" delivering the satirical \"Like, oh my god\" monologue that became a defining text of 1980s teen culture.\n\nHas pursued an acting and writing career rather than a primary music career, including the novels *America the Beautiful* (2001) and *Earth to Moon* (2024, a memoir about growing up in the Zappa household).",
  "morlocks":
    "American garage rock band formed in San Diego in 1984. Long-running lineup centered on Leighton Koizumi (vocals). Style draws on 1960s-style garage rock and proto-punk in the vein of the Chocolate Watchband and the Seeds.\n\nReleased the influential *Emerge* (1985) and several subsequent albums after various reunions and lineup changes. Koizumi later formed the Gravedigger V and the Hangee V. The band remains intermittently active.",
  "morris-day":
    "American singer and actor born Morris Day on December 13, 1956, in Springfield, Illinois; raised in Minneapolis. Lead vocalist for the Time (also styled Morris Day and the Time), the Prince-affiliated funk band formed in 1981. Distinguished by his comic stage persona, choreographed routines with valet/sidekick Jerome Benton, and slick frontman style.\n\nReleased three solo studio albums between *The Color of Success* (1985) and *Guaranteed* (1992). Co-starred with Prince in *Purple Rain* (1984) and *Graffiti Bridge* (1990). Continues to tour with the Time.",
  "mosquito":
    "Generic band name used by multiple unrelated acts. The Mosquito most commonly referenced is the American post-hardcore band from the late 1990s San Francisco scene. Other Mosquitos include the Brazilian indie-pop duo (Juju Stulbach, Chris Root) active in the 2000s.\n\nLimited public documentation distinguishes the specific Mosquito referenced in a typical setlist or record credit; the name has been used by garage, indie, and electronic acts across multiple decades.",
  "motion-city-soundtrack":
    "American rock band formed in Minneapolis in 1997. Long-running lineup: Justin Pierre (vocals), Joshua Cain (guitar), Matt Taylor (bass), Tony Thaxton (drums), and Jesse Johnson (Moog synthesizer). Distinguished by their pop-punk-meets-power-pop sound enhanced by prominent Moog synthesizer.\n\nSix studio albums between *I Am the Movie* (2003) and *Panic Stations* (2015). Commercial peak: *Commit This to Memory* (2005, produced by Mark Hoppus, featuring \"Everything Is Alright\") and *Even If It Kills Me* (2007). The band reunited in 2019 after a 2016 hiatus.",
  "mountain":
    "American hard rock band formed in Long Island, New York in 1969. Lineup historically centered on Leslie West (guitar/vocals, 1945-2020) and Felix Pappalardi (bass/vocals/producer, 1939-1983), with drummer Corky Laing (joined 1969) and various keyboardists. Pappalardi had previously produced Cream's *Disraeli Gears* and *Wheels of Fire*.\n\nReleased six studio albums during their initial run between *Climbing!* (1970) and *Avalanche* (1974). Best-known recording: \"Mississippi Queen\" (1970). Performed at the original Woodstock festival in 1969, only their fourth show as a band. Pappalardi was killed by his wife in 1983; West continued the band intermittently until his death in 2020.",
  "mr-ness":
    "Stage name used by Anthony \"Ness\" Cornelius on the original 1979 Sugar Hill Records recordings of Grandmaster Flash & The Furious Five. Cornelius later went by Scorpio. The Mr. Ness/Scorpio credit appears on early classics including \"The Message\" (1982) and \"Superrappin'\" (1979).\n\nNot to be confused with Mike Ness of Social Distortion. The Furious Five was inducted into the Rock and Roll Hall of Fame as part of Grandmaster Flash and the Furious Five in 2007.",
  "mtx":
    "Same artist as the Mr. T Experience — abbreviated credit variation. American pop-punk band formed in Berkeley, California in 1985. Long-running lineup centered on Frank Portman (vocals/guitar, also known as Dr. Frank). Distinguished by their literate, nerd-coded songwriting drawing on Buddy Holly and the Buzzcocks.\n\nReleased over a dozen studio albums between *Everybody's Entitled to Their Own Opinion* (1986) and *Mtx Forever* (2020). Critical peak: *Love Is Dead* (1996). Portman is also a young-adult novelist (*King Dork*, 2006).",
  "mu330":
    "American ska-punk band formed in St. Louis, Missouri in 1988. Long-running lineup centered on Dan Potthast (vocals/guitar). Distinguished by their hyperactive playing style and prolific recording output during the 1990s third-wave ska boom.\n\nReleased eight studio albums between *Press* (1992) and *Ultra Panic* (2018). Toured extensively with the Asian Man Records roster including Slapstick, Less Than Jake, and the Aquabats. Frequent touring continues sporadically.",
  "mushroomhead":
    "American metal band formed in Cleveland, Ohio in 1993. Long-running ensemble featuring masked performers in numbered jumpsuits (predating Slipknot's similar aesthetic). Lineup has rotated extensively but typically includes 7-9 members covering vocals, dual drum kits, samplers, and guitars.\n\nReleased nine studio albums between *Mushroomhead* (1995) and *Call the Devil* (2024). Best-known release: *XX* (2001), the band's major-label debut on Universal. Distinguished by their integration of percussion-heavy industrial elements with nu-metal songwriting.",
  "my-life-with-the-thrill-kill-kult":
    "American industrial/electronic band formed in Chicago in 1987. Long-running lineup centered on Groovie Mann (vocals) and Buzz McCoy (programming/keyboards). Distinguished by their satirical incorporation of horror-movie samples, B-movie aesthetics, and disco-influenced industrial dance.\n\nOver a dozen studio albums between *I See Good Spirits and I See Bad Spirits* (1988) and *Twilight Programs of the Magick Dark* (2023). Critical peak: *Confessions of a Knife...* (1990), *Sexplosion!* (1991), and *Hit & Run Holiday* (1995). Recorded for Wax Trax! Records during the label's peak.",
  "ndea-davenport":
    "American singer-songwriter born N'Dea Davenport on July 11, 1966, in Atlanta, Georgia. Founding lead vocalist for the Brand New Heavies (1985-1997, 2010-2012). Distinguished by her powerful soul-pop voice.\n\nReleased two solo studio albums: *N'Dea Davenport* (1998) and *Naked Soul of N'Dea Davenport* (2002). The Brand New Heavies were central to the early-1990s acid jazz movement; Davenport sang on the band's commercial peak *Brother Sister* (1994).",
  "nancy-sinatra":
    "American singer and actress born June 8, 1940, in Jersey City, New Jersey. Eldest daughter of Frank Sinatra. Distinguished by her hardened, breathy vocal style that contrasted sharply with her father's polished crooning.\n\nReleased over a dozen studio albums starting with *Boots* (1966, featuring the #1 \"These Boots Are Made for Walkin'\"). Best-known recordings include \"Bang Bang (My Baby Shot Me Down)\" (1966, later recontextualized by Quentin Tarantino in *Kill Bill*), \"Sugar Town\" (1966), and \"Somethin' Stupid\" (1967, a duet with her father). Sang the James Bond theme \"You Only Live Twice\" (1967).",
  "nathaniel-rateliff-the-night-sweats":
    "American soul/Americana band formed in Denver, Colorado in 2013. Lineup: Nathaniel Rateliff (vocals/guitar, b. October 7, 1978, Missouri), Joseph Pope III (bass), Mark Shusterman (keyboards), Patrick Meese (drums), Luke Mossman (guitar), and a horn section. Distinguished by their throwback Stax/Memphis-soul instrumentation paired with Rateliff's gritty, gospel-influenced vocals.\n\nFour studio albums between *Nathaniel Rateliff & The Night Sweats* (2015, featuring the breakout \"S.O.B.\") and *South of Here* (2024). Subsequent peaks: *Tearing at the Seams* (2018) and *The Future* (2021). Rateliff also continues to release introspective folk material as a solo artist (*And It's Still Alright*, 2020).",
  "naughty-by-nature":
    "American hip-hop group formed in East Orange, New Jersey in 1986. Lineup: Treach (Anthony Criss), Vin Rock (Vincent Brown), and DJ Kay Gee (Keir Gist). Mentored by Queen Latifah. Distinguished by Treach's tongue-twisting flow and DJ Kay Gee's sample-heavy production.\n\nEight studio albums between *Independent Leaders* (1989) and *Anthem Inc.* (2011). Commercial peak: *Naughty by Nature* (1991, featuring the diamond-certified \"O.P.P.\") and *19 Naughty III* (1993, featuring \"Hip Hop Hooray\"). Two Grammy Awards.",
  "negative-approach":
    "American hardcore punk band formed in Detroit in 1981. Long-running lineup centered on vocalist John Brannon. Among the foundational acts of the early-1980s Midwestern hardcore scene; toured extensively with Black Flag and Minor Threat.\n\nReleased the *Negative Approach* EP (1982, Touch and Go) and the full-length *Tied Down* (1983). Brannon dissolved the band in 1984; he subsequently led Laughing Hyenas and Easy Action. Negative Approach reformed in 2006 and continues to perform.",
  "neil-diamond":
    "American singer-songwriter born January 24, 1941, in Brooklyn, New York. Among the best-selling music artists of all time, with estimated worldwide sales of 130 million-plus units. Distinguished by his theatrical baritone and his prolific 1960s-70s catalog of compositions for himself and others (\"I'm a Believer\" for the Monkees, \"Red Red Wine\" for UB40, etc.).\n\nReleased over 30 studio albums between *The Feel of Neil Diamond* (1966) and *Melody Road* (2014). Best-known recordings include \"Sweet Caroline\" (1969), \"Cracklin' Rosie\" (1970), \"Song Sung Blue\" (1972), and \"America\" (1980). Inducted into the Rock and Roll Hall of Fame in 2011 and announced retirement from touring in 2018 after a Parkinson's disease diagnosis.",
  "neil-young-promise-of-the-real":
    "Touring and recording collaboration between Neil Young (Canadian-American singer-songwriter, b. November 12, 1945) and the American country-rock band Promise of the Real, led by Lukas Nelson (son of Willie Nelson). The collaboration ran from 2014 to 2019.\n\nReleased *The Monsanto Years* (2015), *Earth* (2016), and *The Visitor* (2017) as Neil Young + Promise of the Real, plus the live release *Paradox* (2018, the soundtrack to the Daryl Hannah-directed film of the same name). Young returned to his earlier touring partners after the 2019 amicable end of the collaboration.",
  "neurosis":
    "American post-metal band formed in Oakland, California in 1985. Long-running lineup: Scott Kelly (vocals/guitar), Steve Von Till (vocals/guitar), Dave Edwardson (bass), Jason Roeder (drums), and Noah Landis (samples/synthesizer). Foundational influence on the post-metal and sludge metal genres.\n\nReleased 11 studio albums between *Pain of Mind* (1987) and *Fires Within Fires* (2016). Critical peak: *Through Silver in Blood* (1996), *Times of Grace* (1999), and *A Sun That Never Sets* (2001). The band has been on indefinite hiatus since 2019, when Scott Kelly publicly acknowledged having been emotionally and physically abusive to his family and stepped back from public performance.",
  "neutral-milk-hotel":
    "American indie rock band formed in Ruston, Louisiana in 1989. Long-running lineup centered on Jeff Mangum (vocals/guitar/songwriter). Member of the Elephant 6 Recording Company collective.\n\nReleased two studio albums: *On Avery Island* (1996) and *In the Aeroplane Over the Sea* (1998). The latter is widely regarded as one of the most acclaimed indie rock albums of the 1990s. Mangum withdrew from public life in 1999 and the band remained dormant until a reunion tour in 2013-2015. Mangum has subsequently kept a low public profile.",
  "new-edition":
    "American R&B group formed in Boston in 1978. Original lineup: Ralph Tresvant (b. 1968), Bobby Brown (b. 1969), Michael Bivins (b. 1968), Ricky Bell (b. 1967), and Ronnie DeVoe (b. 1967). Johnny Gill joined in 1987. The blueprint for the boy-band format adopted by New Kids on the Block, Boyz II Men, and many others. Spawned the spinoff acts Bell Biv DeVoe and Bobby Brown's solo career.\n\nReleased seven studio albums starting with *Candy Girl* (1983). Commercial peak: *New Edition* (1984, featuring \"Cool It Now\" and \"Mr. Telephone Man\"), *All for Love* (1985), and *Heart Break* (1988). The 2017 BET miniseries *The New Edition Story* chronicled the group's history.",
  "new-years-day":
    "American gothic/alternative rock band formed in Anaheim, California in 2005. Long-running lineup centered on Ash Costello (vocals). Style draws on gothic rock, alternative metal, and post-hardcore.\n\nFive studio albums between *My Dear* (2007) and *Half Black Heart* (2024). Subsequent peaks: *Victim to Villain* (2013) and *Malevolence* (2015). Frequent tourmates have included Motionless in White and Falling in Reverse.",
  "new-york-dolls":
    "American rock band formed in New York City in 1971. Original lineup: David Johansen (vocals, 1950-2025), Johnny Thunders (guitar, 1952-1991), Sylvain Sylvain (guitar, 1951-2021), Arthur \"Killer\" Kane (bass, 1949-2004), and Jerry Nolan (drums, 1946-1992). Foundational influence on punk rock, glam rock, and post-punk despite limited commercial success during their original 1971-1977 run.\n\nReleased two studio albums during their original tenure: *New York Dolls* (1973, produced by Todd Rundgren) and *Too Much Too Soon* (1974, produced by Shadow Morton). Reunited in 2004 (with Kane dying weeks after the first reunion show) and released three further albums between *One Day It Will Please Us to Remember Even This* (2006) and *Dancing Backward in High Heels* (2011). David Johansen, the last surviving original member, died in February 2025.",
  "next":
    "American R&B group formed in Minneapolis in 1992. Lineup: brothers Robert \"R.L.\" Huggar and Raphael \"Tweety\" Brown, plus Terry \"T-Low\" Brown. Distinguished by their explicit-but-smooth grown-and-sexy R&B style.\n\nFour studio albums between *Rated Next* (1997) and *The Next Episode* (2007). Commercial peak: *Rated Next* (featuring the diamond-certified \"Too Close\"), which topped the Billboard Hot 100 for five weeks in 1998. R.L. has subsequently pursued a solo career.",
  "nick-cave-the-bad-seeds":
    "Australian-British rock band formed in 1983 by Nick Cave (Australian, b. September 22, 1957) after the dissolution of the Birthday Party. Long-running collaborators include Mick Harvey (until 2009), Blixa Bargeld (until 2003), and Warren Ellis (joined 1995 in the Dirty Three, has been Cave's primary musical partner since the 2000s).\n\nReleased 18 studio albums between *From Her to Eternity* (1984) and *Wild God* (2024). Critical peaks: *The Good Son* (1990), *Henry's Dream* (1992), *Murder Ballads* (1996, featuring duets with Kylie Minogue and PJ Harvey), *No More Shall We Part* (2001), *Push the Sky Away* (2013), *Skeleton Tree* (2016, released shortly after the accidental death of Cave's 15-year-old son Arthur), and *Ghosteen* (2019).",
  "nickelback":
    "Canadian rock band formed in Hanna, Alberta in 1995. Long-running lineup: Chad Kroeger (vocals/guitar), Ryan Peake (guitar), Mike Kroeger (bass), and various drummers. Among the best-selling Canadian rock bands of all time, with estimated worldwide sales of 50 million-plus units, despite (and arguably feeding) widespread critical and online backlash.\n\nReleased 10 studio albums between *Curb* (1996) and *Get Rollin'* (2022). Commercial peak: *Silver Side Up* (2001, featuring \"How You Remind Me,\" the most-played song of the 2000s on US radio), *The Long Road* (2003), *All the Right Reasons* (2005), and *Dark Horse* (2008).",
  "nil-lara":
    "Cuban-American singer-songwriter born in Cuba (raised in Caracas, Venezuela and Miami). Distinguished by his fusion of Cuban tres and Afro-Cuban rhythms with rock songwriting. Affiliated with the mid-1990s Miami singer-songwriter scene.\n\nReleased two studio albums: *My First Child* (1996) and *Nil Lara* (1997, Capitol Records). The latter was produced by Glyn Johns. Subsequent material has been independently released and primarily aimed at the Spanish-language market.",
  "nile-rodgers-chic":
    "American disco-funk band formed in New York City in 1976 by Nile Rodgers (guitar, b. September 19, 1952) and Bernard Edwards (bass, 1952-1996). Reformed under the \"Nile Rodgers & Chic\" name in 1996, after Edwards's death from pneumonia following a concert in Tokyo. Long-running configuration features Rodgers leading a touring band.\n\nThe original Chic released six studio albums between *Chic* (1977) and *Believer* (1983). Commercial peak: *C'est Chic* (1978, featuring \"Le Freak\") and *Risqué* (1979, featuring \"Good Times,\" whose bassline became the foundation for \"Rapper's Delight\"). Rodgers's parallel production career has shaped major recordings for David Bowie, Madonna, Daft Punk, Diana Ross, INXS, and many others. The reformed Chic released *It's About Time* (2018). Inducted into the Rock and Roll Hall of Fame in 2017.",
  "nino-rota":
    "Italian composer born Giovanni Rota Rinaldi on December 3, 1911, in Milan; died April 10, 1979. Best known for his film scores for Federico Fellini (*La Strada*, 1954; *La Dolce Vita*, 1960; *8½*, 1963; *Amarcord*, 1973) and Francis Ford Coppola (*The Godfather*, 1972; *The Godfather Part II*, 1974).\n\nComposed scores for over 150 films, plus 11 operas, four symphonies, and numerous ballets and concertos. Won an Academy Award for *The Godfather Part II* (1974). His main theme from *The Godfather* is among the most recognized themes in film history.",
  "nita-strauss":
    "American guitarist born December 7, 1986, in Los Angeles. Distinguished by her shred-style lead guitar work and her dual career as Alice Cooper's touring guitarist (2014-present) and Demi Lovato's touring guitarist (2018, 2022).\n\nReleased two solo studio albums: *Controlled Chaos* (2018) and *The Call of the Void* (2023). Has also worked extensively as a clinician for Ibanez guitars and recorded with WWE (notably the theme music for wrestler Shinsuke Nakamura).",
  "no-artist":
    "Catalog placeholder used in MusicBrainz and Discogs for releases where no artist credit applies (sound effects records, unreleased test pressings, certain compilations, field recordings without performer credits, etc.). Not a real artist.\n\nRecords in personal collections credited to \"No Artist\" are typically novelty items, sound-effect libraries, test pressings, or oddities where the original release simply did not credit a performer.",
  "no-authority":
    "American boy band formed in Detroit in 1995. Lineup: Eric Stretch, Marcus Thomas, Danny Zavatsky, and Ricky Felix (replaced by Tommy O'Brien). Distinguished by their late-1990s teen-pop aesthetic and being signed by Michael Jackson's MJJ Music imprint.\n\nReleased two studio albums: *Keep on* (1997) and *No Authority* (2002). The group dissolved by the mid-2000s. The TLC-style group name occasionally creates confusion with the unrelated Boston punk band No Authority.",
  "no-innocent-victim":
    "American Christian hardcore band formed in Southern California in 1992. Long-running lineup centered on guitarist Jason Cammarata. Style draws on metallic hardcore in the vein of Strife and Earth Crisis, with explicitly Christian lyrical themes.\n\nReleased four studio albums between *Strength Beyond Strength* (1995) and *Tipping the Scales* (2001). Released primarily on Tooth & Nail Records and Victory Records.",
  "no-use-for-a-name":
    "American punk rock band formed in Sunnyvale, California in 1987. Long-running lineup centered on the late Tony Sly (vocals/guitar, 1970-2012). Distinguished by Sly's melodic punk songwriting and the band's long association with Fat Wreck Chords.\n\nSeven studio albums between *Incognito* (1990) and *The Feel Good Record of the Year* (2008). Critical peak: *Leche con Carne* (1995), *Making Friends* (1997), and *More Betterness!* (1999). Sly died of an apparent accidental drug overdose in 2012 at age 41; the band dissolved.",
  "norman-whitfield":
    "American songwriter, producer, and Motown executive born May 12, 1940, in New York City; died September 16, 2008. Among the architects of the Motown sound and the principal producer behind the Temptations' shift from classic Motown to psychedelic soul.\n\nCo-wrote and produced \"I Heard It Through the Grapevine\" (originally recorded by Gladys Knight & the Pips in 1967, then a #1 hit for Marvin Gaye in 1968), \"Papa Was a Rollin' Stone\" (1972, the Temptations), \"War\" (1970, Edwin Starr), and \"Just My Imagination\" (1971, the Temptations). Founded Whitfield Records in 1975, releasing Rose Royce's \"Car Wash\" (1976). Inducted into the Songwriters Hall of Fame in 2004.",
  "nu-shooz":
    "American funk/pop duo formed in Portland, Oregon in 1979. Long-running duo of John Smith (vocals/guitar) and Valerie Day (vocals). Best known for the international 1986 hit \"I Can't Wait,\" a sleeper success that began as a regional Portland single and grew through dance-club play.\n\nReleased three studio albums between *Poolside* (1986) and *Bagtown* (2010). Subsequent recording activity has been intermittent; the duo continues to perform.",
  "ny-loose":
    "American glam rock/punk band formed in New York City in 1992. Long-running lineup centered on vocalist Brijitte West. Distinguished by their throwback-glam-meets-punk aesthetic. Featured on the *The Crow: City of Angels* soundtrack (1996) with the song \"Spit.\"\n\nReleased *Year of the Rat* (1996). The band dissolved by the late 1990s. West subsequently pursued a solo career under the name Brijitte West & the Desperate Hopefuls.",
  "ok-go":
    "American rock band formed in Chicago in 1998. Long-running lineup: Damian Kulash (vocals/guitar), Tim Nordwind (bass), Dan Konopka (drums), and Andy Ross (guitar, since 2005). Distinguished by elaborately choreographed music videos that have repeatedly gone viral, including the original \"A Million Ways\" (2005), \"Here It Goes Again\" (2006, the treadmill video), and \"This Too Shall Pass\" (2010, the Rube Goldberg machine).\n\nFive studio albums between *OK Go* (2002) and *And the Adjacent Possible* (2025). Won the 2007 Grammy for Best Short Form Music Video for \"Here It Goes Again.\"",
  "old-crow-medicine-show":
    "American old-time string band formed in Harrisonburg, Virginia in 1998. Long-running lineup historically centered on Ketch Secor (vocals/fiddle/harmonica) and Critter Fuqua (banjo/guitar, until 2007). Distinguished by their high-energy stage shows and their reinvigoration of pre-WWII string-band repertoire.\n\nNine studio albums between *Old Crow Medicine Show* (1998) and *Jubilee* (2023). Best-known recording: \"Wagon Wheel\" (2004), built on an unfinished Bob Dylan sketch — eventually a multi-platinum smash via Darius Rucker's 2013 cover. Members of the Grand Ole Opry since 2013.",
  "oliver-nelson":
    "American jazz saxophonist, arranger, and composer born June 4, 1932, in St. Louis, Missouri; died October 28, 1975. Best known for his hard-bop and post-bop work as a leader, and for his prolific career as an arranger for studio sessions, film scores, and television scores.\n\nReleased the landmark *The Blues and the Abstract Truth* (1961, featuring Eric Dolphy, Freddie Hubbard, and Bill Evans). Composed and arranged extensively for film and television including Quincy Jones's *Ironside* (1967) and Henry Mancini's *The Six Million Dollar Man* (1974). Died at age 43 of a heart attack.",
  "olivia":
    "Generic stage name used by multiple unrelated artists. The Olivia referenced in a typical record collection may be either:\n• Olivia Newton-John (Australian-British singer, 1948-2022), credited as simply \"Olivia\" on several early-1970s releases\n• Olivia Longott (American R&B singer, b. 1980), the only female artist signed to G-Unit Records\n• Olivia Rodrigo (American singer, b. 2003), occasionally credited as just \"Olivia\" on some early demo/feature credits\n\nWithout further context the specific Olivia in question cannot be identified.",
  "olivia-newton-john":
    "Australian-British singer and actress born September 26, 1948, in Cambridge, England; raised in Melbourne; died August 8, 2022. Among the best-selling music artists of all time, with estimated worldwide sales of 100 million-plus units.\n\nReleased over 25 studio albums starting with *If Not for You* (1971). Commercial peak: *Have You Never Been Mellow* (1975), *Grease* (1978, the soundtrack to the Paramount film in which she co-starred), and *Physical* (1981, featuring the title-track #1 that spent 10 weeks atop the Billboard Hot 100). Four Grammy Awards. Diagnosed with breast cancer in 1992 and twice more thereafter; her public advocacy for cancer awareness paralleled her continued performing. Died at age 73 of cancer-related complications.",
  "one-king-down":
    "American hardcore band formed in Albany, New York in 1995. Long-running lineup centered on vocalist Rob Fusco. Style draws on metallic hardcore in the late-1990s mode of Hatebreed and Earth Crisis.\n\nReleased three studio albums between *Bloodlust Revenge* (1997) and *God Loves, Man Kills* (2000). Released on Equal Vision Records. The band has been intermittently active in the 2000s and 2010s.",
  "one-way-system":
    "English punk rock band formed in Barrow-in-Furness, Cumbria in 1978. Long-running lineup centered on Gavin Sowerby (vocals). Among the second-wave UK82 punk bands alongside Discharge, GBH, and the Exploited.\n\nReleased the influential *All Systems Go* (1983) on Anagram Records. The band has been intermittently active, with reunion shows and further recordings into the 2010s.",
  "orange-9mm":
    "American post-hardcore band formed in New York City in 1993. Long-running lineup centered on Chaka Malik (vocals, formerly of Burn) and Chris Traynor (guitar, later of Bush). Distinguished by their groove-oriented post-hardcore drawing on Quicksand and Helmet.\n\nReleased three studio albums between *Driver Not Included* (1995) and *Pretend I'm Human* (1999). Traynor subsequently joined Helmet, Bush, and Bad Brains touring lineups; Malik has performed solo and with Burn reunions.",
  "pod":
    "American Christian rock band formed in San Diego in 1992 (officially stylized P.O.D., for Payable on Death). Long-running lineup centered on Sonny Sandoval (vocals) and Marcos Curiel (guitar, with intermittent departures). Distinguished by their reggae-influenced rap-metal style and prominent Christian lyrical themes.\n\nNine studio albums between *Snuff the Punk* (1994) and *Veritas* (2024). Commercial peak: *Satellite* (2001, triple-platinum, featuring \"Alive\" and \"Youth of the Nation\") and *The Fundamental Elements of Southtown* (1999).",
  "pailhead":
    "American industrial supergroup formed in 1987 by Al Jourgensen (Ministry) and Ian MacKaye (Minor Threat, Fugazi). The collaboration paired Jourgensen's industrial production with MacKaye's hardcore vocals and lyrics.\n\nReleased one EP, *Trait* (1988, Wax Trax!), compiled with additional tracks as *No Greater Love* (1988). The collaboration was short-lived; MacKaye's commitment to Fugazi (founded 1987) precluded further work.",
  "pantera":
    "American heavy metal band formed in Arlington, Texas in 1981. Long-running classic lineup: Phil Anselmo (vocals, joined 1987), Dimebag Darrell (guitar, 1966-2004), Rex Brown (bass), and Vinnie Paul (drums, 1964-2018). Began as a glam-metal band before pivoting to the groove-metal style on *Cowboys from Hell* (1990) that defined the band and the genre.\n\nNine studio albums between *Metal Magic* (1983) and *Reinventing the Steel* (2000). Commercial peak: *Cowboys from Hell* (1990), *Vulgar Display of Power* (1992), and *Far Beyond Driven* (1994, the heaviest album ever to debut at #1 on the Billboard 200). Dimebag was murdered by a deranged fan on stage during a Damageplan show in 2004; Vinnie Paul died in 2018 of heart failure. Anselmo and Brown reunited in 2022 with Zakk Wylde (guitar) and Charlie Benante (drums) for ongoing tribute tours.",
  "parliament":
    "American funk band formed in Plainfield, New Jersey in 1968 (as a continuation of the Parliaments, who released the 1967 single \"(I Wanna) Testify\"). Long-running ensemble led by George Clinton (b. July 22, 1941). Together with Funkadelic, formed the core of the P-Funk collective.\n\nReleased 10 studio albums between *Osmium* (1970) and *Trombipulation* (1980). Commercial peak: *Mothership Connection* (1975, featuring \"P. Funk (Wants to Get Funked Up)\" and \"Give Up the Funk\"), *The Clones of Dr. Funkenstein* (1976), and *Funkentelechy vs. the Placebo Syndrome* (1977, featuring \"Flash Light\"). Clinton's P-Funk collective was inducted into the Rock and Roll Hall of Fame in 1997.",
  "pat-travers-band":
    "Canadian rock band formed in 1976 by guitarist Pat Travers (b. April 12, 1954, Toronto). Lineup historically featured Pat Thrall (guitar) and Tommy Aldridge (drums) during the late-1970s commercial peak.\n\nReleased over 20 studio albums starting with *Pat Travers* (1976). Best-known recording: \"Boom Boom (Out Go the Lights)\" (1979, a John Lee Hooker cover), from *Live! Go for What You Know*. Travers continues to perform with rotating personnel and has released multiple albums into the 2020s.",
  "patty-smyth":
    "American singer-songwriter born June 26, 1957, in New York City. Lead vocalist for Scandal (1981-1985) before launching her solo career. Distinguished by her gritty rock vocals and her surprise pop hit \"The Warrior\" (1984, with Scandal).\n\nReleased four solo studio albums between *Never Enough* (1987) and *Live and Unreleased* (2020). Best-known solo single: \"Sometimes Love Just Ain't Enough\" (1992, a duet with Don Henley that peaked at #2 on the Billboard Hot 100). Has been married to tennis great John McEnroe since 1997.",
  "paul-oakenfold":
    "English DJ and music producer born August 30, 1963, in Greenhithe, Kent. Among the most influential trance and progressive house DJs of the 1990s and 2000s. His Cream residency in Liverpool helped establish the British superclub-DJ model that came to define electronic dance music for two decades.\n\nReleased six studio albums starting with *Bunkka* (2002, featuring \"Starry Eyed Surprise\"). Has produced and remixed for U2, Madonna, the Rolling Stones, Snoop Dogg, and many others. Composed the soundtrack to the *Swordfish* (2001) film.",
  "paula-cole":
    "American singer-songwriter born April 5, 1968, in Rockport, Massachusetts. Distinguished by her jazz-trained alto and confessional songwriting.\n\nReleased nine studio albums between *Harbinger* (1994) and *American Quilt* (2021). Commercial peak: *This Fire* (1996, featuring \"Where Have All the Cowboys Gone?\" and \"I Don't Want to Wait\" — the latter familiar from the *Dawson's Creek* opening credits). Won the 1998 Grammy for Best New Artist over runners-up Hanson, Erykah Badu, Fiona Apple, and Sugar Ray. Toured with Lilith Fair throughout 1997-1999.",
  "pavement":
    "American indie rock band formed in Stockton, California in 1989. Lineup historically: Stephen Malkmus (vocals/guitar), Scott Kannberg/Spiral Stairs (guitar), Mark Ibold (bass), Steve West (drums, joined 1993), and Bob Nastanovich (auxiliary percussion/vocals). Distinguished by lo-fi production, slacker-ironic lyrics, and one of the most acclaimed indie-rock catalogs of the 1990s.\n\nFive studio albums between *Slanted and Enchanted* (1992) and *Terror Twilight* (1999). Critical peaks across the entire catalog. Reunited in 2010 and again in 2022-2023 to wider critical reappraisal — particularly of *Terror Twilight*, after the *Terror Twilight: Farewell Horizontal* (2022) reissue. Malkmus has subsequently led the Jicks.",
  "pearl-jam":
    "American rock band formed in Seattle in 1990. Long-running lineup: Eddie Vedder (vocals), Stone Gossard (guitar), Mike McCready (guitar), Jeff Ament (bass), and Matt Cameron (drums, 1998-2024). Among the most commercially successful and longest-running bands to emerge from the early-1990s Seattle grunge scene.\n\nTwelve studio albums between *Ten* (1991) and *Dark Matter* (2024). Commercial peak: *Ten* (diamond-certified), *Vs.* (1993, then the fastest-selling album in history), and *Vitalogy* (1994). Famously withdrew from the Ticketmaster ecosystem in the mid-1990s, testifying before Congress about anti-competitive practices. Inducted into the Rock and Roll Hall of Fame in 2017.",
  "pears":
    "American punk rock band formed in New Orleans in 2014 (officially stylized PEARS, for People Endorsing Agorist Revolutionary Syndicalism, though the band has frequently disclaimed any earnest political reading). Lineup: Zach Quinn (vocals), Brian Pretus (guitar), Erich Goodyear (bass, until 2017), and Jarret Nathan (drums).\n\nFour studio albums between *Go to Prison* (2014) and *PEARS* (2020). Toured extensively with NOFX, Less Than Jake, and Lagwagon. The band remains active.",
  "pete-droge":
    "American singer-songwriter born May 11, 1969, on Bainbridge Island, Washington. Distinguished by his roots-rock songwriting and his association with the Pacific Northwest singer-songwriter scene of the 1990s.\n\nReleased five studio albums between *Necktie Second* (1994) and *Skywatching* (2007). Best-known song: \"If You Don't Love Me (I'll Kill Myself),\" featured on the *Dumb and Dumber* (1994) soundtrack. Has continued to record and tour intermittently.",
  "peter-gabriel":
    "English singer-songwriter and musician born February 13, 1950, in Chobham, Surrey. Founding lead vocalist of Genesis (1967-1975) before launching a successful solo career. Distinguished by his innovative use of world music, his early adoption of music video (with director Stephen R. Johnson on *Sledgehammer*, 1986), and his founding of the WOMAD festival and Real World Records.\n\nReleased 11 solo studio albums starting with *Peter Gabriel* (1977, the first of four self-titled albums). Commercial peak: *So* (1986, featuring \"Sledgehammer\" and \"In Your Eyes\"). Subsequent peaks: *Up* (2002) and *i/o* (2023, his first new pop album in 21 years). Inducted into the Rock and Roll Hall of Fame as a member of Genesis (2010) and as a solo artist (2014).",
  "peter-knight":
    "English violinist born July 1, 1947, in Stockton-on-Tees. Long-running member of Steeleye Span (1970-1977, 1980-2013, intermittent thereafter). Distinguished by his integration of jazz-influenced improvisation into folk-rock fiddling.\n\nReleased solo albums including *Fiddler's Dream* (1980). Knight left Steeleye Span in 2013 after over four decades and subsequently founded the trio Gigspanner. Released *Pete Knight's Gigspanner* (2009) and several subsequent albums.",
  "phantom-rocker-slick":
    "American rock trio formed in 1985 by former Stray Cats Slim Jim Phantom (drums) and Lee Rocker (upright bass) plus guitarist Earl Slick (David Bowie's longtime guitarist).\n\nReleased two studio albums: *Phantom, Rocker & Slick* (1985, featuring the David Bowie-affiliated single \"Men Without Shame\") and *Cover Girl* (1986). The Stray Cats reunion in 1986 ended the project. Phantom and Rocker continue to record and tour with the Stray Cats; Slick continues to perform with various artists including David Bowie's posthumous touring tribute productions.",
  "phil-keaggy-band":
    "Touring/recording band led by American Christian rock guitarist Phil Keaggy (b. March 23, 1951, Youngstown, Ohio). Keaggy is widely regarded as one of the most technically accomplished guitarists in Christian music; Eric Clapton has reportedly cited him as a favorite player.\n\nThe Phil Keaggy Band was a specific 1970s configuration that released *Emerging* (1977). Keaggy has subsequently released over 50 albums spanning solo electric, solo acoustic, instrumental, vocal pop-rock, and Christmas material. Best-known songs include \"Time\" (1976) and \"Way Back Home\" (1980).",
  "phish":
    "American rock band formed in Burlington, Vermont in 1983. Long-running lineup: Trey Anastasio (vocals/guitar), Mike Gordon (bass), Jon Fishman (drums), and Page McConnell (keyboards). The defining band of the post-Grateful Dead jam-band scene.\n\nFifteen studio albums between *Junta* (1989) and *Evolve* (2024). Distinguished by their improvisation-heavy live performances, devoted touring fanbase, and elaborate festival productions (the Clifford Ball, IT, the Big Cypress millennium show, Magnaball, etc.). On hiatus 2000-2002, broke up 2004-2008, has continued to tour heavily since the 2009 reunion. Phish.net and LivePhish.com have archived essentially every show the band has played.",
  "pig":
    "Industrial music project led by English musician Raymond Watts (b. 1959). Long-running solo project, frequently augmented by collaborators including Steve White, Sascha Konietzko (KMFDM), and Günter Schulz (KMFDM). Distinguished by Watts's sneering vocals and his blending of industrial, electronic, and hard rock elements.\n\nReleased over a dozen studio albums between *A Poke in the Eye... With a Sharp Stick* (1988) and *Red Room* (2023). Watts has also been a member of KMFDM, Schaft, and Schwein. Frequent collaborator with Sascha Konietzko.",
  "pinetop-perkins":
    "American blues pianist born Joseph William Perkins on July 7, 1913, in Belzoni, Mississippi; died March 21, 2011. Member of Muddy Waters's band (1969-1980) and the Legendary Blues Band (1980-1991). Distinguished by his deeply traditional Delta-blues piano style and his exceptional longevity — performing and recording into his late 90s.\n\nReleased over a dozen solo studio albums starting with *Boogie Woogie King* (1976). Won the Grammy for Best Traditional Blues Album for *Joined at the Hip* (2010, with Willie \"Big Eyes\" Smith) — at age 97, making him the oldest Grammy recipient in any category. Died at age 97 of cardiac arrest.",
  "pitbull":
    "American rapper, singer, and entrepreneur born Armando Christian Pérez on January 15, 1981, in Miami. Of Cuban descent. Adopted the stage name \"Pitbull\" early in his career. Distinguished by Latin-pop-influenced dance tracks frequently featuring spoken-word hype phrases and his signature \"Dale\" tag.\n\nReleased 12 studio albums starting with *M.I.A.M.I.* (2004). Commercial peak: *Planet Pit* (2011, featuring \"Give Me Everything\"), *Global Warming* (2012), and *Globalization* (2014). Recorded the World Cup theme \"We Are One (Ole Ola)\" (2014, with Jennifer Lopez and Claudia Leitte).",
  "pj-harvey":
    "English singer-songwriter and musician born Polly Jean Harvey on October 9, 1969, in Bridport, Dorset. Distinguished by her stylistic restlessness, ranging from raw blues-rock to polished art-pop to spoken-word-driven political work.\n\nReleased 10 studio albums starting with *Dry* (1992). Commercial and critical peaks: *To Bring You My Love* (1995), *Stories from the City, Stories from the Sea* (2000), *White Chalk* (2007), *Let England Shake* (2011), and *I Inside the Old Year Dying* (2023). The first artist to win the Mercury Prize twice, for *Stories from the City* (2001) and *Let England Shake* (2011). Appointed MBE in 2013.",
  "placebo":
    "British rock band formed in London in 1994. Long-running duo of Brian Molko (vocals/guitar, American/Belgian) and Stefan Olsdal (bass/guitar, Swedish), plus various drummers (currently Steve Forrest). Distinguished by Molko's androgynous vocals and the band's pronounced glam-rock influences.\n\nReleased eight studio albums between *Placebo* (1996) and *Never Let Me Go* (2022). Commercial peak: *Without You I'm Nothing* (1998) and *Black Market Music* (2000). Best-known singles include \"Pure Morning\" (1998), \"Every You Every Me\" (1999), and \"The Bitter End\" (2003).",
  "pointer-sisters":
    "American R&B group formed in Oakland, California in 1969. Original lineup: sisters Ruth (b. 1946), Anita (1948-2022), Bonnie (1950-2020), and June (1953-2006). Bonnie left in 1977 for a solo career; the group continued as a trio. Distinguished by their stylistic versatility across R&B, pop, country, and disco.\n\nReleased 14 studio albums between *The Pointer Sisters* (1973) and *Stars* (1994). Won the 1974 Grammy for Best Country Vocal Performance by a Duo or Group for \"Fairytale\" — the first African-American group to win a country Grammy. Commercial peak: *Break Out* (1983, featuring \"Jump (For My Love),\" \"I'm So Excited,\" and \"Automatic\"). Three Grammy Awards total.",
  "possessed":
    "American death/thrash metal band formed in Bay Area, California in 1983. Long-running lineup centered on vocalist/bassist Jeff Becerra. Widely credited as one of the first death metal bands, with their 1985 debut *Seven Churches* often cited as the genre's foundational album.\n\nReleased *Seven Churches* (1985) and *Beyond the Gates* (1986) during their original run, then reformed in 2007 (after Becerra was paralyzed from the waist down in a 1989 robbery). Released the comeback *Revelations of Oblivion* (2019) after a 33-year studio gap. The band continues to record and perform with Becerra fronting from a wheelchair.",
  "powerman-5000":
    "American industrial metal band formed in Boston in 1991. Long-running lineup centered on Spider One (vocals, born Michael David Cummings, brother of Rob Zombie). Distinguished by their science-fiction-themed lyrics and their late-1990s commercial peak alongside the broader nu-metal wave.\n\nReleased 10 studio albums between *True Force* (1994) and *The Noble Rot* (2020). Commercial peak: *Tonight the Stars Revolt!* (1999, featuring \"When Worlds Collide\") and *Anyone for Doomsday?* (2001).",
  "prick":
    "American industrial rock band formed in Cleveland, Ohio in 1989. Long-running lineup centered on Kevin McMahon (formerly of the Lucky Pierre band). Notable for being signed to Trent Reznor's Nothing Records and for the considerable Trent Reznor influence on their production.\n\nReleased the self-titled *Prick* (1995) on Interscope/Nothing. The follow-up *The Wreckard* (2002) was independently released. The band has been intermittently active in subsequent decades.",
  "procol-harum":
    "English rock band formed in Southend-on-Sea, Essex in 1967. Long-running lineup historically centered on Gary Brooker (vocals/keyboards, 1945-2022) and lyricist Keith Reid (1946-2023). Distinguished by their classical-music influences (particularly Bach) and Matthew Fisher's church-organ work.\n\nReleased 12 studio albums between *Procol Harum* (1967) and *Novum* (2017). Best-known recording: \"A Whiter Shade of Pale\" (1967), an immediate worldwide #1 that has remained one of the most-played songs in radio history. Inducted into the Songwriters Hall of Fame in 2018. Brooker died in 2022 of cancer; Reid died in 2023.",
  "prong":
    "American metal band formed in New York City in 1986. Long-running lineup centered on Tommy Victor (vocals/guitar). Distinguished by their groove-metal-meets-hardcore style and influence on industrial metal and the eventual rise of nu-metal.\n\nThirteen studio albums between *Primitive Origins* (1987) and *State of Emergency* (2023). Critical peak: *Beg to Differ* (1990), *Prove You Wrong* (1991), and *Cleansing* (1994, featuring \"Snap Your Fingers, Snap Your Neck\"). Victor has also performed with Danzig (1996-1998, 2002-2003, 2009-present) and Ministry.",
  "propagandhi":
    "Canadian punk rock band formed in Portage la Prairie, Manitoba in 1986. Long-running lineup centered on Chris Hannah (vocals/guitar) and Jord Samolesky (drums). Distinguished by their explicitly political lyrics (anti-capitalist, anti-imperialist, animal rights, queer rights) and their increasing technical proficiency across their catalog.\n\nReleased eight studio albums between *How to Clean Everything* (1993) and *At Peace* (2024). Critical peak: *Today's Empires, Tomorrow's Ashes* (2001), *Potemkin City Limits* (2005), and *Supporting Caste* (2009). Released primarily on Fat Wreck Chords and the band's own G7 Welcoming Committee Records.",
  "pushmonkey":
    "American rock band formed in Austin, Texas in 1992. Long-running lineup centered on Tony Park (vocals). Distinguished by their hybrid alternative-metal sound drawing on Tool, Soundgarden, and other turn-of-the-millennium alternative/hard rock.\n\nReleased three studio albums between *Pushmonkey* (1998) and *Together* (2008). Toured with Tool, Cheap Trick, and others. The band has been intermittently active in subsequent years.",
  "puya":
    "Puerto Rican alternative metal band formed in San Juan in 1989. Long-running lineup centered on Sergio Curbelo (vocals). Distinguished by their integration of Latin rhythms (salsa, bomba, plena) with nu-metal and Latin metal.\n\nReleased four studio albums between *Puya* (1995) and *Areito* (2018). Critical peak: *Fundamental* (1999, MCA Records), which combined Latin percussion with heavy metal in a way that prefigured a wave of Latin alternative rock acts.",
  "queen-adam-lambert":
    "Touring collaboration between the surviving members of Queen — Brian May (guitar, b. 1947) and Roger Taylor (drums, b. 1949) — and American vocalist Adam Lambert (b. January 29, 1982). Lambert first performed with the band on *American Idol* in 2009; the formal collaboration began in 2011 and continues touring intermittently as of 2025.\n\nNo new studio material has been recorded; the project is touring-only. The configuration has been notably successful commercially despite (or because of) the inevitable comparisons to the late Freddie Mercury. Released the live album *Live Around the World* (2020).",
  "queen-latifah":
    "American rapper, singer, and actress born Dana Elaine Owens on March 18, 1970, in Newark, New Jersey. Pioneering female hip-hop artist of the late 1980s and 1990s before pivoting to a successful film, television, and singing career.\n\nReleased seven studio albums between *All Hail the Queen* (1989) and *Persona* (2009). Best-known recording: \"U.N.I.T.Y.\" (1993), which won the 1995 Grammy for Best Rap Solo Performance. Co-founded the Flavor Unit Entertainment record label/management company. Starred in the film *Chicago* (2002, Oscar nomination for Best Supporting Actress) and the long-running USA Network drama *The Equalizer* (2021-present).",
  "queensrche":
    "Same artist as Queensrÿche — different character encoding. American progressive metal band formed in Bellevue, Washington in 1982. Long-running classic lineup: Geoff Tate (vocals, until 2012), Chris DeGarmo (guitar, until 1998), Michael Wilton (guitar), Eddie Jackson (bass), and Scott Rockenfield (drums). Distinguished by their progressive-rock-meets-metal arrangements and Tate's operatic vocals.\n\nReleased 16 studio albums between *Queensrÿche* (1983) and *Digital Noise Alliance* (2022). Commercial peak: *Operation: Mindcrime* (1988, a concept album) and *Empire* (1990, featuring \"Silent Lucidity\"). Tate was fired in 2012 and there have been two competing Queensrÿche entities since (the band continues with new vocalist Todd La Torre).",
  "quincy-jones":
    "American record producer, composer, conductor, and arranger born March 14, 1933, in Chicago, Illinois; died November 3, 2024. Among the most influential figures in 20th-century popular music. Produced the three best-selling Michael Jackson albums (*Off the Wall*, *Thriller*, *Bad*) — *Thriller* (1982) remains the best-selling album in history at over 70 million copies.\n\nReleased numerous solo and big-band albums including *The Dude* (1981) and *Back on the Block* (1989). Composed extensively for film and television including *In the Heat of the Night* (1967), *In Cold Blood* (1967), and *The Wiz* (1978). Won 28 Grammy Awards from 80 nominations, the second-most in Grammy history. Inducted into the Rock and Roll Hall of Fame in 2013. Died at age 91.",
  "rage-against-the-machine":
    "American rock band formed in Los Angeles in 1991. Lineup: Zack de la Rocha (vocals), Tom Morello (guitar), Tim Commerford (bass), and Brad Wilk (drums). Distinguished by Morello's innovative use of guitar effects to produce DJ-like sonic textures and the band's explicitly leftist political lyrics. Architects of the rap-metal genre.\n\nFour studio albums between *Rage Against the Machine* (1992) and *Renegades* (2000, a covers album). Critical and commercial peak: the self-titled debut and *Evil Empire* (1996, #1 on the Billboard 200). De la Rocha quit in 2000; the remaining three formed Audioslave with Chris Cornell. RATM reunited in 2007, broke up again in 2011, reunited in 2019-2022 (when Zack de la Rocha tore his Achilles tendon on stage, prematurely ending the tour). Inducted into the Rock and Roll Hall of Fame in 2023.",
  "ralph-sharon-and-his-orchestra":
    "Backing orchestra led by English-American jazz pianist Ralph Sharon (1923-2015). Best known as Tony Bennett's longtime musical director and accompanist (1957-2002, with intermittent gaps).\n\nReleased numerous instrumental and accompaniment albums including *The Ralph Sharon Trio* (1957) and *Modern Jazz Beat* (1956). Sharon is the pianist credited with first showing Tony Bennett the demo of \"I Left My Heart in San Francisco\" (1962), which Sharon had found in his shirt pocket. Continued performing with Bennett into the early 2000s.",
  "ralph-stanley-the-clinch-mountain-boys":
    "American bluegrass and old-time band led by Ralph Stanley (1927-2016) after the death of his brother Carter Stanley in 1966 dissolved the Stanley Brothers. Long-running lineup historically featured Ricky Skaggs, Keith Whitley, and Larry Sparks at various points.\n\nThe Clinch Mountain Boys backed Stanley on dozens of albums from the late 1960s through Stanley's 2016 death. Stanley achieved late-career mainstream visibility through *O Brother, Where Art Thou?* (2000), his unaccompanied recording of \"O Death\" winning the 2002 Grammy for Best Male Country Vocal Performance.",
  "rammstein":
    "German industrial metal band formed in Berlin in 1994. Long-running lineup: Till Lindemann (vocals), Richard Kruspe (guitar), Paul Landers (guitar), Oliver Riedel (bass), Christoph Schneider (drums), and Christian \"Flake\" Lorenz (keyboards). Distinguished by their pyrotechnic-heavy live shows, deliberately confrontational German-language lyrics, and the \"Neue Deutsche Härte\" sound they helped define.\n\nEight studio albums between *Herzeleid* (1995) and *Zeit* (2022). Commercial peak: *Sehnsucht* (1997), *Mutter* (2001), *Reise, Reise* (2004), and *Rosenrot* (2005). Have repeatedly topped the German album charts and become one of the most commercially successful European metal exports of all time.",
  "ramoms":
    "American Ramones tribute act featuring members who are mothers — hence the wordplay on Ramones/Moms. Active primarily in the New York and Connecticut tribute-circuit scenes. The Ramoms began performing in 2014.\n\nThe band performs Ramones material in costume and persona, with lineup members styled as Joey Ramom, Johnny Ramom, Dee Dee Ramom, and Marky Ramom variants. Has appeared at festivals including Riot Fest. Limited studio output; primarily a live tribute act.",
  "rascal-flatts":
    "American country band formed in Columbus, Ohio in 1999. Lineup: Gary LeVox (vocals), Jay DeMarcus (bass/vocals, cousin of LeVox), and Joe Don Rooney (guitar/vocals). Distinguished by their pop-country crossover sound and their three-part vocal harmonies.\n\nReleased 10 studio albums between *Rascal Flatts* (2000) and *How They Remember You* (2020, an EP). Commercial peak: *Me and My Gang* (2006), *Still Feels Good* (2007), and *Unstoppable* (2009). Best-known singles include \"Bless the Broken Road\" (2004) and \"What Hurts the Most\" (2006). The band announced their breakup in 2020.",
  "ratdog":
    "American rock band formed in 1995 by Grateful Dead guitarist Bob Weir (b. October 16, 1947). Long-running lineup featured Rob Wasserman (bass, 1952-2016), Jay Lane (drums), and Jeff Chimenti (keyboards). Began as an acoustic duo with Wasserman before expanding to a touring band.\n\nReleased the studio album *Evening Moods* (2000) plus several live releases. Active touring 1995-2014, with sporadic shows since. Weir's subsequent projects include Furthur (2009-2014), Dead & Company (2015-present), and the Wolf Bros (2018-present).",
  "ray-charles":
    "American singer, pianist, and composer born Ray Charles Robinson on September 23, 1930, in Albany, Georgia; died June 10, 2004. Among the architects of soul music — fusing gospel, blues, jazz, and country into a hybrid that profoundly shaped American popular music. Blind from age seven due to glaucoma.\n\nReleased over 70 studio albums between *Hallelujah I Love Her So* (1957) and *Genius Loves Company* (2004). Critical and commercial peaks: *Modern Sounds in Country and Western Music* (1962), the *Genius* series of recordings on Atlantic, and the late-career *Genius Loves Company* (eight posthumous Grammys, 2005). 17 Grammy Awards. Inducted into the Rock and Roll Hall of Fame in 1986 as an inaugural member.",
};

async function main() {
  const dryRun = process.argv.includes("--dry-run");
  const force = process.argv.includes("--force");
  const { containers } = await import("../lib/cosmos");
  const { getStoredArtist } = await import("../lib/artists");

  let written = 0;
  let skipped = 0;
  let missing = 0;

  for (const [slug, description] of Object.entries(DESCRIPTIONS)) {
    const existing = await getStoredArtist(slug);
    if (!existing) {
      console.log(`✗ ${slug}: no stored doc found`);
      missing += 1;
      continue;
    }
    if (existing.description && !force) {
      console.log(`↷ ${slug}: already has description — skipping`);
      skipped += 1;
      continue;
    }
    if (dryRun) {
      console.log(`◌ ${slug}: would write ${description.length} chars`);
      written += 1;
      continue;
    }
    const updated = {
      ...existing,
      description,
      updatedAt: new Date().toISOString(),
    };
    await containers.artists.item(slug, slug).replace(updated);
    console.log(`✓ ${slug}: ${description.length} chars`);
    written += 1;
  }

  console.log(`\nDone. written=${written} skipped=${skipped} missing=${missing}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
