import { config as loadEnv } from "dotenv";
loadEnv({ path: ".env.local" });

const DESCRIPTIONS: Record<string, string> = {
  "ablard":
    "Obscure act, limited public information available. Likely a regional or independent project tied to a 1990s/2000s pop-punk or hardcore-adjacent scene. Only thinly documented in commercial discographies.",
  "blue-moon-soup":
    "Obscure American indie act from the 1990s. Limited public documentation; appears to be a regional pop-rock or jam-band project.",
  "blues-brothers":
    "American blues revue founded in 1978 by Saturday Night Live cast members Dan Aykroyd (vocals/harmonica, as Elwood Blues) and John Belushi (vocals, as Jake Blues). Backed by a long-running professional band including Steve Cropper (guitar), Donald \"Duck\" Dunn (bass), and the SNL horns. Originally conceived as a parody on SNL; became a successful touring and recording act.\n\nReleased the live debut *Briefcase Full of Blues* (1978, which hit #1 on the Billboard 200) and the *The Blues Brothers* soundtrack (1980), among others. The 1980 film *The Blues Brothers* — directed by John Landis — became a cult classic. Belushi died of a drug overdose in 1982; Aykroyd continued the act with brother Jim Belushi and others.",
  "bob-dylan":
    "American singer-songwriter born Robert Zimmerman on May 24, 1941, in Duluth, Minnesota. Among the most influential and prolific singer-songwriters in popular music history. Awarded the Nobel Prize in Literature in 2016 — the first songwriter to receive the honor.\n\nReleased 40 studio albums between *Bob Dylan* (1962) and *Shadow Kingdom* (2023). Career-defining peaks include *Highway 61 Revisited* (1965), *Blonde on Blonde* (1966), *Blood on the Tracks* (1975), and *Time Out of Mind* (1997). Ten Grammy Awards. Inducted into the Rock and Roll Hall of Fame in 1988.",
  "bob-marley-the-wailers":
    "Jamaican reggae band formed in Kingston in 1963. Original lineup: Bob Marley (vocals/guitar, 1945-1981), Peter Tosh (guitar/vocals, 1944-1987), and Bunny Wailer (vocals, 1947-2021). Tosh and Wailer departed in 1974; subsequent lineups were typically billed as \"Bob Marley & The Wailers\" with various backing musicians.\n\nTwelve studio albums between *The Wailing Wailers* (1965) and *Uprising* (1980). Foundational releases include *Catch a Fire* (1973), *Burnin'* (1973), *Natty Dread* (1974), *Rastaman Vibration* (1976), and *Exodus* (1977, which *Time* magazine called the best album of the 20th century). Bob Marley died of cancer in May 1981. Inducted into the Rock and Roll Hall of Fame in 1994.",
  "bob-marley-and-the-wailers":
    "Same artist as Bob Marley & The Wailers — different Discogs/setlist.fm spelling variant. Jamaican reggae band formed in Kingston in 1963 by Bob Marley, Peter Tosh, and Bunny Wailer. The most commercially and culturally influential reggae act in history. Twelve studio albums between 1965 and 1980; Marley died of cancer in 1981. Inducted into the Rock and Roll Hall of Fame in 1994.",
  "bobby-brown":
    "American singer born February 5, 1969, in Boston. First gained prominence as a member of New Edition (1981-1985) before launching a solo career.\n\nReleased eight solo studio albums between *King of Stage* (1986) and *The Masterpiece* (2012). Commercial peak: *Don't Be Cruel* (1988), the second-best-selling album of 1989, featuring the singles \"Don't Be Cruel,\" \"Roni,\" \"Every Little Step,\" and \"My Prerogative.\" Subsequent peak: *Bobby* (1992, featuring \"Humpin' Around\"). Brown's much-publicized 1992-2007 marriage to Whitney Houston and recurring substance-abuse issues defined the public's perception of his later career.",
  "bobby-sherman":
    "American singer and actor (1943-2025). Born in Santa Monica, California. One of the leading teen idols of the late 1960s and early 1970s, with frequent appearances on television variety shows and the sitcom *Here Come the Brides* (1968-1970).\n\nReleased multiple studio albums starting with *Bobby Sherman* (1969). Best-known singles include \"Little Woman,\" \"La La La (If I Had You),\" \"Easy Come, Easy Go,\" and \"Julie, Do Ya Love Me\" — all top-10 US hits in 1969-1970. Pursued a second career as an EMT and emergency medical instructor from the 1980s onward.",
  "boingo":
    "American rock band formed in 1994 as a rebranding of Oingo Boingo. Lineup: Danny Elfman (vocals/guitar), Steve Bartek (guitar), John Avila (bass), Sluggo (drums), and various horns. The shortened name signaled a stylistic shift toward a more guitar-driven, less ska-influenced sound.\n\nReleased one studio album under the Boingo name: *Boingo* (1994). The band dissolved in 1995 with Elfman pursuing his film-scoring career full-time. The Boingo/Oingo Boingo catalog has continued to influence subsequent alternative-rock acts.",
  "boredoms":
    "Japanese experimental rock band formed in Osaka in 1986 by Yamantaka Eye (vocals/electronics). Long-running lineup also includes Yoshimi P-We (drums/vocals, who appears as the subject of the Flaming Lips' \"Yoshimi Battles the Pink Robots\"). Pioneers of Japanese noise rock; collaborators with Sonic Youth, John Zorn, and others.\n\nReleased over 15 studio albums starting with *Onanie Bomb Meets the Sex Pirates* (1988). Best-known releases include *Pop Tatari* (1992), *Chocolate Synthesizer* (1994), and *Super Roots 6: A Live in Tokyo World ... My Friend's Going Crazy* (1999). Active intermittently with extended hiatuses.",
  "both-worlds":
    "American hardcore/post-hardcore band formed in New York City in 1995. Side project of Walter Schreifels (vocals/guitar, of Quicksand and Gorilla Biscuits) and Civ (vocals, of Gorilla Biscuits) plus rotating members. Brief, prolific output during the late-1990s NYHC scene.\n\nReleased two studio albums: *Memory Rendered Visible* (1996) and *We're Not Quite to Eternity Yet* (1998). Released primarily on Another Planet and Some Records. The band has been inactive since the late 1990s.",
  "bowie":
    "Same artist as David Bowie — different Discogs/setlist.fm credit variation. English musician (1947-2016), born David Robert Jones in Brixton, London. One of the most influential artists in popular music history. Released 27 studio albums between 1967 and 2016. Distinguished by persistent reinvention across his career. Inducted into the Rock and Roll Hall of Fame in 1996.",
  "boyz-ii-men":
    "American R&B vocal group formed in Philadelphia in 1985. Classic lineup: Nathan Morris, Wanyá Morris, Shawn Stockman, and Michael McCary (1985-2003). One of the best-selling R&B groups in history, with an estimated 60 million-plus units sold worldwide.\n\nReleased ten studio albums starting with *Cooleyhighharmony* (1991). Commercial peak: *II* (1994, featuring \"I'll Make Love to You\" and \"On Bended Knee\"), *Evolution* (1997), and *Nathan Michael Shawn Wanya* (2000). The 1992 single \"End of the Road\" held the Billboard #1 spot for 13 weeks, breaking Elvis Presley's previous record. Michael McCary departed in 2003 due to scoliosis; the trio has continued.",
  "br5-49":
    "American country band formed in Nashville in 1993. Lineup: Chuck Mead (vocals/guitar), Gary Bennett (vocals/guitar, 1993-2001), Smilin' Jay McDowell (bass, 1993-1999), Don Herron (steel guitar/fiddle), and Hawk Shaw Wilson (drums). Distinguished by their honky-tonk and Western swing throwback aesthetic; named after a phone number from the *Hee Haw* TV show.\n\nFive studio albums between *Live from Robert's* (1996) and *Tangled in the Pines* (2001). The band built a substantial following through long-running residencies at the Nashville bar Robert's Western World. Disbanded in 2006.",
  "braid":
    "American emo band formed in Champaign, Illinois in 1993. Lineup: Bob Nanna (vocals/guitar), Chris Broach (vocals/guitar), Todd Bell (bass), and Damon Atkinson (drums). Considered foundational to second-wave emo alongside the Promise Ring and Mineral.\n\nThree studio albums in the original era: *Frankie Welfare Boy Age Five* (1995), *The Age of Octeen* (1996), and *Frame & Canvas* (1998). Disbanded in 1999, reunited in 2014 for *No Coast* (2014). Nanna also led Hey Mercedes and the Forecast.",
  "bret-michaels":
    "American singer born March 15, 1963, in Butler, Pennsylvania. Best known as the lead vocalist of Poison (1983-present). Has pursued a parallel solo career, an extensive television career (most notably *Rock of Love* on VH1, 2007-2009), and various business ventures.\n\nReleased nine solo studio albums between *A Letter from Death Row* (1998) and *Rock My World* (2008) and beyond. The 2010 brain hemorrhage that nearly killed him became the subject of his memoir *Roses & Thorns* (2013). Continues to tour with both Poison and as a solo act.",
  "brian-dewan":
    "American singer-songwriter, instrument builder, and visual artist based in Catskill, New York. Distinguished by his minimalist songwriting, deliberately archaic vocal style, and use of self-built instruments — including the \"Dewanatron\" series of analog synthesizers (built with cousin Leon Dewan).\n\nReleased multiple studio albums starting with *Tells the Story* (1993). The Dewanatrons have been featured in art museums and electronic-music festivals; his songs have been used in PBS specials and documentary work. Continues to perform and record sporadically.",
  "bring-me-the-horizon":
    "English rock band formed in Sheffield in 2004. Long-running lineup: Oli Sykes (vocals), Lee Malia (guitar), Matt Kean (bass), Matt Nicholls (drums), and Jordan Fish (keyboards, 2013-2023). The band's style has evolved from deathcore (debut) through metalcore to alternative rock to pop.\n\nSeven studio albums between *Count Your Blessings* (2006) and *Post Human: Survival Horror* (2020). Commercial peak: *Sempiternal* (2013), *That's the Spirit* (2015, a #1 UK album), and *Amo* (2019, also a #1 UK album). Jordan Fish departed in late 2023; the band continues.",
  "brownie-mary":
    "American rock band formed in San Diego in the early 1990s. Limited national exposure; primarily a regional act in the Southern California alternative-rock and post-hardcore scenes.",
  "bruce-hornsby":
    "American singer-songwriter, pianist, and bandleader born November 23, 1954, in Williamsburg, Virginia. First gained prominence with his band Bruce Hornsby and the Range (1986-1991). Subsequently joined the Grateful Dead as a touring keyboardist (1990-1995) and pursued an extensive solo and collaborative career.\n\nReleased over 25 studio albums spanning piano-driven pop, jazz, country, and classical material. Best-known releases include *The Way It Is* (1986, the title track was a #1 single), *Scenes from the Southside* (1988), and *Hot House* (1995). Won the 1986 Grammy for Best New Artist. Continues to record and tour with various ensembles.",
  "bryan-adams":
    "Canadian singer-songwriter and photographer born November 5, 1959, in Kingston, Ontario. Among the most commercially successful Canadian recording artists in history, with an estimated 75 million-plus albums sold worldwide.\n\nReleased 16 studio albums between *Bryan Adams* (1980) and *So Happy It Hurts* (2022). Commercial peak: *Reckless* (1984, featuring \"Run to You,\" \"Summer of '69,\" \"Heaven\"), *Into the Fire* (1987), and *Waking Up the Neighbours* (1991, featuring the international hit \"(Everything I Do) I Do It for You\" from *Robin Hood: Prince of Thieves*).",
  "buck-owens-and-his-buckaroos":
    "American country band led by Buck Owens (1929-2006). Pioneer of the \"Bakersfield sound\" — a stripped-down, twangy honky-tonk approach in opposition to the polished Nashville sound. The Buckaroos backing band — particularly guitarist Don Rich (1941-1974) — was as identifiable to fans as Owens himself.\n\nReleased dozens of albums between *Buck Owens* (1961) and *Hot Dog!* (1988). Career peak: 21 #1 US country singles between 1963 and 1972. Co-hosted *Hee Haw* (1969-1986). Don Rich died in a motorcycle accident in 1974, a blow Owens described as devastating. Inducted into the Country Music Hall of Fame in 1996.",
  "buffalo-springfield":
    "American-Canadian rock band formed in Los Angeles in 1966 by Stephen Stills, Neil Young, Richie Furay (vocals/guitar), Bruce Palmer (bass), and Dewey Martin (drums). Active just two years (1966-1968), but a defining act of the late-1960s folk-rock scene and the starting point for multiple subsequent supergroups.\n\nThree studio albums: *Buffalo Springfield* (1966), *Buffalo Springfield Again* (1967), and *Last Time Around* (1968). Best-known single: \"For What It's Worth\" (1967), written by Stills. Members went on to Crosby, Stills, Nash & Young (Stills, Young); Poco (Furay); the Souther-Hillman-Furay Band; and other projects. Inducted into the Rock and Roll Hall of Fame in 1997.",
  "built-to-spill":
    "American indie rock band formed in Boise, Idaho in 1992 by Doug Martsch (vocals/guitar). Long-running lineup also includes Brett Netson (guitar) and various rhythm sections. The band's touring lineup has rotated significantly.\n\nNine studio albums starting with *Ultimate Alternative Wavers* (1993). Critical peak: *There's Nothing Wrong with Love* (1994), *Perfect from Now On* (1997), and *Keep It Like a Secret* (1999). Released primarily on Warner Bros. and Up Records. The band has been continuously active.",
  "burl-ives":
    "American actor, author, and singer (1909-1995). Born in Hunt City, Illinois. Career spanned folk music, country, pop standards, and acting — including a 1958 Academy Award for Best Supporting Actor in *The Big Country*. Best known to modern audiences as the voice of Sam the Snowman (and singer of the title song) in the 1964 stop-motion TV special *Rudolph the Red-Nosed Reindeer*.\n\nReleased dozens of albums between the 1940s and 1980s. Best-known songs include \"Big Rock Candy Mountain,\" \"A Little Bitty Tear,\" \"Funny Way of Laughin'\" (1962 Grammy winner), \"Holly Jolly Christmas,\" and \"Silver and Gold.\" The latter two became Christmas standards.",
  "burn":
    "American hardcore band formed in New York City in 1989. Lineup: Chaka Malik (vocals), Gavin Van Vlack (guitar), Alex Napack (bass), and Alan Cage (drums). Considered foundational to the NYHC \"post-hardcore\" sound that followed.\n\nReleased one EP in the original era — the self-titled *Burn* (1990) on Revelation Records — plus the LP *Last Great Sea* (2017) after a reunion. The band's brief original tenure was deeply influential; Van Vlack and Cage went on to Absolution and Beyond, with Cage later joining Quicksand. Malik later led Orange 9mm.",
  "bush":
    "English rock band formed in London in 1992. Long-running lineup centered on Gavin Rossdale (vocals/guitar). Other key members included Nigel Pulsford (guitar, 1992-2002), Dave Parsons (bass, 1992-2002), and Robin Goodridge (drums, 1992-2002). One of the few British bands to achieve more commercial success in the US than at home.\n\nNine studio albums starting with *Sixteen Stone* (1994, multi-platinum in the US, featuring \"Glycerine,\" \"Comedown,\" and \"Machinehead\"). Subsequent peak: *Razorblade Suitcase* (1996) and *The Science of Things* (1999). The band dissolved in 2002 and reformed in 2010 with a new lineup behind Rossdale.",
  "capleton":
    "Jamaican reggae and dancehall artist born Clifton George Bailey III on April 13, 1967, in St. Mary, Jamaica. Often called \"the Prophet\" or \"the Fireman.\" Distinguished by his Rastafarian spiritual content and fiery delivery.\n\nReleased over 20 studio albums starting with *Lotion Man* (1991). Commercial peak: *Prophecy* (1995), *I-Testament* (1997), *More Fire* (2000), and *Still Blazin'* (2002). Has been a consistent fixture in dancehall through the 2000s and 2010s.",
  "carole-king":
    "American singer-songwriter and pianist born February 9, 1942, in New York City. First gained prominence as half of the songwriting team Goffin/King (with then-husband Gerry Goffin) — they wrote over 100 charting songs between 1959 and 1968, including \"Will You Love Me Tomorrow,\" \"The Loco-Motion,\" and \"(You Make Me Feel Like) A Natural Woman.\"\n\nLaunched her solo recording career with *Writer* (1970); follow-up *Tapestry* (1971) sold over 25 million copies worldwide and won four Grammy Awards. Released 14 subsequent solo studio albums through *A Holiday Carole* (2011). Inducted into the Rock and Roll Hall of Fame three times — as a solo artist (2021), with Goffin (1990), and as a Lyricist Hall of Fame inductee.",
  "cast-iron-hike":
    "American hardcore band formed in New Haven, Connecticut in 1991. Long-running lineup centered on vocalist Joe Vasquez. Style draws on hardcore punk, post-hardcore, and emo.\n\nTwo studio albums: *Watch It Burn* (1996) and *Pig Iron* (1998). Released on Victory Records. The band has been inactive since the early 2000s.",
  "cathedral":
    "English doom metal band formed in Coventry in 1989 by Lee Dorrian (vocals, formerly of Napalm Death) and Garry \"Gaz\" Jennings (guitar). Pioneers of the British doom metal revival alongside Paradise Lost and My Dying Bride.\n\nTen studio albums between *Forest of Equilibrium* (1991) and *The Last Spire* (2013). Best-known releases include *The Ethereal Mirror* (1993) and *Endtyme* (2001). Dorrian founded Rise Above Records (which has released material by Orange Goblin, Electric Wizard, and many others). The band performed a farewell tour in 2013.",
  "cave-in":
    "American rock band formed in Methuen, Massachusetts in 1995. Long-running lineup: Stephen Brodsky (vocals/guitar), Adam McGrath (guitar), Caleb Scofield (bass, died 2018), and John-Robert Conners (drums). Style has shifted across albums from hardcore through post-metal to alternative rock and back.\n\nSeven studio albums between *Until Your Heart Stops* (1998) and *Heavy Pendulum* (2022). Best-known releases include *Jupiter* (2000) and *Antenna* (2003, their major-label debut). Scofield died in a car accident in March 2018; the band returned with *Final Transmission* (2019) featuring his final demo recordings.",
  "cell":
    "American alternative rock band formed in New York City in 1989. Lineup: Jerry Dirienzo (vocals/guitar), Ian James (guitar), David Motamed (bass, also of Das Damen), and Keith Nealy (drums).\n\nTwo studio albums: *Slo*Blo* (1991) and *Living Room* (1994). Released primarily on Ecstatic Peace! (Thurston Moore's label) and DGC. The band toured with Sonic Youth, Smashing Pumpkins, and Helmet during the early-1990s alternative wave. Dissolved in the mid-1990s.",
  "chely-wright":
    "American country singer-songwriter born October 25, 1970, in Kansas City, Missouri. Came out as a lesbian in 2010 — one of the first major-label country artists to do so. The disclosure significantly impacted her commercial standing in the country market.\n\nReleased nine studio albums between *Woman in the Moon* (1994) and *Revival* (2019). Commercial peak: *Single White Female* (1999, featuring the title track, her only #1 country single) and *Never Love You Enough* (2001). Her 2010 memoir *Like Me: Confessions of a Heartland Country Singer* chronicled her experiences in country music.",
  "cherry-poppin-daddies":
    "American swing band formed in Eugene, Oregon in 1989 by Steve Perry (vocals/guitar; not the Journey singer). Lineup also includes Daniel Schmid (bass) and various horns. Style fuses swing, ska, jump blues, jazz, and punk.\n\nEight studio albums starting with *Ferociously Stoned* (1990). Commercial breakthrough: *Zoot Suit Riot* (1997), the title track of which became one of the defining hits of the late-1990s swing revival, selling over 3 million copies on the compilation re-release. Subsequent releases include *Soul Caddy* (2000), *Susquehanna* (2008), and *Bigger Life* (2019).",
  "chevelle":
    "American rock band formed in Grayslake, Illinois in 1995 by brothers Pete Loeffler (vocals/guitar), Sam Loeffler (drums), and Joe Loeffler (bass, 1995-2005). Bassists since Joe's departure include Geno Lenardo, Dean Bernardini (Pete and Sam's brother-in-law, 2005-2022), and Kemble Walters.\n\nTen studio albums starting with *Point #1* (1999). Commercial peak: *Wonder What's Next* (2002, multi-platinum, featuring \"The Red\" and \"Send the Pain Below\"), *This Type of Thinking (Could Do Us In)* (2004), *Vena Sera* (2007), and *Sci-Fi Crimes* (2009). Continuously active.",
  "chic":
    "American disco band formed in New York City in 1976 by guitarist Nile Rodgers and bassist Bernard Edwards (died 1996). Distinguished by Edwards's slap-bass and Rodgers's chicken-scratch rhythm guitar — both pioneering the sound that would shape disco and influence countless subsequent funk, R&B, and pop productions.\n\nReleased six studio albums in the original era between *Chic* (1977) and *Believer* (1983). Best-known releases include *C'est Chic* (1978, featuring \"Le Freak\") and *Risqué* (1979, featuring \"Good Times\" — the bassline of which became the foundation of the Sugarhill Gang's \"Rapper's Delight\"). Edwards and Rodgers also produced for Sister Sledge, Diana Ross, David Bowie, and Madonna. Inducted into the Rock and Roll Hall of Fame in 2017.",
  "chimaira":
    "American metalcore band formed in Cleveland in 1998. Long-running lineup centered on Mark Hunter (vocals) and Rob Arnold (guitar). Multiple lineup changes through their career; Hunter has been the only continuous member.\n\nSeven studio albums between *Pass Out of Existence* (2001) and *Crown of Phantoms* (2013). Best-known releases include the self-titled third album (2005, featuring \"Nothing Remains\") and *Resurrection* (2007). The band dissolved in 2014.",
  "chloe-halle":
    "American R&B duo Chloe x Halle, sisters Chloe Bailey (born 1998) and Halle Bailey (born 2000). Discovered by Beyoncé after their YouTube covers gained viral attention; signed to her Parkwood Entertainment in 2015.\n\nReleased two studio albums: *The Kids Are Alright* (2018) and *Ungodly Hour* (2020). Both sisters have since pursued individual careers in music, acting, and film — Halle starred as Ariel in *The Little Mermaid* (2023); Chloe released her debut solo album *In Pieces* (2023). The duo has continued to perform together intermittently.",
  "chris-botti":
    "American jazz trumpeter born October 12, 1962, in Portland, Oregon. Among the most commercially successful instrumental jazz artists of the 2000s and 2010s. Distinguished by his lyrical melodic approach and frequent collaborations with pop and classical artists.\n\nReleased over a dozen studio albums starting with *First Wish* (1995). Commercial peak: *To Love Again: The Duets* (2005), *Italia* (2007), and the multi-platinum *Chris Botti in Boston* (2009). Has collaborated with Sting, Tony Bennett, Andrea Bocelli, and Yo-Yo Ma. Won the 2013 Grammy for Best Pop Instrumental Album for *Impressions* (2012).",
  "christina-aguilera":
    "American singer-songwriter born December 18, 1980, in Staten Island, New York. Among the leading pop singers of the late 1990s and 2000s; distinguished by her vocal range and willingness to explore stylistic territory beyond mainstream pop.\n\nReleased nine studio albums between *Christina Aguilera* (1999) and *Aguilera* (2022). Commercial peak: *Christina Aguilera* (1999, featuring \"Genie in a Bottle\" and \"What a Girl Wants\"), *Stripped* (2002, featuring \"Beautiful\" and \"Fighter\"), and *Back to Basics* (2006). Five Grammy Awards. Coach on *The Voice* (US) for four seasons.",
  "chubby-checker":
    "American singer born Ernest Evans on October 3, 1941, in Spring Gulley, South Carolina. Career-defining single \"The Twist\" (1960) launched a worldwide dance craze and has been the only single ever to reach #1 on the Billboard Hot 100 in two separate chart runs (1960 and 1962).\n\nReleased over 25 studio albums between *Twist with Chubby Checker* (1960) and *Towards the Future* (1985). Other notable singles include \"Pony Time\" (1961, #1), \"Limbo Rock\" (1962), and the Dee Dee Sharp duet \"Slow Twistin'\" (1962). Continues to perform live; *Billboard* magazine named \"The Twist\" the #1 song of the rock era for the 50-year period of 1956-2006.",
  "clint-black":
    "American country singer-songwriter born February 4, 1962, in Long Branch, New Jersey. Among the leading neo-traditional country artists of the late 1980s and 1990s.\n\nReleased over a dozen studio albums starting with *Killin' Time* (1989), which produced four consecutive #1 country singles and won the Country Music Association's Album of the Year. Subsequent peaks: *Put Yourself in My Shoes* (1990), *The Hard Way* (1992), and *No Time to Kill* (1993). Married to actress Lisa Hartman Black; the couple has frequently collaborated.",
  "coheed-and-cambria":
    "American progressive rock band formed in Nyack, New York in 1995 (originally as Shabütie). Long-running lineup: Claudio Sanchez (vocals/guitar), Travis Stever (guitar), Josh Eppard (drums), and various bassists. Distinguished by their interconnected concept albums set in \"the Amory Wars\" — a sci-fi universe Sanchez has elaborated across multiple comics and novels.\n\nTen studio albums starting with *The Second Stage Turbine Blade* (2002). Best-known releases include *In Keeping Secrets of Silent Earth: 3* (2003), *Good Apollo, I'm Burning Star IV, Volume One: From Fear Through the Eyes of Madness* (2005), and *The Color Before the Sun* (2015) — the latter their only non-concept album.",
  "cold-water-flat":
    "American alternative rock band formed in Amherst, Massachusetts in 1989. Lineup: Paul Janovitz (vocals/guitar), Ted Silva (bass), and Paul Harding (drums). Janovitz is the younger brother of Buffalo Tom's Bill Janovitz.\n\nTwo studio albums: *Listen* EP (1992) and the self-titled debut (1994). Released on MCA. The band toured with Sloan, Sebadoh, and Lemonheads in the early 1990s before disbanding.",
  "collective-soul":
    "American rock band formed in Stockbridge, Georgia in 1992. Long-running lineup centered on brothers Ed Roland (vocals/guitar) and Dean Roland (rhythm guitar). Drummer Will Turpin (bass) has been continuous since formation.\n\nEleven studio albums starting with *Hints Allegations and Things Left Unsaid* (1994). Commercial peak: *Collective Soul* (1995, featuring \"December\" and \"The World I Know\") and *Disciplined Breakdown* (1997). Continuously active and prolific into the 2020s.",
  "common":
    "American rapper and actor born Lonnie Rashid Lynn on March 13, 1972, in Chicago. One of the most respected lyricists in conscious hip-hop. Long-running collaborations with producers No I.D., J Dilla, and Kanye West.\n\nReleased 14 studio albums between *Can I Borrow a Dollar?* (1992) and *And Then We Pray* (2023). Critical peak: *Resurrection* (1994), *Like Water for Chocolate* (2000), and *Be* (2005). Won the 2015 Academy Award for Best Original Song (\"Glory,\" with John Legend) for *Selma*. Pursues a parallel acting career with roles in *Hell on Wheels*, *John Wick: Chapter 2*, and the *Now You See Me* franchise.",
  "concrete-blonde":
    "American rock band formed in Los Angeles in 1982 as Dream 6. Lineup: Johnette Napolitano (vocals/bass), James Mankey (guitar), and various drummers — Harry Rushakoff was the most consistent (1986-1994). Distinguished by Napolitano's powerful contralto and the band's goth-tinged alternative rock approach.\n\nSix studio albums between the self-titled 1986 debut and *Mojave* (2004). Best-known releases include *Bloodletting* (1990, featuring \"Joey\") and *Walking in London* (1992). Released primarily on IRS and Capitol. The band has been intermittently active since their 2002 reunion.",
  "coney-hatch":
    "Canadian hard rock band formed in Toronto in 1980. Long-running lineup: Carl Dixon (vocals/guitar), Andy Curran (vocals/bass), Steve Shelski (guitar), and Dave Ketchum (drums). Named after the Coney Hatch psychiatric hospital in London.\n\nFour studio albums starting with the self-titled debut (1982). Best-known releases include *Outa Hand* (1983) and *Friction* (1985). The band split in 1985 and reunited for tours and the 2013 album *Four*. Dixon was severely injured in a 2008 car accident in Australia but recovered.",
  "corbinhanner":
    "American country duo Bob Corbin and Dave Hanner, formed in Pittsburgh in 1980. Both members are accomplished songwriters; their material has been recorded by Alabama, Mel Tillis, the Oak Ridge Boys, and many other country artists.\n\nReleased five studio albums between *For the Sake of the Song* (1980) and *Black & White Photograph* (1992). Best-known release: *Corbin/Hanner* (1990). The duo's commercial peak coincided with substantial regional touring in the Mid-Atlantic and Southeastern US.",
  "corrosion-of-conformity":
    "American rock band formed in Raleigh, North Carolina in 1982. Long-running lineup centered on Pepper Keenan (vocals/guitar, 1989-2006, 2014-present), Woody Weatherman (guitar), and Reed Mullin (drums, died 2020). Vocalists: Eric Eycke (1982-1984), Mike Dean (1984-1988, 1993-1995), Karl Agell (1988-1993), and Keenan since 1989.\n\nTen studio albums between *Eye for an Eye* (1984) and *No Cross No Crown* (2018). Stylistic eras: 1980s hardcore-crossover, 1990s Southern/sludge metal, 2010s back to hardcore-meets-Southern-metal. Best-known releases include *Blind* (1991), *Deliverance* (1994), and *America's Volume Dealer* (2000).",
  "cradle-of-filth":
    "English extreme metal band formed in Suffolk in 1991. Long-running lineup centered on vocalist Dani Filth. Multiple lineup changes through the band's career; Dani is the only continuous member. Style fuses black metal, gothic metal, and symphonic metal with horror-themed lyrics.\n\nFourteen studio albums starting with *The Principle of Evil Made Flesh* (1994). Best-known releases include *Dusk... and Her Embrace* (1996), *Cruelty and the Beast* (1998), and *Midian* (2000). The band's elaborate stage productions, gothic imagery, and Dani's distinctive shriek-and-growl vocals have made them one of the most visible extreme metal acts globally.",
  "crashdog":
    "American Christian hardcore band formed in Chicago in 1989. Lineup: Spike Nard (vocals), Mark Hochberg (guitar), Steve Plowman (bass), and Mike Hochberg (drums). Distinguished by their politically charged lyrics addressing poverty, social justice, and Christian liberation theology.\n\nFour studio albums between *Cashist System* (1992) and *Outer Crust* (1996). Released primarily on Grrr Records, the Christian-music label associated with Resurrection Band's Glenn Kaiser. The band was associated with the Jesus People USA community in Chicago.",
  "crazy-horse":
    "American rock band formed in 1969 as the longtime backing band of Neil Young. Long-running lineup: Frank \"Poncho\" Sampedro (guitar, 1975-2014), Billy Talbot (bass), and Ralph Molina (drums) — Talbot and Molina have been continuous since formation. Original guitarist Danny Whitten (1969-1972) died of an overdose in November 1972.\n\nReleased multiple studio albums under their own name starting with *Crazy Horse* (1971). As Neil Young's backing band, performed on his classics *Everybody Knows This Is Nowhere* (1969), *After the Gold Rush* (1970), *Tonight's the Night* (1975), *Zuma* (1975), *Rust Never Sleeps* (1979), and dozens of subsequent Young albums.",
  "creation-is-crucifixion":
    "American grindcore band formed in Pittsburgh in 1995. Long-running lineup centered on vocalist Bruce Reisig and guitarist Brett Wenger. Distinguished by their cyberpunk-themed lyrics and the technical complexity of their compositions.\n\nThree studio albums between *Automata* (1998) and *Descent from Heaven* (1999). Released primarily on Hewhocorrupts Inc. and Sound Pollution. The band was on hiatus through much of the 2000s.",
  "creedence-clearwater-revival":
    "American rock band formed in El Cerrito, California in 1959 (originally as the Blue Velvets). Lineup: John Fogerty (vocals/guitar), Tom Fogerty (rhythm guitar, his brother, 1959-1971, died 1990), Stu Cook (bass), and Doug Clifford (drums). Best known as CCR. Among the most commercially successful and influential American rock bands of the late 1960s.\n\nSeven studio albums in three years (1968-1972): *Creedence Clearwater Revival* (1968), *Bayou Country* (1969), *Green River* (1969), *Willy and the Poor Boys* (1969), *Cosmo's Factory* (1970), *Pendulum* (1970), and *Mardi Gras* (1972). John Fogerty wrote nearly all the material — \"Proud Mary,\" \"Bad Moon Rising,\" \"Fortunate Son,\" \"Born on the Bayou,\" \"Have You Ever Seen the Rain,\" and many more. Inducted into the Rock and Roll Hall of Fame in 1993.",
  "cro-mags":
    "American hardcore band formed in New York City in 1981. Lineup: John Joseph (vocals), Harley Flanagan (bass/vocals), and various other members. Considered foundational to New York hardcore (NYHC) and the metallic-hardcore crossover.\n\nFive studio albums starting with *The Age of Quarrel* (1986). Best-known releases include *Best Wishes* (1989) and *Alpha-Omega* (1992). Long-running legal and personal disputes between John Joseph and Harley Flanagan have led to two competing \"Cro-Mags\" touring entities: Cro-Mags JM (led by Joseph) and Cro-Mags (led by Flanagan).",
  "crosby-stills-nash-young":
    "American supergroup formed in Los Angeles in 1969. Lineup: David Crosby (vocals/guitar, formerly of the Byrds; died 2023), Stephen Stills (vocals/guitar, formerly of Buffalo Springfield), Graham Nash (vocals/guitar, formerly of the Hollies), and Neil Young (vocals/guitar, also formerly of Buffalo Springfield). The full four-member lineup performed intermittently; Young's participation has been particularly sporadic.\n\nTwo full-quartet studio albums in the early era: *Déjà Vu* (1970) and *Looking Forward* (1999). The trio CSN released several additional albums. Their second public performance (after a single 1969 LA Forum show) was at Woodstock in August 1969. Inducted into the Rock and Roll Hall of Fame in 1997.",
  "crossfaith":
    "Japanese metalcore band formed in Osaka in 2006. Long-running lineup: Kenta Koie (vocals), Kazuki Takemura (guitar), Hiroki Ikegawa (bass), and Tatsuya Amano (drums, 2006-2020). Style fuses metalcore with electronic music, including extensive use of synthesizers and drum machines.\n\nFive studio albums starting with *The Artificial Theory for the Dramatic Beauty* (2009). Commercial peak: *Apocalyze* (2013) and *Xeno* (2015). The band has been a fixture on European and Japanese metal festivals; significant US touring with Bring Me the Horizon and Architects.",
  "crowded-house":
    "Australian-New Zealand rock band formed in Melbourne in 1985. Long-running lineup: Neil Finn (vocals/guitar), Paul Hester (drums, 1985-1994, died 2005), and Nick Seymour (bass). Various second guitarists/keyboardists have included Mark Hart, Tim Finn (Neil's brother, formerly of Split Enz), and Neil's son Liam Finn.\n\nSeven studio albums between the self-titled 1986 debut and *Gravity Stairs* (2024). Commercial peak: *Crowded House* (1986, featuring \"Don't Dream It's Over\"), *Temple of Low Men* (1988), and *Woodface* (1991). Hester died by suicide in 2005. The band has continued under Neil Finn's leadership.",
  "crown-of-thorns":
    "American glam metal band formed in New York City in 1991 by guitarist Jean Beauvoir (formerly of the Plasmatics and a successful 1980s solo artist/songwriter). Long-running lineup also includes Micki Free (guitar) and various rhythm sections.\n\nReleased four studio albums starting with the self-titled debut (1993). Best-known releases include *Lost Cathedral* (1995) and *Karma* (2002). Particularly successful in Europe and Japan. Beauvoir's parallel career has included songwriting and producing for KISS, the Ramones, and various other artists.",
  "cultus-black":
    "American metal band formed in the mid-2010s. Style draws on industrial metal and dark electronic music. Limited public information available; appears to be an independent project tied to the underground extreme-metal scene.",
  "cyndi-lauper":
    "American singer-songwriter born June 22, 1953, in Brooklyn, New York. Distinguished by her four-octave vocal range, deliberately unconventional fashion sense, and the way her recordings consistently spanned pop, rock, dance, blues, country, and standards.\n\nReleased twelve solo studio albums between *She's So Unusual* (1983) and *Detour* (2016). Commercial peak: *She's So Unusual* (the first debut album by a female solo artist to produce four top-five US singles — \"Girls Just Want to Have Fun,\" \"Time After Time,\" \"She Bop,\" and \"All Through the Night\") and *True Colors* (1986). Co-wrote the songs for the Broadway musical *Kinky Boots* (2013), winning a Tony Award. Inducted into the Songwriters Hall of Fame in 2015.",
  "cypress-hill":
    "American hip-hop group formed in South Gate, California in 1988. Lineup: B-Real (Louis Freese, vocals), Sen Dog (Senen Reyes, vocals), DJ Muggs (Lawrence Muggerud, production), and Eric \"Bobo\" Correa (percussion, since 1995). Pioneers of West Coast hip-hop and the first Latino rap group to achieve major US commercial success.\n\nNine studio albums starting with *Cypress Hill* (1991). Commercial peak: the debut and *Black Sunday* (1993, featuring \"Insane in the Brain\"). The 1995 album *Cypress Hill III: Temples of Boom* shifted toward darker, slower production. The group has been outspokenly pro-cannabis throughout its career, contributing to the cultural mainstreaming of marijuana legalization.",
  "dri":
    "American crossover thrash band formed in Houston, Texas in 1982 as D.R.I. — \"Dirty Rotten Imbeciles.\" Long-running lineup centered on brothers Spike Cassidy (guitar, 1982-2018) and Kurt Brecht (vocals). Considered foundational to the hardcore-thrash crossover alongside Suicidal Tendencies and Corrosion of Conformity.\n\nNine studio albums starting with *Dirty Rotten LP* (1983). Best-known releases include *Dealing with It!* (1985), *Crossover* (1987, the album that effectively named the genre), and *4 of a Kind* (1988). Spike Cassidy was diagnosed with colon cancer in 2008 and has periodically halted touring for treatment.",
  "dad-brains":
    "American pop-punk band formed by members of various 1990s/2000s skate-punk and pop-punk acts as a side project celebrating fatherhood. Members typically include musicians from bands like NOFX, Lagwagon, and Strung Out.\n\nReleased multiple EPs and singles; the title \"I'm Old\" (2018) became something of a meme in the broader pop-punk community.",
  "dallas-taylor":
    "American drummer (1948-2015). Best known as the drummer on Crosby, Stills & Nash's eponymous 1969 debut, as well as Stephen Stills's solo work. Subsequent recurring health issues — including a liver transplant — shaped much of his post-touring career.\n\nDrummed on *Crosby, Stills & Nash* (1969) and on multiple early Stills solo albums. Worked as a substance-abuse counselor for many years after his own recovery. Released the autobiography *Prisoner of Woodstock* (1994) chronicling the late-1960s and early-1970s music scene.",
  "danzig":
    "American heavy metal band formed in Lodi, New Jersey in 1987 by Glenn Danzig (vocals, previously of the Misfits and Samhain). Long-running lineup also included John Christ (guitar, 1987-1995), Eerie Von (bass, 1987-1995), and Chuck Biscuits (drums, 1987-1994). Style draws on heavy metal, blues, and dark gothic imagery.\n\nTwelve studio albums between *Danzig* (1988) and *Danzig Sings Elvis* (2020). Commercial peak: *Danzig* (1988), *Danzig II: Lucifuge* (1990), *Danzig III: How the Gods Kill* (1992), and *Danzig 4* (1994, featuring \"Mother\" — which became Danzig's only top-40 hit after MTV picked it up in 1994). Danzig has also pursued the comic-book publishing imprint Verotik.",
  "dave-alvin":
    "American singer-songwriter and guitarist born November 11, 1955, in Downey, California. First gained prominence as guitarist of the Blasters (1979-1986) — the band he co-founded with his brother Phil. Launched a successful solo career in 1986.\n\nReleased over a dozen solo studio albums starting with *Romeo's Escape* (1987). Best-known releases include *Blue Blvd* (1991), *King of California* (1994), *Public Domain: Songs from the Wild Land* (2000, which won the Grammy for Best Contemporary Folk Album), and *Eleven Eleven* (2011). Periodically reunites with his brother Phil for tours and the album *Common Ground: Dave Alvin and Phil Alvin Play and Sing the Songs of Big Bill Broonzy* (2014).",
  "dave-matthews-tim-reynolds":
    "Duo concerts/recordings of Dave Matthews (vocals/guitar, of the Dave Matthews Band) and Tim Reynolds (guitar). Reynolds has been a frequent collaborator with the Dave Matthews Band since the early 1990s. The acoustic-duo format has produced several commercially successful live releases.\n\nKey releases include *Live at Luther College* (1999), *Live at Radio City* (2007), and *Live in Las Vegas* (2010). The duo format strips down the Dave Matthews Band's material to two acoustic guitars and vocals, with extended improvisational interplay between Matthews and Reynolds.",
  "david-gans":
    "American singer-songwriter, journalist, and Grateful Dead historian born in Long Beach, California in 1953. Long-running host of the syndicated radio program *The Grateful Dead Hour* (since 1985); author of multiple books on the Grateful Dead.\n\nReleased multiple studio albums of original material starting in the 1980s. Often performs Grateful Dead material in acoustic configurations alongside his own songs. Continues to host and produce Grateful Dead-related radio and podcast content.",
  "david-grisman":
    "American mandolinist born March 17, 1945, in Hackensack, New Jersey. Pioneer of \"Dawg music\" — his own fusion of bluegrass, jazz, gypsy swing, Latin, and folk. Long-running collaborator with Jerry Garcia of the Grateful Dead, including the duo album *Garcia/Grisman* (1991) and several others.\n\nReleased over 30 studio albums starting with *The David Grisman Quintet* (1977). Best-known releases include the Grisman Quintet's foundational work and the long-running *Acoustic Disc* label catalog (which Grisman founded). Continues to record and tour.",
  "david-grusin":
    "American composer, arranger, pianist, and bandleader born June 26, 1934, in Littleton, Colorado. Among the most prolific American film composers of the 1970s and 1980s. Won the 1989 Academy Award for Best Original Score for *The Milagro Beanfield War*.\n\nKey film scores include *The Goodbye Girl* (1977), *On Golden Pond* (1981), *Tootsie* (1982), and *The Firm* (1993). Also a noted jazz pianist; co-founded GRP Records with Larry Rosen in 1976. Released over 20 albums as a leader. Ten Grammy Awards.",
  "davie-allan":
    "American guitarist born February 21, 1943, in Glendale, California. Pioneer of \"fuzz guitar\" rock — distorted, instrumental garage rock that became the signature sound of late-1960s American \"biker films.\" His band Davie Allan and the Arrows scored many of the era's exploitation films.\n\nReleased numerous albums between *The Wild Angels* soundtrack (1966) and recent releases. Best-known recordings include \"Blue's Theme\" (1966), \"Apache '65,\" and \"Devil's Angels.\" Continues to record and perform sporadically; has remained a touchstone for surf-rock and garage-rock revivalists.",
  "davy-jones":
    "English actor and singer (1945-2012). Born in Manchester, England. Best known as a member of the Monkees (1965-2012, intermittently), the made-for-television rock band assembled for the NBC sitcom of the same name.\n\nReleased multiple solo studio albums starting with *David Jones* (1965, released before his Monkees fame). Best-known solo work: *Davy Jones* (1971). The Monkees-era catalog and the 1986 nostalgia-tour reunion defined the public's perception of him. Died of a heart attack in February 2012.",
  "dawes":
    "American folk-rock band formed in Los Angeles in 2009. Long-running lineup centered on brothers Taylor Goldsmith (vocals/guitar) and Griffin Goldsmith (drums). Other members have rotated, with Wylie Gelber (bass) the longest-tenured non-brother.\n\nEight studio albums starting with *North Hills* (2009). Best-known releases include *Nothing Is Wrong* (2011), *Stories Don't End* (2013), and *We're All Gonna Die* (2016). Taylor Goldsmith is married to actress and musician Mandy Moore; they have collaborated on multiple projects.",
  "dayinthelife":
    "American hardcore band formed in Bensalem, Pennsylvania in 1995. Long-running lineup centered on vocalist Chris Strunk. Often stylized as \"dayinthelife...\" with lowercase letters and ellipsis. Style draws on hardcore punk, post-hardcore, and emotional hardcore (emo).\n\nFive studio albums between *Self-Realization* (1996) and *Sleeper* (2001). Released primarily on Trustkill Records during the label's early underground hardcore peak. The band has been inactive since the early 2000s.",
};

async function main() {
  const dryRun = process.argv.includes("--dry-run");
  const force = process.argv.includes("--force");
  const { containers } = await import("../lib/cosmos");
  const { getStoredArtist } = await import("../lib/artists");

  let written = 0;
  let skipped = 0;
  let missing = 0;

  for (const [slug, description] of Object.entries(DESCRIPTIONS)) {
    const existing = await getStoredArtist(slug);
    if (!existing) {
      console.log(`✗ ${slug}: no stored doc found`);
      missing += 1;
      continue;
    }
    if (existing.description && !force) {
      console.log(`↷ ${slug}: already has description — skipping`);
      skipped += 1;
      continue;
    }
    if (dryRun) {
      console.log(`◌ ${slug}: would write ${description.length} chars`);
      written += 1;
      continue;
    }
    const updated = {
      ...existing,
      description,
      updatedAt: new Date().toISOString(),
    };
    await containers.artists.item(slug, slug).replace(updated);
    console.log(`✓ ${slug}: ${description.length} chars`);
    written += 1;
  }

  console.log(`\nDone. written=${written} skipped=${skipped} missing=${missing}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
