import { config as loadEnv } from "dotenv";
loadEnv({ path: ".env.local" });

const DESCRIPTIONS: Record<string, string> = {
  "elo":
    "Same artist as Electric Light Orchestra — different Discogs/setlist.fm credit variation. English rock band formed in Birmingham in 1970 by Jeff Lynne, Roy Wood, and Bev Bevan. The band's signature sound combined Beatles-influenced melody, classical strings, and emerging synthesizer technology. Thirteen studio albums under the original ELO banner between 1971 and 1986. Inducted into the Rock and Roll Hall of Fame in 2017.",
  "front-line-assembly":
    "Canadian industrial band formed in Vancouver in 1986 by Bill Leeb (vocals/programming, formerly of Skinny Puppy). Long-running collaborator Rhys Fulber (keyboards/programming) has been Leeb's primary partner. Pioneers of industrial dance and EBM-influenced electronic body music.\n\nReleased 17 studio albums starting with *The Initial Command* (1987). Critical peak: *Caustic Grip* (1990), *Tactical Neural Implant* (1992), *Millennium* (1994), and *Hard Wired* (1995). Leeb has also led the parallel projects Delerium (with Fulber) and Noise Unit.",
  "fuel":
    "American rock band formed in Harrisburg, Pennsylvania in 1989 (originally as Small the Joy). Long-running lineup centered on Carl Bell (guitar/songwriter) and Brett Scallions (vocals, 1994-2006, 2010-present). Style draws on post-grunge and alternative rock.\n\nFive studio albums starting with *Sunburn* (1998, multi-platinum, featuring \"Shimmer\"). Subsequent peaks: *Something Like Human* (2000, featuring \"Hemorrhage (In My Hands)\") and *Natural Selection* (2003). Released *Anomaly* (2024) after a decade-plus gap. Continues to tour.",
  "fugazi":
    "American post-hardcore band formed in Washington, D.C. in 1987. Lineup: Ian MacKaye (vocals/guitar, formerly of Minor Threat), Guy Picciotto (vocals/guitar), Joe Lally (bass), and Brendan Canty (drums). Distinguished by their fiercely independent business model — never charging more than $5-10 for a show, refusing major-label offers, releasing on their own Dischord Records.\n\nSix studio albums between *Repeater* (1990) and *The Argument* (2001). Critical peak: *Repeater*, *In on the Kill Taker* (1993), and *Red Medicine* (1995). The band has been on indefinite hiatus since 2003. The 2003 *Fugazi Live Series* has released over 800 live recordings on Dischord, with proceeds going to the band.",
  "full-blown-aids":
    "American grindcore band formed in Boston in 2005. Short-lived side project of Boston hardcore musicians. Style draws on grindcore, powerviolence, and crust punk. Limited public documentation; primarily known among genre completists.",
  "fun-boy-three":
    "English new wave band formed in Coventry in 1981 by three former Specials members: Terry Hall (vocals), Lynval Golding (guitar/vocals), and Neville Staple (vocals/percussion). Halls's departure from the Specials in 1981 led to the trio's formation.\n\nTwo studio albums: *Fun Boy Three* (1982) and *Waiting* (1983). Best-known singles include \"It Ain't What You Do (It's the Way That You Do It)\" (1982, with Bananarama) and \"Our Lips Are Sealed\" (1983, co-written by Hall with the Go-Go's Jane Wiedlin). The band split in 1983.",
  "fury-of-five":
    "American hardcore band formed in Hamilton, New Jersey in 1992. Long-running lineup centered on vocalist Stikman. Style draws on metallic hardcore and the East Coast \"toughguy\" hardcore scene.\n\nThree studio albums between *Resurrection of the Scrolls* (1996) and *No Reason to Smile* (1999). Released primarily on We Bite America Records. The band has been intermittently active across several reunion stints.",
  "garth-brooks":
    "American country singer-songwriter born February 7, 1962, in Tulsa, Oklahoma. Among the best-selling solo recording artists in US history, with estimated US sales of 170 million-plus units. The integration of stadium-rock theatrics into country touring during his 1990s peak transformed the country-music industry.\n\nReleased 14 studio albums starting with *Garth Brooks* (1989). Commercial peak: *No Fences* (1990), *Ropin' the Wind* (1991, the first country album to debut at #1 on the Billboard 200), *The Chase* (1992), and *In Pieces* (1993). Retired from recording 2001-2014; returned with *Man Against Machine* (2014). Inducted into the Country Music Hall of Fame in 2012.",
  "garth-brooks-with-trisha-yearwood":
    "Garth Brooks's duet/collaboration releases with his wife Trisha Yearwood (born September 19, 1964, in Monticello, Georgia). Yearwood is a major country artist in her own right with 15-plus studio albums and three Grammy Awards.\n\nThe duo has released several joint albums: *Christmas Together* (2016) and *Mum's the Word* (2020), among others. They have also frequently collaborated on the *Friends in Low Places* and *Garth Brooks Live in Las Vegas* concert residency projects.",
  "gathering-field":
    "American rock band formed in Pittsburgh in 1991. Long-running lineup centered on Bill Deasy (vocals) and Dave Brown (guitar). The band's name references Walt Whitman's poetry. Style draws on folk-rock and alternative rock with literary lyrical content.\n\nFour studio albums between *Lost in America* (1995) and *So Close to Heaven* (1999). Best-known release: *Lost in America* (1995), featuring the single \"Lost in America.\" Released primarily on Atlantic Records and Razor & Tie. Deasy has continued to release solo material.",
  "genesis":
    "English rock band formed in Surrey in 1967. Original lineup: Peter Gabriel (vocals, 1967-1975), Tony Banks (keyboards), Mike Rutherford (bass/guitar), Anthony Phillips (guitar, 1967-1970), and various drummers. Phil Collins (drums, vocals after Gabriel) joined in 1970; Steve Hackett (guitar) joined in 1971 and departed in 1977.\n\nFifteen studio albums between *From Genesis to Revelation* (1969) and *Calling All Stations* (1997). The band's stylistic evolution from progressive-rock to pop is unusually pronounced — *Selling England by the Pound* (1973) and *The Lamb Lies Down on Broadway* (1974) represent the Gabriel-era progressive peak; *Invisible Touch* (1986) and *We Can't Dance* (1991) represent the Collins-era pop peak. Inducted into the Rock and Roll Hall of Fame in 2010.",
  "george-tammy":
    "Duet recordings of country singers George Jones (1931-2013) and Tammy Wynette (1942-1998), who were married from 1969 to 1975 and continued to record duets and tour together intermittently afterward.\n\nReleased over a dozen duet albums starting with *We Go Together* (1971). Best-known duet singles include \"We're Gonna Hold On\" (1973), \"Golden Ring\" (1976), and \"Near You\" (1977) — all #1 country hits. The chaotic nature of their marriage and continued collaboration despite their divorce became one of country music's most-discussed personal narratives.",
  "george-clinton-and-the-p-funk-all-stars":
    "American funk collective led by George Clinton (born July 22, 1941, in Kannapolis, North Carolina). The P-Funk All Stars consolidates members of Clinton's earlier bands — Parliament, Funkadelic, the Brides of Funkenstein, and others — into a single performing entity.\n\nReleased multiple studio albums starting with *Urban Dancefloor Guerillas* (1983). Clinton's broader Parliament-Funkadelic catalog has been a foundational influence on hip-hop sampling, with songs from \"Atomic Dog\" to \"Mothership Connection\" appearing in countless productions. Inducted into the Rock and Roll Hall of Fame as part of Parliament-Funkadelic in 1997.",
  "george-harrison":
    "English musician (1943-2001). Born in Liverpool. Best known as lead guitarist of the Beatles (1960-1970), where he was the youngest member and the band's chief Indian-music advocate. Pursued a successful solo career after the Beatles' dissolution and was a founding member of the Traveling Wilburys (with Bob Dylan, Roy Orbison, Tom Petty, and Jeff Lynne).\n\nTwelve solo studio albums between *Wonderwall Music* (1968, while still in the Beatles) and the posthumous *Brainwashed* (2002). Commercial peak: *All Things Must Pass* (1970, a triple LP), *Living in the Material World* (1973), and *Cloud Nine* (1987, featuring \"Got My Mind Set on You\"). Died of lung cancer in November 2001. Inducted into the Rock and Roll Hall of Fame as a solo artist (2004) and with the Beatles (1988).",
  "george-thorogood-the-destroyers":
    "American blues-rock band formed in Wilmington, Delaware in 1973 by guitarist/vocalist George Thorogood. Long-running lineup also includes Jeff Simon (drums, since 1973), Bill Blough (bass, since 1976), Hank Carter (saxophone), and Jim Suhler (guitar).\n\nReleased 17 studio albums starting with *George Thorogood and the Destroyers* (1977). Best-known songs include \"Bad to the Bone\" (1982), \"One Bourbon, One Scotch, One Beer\" (1977, a cover of John Lee Hooker), and \"Move It On Over\" (1978, a cover of Hank Williams). Continues to tour extensively.",
  "gerry-mulligan":
    "American jazz saxophonist and composer (1927-1996). Born in Queens, New York. Among the most influential baritone saxophonists in jazz history; pioneer of the \"cool jazz\" movement alongside Miles Davis (with whom he co-composed parts of the *Birth of the Cool* sessions, 1948-1950).\n\nReleased dozens of albums under his own name between *Mulligan Plays Mulligan* (1951) and *Dragonfly* (1995). The pianoless Gerry Mulligan Quartet with trumpeter Chet Baker (1952-1953) was one of the most-discussed jazz groupings of the early 1950s. Also led big bands, sextets, and septets. Continued to record and perform until shortly before his 1996 death.",
  "gerry-rafferty":
    "Scottish singer-songwriter (1947-2011). Born in Paisley, Scotland. First gained prominence as a member of Stealers Wheel (1972-1975, featuring the hit \"Stuck in the Middle with You\") before launching a solo career.\n\nReleased ten solo studio albums between *Can I Have My Money Back?* (1971) and the posthumous *Life Goes On* (2009). Commercial peak: *City to City* (1978), which sold over 5 million copies on the strength of \"Baker Street\" (with its iconic Raphael Ravenscroft saxophone solo) and \"Right Down the Line.\" Subsequent peak: *Night Owl* (1979).",
  "get-dead":
    "American punk rock band formed in San Francisco in 2007. Long-running lineup centered on Sam King (vocals). Style draws on folk-influenced punk, ska, and street-punk.\n\nFour studio albums starting with *Bad News* (2014). Best-known releases include *Honesty Lives Elsewhere* (2016) and *Dancing with the Curse* (2020). Released primarily on Fat Wreck Chords. The band has been continuously active.",
  "gg-allin":
    "American singer (1956-1993). Born Jesus Christ Allin in Lancaster, New Hampshire. Among the most controversial figures in punk and hardcore history, known for deliberately provocative and confrontational live performances that frequently involved nudity, self-harm, and audience interaction.\n\nReleased over a dozen studio albums between *Always Was, Is, and Always Shall Be* (1980) and the posthumous *Brutality and Bloodshed for All* (1993). Subject of the 1993 Todd Phillips documentary *Hated: GG Allin and the Murder Junkies*. Died of a heroin overdose in June 1993 just hours after a performance — fulfilling his longtime promise to commit suicide on stage.",
  "gillian-welch":
    "American singer-songwriter born October 2, 1967, in New York City. Long-running musical and personal partnership with guitarist/producer David Rawlings (born 1969). The duo performs as a unit on most of Welch's recordings.\n\nReleased five studio albums between *Revival* (1996) and *The Harrow & the Harvest* (2011). Contributed to the *O Brother, Where Art Thou?* (2000) soundtrack, which won the 2001 Album of the Year Grammy. Rawlings has also released several albums credited to himself with Welch as a co-conspirator. The duo has been continuously active across the Americana and folk circuits.",
  "giorgio-moroder":
    "Italian record producer and composer born Hansjörg Moroder on April 26, 1940, in Urtijëi, Italy. Pioneer of electronic dance music and one of the most influential disco-era producers. Often credited as the \"Father of Disco.\"\n\nReleased over a dozen solo studio albums starting with *That's Bubblegum, That's Giorgio* (1969). Best-known production work includes Donna Summer's *I Remember Yesterday* (1977, featuring \"I Feel Love\" — widely considered the foundational electronic dance track), the *Midnight Express* soundtrack (1978, Oscar-winning), and *Flashdance* (1983, including \"What a Feeling\" — also Oscar-winning). Won the Oscar for Best Original Song in 1984 for \"Take My Breath Away\" (from *Top Gun*).",
  "girl-talk":
    "American DJ and mashup producer born Gregg Gillis on October 26, 1981, in Pittsburgh, Pennsylvania. Distinguished by his exceptionally dense mashups — typically combining dozens of samples per track into a single continuous mix.\n\nReleased five studio albums between *Secret Diary* (2002) and *All Day* (2010). *Feed the Animals* (2008) was distributed under a pay-what-you-want model and notably tested the limits of fair-use copyright law via its 322 sample sources. Gillis has performed extensively at music festivals.",
  "girls-against-boys":
    "American rock band formed in Washington, D.C. in 1988. Long-running lineup: Scott McCloud (vocals/guitar), Eli Janney (keyboards), Johnny Temple (bass), and Alexis Fleisig (drums). Distinguished by their two-bassist configuration (Janney's keyboard parts often function as a second bassline).\n\nSix studio albums starting with *Nineties vs. Eighties* (1990). Best-known releases include *Cruise Yourself* (1994), *House of GVSB* (1996), and *Freak*on*ica* (1998, their major-label debut on Geffen). Released primarily on Touch and Go and DGC. The band has been on indefinite hiatus since 2002.",
  "gloria-estefan":
    "Cuban-American singer born Gloria María Milagrosa Fajardo on September 1, 1957, in Havana, Cuba. First gained prominence as lead vocalist of the Miami Sound Machine (1977-1989) before launching a solo career. Three Grammy Awards.\n\nReleased over a dozen solo studio albums between *Cuts Both Ways* (1989) and *Brazil305* (2020). Commercial peak: *Into the Light* (1991, following a 1990 tour bus accident that nearly paralyzed her), *Mi Tierra* (1993, her Spanish-language Grammy-winning album), and *Destiny* (1996, the official Atlanta Olympics album).",
  "god-forbid":
    "American metalcore band formed in New Brunswick, New Jersey in 1996. Long-running lineup: Byron Davis (vocals), Doc Coyle (guitar), Dallas Coyle (guitar, 1996-2009, his brother), John Outcalt (bass), and Corey Pierce (drums).\n\nSix studio albums starting with *Reject the Sickness* (1999). Best-known releases include *Determination* (2001), *Gone Forever* (2004), and *IV: Constitution of Treason* (2005). The band dissolved in 2013. Doc Coyle joined Bad Wolves; Davis later joined Bury Your Dead.",
  "god-street-wine":
    "American jam band formed in New York City in 1988. Lineup: Lo Faber (vocals/guitar), Aaron Maxwell (vocals/guitar), Dan Pifer (bass), Tomo (Tom Osander, drums), and Jon Bevo (keyboards). Style draws on jam-band tradition, folk-rock, and gospel.\n\nFour studio albums between *$1.99 Romances* (1992) and *God Street Wine* (1996). The band cultivated a substantial live following in the early-1990s East Coast jam-band scene before dissolving in 1999. Periodic reunions have continued since.",
  "goo-goo-dolls":
    "American rock band formed in Buffalo, New York in 1986 by John Rzeznik (vocals/guitar) and Robby Takac (bass). The band's name and concept emerged from a True Detective magazine ad. Long-running drummer Mike Malinin played from 1995 to 2013.\n\nThirteen studio albums starting with *Goo Goo Dolls* (1987). Commercial peak: *A Boy Named Goo* (1995, featuring \"Name\") and *Dizzy Up the Girl* (1998, featuring \"Iris\" — which spent 18 weeks at #1 on the Adult Top 40 chart, a long-running record). Continuously active.",
  "good-riddance":
    "American punk rock band formed in Santa Cruz, California in 1986. Long-running lineup: Russ Rankin (vocals), Luke Pabich (guitar), Sean Sellers (drums), and various bassists. Style draws on melodic hardcore and political punk.\n\nNine studio albums starting with *For God and Country* (1995). Best-known releases include *A Comprehensive Guide to Moderne Rebellion* (1996), *Operation Phoenix* (1999), and *Symptoms of a Leveling Spirit* (2001). Released primarily on Fat Wreck Chords. The band has been continuously active despite a 2007-2012 hiatus.",
  "govt-mule":
    "American rock band formed in 1994 as a side project by Allman Brothers Band members Warren Haynes (vocals/guitar) and Allen Woody (bass, died 2000). Drummer Matt Abts has been with the band since formation; keyboardist Danny Louis joined in 2002. After Woody's death, Andy Hess and later Jorgen Carlsson (since 2008) have handled bass duties.\n\nReleased over a dozen studio albums starting with *Gov't Mule* (1995). Best-known releases include *Dose* (1998), *Life Before Insanity* (2000), and *High & Mighty* (2006). The band has continued as Haynes's primary touring vehicle alongside his Allman Brothers Band commitments.",
  "graham-central-station":
    "American funk band formed in 1973 by bassist Larry Graham (formerly of Sly and the Family Stone). Distinguished by Graham's pioneering slap-bass technique, which fundamentally reshaped bass playing in funk and subsequent genres.\n\nReleased eight studio albums between *Graham Central Station* (1974) and *My Radio Sure Sounds Good to Me* (1978). Best-known songs include \"Hair\" and \"The Jam\" (both 1974). Graham revived the band intermittently from the 1990s onward, releasing *GCS2000* (1999) and *Raise Up* (2012) — the latter featuring Prince, who was Graham's longtime collaborator and bandmate in the New Power Generation.",
  "grand-funk":
    "Shortened name often used by Grand Funk Railroad, particularly during their 1973-1976 commercial peak when the band briefly dropped \"Railroad\" from their billing. American rock trio formed in Flint, Michigan in 1969.\n\nReleased multiple albums under the shortened name including *Phoenix* (1972), *We're an American Band* (1973, featuring the #1 title track), and *Shinin' On* (1974, featuring a cover of \"The Loco-Motion\"). The full lineup eventually re-adopted the original \"Grand Funk Railroad\" name. Inducted into Hollywood Walk of Fame in 1999.",
  "grand-funk-railroad":
    "American rock band formed in Flint, Michigan in 1969. Original lineup: Mark Farner (vocals/guitar), Mel Schacher (bass), and Don Brewer (drums). Among the most commercially successful American rock bands of the early 1970s, with substantial controversy over critical disdain despite enormous album sales.\n\nReleased 13 studio albums starting with *On Time* (1969). Commercial peak: *Closer to Home* (1970), *Survival* (1971), *Phoenix* (1972), and *We're an American Band* (1973, their first #1 album). The band's 1971 Shea Stadium concert sold out faster than the Beatles' 1965 Shea Stadium show.",
  "grandmaster-melle-mel":
    "American rapper born Melvin Glover on May 15, 1961, in the Bronx. Best known as a member of Grandmaster Flash and the Furious Five (1976-1983). The 1982 single \"The Message\" (with Flash and the Furious Five) is widely considered one of the most important early hip-hop singles for its socially conscious lyrical content.\n\nReleased several solo and Furious Five-related releases starting with *Greatest Messages* (1984). Inducted into the Rock and Roll Hall of Fame with Grandmaster Flash and the Furious Five in 2007 — the first hip-hop act to be inducted.",
  "grandmaster-melle-mel-the-furious-five":
    "American hip-hop group formed in the South Bronx in 1976 by Joseph Saddler (Grandmaster Flash, DJ). The Furious Five rapping component included Cowboy (Keith Wiggins, died 1989), Melle Mel (Melvin Glover), Kidd Creole (Nathaniel Glover), Mr. Ness/Scorpio (Eddie Morris), and Rahiem (Guy Williams). Pioneers of hip-hop performance as a distinct musical/cultural form.\n\nReleased three studio albums in the original era between *The Message* (1982) and *On the Strength* (1988). Best-known single: \"The Message\" (1982), one of the foundational socially conscious hip-hop tracks. Inducted into the Rock and Roll Hall of Fame in 2007 — the first hip-hop act so recognized.",
  "gravity-kills":
    "American industrial rock band formed in Jefferson City, Missouri in 1995. Lineup: Jeff Scheel (vocals), Matt Dudenhoeffer (guitar), Doug Firley (keyboards), and Kurt Kerns (bass).\n\nThree studio albums between *Gravity Kills* (1996, featuring \"Guilty\") and *Superstarved* (2002). The 1996 single \"Guilty\" was featured on the *Seven* (1995) and *The Crow: City of Angels* (1996) soundtracks. The band has been inactive since 2003.",
  "great-american-taxi":
    "American jam band formed in Boulder, Colorado in 2006 by Vince Herman (vocals/guitar, of Leftover Salmon). Multiple members from the broader Colorado jam-band scene have rotated through the lineup. Style draws on country, jam-band, and Americana.\n\nFour studio albums between *Streets of Gold* (2007) and *Reckless Habits* (2015). The band's revolving lineup has included Chad Staehly (keyboards), Brian Adams (bass), and Jim Lewin (guitar). Currently semi-active around Herman's primary Leftover Salmon commitments.",
  "gren":
    "American alternative rock band formed in San Diego in the mid-1990s. Lineup: Jeff Bayer (vocals/guitar) and various other members. Style draws on post-grunge alternative rock.\n\nReleased multiple studio albums; primarily a regional Southern California act. Limited national exposure.",
  "greta-van-fleet":
    "American rock band formed in Frankenmuth, Michigan in 2012. Lineup: Josh Kiszka (vocals), Jake Kiszka (guitar), Sam Kiszka (bass/keyboards), and Danny Wagner (drums). The Kiszka members are three brothers (Sam and Josh are twins; Jake is their older brother). Style closely echoes 1970s Led Zeppelin, with comparisons that have been both their greatest commercial asset and frequent critical liability.\n\nFour studio albums between *From the Fires* (2017) and *Starcatcher* (2023). Won the 2019 Grammy for Best Rock Album for *From the Fires*. Continuously active.",
  "grim-reaper":
    "English heavy metal band formed in Droitwich, Worcestershire in 1979. Long-running lineup centered on Steve Grimmett (vocals, 1979-2008, 2017-2022, died 2022) and Nick Bowcott (guitar).\n\nThree studio albums in the original era: *See You in Hell* (1983), *Fear No Evil* (1985), and *Rock You to Hell* (1987). The band split in 1989; Grimmett revived the project in 2006 as Steve Grimmett's Grim Reaper after legal disputes over the original name. Grimmett's right leg was amputated in 2017 after a tour-related illness; he died in 2022.",
  "grotus":
    "American industrial rock band formed in San Francisco in 1989. Lineup: Lars Fox (vocals/programming), John Carson (vocals/guitar), Adam Tanner (bass), and Bruce Boyd (drums). Distinguished by their fusion of industrial, world music, and political/anti-corporate lyrical content.\n\nThree studio albums between *Brown* (1991) and *Mass* (1994). Released primarily on Spirit Records and London Records. The band dissolved in the mid-1990s.",
  "gtr":
    "English progressive rock supergroup formed in 1985 by guitarists Steve Howe (formerly of Yes and Asia) and Steve Hackett (formerly of Genesis). Lineup also included Max Bacon (vocals), Phil Spalding (bass), and Jonathan Mover (drums). The band's name is the abbreviation for \"guitar.\"\n\nReleased one studio album: *GTR* (1986), which produced the top-20 single \"When the Heart Rules the Mind.\" Howe departed in 1987 after creative differences with Hackett over the direction of the never-completed second album. Hackett briefly revived the project as GTR2 in 1989 with new musicians before disbanding it.",
  "guns-n-roses":
    "American rock band formed in Los Angeles in 1985. Classic lineup: Axl Rose (vocals), Slash (guitar), Izzy Stradlin (rhythm guitar, 1985-1991), Duff McKagan (bass), and Steven Adler (drums, 1985-1990, replaced by Matt Sorum). One of the most commercially successful rock bands in history, with estimated worldwide sales over 100 million units.\n\nSeven studio albums starting with *Appetite for Destruction* (1987). *Appetite* is the best-selling debut album in US history at over 18 million copies. Commercial peak: *G N' R Lies* (1988), *Use Your Illusion I* and *Use Your Illusion II* (both 1991, released simultaneously), and *Chinese Democracy* (2008, released after a 17-year wait). The classic lineup reunited in 2016 (minus Stradlin and Adler) for the ongoing \"Not in This Lifetime...\" tour.",
  "guttermouth":
    "American punk rock band formed in Huntington Beach, California in 1988. Long-running lineup centered on Mark Adkins (vocals). Distinguished by deliberately offensive lyrics and a willingness to mock virtually every social group.\n\nNine studio albums between *Full Length* (1991) and *Eat Your Face* (2024). Best-known releases include *Friendly People* (1994), *Teri Yakimoto* (1996), and *Gusto* (1999). Released primarily on Nitro Records (Dexter Holland of the Offspring's label).",
  "h2o":
    "Same artist as the previously described H₂O — different Discogs/setlist.fm spelling variant. American hardcore band formed in New York City in 1995 by Toby Morse (vocals), Todd Morse (guitar), Adam Blake (bass), and Eric Rice (drums). Best known for melodic hardcore with positive, drug-free messaging. Six studio albums between 1996 and 2015.",
  "half-life":
    "American hardcore band formed in Pittsburgh in the mid-1980s. Long-running lineup centered on members of the Pittsburgh punk scene. Style draws on hardcore punk with melodic elements.\n\nReleased multiple studio albums including the namesake *Never Give In* (1989). Primarily a regional act with limited national distribution.",
  "handsome":
    "American post-hardcore band formed in New York City in 1994. Lineup: Jeremy Chatelain (vocals), Tom Capone (guitar, formerly of Quicksand), Pete Hines (drums), Eddie Nappi (bass), and Pete Mengede (guitar, formerly of Helmet).\n\nReleased one studio album: *Handsome* (1997), produced by Terry Date. The band toured with Hum and Far before dissolving in 1998 amid label disputes. Members went on to numerous other projects.",
  "hank-williams":
    "American country singer-songwriter (1923-1953). Born in Mount Olive, Alabama. Widely considered one of the most influential figures in country music history — and one of the most influential American songwriters of the 20th century across all genres. His country-blues fusion influenced rock and roll's development.\n\nReleased dozens of singles during his short career (he died at age 29). Posthumous compilations have collected his vast output. Best-known songs include \"Move It On Over\" (1947), \"Lovesick Blues\" (1949), \"Cold, Cold Heart\" (1951), \"Hey Good Lookin'\" (1951), \"Honky Tonk Blues\" (1952), \"Jambalaya (On the Bayou)\" (1952), and \"I'm So Lonesome I Could Cry\" (1949). Died from heart failure in the back of a Cadillac on New Year's Day 1953. Inducted into the Country Music Hall of Fame in 1961.",
  "hank-williams-jr":
    "American country singer-songwriter born Randall Hank Williams on May 26, 1949, in Shreveport, Louisiana. Son of Hank Williams. After spending his early career performing his father's material, transitioned in the late 1970s to a Southern-rock-influenced country sound that would define his commercial peak.\n\nReleased over 50 studio albums between *Hank Williams Jr. Sings the Songs of Hank Williams* (1964) and *Rich White Honky Blues* (2022). Commercial peak: *Family Tradition* (1979), *Whiskey Bent and Hell Bound* (1979), *Habits Old and New* (1980), and *Greatest Hits* (1982). Long-running performer of the *Monday Night Football* theme \"All My Rowdy Friends Are Here on Monday Night\" (1989-2011, returned in 2017).",
  "hanzel-und-gretyl":
    "American industrial metal band formed in New York City in 1993. Lineup: Vas Kallas (vocals/bass) and Kaiser von Loopy (guitar/keyboards). The band's name plays on the Brothers Grimm tale; their lyrics frequently use deliberately exaggerated mock-German imagery.\n\nFive studio albums between *Ausgeflippt* (1995) and *Black Forest Metal* (2014). Best-known release: *Über Alles* (2003). Released primarily on Energy Records and Metropolis Records.",
  "hard-ons":
    "Australian punk rock band formed in Sydney in 1982. Long-running lineup: Ray Ahn (bass), Peter Black (guitar/vocals), and Keish de Silva (drums, 1982-2017). Tim Rogers of You Am I joined as a vocalist briefly in 2018; Tim Rogers is currently the band's vocalist as of 2022.\n\nReleased over a dozen studio albums starting with *Smell My Finger* (1985). Best-known releases include *Hard-Ons* (1985), *Hot for Your Love, Baby* (1987), and *Yummy!* (1990). The band has been a consistent fixture on the Australian punk and hardcore touring circuit for over four decades.",
  "harry-belafonte":
    "American singer, actor, and civil rights activist (1927-2023). Born in Harlem, New York. Often credited with popularizing Caribbean music in the US during the 1950s. Recipient of multiple lifetime achievement honors, including the Kennedy Center Honors (1989) and the Jean Hersholt Humanitarian Award (2014).\n\nReleased over 30 studio albums between *Mark Twain and Other Folk Favorites* (1954) and *Belafonte 89* (1988). Commercial peak: *Calypso* (1956), the first single-artist album in any genre to sell over a million copies in a year. Best-known songs include \"Day-O (The Banana Boat Song)\" and \"Jump in the Line.\" An outspoken civil-rights activist and close associate of Martin Luther King Jr.; organized the 1985 \"We Are the World\" charity single for African famine relief.",
  "hawkwind":
    "English rock band formed in Notting Hill, London in 1969. Long-running lineup centered on Dave Brock (vocals/guitar/keyboards) — the only continuous member since formation. Foundational to space rock; influential on subsequent psychedelic-rock, progressive-rock, and stoner-rock acts. Lemmy Kilmister played bass with the band from 1971 to 1975 before being fired and forming Motörhead.\n\nReleased over 30 studio albums starting with *Hawkwind* (1970). Commercial peak: *In Search of Space* (1971), *Doremi Fasol Latido* (1972), *Space Ritual* (1973, a double live album), and *Quark, Strangeness and Charm* (1977). The band has remained continuously active for over 55 years across dozens of lineup changes.",
  "head-east":
    "American rock band formed in Carbondale, Illinois in 1969. Long-running lineup: John Schlitt (vocals, 1969-1980, later of Petra), Roger Boyd (keyboards/guitar), Mike Somerville (guitar, 1969-1978), Steve Huston (drums), and Dan Birney (bass).\n\nReleased ten studio albums between *Flat as a Pancake* (1975) and *Choice of Weapons* (1989). Best-known song: \"Never Been Any Reason,\" the opening track of *Flat as a Pancake*. Boyd has continued the band into the 2020s with rotating lineups.",
  "hearn-aid":
    "1985-1986 metal charity-record project organized by Ronnie James Dio (Dio, Black Sabbath) to raise funds for African famine relief. Modeled on the broader \"We Are the World\" / \"Do They Know It's Christmas?\" charity efforts of the same era.\n\nReleased a single, \"Stars,\" featuring vocals and solos from over 40 metal-genre musicians including members of Dio, Iron Maiden, Quiet Riot, Twisted Sister, Mötley Crüe, Judas Priest, Spinal Tap, and Yngwie Malmsteen. Released by Mercury Records in 1986.",
  "heaven-hell":
    "American-Irish heavy metal supergroup formed in 2006 as a touring vehicle for the Dio-era Black Sabbath lineup: Ronnie James Dio (vocals, died 2010), Tony Iommi (guitar), Geezer Butler (bass), and Vinny Appice (drums). The name was chosen to distinguish the touring project from the Ozzy-fronted Black Sabbath reunions and from the band's classic-era *Heaven and Hell* (1980) album.\n\nReleased one studio album: *The Devil You Know* (2009), which debuted at #8 on the Billboard 200. Dio died of stomach cancer in May 2010 at age 67, ending the project. The remaining members have not performed under the Heaven & Hell name since.",
  "helloween":
    "German power metal band formed in Hamburg in 1984. Long-running lineup centered on Markus Grosskopf (bass, since formation) and Michael Weikath (guitar, since 1985). Vocalists: Kai Hansen (1984-1988, returned 2016), Michael Kiske (1986-1993, returned 2016), and Andi Deris (since 1993). Foundational to European power metal.\n\nReleased 17 studio albums starting with *Walls of Jericho* (1985). Commercial peak: *Keeper of the Seven Keys, Part I* (1987) and *Keeper of the Seven Keys, Part II* (1988). The 2016 \"Pumpkins United\" tour reunited Hansen and Kiske with the modern lineup as a three-vocalist configuration. Released the self-titled *Helloween* (2021) with that expanded lineup.",
  "hermans-hermits-starring-peter-noone":
    "Touring version of the British Invasion band Herman's Hermits (1962-1971), led by original vocalist Peter Noone (born 1947). Noone has performed under variations of the name since 1973; legal disputes between Noone and other former Hermits have led to multiple competing touring entities under similar names.\n\nThe original Herman's Hermits released eight studio albums in the original era (1965-1971) and had ten top-ten US singles, including \"I'm Henry VIII, I Am,\" \"Mrs. Brown, You've Got a Lovely Daughter,\" and \"There's a Kind of Hush.\" Noone's touring version continues to perform that material.",
  "heyrocco":
    "American rock band formed in Charleston, South Carolina in 2010. Lineup: Nathan Merli (vocals/guitar), Chris Cool (bass), and Tanner Cooper (drums). Style draws on garage rock and grunge revival.\n\nReleased multiple studio albums starting with *Saturdazed* (2012). Best-known release: *Teenage Movie Soundtrack* (2015). Released primarily on Vagrant Records and independent labels.",
  "histandard":
    "Japanese punk rock band formed in Yokohama in 1991. Lineup: Akihiro Nanba (vocals/bass), Ken Yokoyama (guitar/vocals), and Tsuneo Tsutsui (drums, also of Bad Mouth). Among the most commercially successful Japanese punk bands.\n\nReleased five studio albums between *Last of Sunny Day* (1995) and *The Gift* (2017). Best-known release: *Making the Road* (1999). The band has performed primarily in Japan; founder of the Air Jam festival. Pioneers of Japanese melodic hardcore.",
  "hoi-polloi":
    "American Christian alternative rock band formed in the early 1990s. Limited public documentation; appears to be associated with the Tooth & Nail Records / R.E.X. Music label catalog of mid-1990s Christian rock.",
  "hole":
    "American rock band formed in Los Angeles in 1989 by Courtney Love (vocals/guitar) and Eric Erlandson (guitar). The classic lineup also included Kristen Pfaff (bass, died 1994), Patty Schemel (drums, 1992-1998), and Melissa Auf der Maur (bass, 1994-1999).\n\nFour studio albums between *Pretty on the Inside* (1991) and *Nobody's Daughter* (2010). Commercial peak: *Live Through This* (1994, released just days after Kurt Cobain's death) and *Celebrity Skin* (1998). The band has not released a studio album under the Hole name since 2010; Love has periodically pursued solo work and threatened reunions.",
  "home-grown":
    "American pop-punk band formed in Huntington Beach, California in 1994. Lineup: Adam Lohrbach (vocals/guitar), John \"Po\" Tran (guitar), Iam Pope (bass, died 2016), and various drummers. Closely associated with the late-1990s SoCal pop-punk scene alongside the Vandals and Zebrahead.\n\nFive studio albums between *That's Business* (1995) and *Kings of Pop* (2002). Best-known release: *Act Your Age* (1998). Released primarily on Outpost Recordings. The band has been on extended hiatus since the early 2000s. Iam Pope died in 2016.",
  "hot-butter":
    "American studio group active 1972. Best known for the single \"Popcorn,\" an electronic instrumental cover of the 1969 Gershon Kingsley composition. The single reached #9 on the Billboard Hot 100 in 1972, becoming one of the first commercially successful electronic instrumental hits.\n\nThe group was a one-off studio project led by keyboardist Stan Free; no significant follow-up recordings exist. \"Popcorn\" has been covered hundreds of times since and continues to appear in films, TV programs, and electronic-music samples.",
  "howard-jones":
    "English musician born John Howard Jones on February 23, 1955, in Southampton. Distinguished by his exclusively keyboard-based one-man-band performances during his early 1980s commercial peak — his solo synthesizer setup and mime performer Jed Hoile defined the visual presentation.\n\nReleased 13 studio albums between *Human's Lib* (1984) and *Dialogue* (2022). Commercial peak: *Human's Lib* (1984, featuring \"New Song\" and \"What Is Love?\") and *Dream into Action* (1985, featuring \"Things Can Only Get Better\"). Continues to tour with various ensembles.",
  "huey-lewis-the-news":
    "Same artist as the previously described Huey Lewis and the News — different Discogs/setlist.fm credit variation. American pop rock band formed in San Francisco in 1979 by vocalist Huey Lewis. The 1983 album *Sports* sold over 7 million copies in the US. Lewis revealed Ménière's disease in 2018, ending touring.",
  "humble-gods":
    "American punk rock band formed in Los Angeles in the mid-1990s by Mike Vallely (vocals, also a professional skateboarder). Style draws on hardcore punk and skate-punk.\n\nReleased two studio albums between *No Heroes* (1996) and *The Lighter Side of Mass Destruction* (2008). Released primarily on Triple X Records. Vallely has continued in a parallel professional skateboarding career.",
  "huntress":
    "American heavy metal band formed in Highland, California in 2009. Lineup: Jill Janus (vocals, 1975-2018, died), Blake Meahl (guitar), Anthony Crocamo (guitar, 2009-2014), Carl Wierzbicky (bass), and Eli Santana (guitar, since 2014). Janus's high operatic vocals were the band's most distinctive feature.\n\nThree studio albums between *Spell Eater* (2012) and *Static* (2015). Janus died by suicide in August 2018, ending the band. She had been outspoken about her struggles with mental illness and physical health throughout her career.",
  "i-see-stars":
    "American electronicore band formed in Warren, Michigan in 2006. Long-running lineup centered on brothers Devin Oliver (vocals) and Andrew Oliver (drums, 2006-2014). Style fuses metalcore, electronic music, and post-hardcore.\n\nSix studio albums between *3-D* (2009) and *Treehouse* (2016). Best-known releases include *Digital Renegade* (2012) and *New Demons* (2013). Released primarily on Sumerian Records.",
  "icarus-witch":
    "American heavy metal band formed in Pittsburgh in 2003. Long-running lineup centered on bassist Jason Myers and vocalist Christopher Shaner. Style draws on classic heavy metal, NWOBHM, and progressive metal.\n\nFour studio albums between *Roses on White Lace* (2005) and *Goodbye Cruel World* (2012). Released primarily on Cleopatra Records and AOR Heaven.",
  "ice-cube":
    "American rapper, actor, and filmmaker born O'Shea Jackson on June 15, 1969, in Los Angeles. Founding member of N.W.A (1986-1989) before launching a successful solo career. Among the most commercially successful hip-hop figures to transition to a parallel acting career.\n\nReleased ten solo studio albums between *AmeriKKKa's Most Wanted* (1990) and *Man Down* (2024). Commercial peak: *Death Certificate* (1991), *The Predator* (1992, the first album to debut at #1 on both the Billboard 200 and Top R&B/Hip-Hop Albums charts), and *Lethal Injection* (1993). Acting career includes *Boyz n the Hood* (1991), the *Friday* franchise (which he wrote), and the *Barbershop* franchise. Inducted into the Rock and Roll Hall of Fame with N.W.A in 2016.",
  "inside-out":
    "American hardcore band formed in Orange County, California in 1988. Lineup: Zack de la Rocha (vocals, later of Rage Against the Machine), Vic DiCara (guitar), Mark Haake (bass), and Alan Pacheco (drums). Highly influential despite a brief two-year active span.\n\nReleased one EP: *No Spiritual Surrender* (1990, on Revelation Records). De la Rocha went on to form Rage Against the Machine; the band's brief output remains a touchstone of late-1980s SoCal hardcore.",
  "integrity":
    "American hardcore band formed in Cleveland in 1988 by Dwid Hellion (vocals, the band's only continuous member). Long-running lineup also included Aaron Melnick (guitar, 1989-2003) and various other members. Style fuses metallic hardcore, sludge metal, and occult imagery.\n\nReleased over a dozen studio albums starting with *Those Who Fear Tomorrow* (1991). Best-known releases include *Humanity Is the Devil* (1995, an EP), *Seasons in the Size of Days* (1997), and *Howling, for the Nightmare Shall Consume* (2017). Dwid Hellion runs the Holy Terror Records label.",
  "interpol":
    "American rock band formed in New York City in 1997. Lineup: Paul Banks (vocals/guitar), Daniel Kessler (guitar), Sam Fogarino (drums, since 2000), and Carlos Dengler (bass, 1997-2010). Distinguished by their post-punk-revival sound during the early-2000s indie rock wave.\n\nSeven studio albums starting with *Turn On the Bright Lights* (2002). Critical peak: *Turn On the Bright Lights* and *Antics* (2004). Subsequent releases include *Our Love to Admire* (2007), the self-titled fourth album (2010), and *The Other Side of Make-Believe* (2022). Dengler departed in 2010; Brad Truax has handled bass duties since.",
  "iron-butterfly":
    "American rock band formed in San Diego in 1966. Original lineup: Doug Ingle (vocals/keyboards, died 2024), Erik Brann (guitar, died 2003), Lee Dorman (bass, died 2012), and Ron Bushy (drums, died 2021). Often cited as one of the earliest heavy-metal-adjacent acts.\n\nFive studio albums between *Heavy* (1968) and *Sun and Steel* (1975). Best-known release: *In-A-Gadda-Da-Vida* (1968), whose 17-minute title track filled the entire second side of the LP and became one of the most popular FM-radio cuts of the era. The band's various reformations have continued into the 2020s.",
  "jack-johnson":
    "American singer-songwriter, surfer, and filmmaker born May 18, 1975, in North Shore, Oahu. First gained prominence as a documentary filmmaker (the surf film *Thicker Than Water*, 2000) before launching a music career.\n\nReleased nine studio albums between *Brushfire Fairytales* (2001) and *Meet the Moonlight* (2022). Commercial peak: *On and On* (2003), *In Between Dreams* (2005, his biggest album, featuring \"Better Together\" and \"Banana Pancakes\"), and *Sleep Through the Static* (2008). Co-founded Brushfire Records, his own label, in 2002.",
  "jack-six":
    "American jazz bassist (1930-2015). Born John Robert Six in Danville, Indiana. Best known as the bassist for the Dave Brubeck Quartet during the post-classic-quartet era (1968-1972), replacing the long-tenured Eugene Wright.\n\nAlso performed with Gerry Mulligan, Stan Getz, and many other major jazz figures. Released few albums as a leader; primarily known as a sideman across the post-1960s mainstream jazz scene.",
  "jack-white":
    "American musician and producer born John Anthony Gillis on July 9, 1975, in Detroit. Co-founder of the White Stripes (1997-2011) with Meg White; also a member of the Raconteurs (since 2005) and the Dead Weather (since 2009). Solo career launched in 2012.\n\nSix solo studio albums between *Blunderbuss* (2012) and *No Name* (2024). Critical peak: *Blunderbuss* and *Lazaretto* (2014). Founded Third Man Records in 2001 as both his own label and a Nashville-based brick-and-mortar storefront/pressing plant. Among the most commercially successful champions of vinyl culture in the 21st century.",
  "james-brown":
    "American singer (1933-2006). Born in Barnwell, South Carolina. Often called \"the Godfather of Soul\" and \"the Hardest-Working Man in Show Business.\" One of the most foundational figures in soul, R&B, and funk; widely cited as inventing funk as a distinct musical genre.\n\nReleased over 50 studio albums between *Please Please Please* (1958) and *The Next Step* (2002). Career peaks include *Live at the Apollo* (1963), *Cold Sweat* (1967, the song widely cited as the first true funk recording), *Say It Loud — I'm Black and I'm Proud* (1969), and *The Payback* (1973). Inducted into the Rock and Roll Hall of Fame in 1986. Died on Christmas Day 2006.",
  "jamey-johnson":
    "American country singer-songwriter born July 14, 1975, in Enterprise, Alabama. Distinguished by his traditional honky-tonk approach and refusal of mainstream Nashville production trends.\n\nReleased five studio albums between *They Call Me Country* (2006) and *Living for a Song: A Tribute to Hank Cochran* (2012). Critical peak: *That Lonesome Song* (2008, certified gold) and *The Guitar Song* (2010, a double album that debuted at #4 on the Billboard 200). Has written hits for Trace Adkins, George Strait, and others.",
  "jan-dean":
    "American surf rock duo of Jan Berry (1941-2004) and Dean Torrence (born 1940). Active 1958-1966 in their classic era and intermittently thereafter. Among the foundational acts of the California surf-rock and hot-rod-music waves alongside the Beach Boys.\n\nReleased over a dozen studio albums during the original era. Best-known singles include \"Surf City\" (1963, the first surf song to reach Billboard #1), \"Drag City\" (1963), \"Dead Man's Curve\" (1964, which presciently described a near-fatal car accident Jan Berry would suffer two years later), and \"The Little Old Lady from Pasadena\" (1964). Jan Berry suffered severe brain injuries from a 1966 car accident and spent decades recovering. Died in 2004 from complications.",
  "janes-addiction":
    "American rock band formed in Los Angeles in 1985. Lineup: Perry Farrell (vocals), Dave Navarro (guitar), Eric Avery (bass), and Stephen Perkins (drums). Foundational to the alternative-rock explosion of the late 1980s and early 1990s; the band's 1991 dissolution led directly to Farrell's founding of the Lollapalooza festival.\n\nFour studio albums between *Jane's Addiction* (1987, a live album) and *The Great Escape Artist* (2011). Commercial peak: *Nothing's Shocking* (1988) and *Ritual de lo Habitual* (1990, featuring \"Been Caught Stealing\"). The band has reunited several times; their 2024 reunion tour ended dramatically with an on-stage altercation between Farrell and Navarro.",
  "jars-of-clay":
    "American Christian rock band formed in Greenville, Illinois in 1993. Lineup: Dan Haseltine (vocals), Charlie Lowell (keyboards), Stephen Mason (guitar), and Matt Odmark (guitar). Among the most commercially successful Christian rock acts of the 1990s and 2000s.\n\nEleven studio albums starting with *Jars of Clay* (1995, multi-platinum, featuring the crossover hit \"Flood\"). Best-known releases include *Much Afraid* (1997) and *The Eleventh Hour* (2002). Three Grammy Awards. Co-founded Blood:Water, a Christian charity addressing the African HIV/AIDS and water crises, in 2004.",
};

async function main() {
  const dryRun = process.argv.includes("--dry-run");
  const force = process.argv.includes("--force");
  const { containers } = await import("../lib/cosmos");
  const { getStoredArtist } = await import("../lib/artists");

  let written = 0;
  let skipped = 0;
  let missing = 0;

  for (const [slug, description] of Object.entries(DESCRIPTIONS)) {
    const existing = await getStoredArtist(slug);
    if (!existing) {
      console.log(`✗ ${slug}: no stored doc found`);
      missing += 1;
      continue;
    }
    if (existing.description && !force) {
      console.log(`↷ ${slug}: already has description — skipping`);
      skipped += 1;
      continue;
    }
    if (dryRun) {
      console.log(`◌ ${slug}: would write ${description.length} chars`);
      written += 1;
      continue;
    }
    const updated = {
      ...existing,
      description,
      updatedAt: new Date().toISOString(),
    };
    await containers.artists.item(slug, slug).replace(updated);
    console.log(`✓ ${slug}: ${description.length} chars`);
    written += 1;
  }

  console.log(`\nDone. written=${written} skipped=${skipped} missing=${missing}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
