import { config as loadEnv } from "dotenv";
loadEnv({ path: ".env.local" });

const DESCRIPTIONS: Record<string, string> = {
  "downset":
    "American rap rock band formed in Los Angeles in 1990. Lineup: Rey Oropeza (vocals), Rogelio Lozano (guitar), James Morris (bass), and Chris Lee (drums). Influential to the development of the rap-metal hybrid alongside Rage Against the Machine and Body Count.\n\nFive studio albums between 1994 and 2014, including the self-titled debut (1994), *Do We Speak a Dead Language?* (1996), and *Universal* (2000). Released primarily on Mercury and Epitaph. The band has performed intermittent reunion tours since the mid-2000s.",
  "earth-crisis":
    "American hardcore band formed in Syracuse, New York in 1989. Long-running lineup centered on Karl Buechner (vocals) and Dennis Merrick (drums). Foundational to the 1990s straightedge and vegan-hardcore scenes; the band's politically charged lyrics shaped a generation of activist-minded hardcore acts.\n\nSeven studio albums starting with *Destroy the Machines* (1995). Best-known releases include *Gomorrah's Season Ends* (1996), *Breed the Killers* (1998), and the reunion album *To the Death* (2009). Disbanded in 2001 and reunited in 2007.",
  "elton-john":
    "English singer-songwriter and pianist born Reginald Kenneth Dwight in 1947 in Pinner, Middlesex. Long-running songwriting partnership with lyricist Bernie Taupin (since 1967) has produced the majority of his catalog. Among the best-selling music artists of all time, with over 300 million units sold worldwide.\n\nReleased 32 studio albums between *Empty Sky* (1969) and *The Lockdown Sessions* (2021). Commercial peak: *Honky Château* (1972), *Don't Shoot Me I'm Only the Piano Player* (1973), *Goodbye Yellow Brick Road* (1973), and *Captain Fantastic and the Brown Dirt Cowboy* (1975). The 1997 \"Candle in the Wind 1997\" tribute to Princess Diana remains the best-selling single in history. Inducted into the Rock and Roll Hall of Fame in 1994.",
  "elvis-costello-the-attractions":
    "Same artist as the previously described Elvis Costello and The Attractions — different Discogs spelling variant. English rock band fronted by Elvis Costello (born Declan MacManus, 1954) with backing band the Attractions: Steve Nieve (keyboards), Bruce Thomas (bass), and Pete Thomas (drums). Active 1977-1986, plus intermittent later projects.\n\nProduced 11 studio albums together including *This Year's Model* (1978), *Armed Forces* (1979), *Get Happy!!* (1980), and *Imperial Bedroom* (1982). The partnership's three-album opening run is widely considered foundational to British new wave songwriting.",
  "elvis-presley":
    "American singer, musician, and actor (1935-1977). Born in Tupelo, Mississippi. Widely regarded as the most popular and influential American musician of the 20th century — a foundational figure in rock and roll, rockabilly, gospel, and country crossover. Often referred to as \"the King of Rock and Roll\" or simply \"the King.\"\n\nReleased 24 studio albums during his lifetime, plus dozens of compilation, soundtrack, and live albums. Initial commercial breakthrough on Sun Records (1954) and RCA (1955 onward). Major career arcs include his 1968 \"Comeback Special\" return after a decade of mostly soundtrack work, and the Las Vegas residency era (1969-1977). Inducted into the Rock and Roll Hall of Fame in 1986.",
  "emmylou-harris":
    "American singer-songwriter born April 2, 1947, in Birmingham, Alabama. First gained prominence as harmony vocalist with Gram Parsons before launching a solo career after his 1973 death. Bridged country, folk, rock, and bluegrass across her decades-long discography.\n\nReleased over 25 studio albums starting with *Gliding Bird* (1969) and the breakthrough *Pieces of the Sky* (1975). Subsequent peaks: *Elite Hotel* (1975), *Wrecking Ball* (1995, produced by Daniel Lanois), and the 1987 collaboration *Trio* with Dolly Parton and Linda Ronstadt. Fourteen Grammy Awards. Inducted into the Country Music Hall of Fame in 2008.",
  "ennio-morricone":
    "Italian composer and conductor (1928-2020). Born in Rome. Among the most prolific and influential film composers in history, with over 400 scores credited across film, television, and theater. Particularly known for the trumpet-and-whistle motifs of his work with director Sergio Leone.\n\nKey scores include *A Fistful of Dollars* (1964), *The Good, the Bad and the Ugly* (1966), *Once Upon a Time in the West* (1968), *Cinema Paradiso* (1988), *The Untouchables* (1987), and *The Hateful Eight* (2015) — the last finally winning him a competitive Academy Award after five previous nominations. Received an honorary Oscar in 2007.",
  "fantmas":
    "American experimental rock supergroup formed in 1998. Lineup: Mike Patton (vocals, also of Faith No More and Mr. Bungle), Buzz Osborne (guitar, of the Melvins), Trevor Dunn (bass, of Mr. Bungle), and Dave Lombardo (drums, of Slayer). Distinguished by genre-collision composition spanning death metal, jazz, lounge, and avant-garde.\n\nFour studio albums: the self-titled debut (1999), *The Director's Cut* (2001, all film-score covers), *Delìrium Còrdia* (2004, a single 74-minute composition), and *Suspended Animation* (2005). Released primarily on Ipecac Recordings, Patton's own label. Active intermittently.",
  "fat-boys":
    "American hip-hop trio formed in Brooklyn, New York in 1982. Lineup: Mark \"Prince Markie Dee\" Morales (died 2021), Damon \"Kool Rock-Ski\" Wimbley, and Darren \"Buff Love\" Robinson (died 1995). Originally known as the Disco 3 before adopting the Fat Boys name. Pioneered the comedic, lighthearted style of hip-hop and the use of human beatboxing.\n\nSix studio albums between *Fat Boys* (1984) and *Mack Daddy* (1991). Commercial peak: *Crushin'* (1987, featuring the Beach Boys collaboration \"Wipeout\"). The trio also appeared in the films *Krush Groove* (1985) and *Disorderlies* (1987).",
  "fear-factory":
    "American industrial metal band formed in Los Angeles in 1989. Long-running lineup centered on Burton C. Bell (vocals, 1989-2020) and Dino Cazares (guitar, 1989-2002, 2009-present). Foundational to industrial metal alongside Ministry and Nine Inch Nails; the band's clean/harsh dual vocal approach influenced subsequent metalcore and nu-metal acts.\n\nTen studio albums starting with *Soul of a New Machine* (1992). Best-known releases include *Demanufacture* (1995), *Obsolete* (1998), and *Digimortal* (2001). Bell departed in 2020 after extended legal disputes with Cazares; the band has continued with new vocalist Milo Silvestro.",
  "five-iron-frenzy":
    "American ska-punk band formed in Denver, Colorado in 1995. Long-running lineup: Reese Roper (vocals), Micah Ortega (guitar), Sonnie Johnston (guitar), Keith Hoerig (bass), Andrew Verdecchio (drums), Leanor \"Jeff\" Ortega (trumpet), and Dennis Culp (trombone). Initially associated with the Christian rock scene; the band's lyrical content combines satirical commentary, humor, and faith.\n\nEight studio albums between *Upbeats and Beatdowns* (1996) and *Until This Shakes Apart* (2021). Best-known releases include *Our Newest Album Ever!* (1997) and *All the Hype That Money Can Buy* (2000). Disbanded in 2003 after an extensive farewell tour; reunited in 2011 via a Kickstarter campaign.",
  "foo-fighters":
    "American rock band formed in Seattle in 1994 by Dave Grohl (vocals/guitar, formerly the drummer of Nirvana). Long-running lineup: Grohl, Nate Mendel (bass, 1995-present), Pat Smear (guitar, 1995-1997, 2010-present), Chris Shiflett (guitar, 1999-present), and the late Taylor Hawkins (drums, 1997-2022).\n\nEleven studio albums starting with the 1995 self-titled debut. Commercial peak: *The Colour and the Shape* (1997), *There Is Nothing Left to Lose* (1999), and *One by One* (2002). Sixteen Grammy Awards. Hawkins died in March 2022; the band returned to touring with Josh Freese on drums and released *But Here We Are* (2023).",
  "gary-hoey":
    "American rock guitarist born March 2, 1960, in Lowell, Massachusetts. Distinguished by his blend of blues, hard rock, and instrumental surf-rock arrangements. Briefly considered for the Ozzy Osbourne band in 1987 before Zakk Wylde won the gig.\n\nReleased over 20 studio albums starting with *Animal Instinct* (1993). Best-known releases include *Endless Summer II* (1994, a surf-rock instrumental album), *Bug Alley* (1996), and the Christmas-themed *Ho! Ho! Hoey* series (1995-2003). Continues to tour with his own band.",
  "george-carlin":
    "American stand-up comedian (1937-2008). Born in The Bronx, New York. Among the most influential American comedians of the 20th century, known for his observational humor, political commentary, and use of language. His \"Seven Words You Can Never Say on Television\" routine led to the 1978 Supreme Court case FCC v. Pacifica Foundation.\n\nReleased 22 comedy albums and 14 HBO specials between 1960 and his 2008 death. Commercial peak: *AM & FM* (1972), *Class Clown* (1972, featuring the \"Seven Words\" routine), and the long-running series of HBO specials starting with *On Location: George Carlin at USC* (1977). Posthumously received the Mark Twain Prize for American Humor in 2008.",
  "george-jones":
    "American country singer (1931-2013). Born in Saratoga, Texas. Among the most acclaimed and influential country vocalists in history, with a distinctive style that influenced subsequent generations of country singers. Often referred to as \"the Possum\" or \"No Show Jones.\"\n\nReleased over 80 studio albums between 1957 and 2013. Critical peak: \"He Stopped Loving Her Today\" (1980), widely cited as one of the greatest country songs ever recorded. Other key releases include *White Lightning* (1959), *Walls Can Fall* (1992), and several duet albums with then-wife Tammy Wynette. Inducted into the Country Music Hall of Fame in 1992.",
  "god-lives-underwater":
    "American industrial rock band formed in Camp Hill, Pennsylvania in 1993. Long-running lineup centered on David Reilly (vocals, 1993-2005, died 2005) and Jeff Turzo (keyboards/programming). Style fused industrial textures with melodic alternative-rock songwriting.\n\nFour studio albums between *Empty* EP (1995) and *Up Off the Floor* (2004). The single \"From Your Mouth\" from *Empty* gained MTV rotation. Reilly died of a drug overdose in October 2005, ending the band.",
  "godsmack":
    "American rock band formed in Lawrence, Massachusetts in 1995. Long-running lineup: Sully Erna (vocals), Tony Rombola (guitar), Robbie Merrill (bass), and Shannon Larkin (drums, since 2002, replacing Tommy Stewart). Distinguished by their direct, riff-heavy hard rock approach and Erna's tribal-drumming centerpiece in live performances.\n\nEight studio albums starting with the self-titled 1998 debut. Five consecutive #1 Billboard 200 albums between 2003 and 2014. Best-known releases include *Awake* (2000), *Faceless* (2003), and *The Oracle* (2010). The band has been one of the most consistently commercial American hard-rock acts of the 2000s and 2010s.",
  "hatebreed":
    "American hardcore band formed in Bridgeport, Connecticut in 1994. Lineup: Jamey Jasta (vocals), Chris Beattie (bass), Wayne Lozinak (guitar, 1994-1999, 2009-present), and Matt Byrne (drums, 2001-present). Foundational to the hardcore-metal crossover \"toughguy\" subgenre and influential on subsequent metalcore.\n\nNine studio albums starting with *Satisfaction Is the Death of Desire* (1997). Best-known releases include *Perseverance* (2002), *The Rise of Brutality* (2003), and *For the Lions* (2009, a covers album). Jasta hosts *The Jasta Show* podcast and previously hosted *Headbangers Ball* on MTV2 (2003-2007).",
  "heatwave":
    "British-American funk band formed in West Germany in 1975 by American servicemen brothers Johnnie and Keith Wilder (vocals). Long-running lineup also included Rod Temperton (keyboards/songwriter, died 2016), Jesse Whitten (guitar, died 1977), and Mario Mantese (bass). The band's name reflects its multinational origins — members hailed from the US, the UK, Switzerland, Czechoslovakia, Jamaica, and Spain.\n\nSix studio albums between *Too Hot to Handle* (1976) and *The Fire* (1988). Commercial peak: *Too Hot to Handle* (featuring \"Boogie Nights\") and *Central Heating* (1977, featuring \"Always and Forever\"). Rod Temperton departed to write for Michael Jackson (notably \"Off the Wall,\" \"Rock with You,\" and \"Thriller\").",
  "helmet":
    "American alternative metal band formed in New York City in 1989 by guitarist/vocalist Page Hamilton. Original lineup included Peter Mengede (guitar), Henry Bogdan (bass), and John Stanier (drums, later of Battles). Distinguished by aggressive, technically precise riffing and influential on subsequent post-hardcore and metalcore acts.\n\nEight studio albums starting with *Strap It On* (1990). Commercial peak: *Meantime* (1992) and *Betty* (1994). The band briefly broke up in 1998 and reformed in 2004 as a Hamilton-led project with various supporting musicians.",
  "henry-rollins":
    "American singer, spoken-word artist, writer, and actor born February 13, 1961, in Washington, D.C. First gained prominence as vocalist for Black Flag (1981-1986); subsequently led the Rollins Band and pursued an extensive spoken-word and acting career.\n\nReleased ten Rollins Band studio albums between *Hot Animal Machine* (1987) and *Get Some Go Again* (2000). Solo spoken-word albums and books span dozens of releases. Acting credits include *Heat* (1995), *Lost Highway* (1997), and the title role in the film *He Never Died* (2015). Long-running radio host on KCRW (2009-2016).",
  "hot-tuna":
    "American blues-rock band formed in San Francisco in 1969 by Jefferson Airplane members Jorma Kaukonen (guitar/vocals) and Jack Casady (bass). Originally a side project; became a full-time pursuit after the Airplane disbanded in 1972. Style spans acoustic country blues and electric heavy blues, often distinguished by extended improvisational sets.\n\nReleased 16 studio albums between *Hot Tuna* (1970) and *Steady as She Goes* (2011). Active intermittently across five decades, with Kaukonen and Casady the only continuous members.",
  "ice-nine-kills":
    "American metalcore band formed in Boston in 2000 by vocalist Spencer Charnas. Long-running lineup also includes Dan Sugarman (guitar) and Patrick Galante (drums). Distinguished by horror-themed concept albums; nearly every song on the band's recent albums is inspired by a specific horror film or novel.\n\nSeven studio albums starting with *Last Chance to Make Amends* (2006). Commercial peak: *The Silver Scream* (2018) and *The Silver Scream 2: Welcome to Horrorwood* (2021). Charnas's stage presentation incorporates horror-film props and theatrical elements during live performances.",
  "iggy-pop":
    "American singer-songwriter and actor (born James Newell Osterberg Jr., 1947). First gained prominence as vocalist of the Stooges (1967-1974, 2003-2016); his solo career has spanned six decades. Often called \"the Godfather of Punk\" for his foundational influence on the genre.\n\nNineteen solo studio albums between *The Idiot* (1977, co-written with David Bowie) and *Every Loser* (2023). Commercial peak: *Lust for Life* (1977), *New Values* (1979), and *Blah-Blah-Blah* (1986). The Stooges were inducted into the Rock and Roll Hall of Fame in 2010.",
  "incubus":
    "American rock band formed in Calabasas, California in 1991. Long-running lineup: Brandon Boyd (vocals), Mike Einziger (guitar), José Pasillas (drums), Chris Kilmore (DJ/keyboards, since 1998), and various bassists — Ben Kenney joined in 2003. Style evolved from funk-metal early on toward alternative rock and adult-contemporary pop in later albums.\n\nEight studio albums starting with *Fungus Amongus* (1995). Commercial peak: *Make Yourself* (1999, featuring \"Drive\"), *Morning View* (2001), and *A Crow Left of the Murder* (2004). Continuously active.",
  "inxs":
    "Australian rock band formed in Sydney in 1977. Original lineup: Michael Hutchence (vocals, died 1997), Andrew Farriss (keyboards), Jon Farriss (drums), Tim Farriss (guitar), Kirk Pengilly (saxophone/guitar), and Garry Gary Beers (bass). Three of the six members were Farriss brothers.\n\nTwelve studio albums starting with the self-titled 1980 debut. Commercial peak: *Kick* (1987, multi-platinum, featuring \"Need You Tonight,\" \"Devil Inside,\" and \"Never Tear Us Apart\") and *X* (1990). Hutchence died by suicide in November 1997. The band continued with various vocalists including J.D. Fortune (chosen via the 2005 reality show *Rock Star: INXS*) before dissolving in 2012.",
  "janet-jackson":
    "American singer, songwriter, dancer, and actress born May 16, 1966, in Gary, Indiana. The youngest of the Jackson family musical dynasty. Commercial breakthrough came with her third album, transitioning her from a teen TV actor to one of the defining pop artists of the late 20th century.\n\nEleven studio albums between *Janet Jackson* (1982) and *Unbreakable* (2015). Commercial peak: *Control* (1986), *Janet Jackson's Rhythm Nation 1814* (1989), *janet.* (1993), and *The Velvet Rope* (1997). Frequent collaborator with the production team Jimmy Jam and Terry Lewis. Inducted into the Rock and Roll Hall of Fame in 2019.",
  "jason-and-the-scorchers":
    "American rock band formed in Nashville in 1981. Lineup: Jason Ringenberg (vocals), Warner E. Hodges (guitar), Jeff Johnson (bass), and Perry Baggs (drums, died 2012). Foundational to the \"cowpunk\" subgenre that fused traditional country with punk rock; influence acknowledged by subsequent acts including Drive-By Truckers and Old 97's.\n\nSeven studio albums between *Fervor* (1983) and *Halcyon Times* (2010). Best-known releases include *Lost & Found* (1985) and *Still Standing* (1986). Released primarily on EMI America and Mammoth. The band has reunited multiple times since.",
  "jeff-beck":
    "English rock guitarist (1944-2023). First gained prominence as guitarist for the Yardbirds (1965-1966), then the Jeff Beck Group (1967-1969). Widely considered one of the most innovative electric guitarists in rock history, particularly for his pioneering use of feedback, distortion, and the volume/tone knob.\n\nReleased 16 studio albums between *Truth* (1968) and *18* (2022, with Johnny Depp). Critical peak: *Blow by Blow* (1975) and *Wired* (1976), both produced by George Martin. Eight Grammy Awards. Inducted into the Rock and Roll Hall of Fame three times — with the Yardbirds (1992), as a solo artist (2009), and the *Rolling Stone* lists. Beck died of bacterial meningitis in January 2023.",
  "jerry-lee-lewis":
    "American pianist, singer, and songwriter (1935-2022). Born in Ferriday, Louisiana. Often referred to as \"the Killer.\" One of the most influential figures in the development of rock and roll, with a piano-pounding performance style that paralleled the early Elvis Presley.\n\nReleased over 40 studio albums between *Jerry Lee Lewis* (1958) and *Mean Old Man* (2010). Best-known singles include \"Whole Lotta Shakin' Goin' On\" and \"Great Balls of Fire\" (1957). Career-derailing 1958 scandal over his marriage to his 13-year-old cousin Myra Gale Brown effectively ended his rock and roll career; he successfully pivoted to country music in the late 1960s. Inducted into the Rock and Roll Hall of Fame in 1986.",
  "joan-jett-the-blackhearts":
    "American rock band led by Joan Jett (vocals/guitar). Jett (born September 22, 1958, in Philadelphia) first gained prominence as guitarist/vocalist of the Runaways (1975-1979) before forming the Blackhearts in 1979 with manager Kenny Laguna producing.\n\nTen studio albums starting with *Bad Reputation* (1981). Commercial peak: *I Love Rock 'n Roll* (1981, featuring the title track, a #1 hit that remained for seven weeks). Subsequent peaks include *Album* (1983) and *Up Your Alley* (1988). Co-founded Blackheart Records in 1980, making it one of the first artist-owned independent labels. Inducted into the Rock and Roll Hall of Fame in 2015.",
  "john-cougar-mellencamp":
    "American rock musician born John J. Mellencamp on October 7, 1951, in Seymour, Indiana. Initially recorded as \"Johnny Cougar\" (1976-1982), then \"John Cougar\" (1979-1983), then \"John Cougar Mellencamp\" (1983-1991), and finally \"John Mellencamp\" (1991-present).\n\nReleased 25 studio albums between *Chestnut Street Incident* (1976) and *Strictly a One-Eyed Jack* (2022). Commercial peak: *American Fool* (1982, featuring \"Hurts So Good\" and \"Jack & Diane\"), *Uh-Huh* (1983, featuring \"Pink Houses\"), and *Scarecrow* (1985). Co-founded Farm Aid with Willie Nelson and Neil Young in 1985. Inducted into the Rock and Roll Hall of Fame in 2008.",
  "john-fogerty":
    "American singer-songwriter and guitarist born May 28, 1945, in Berkeley, California. First gained prominence as the primary songwriter and vocalist of Creedence Clearwater Revival (1967-1972). Decades-long legal battles with Fantasy Records owner Saul Zaentz over the CCR catalog defined much of his post-CCR career.\n\nEleven solo studio albums between *The Blue Ridge Rangers* (1973) and *Fogerty's Factory* (2020). Commercial peak: *Centerfield* (1985, featuring the title track and \"The Old Man Down the Road\"). In 2023, Fogerty finally bought back the publishing rights to most of his CCR songs. Inducted into the Rock and Roll Hall of Fame with CCR in 1993.",
  "john-kay-steppenwolf":
    "Steppenwolf is a Canadian-American rock band formed in Los Angeles in 1967 by German-born John Kay (vocals/guitar). The classic lineup included Michael Monarch (guitar), Goldy McJohn (keyboards, died 2017), Rushton Moreve (bass), and Jerry Edmonton (drums, died 1993).\n\nReleased 14 studio albums between *Steppenwolf* (1968) and *Rise and Shine* (1990). Commercial peak: \"Born to Be Wild\" and \"Magic Carpet Ride\" (1968), both prominently featured in the film *Easy Rider* (1969). The band dissolved in 1972, reformed multiple times through the 1980s, and Kay retired from touring in 2018.",
  "journey":
    "American rock band formed in San Francisco in 1973. Long-running classic lineup: Steve Perry (vocals, 1977-1987, 1995-1998), Neal Schon (guitar, since formation), Jonathan Cain (keyboards, since 1980), Ross Valory (bass, 1973-2020), and various drummers. Arnel Pineda has been the band's primary vocalist since 2007.\n\nFifteen studio albums starting with *Journey* (1975). Commercial peak: *Escape* (1981, featuring \"Don't Stop Believin'\") and *Frontiers* (1983). \"Don't Stop Believin'\" later became the best-selling digital track from the 20th century after a memorable use in the 2007 *Sopranos* finale. Inducted into the Rock and Roll Hall of Fame in 2017.",
  "julian-lennon":
    "British musician born John Charles Julian Lennon on April 8, 1963, in Liverpool. Eldest son of John Lennon and Cynthia Lennon. Pursued a solo recording career starting in 1984 while contending with the unavoidable comparison to his father.\n\nReleased eight solo studio albums between *Valotte* (1984) and *Jude* (2022). Commercial peak: *Valotte* (1984, multi-platinum, featuring the title track and \"Too Late for Goodbyes\"). Subsequent work has incorporated more experimental electronic and acoustic elements. The 2022 cover of \"Imagine\" — recorded as a fundraiser for Ukrainian relief — was his first-ever recording of the song.",
  "junior-brown":
    "American country and Western singer-songwriter and guitarist born June 12, 1952, in Cottonwood, Arizona. Known for the \"guit-steel,\" a custom double-neck instrument combining a six-string electric guitar with a lap steel guitar that he plays from a standing position.\n\nReleased ten studio albums starting with *12 Shades of Brown* (1990). Best-known releases include *Guit with It* (1993), *Junior High* (1995), and *Long Walk Back* (1998). His material spans honky-tonk, Western swing, surf, and rockabilly; live performances typically include extended instrumental showcases of the guit-steel.",
  "karma-to-burn":
    "American instrumental stoner rock band formed in Morgantown, West Virginia in 1994. Long-running lineup centered on guitarist William Mecum and bassist Rich Mullins (died 2014). Distinguished by their primarily instrumental approach — most songs are numbered rather than titled.\n\nSeven studio albums between the self-titled debut (1997) and *Arch Stanton* (2014). Best-known releases include *Wild Wonderful Purgatory* (1999) and *Almost Heathen* (2001). Released primarily on Roadrunner and Spinerock. The band has been intermittently active across multiple lineup changes.",
  "kenny-wayne-shepherd":
    "American blues-rock guitarist born June 12, 1977, in Shreveport, Louisiana. Released his debut album at age 18; one of the youngest commercially successful blues guitarists of the 1990s blues-revival era.\n\nReleased 12 studio albums starting with *Ledbetter Heights* (1995). Commercial peak: *Trouble Is...* (1997) and *Live On* (1999), both multi-platinum. Subsequent albums have leaned toward purer blues territory including *10 Days Out: Blues from the Backroads* (2007), a documentary-style album featuring elderly blues legends. Continues to tour with his own band.",
  "kings-x":
    "American rock band formed in Springfield, Missouri in 1980 (originally as the Edge). Long-running trio: Doug Pinnick (bass/vocals), Ty Tabor (guitar), and Jerry Gaskill (drums). Style fuses hard rock, progressive rock, Beatles-influenced harmony, and gospel.\n\nThirteen studio albums starting with *Out of the Silent Planet* (1988). Critical peak: *Gretchen Goes to Nebraska* (1989) and *Faith Hope Love* (1990). The band has been continuously active since 1980 with the same three-member lineup — exceptionally rare for any rock band over a 45-year span.",
  "krokus":
    "Swiss hard rock band formed in Solothurn in 1975. Long-running lineup centered on Chris von Rohr (bass/vocals) and Fernando von Arb (guitar). Vocalist Marc Storace has been the band's most identifiable voice since 1980.\n\nSeventeen studio albums starting with *Krokus* (1976). Commercial peak: *Headhunter* (1983, featuring the title track and \"Eat the Rich\") and *The Blitz* (1984). The band has often been compared to AC/DC stylistically, sharing producers, riff-rock structures, and stadium-rock instincts. Performed a farewell tour in 2019.",
  "kyuss":
    "American stoner rock band formed in Palm Desert, California in 1987. Lineup: John Garcia (vocals), Josh Homme (guitar, later of Queens of the Stone Age), Scott Reeder (bass, 1992-1995, replacing original bassist Nick Oliveri), and Brant Bjork (drums, 1987-1993, replaced by Alfredo Hernández). Considered foundational to stoner rock and desert rock.\n\nFour studio albums between *Wretch* (1991) and *...And the Circus Leaves Town* (1995). Critical peak: *Blues for the Red Sun* (1992) and *Welcome to Sky Valley* (1994). The band dissolved in 1995, with Homme forming Queens of the Stone Age the following year. Members have reunited under variations of the Kyuss name; legal disputes have prevented use of the full band name in some configurations.",
  "l7":
    "American rock band formed in Los Angeles in 1985. Lineup: Donita Sparks (vocals/guitar), Suzi Gardner (vocals/guitar), Jennifer Finch (bass, 1986-1996, 2014-present), and Dee Plakas (drums, 1988-present). One of the foundational all-female bands of the 1990s alternative rock wave.\n\nSeven studio albums between *L7* (1988) and *Scatter the Rats* (2019). Commercial peak: *Bricks Are Heavy* (1992, featuring \"Pretend We're Dead\"). The band split in 2001 and reunited in 2014; *Scatter the Rats* was their first studio album in 20 years. A 2017 documentary film, *L7: Pretend We're Dead*, chronicled their history.",
  "lamb-of-god":
    "American heavy metal band formed in Richmond, Virginia in 1994 (originally as Burn the Priest, the name reverted-to in 2018 for a covers album). Long-running lineup: Randy Blythe (vocals), Mark Morton (guitar), Willie Adler (guitar), John Campbell (bass), and Chris Adler (drums, 1994-2019, replaced by Art Cruz).\n\nNine studio albums starting with *New American Gospel* (2000). Commercial peak: *As the Palaces Burn* (2003), *Ashes of the Wake* (2004), *Sacrament* (2006), and *Wrath* (2009). Considered foundational to the \"New Wave of American Heavy Metal\" alongside Killswitch Engage and Shadows Fall. Blythe was charged with manslaughter in the Czech Republic in 2012 over a fan's death at a 2010 concert; he was eventually acquitted.",
  "lesley-gore":
    "American singer and songwriter (1946-2015). Born in Brooklyn, New York. Most successful as a teenage pop star in the early 1960s; later became a noted songwriter, LGBTQ activist, and PBS host.\n\nReleased eight studio albums between *I'll Cry If I Want To* (1963) and *Ever Since* (2005). Commercial peak: her 1963 debut featuring the #1 single \"It's My Party,\" produced by Quincy Jones (his first commercial breakthrough as a producer). Other notable singles include \"Judy's Turn to Cry\" (1963), \"She's a Fool\" (1963), and the feminist anthem \"You Don't Own Me\" (1963). Co-wrote songs for the film *Fame* (1980), including the Oscar-nominated \"Out Here on My Own.\"",
  "link-wray":
    "American guitarist (1929-2005). Born in Dunn, North Carolina. Among the most influential rock guitarists in history despite never having a top-40 hit. His 1958 instrumental \"Rumble\" — the only song to be banned from US radio because of its supposed potential to incite gang violence, despite having no lyrics — pioneered distorted electric guitar tone and the use of the power chord.\n\nReleased over 20 studio albums between *Link Wray and the Wraymen* (1960) and *Barbed Wire* (2000). Critical peak: the 1971 self-titled \"comeback\" album produced in a converted Maryland chicken coop. Wray has been cited as a foundational influence by Pete Townshend, Jimmy Page, Jeff Beck, Iggy Pop, and Bob Dylan.",
  "lionize":
    "American rock band formed in Silver Spring, Maryland in 2006. Lineup: Nate Bergman (vocals/guitar), Henry Upton (bass), Chris Brooks (keyboards), and Chase Lapp (drums). Style draws on classic rock, reggae, dub, blues, and prog.\n\nSeven studio albums starting with the self-titled debut (2008). Best-known releases include *Destruction Manual* (2012), *Jetpack Soundtrack* (2014), and *Nuclear Soul* (2017). Released primarily on the Frenchkiss and Weathermaker labels (the latter operated by Clutch). Bergman departed for a solo career in 2019; the band has been inactive since.",
  "live":
    "American rock band formed in York, Pennsylvania in 1988 (originally as Public Affection). Lineup: Ed Kowalczyk (vocals/guitar, 1988-2009, 2016-present), Chad Taylor (guitar), Patrick Dahlheimer (bass), and Chad Gracey (drums). Foundational to the post-grunge era of mainstream American rock.\n\nNine studio albums starting with *Mental Jewelry* (1991). Commercial peak: *Throwing Copper* (1994), which sold over 8 million copies in the US on the strength of \"Selling the Drama,\" \"I Alone,\" and \"Lightning Crashes.\" Kowalczyk departed in 2009 and rejoined in 2016 after extensive legal disputes with the band over rights.",
  "living-colour":
    "American rock band formed in New York City in 1984. Long-running lineup: Corey Glover (vocals), Vernon Reid (guitar), Will Calhoun (drums), and Doug Wimbish (bass, since 1992, replacing Muzz Skillings). Distinguished by their virtuosic musicianship, genre-fusion (rock, funk, jazz, hip-hop), and a rare visibility as a Black rock band in the late-1980s and early-1990s alternative wave.\n\nSix studio albums starting with *Vivid* (1988, featuring the breakthrough single \"Cult of Personality\"). Subsequent releases include *Time's Up* (1990) and *Stain* (1993). The band broke up in 1995 and reunited in 2000. Vernon Reid co-founded the Black Rock Coalition in 1985.",
  "loverboy":
    "Canadian rock band formed in Calgary, Alberta in 1979. Long-running lineup: Mike Reno (vocals), Paul Dean (guitar), Doug Johnson (keyboards), Scott Smith (bass, 1979-2000, died 2000), and Matt Frenette (drums). One of the most commercially successful Canadian acts of the 1980s.\n\nSeven studio albums starting with *Loverboy* (1980). Commercial peak: *Get Lucky* (1981, featuring \"Working for the Weekend\") and *Keep It Up* (1983). Bassist Scott Smith was lost at sea off the California coast in November 2000; replaced by Spider Sinnaeve. The band has continued touring extensively.",
  "lush":
    "English alternative rock band formed in London in 1987. Lineup: Miki Berenyi (vocals/guitar), Emma Anderson (vocals/guitar), Phil King (bass, 1992-1996, replacing Steve Rippon), and Chris Acland (drums, died 1996). Initially associated with the British shoegazing scene before pivoting toward Britpop on their final album.\n\nFour studio albums between *Scar* (1989) and *Lovelife* (1996). Chris Acland died by suicide in October 1996, ending the band. Lush reunited briefly in 2015-2016 for a tour and the *Blind Spot* EP. The 2024 album *Beautiful Garbage* (under the name Piroshka, a Berenyi-Anderson collaboration) explored similar territory.",
  "madball":
    "American hardcore band formed in New York City in 1988. Lineup: Freddy Cricien (vocals, half-brother of Roger Miret of Agnostic Front), Mitts (guitar, since 1995), Hoya Roc (bass, since 1989), and various drummers. Founding member of the NYHC \"Crew\" scene that crossed over into broader extreme metal popularity.\n\nTen studio albums starting with *Set It Off* (1994). Best-known releases include *Demonstrating My Style* (1996), *Hold It Down* (2000), and *Empire* (2010). Continuously active across multiple decades, with Cricien remaining the band's only continuous member.",
  "manowar":
    "American heavy metal band formed in Auburn, New York in 1980 by bassist Joey DeMaio and guitarist Ross \"the Boss\" Friedman (later replaced by Karl Logan, 1994-2018). Vocalist Eric Adams has been the band's only continuous singer since formation. Distinguished by mythological/Conan-influenced lyrics, leather-and-loincloth stage attire, and extreme stage-volume performances.\n\nTwelve studio albums starting with *Battle Hymns* (1982). Best-known releases include *Into Glory Ride* (1983), *Kings of Metal* (1988), and *The Triumph of Steel* (1992). The 1984 Guinness Book of World Records listed Manowar as the loudest band in the world (a title later contested by other acts).",
  "masked-intruder":
    "American pop-punk band formed in Madison, Wisconsin in 2009. The four members perform anonymously under masked personas — Intruder Blue (vocals/guitar), Intruder Green (guitar), Intruder Red (bass), and Intruder Yellow (drums) — with elaborate burglar-themed stage presentation. The band's lyrical content consistently fuses pop-punk love songs with the conceit that the protagonists are habitual criminals.\n\nFour studio albums starting with the self-titled debut (2012). Best-known releases include *M.I.* (2014) and *III* (2019). Released primarily on Red Scare Industries and Fat Wreck Chords.",
  "meat-loaf":
    "American singer and actor (born Marvin Lee Aday, 1947-2022). Distinguished by his powerful tenor voice, theatrical stage presentation, and long-running partnership with songwriter Jim Steinman.\n\nTwelve studio albums starting with *Bat Out of Hell* (1977), one of the best-selling albums of all time at over 43 million copies worldwide. Subsequent peaks: *Bad Attitude* (1984), *Bat Out of Hell II: Back into Hell* (1993, featuring \"I'd Do Anything for Love (But I Won't Do That)\"), and *Bat Out of Hell III: The Monster Is Loose* (2006). Also a notable actor — most famously as Eddie in *The Rocky Horror Picture Show* (1975). Died in January 2022.",
  "men-at-work":
    "Australian rock band formed in Melbourne in 1978. Lineup: Colin Hay (vocals/guitar), Ron Strykert (guitar), Greg Ham (saxophone/flute/keyboards, died 2012), John Rees (bass), and Jerry Speiser (drums). Among the most commercially successful Australian acts of the early 1980s.\n\nThree studio albums in the original era: *Business as Usual* (1981, featuring \"Who Can It Be Now?\" and \"Down Under\"), *Cargo* (1983), and *Two Hearts* (1985). *Business as Usual* spent 15 weeks at #1 on the Billboard 200, the longest run by a debut album at the time. The band dissolved in 1985 and has reunited periodically since.",
  "michael-jackson":
    "American singer, songwriter, and dancer (1958-2009). Born in Gary, Indiana. One of the most commercially successful and influential entertainers in popular music history. Began his career as the youngest member of the Jackson 5 in 1964; launched his adult solo career with *Off the Wall* (1979).\n\nTen solo studio albums between *Got to Be There* (1972) and the posthumous *Michael* (2010). Commercial peak: *Thriller* (1982), which has sold over 70 million copies worldwide — the best-selling album in history by most counts. Subsequent peaks: *Bad* (1987), *Dangerous* (1991), and *HIStory* (1995). Thirteen Grammy Awards. Inducted into the Rock and Roll Hall of Fame twice — with the Jackson 5 (1997) and as a solo artist (2001).",
  "mick-taylor":
    "English guitarist born January 17, 1949, in Welwyn Garden City. Best known as a member of the Rolling Stones (1969-1974), where he replaced founder Brian Jones. His tenure on five Stones studio albums — including *Sticky Fingers* (1971), *Exile on Main St.* (1972), and *Goats Head Soup* (1973) — coincided with the band's critical peak.\n\nReleased six solo studio albums starting with *Mick Taylor* (1979). Has frequently performed with Bob Dylan, John Mayall (with whom he played in the Bluesbreakers before joining the Stones), and various blues-rock acts. Has reunited periodically with the Rolling Stones for select tours since the 1980s.",
  "millencolin":
    "Swedish punk rock band formed in Örebro in 1992. Long-running lineup: Nikola Šarčević (vocals/bass), Mathias Färm (guitar), Erik Ohlsson (guitar), and Fredrik Larzon (drums) — all four members continuous since formation.\n\nNine studio albums starting with *Tiny Tunes* (1994). Commercial peak: *Pennybridge Pioneers* (2000) and *Home from Home* (2002). Released primarily on Burning Heart Records (until 2004) and the band's own Soundpollution label. Continuously active.",
  "ministry":
    "American industrial metal band formed in Chicago in 1981. Long-running lineup centered on Al Jourgensen (vocals/guitar/programming). Other key members include Paul Barker (bass/programming, 1986-2003) and various drummers. Foundational to industrial metal alongside KMFDM, Skinny Puppy, and Nine Inch Nails.\n\nFifteen studio albums starting with *With Sympathy* (1983, a synth-pop album Jourgensen has since disowned). Commercial peak: *The Land of Rape and Honey* (1988), *The Mind Is a Terrible Thing to Taste* (1989), and *Psalm 69* (1992, featuring \"Jesus Built My Hotrod\"). The band dissolved in 2008, reformed in 2012, and has continued with various lineups since.",
  "minor-threat":
    "American hardcore band formed in Washington, D.C. in 1980. Lineup: Ian MacKaye (vocals), Lyle Preslar (guitar), Brian Baker (bass, later guitar), and Jeff Nelson (drums). Foundational to hardcore punk and the originators of straightedge as a cultural movement (the 1981 song \"Straight Edge\" coined the term).\n\nOne studio album and three EPs in the band's 1980-1983 run, all collected on the posthumous *Complete Discography* (1989). Best-known releases: the *Minor Threat* (1981) and *In My Eyes* (1981) EPs, and the LP *Out of Step* (1983). MacKaye and Nelson co-founded Dischord Records, one of the most influential American independent labels. MacKaye later formed Embrace and Fugazi.",
  "misfits":
    "American horror punk band formed in Lodi, New Jersey in 1977. Original lineup: Glenn Danzig (vocals, 1977-1983), Jerry Only (bass, 1977-1983, 1995-present), Bobby Steele (guitar, 1978-1980), and various drummers. Pioneers of \"horror punk\" — punk rock with horror-movie-themed imagery, lyrics, and aesthetics, including the band's iconic skull logo and \"devilock\" hairstyle.\n\nTwo studio albums in the original era: *Walk Among Us* (1982) and *Earth A.D./Wolfs Blood* (1983). Danzig fired the band in 1983 to form Samhain (later Danzig). The Misfits resumed in 1995 with Only's brother Doyle (guitar) and singer Michale Graves. The original Danzig-Only lineup reunited for limited touring starting in 2016.",
  "molly-hatchet":
    "American Southern rock band formed in Jacksonville, Florida in 1971. Long-running lineup centered on Dave Hlubek (guitar, 1971-1995, died 2017). Vocalists included Danny Joe Brown (1975-1980, 1982-1996, died 2005) and Jimmy Farrar (1980-1982). Distinguished by the band's three-guitar attack and Frank Frazetta-painted album covers.\n\nFourteen studio albums starting with *Molly Hatchet* (1978). Commercial peak: *Flirtin' with Disaster* (1979, double-platinum) and *Beatin' the Odds* (1980). The band has cycled through dozens of members across its decades-long history. Only original member Phil McCormack (vocals, 1996-2019) was on board for the band's recent era; McCormack died in 2019.",
  "mr-big":
    "American hard rock band formed in Los Angeles in 1988. Lineup: Eric Martin (vocals), Paul Gilbert (guitar, 1988-1996, 2009-present), Billy Sheehan (bass), and Pat Torpey (drums, 1988-2018, died 2018). Distinguished by the virtuosic musicianship of Gilbert and Sheehan, both renowned as instructional-video instructors.\n\nNine studio albums starting with the 1989 self-titled debut. Commercial peak: *Lean into It* (1991), featuring the #1 single \"To Be with You.\" Gilbert departed in 1996 (replaced by Richie Kotzen, 1999-2002), and the band dissolved in 2002. Reformed in 2009 with the original lineup. Torpey died of complications from Parkinson's disease in 2018.",
  "nashville-pussy":
    "American rock band formed in Atlanta in 1996. Long-running lineup: Blaine Cartwright (vocals/guitar), Ruyter Suys (lead guitar), and various rhythm sections. Cartwright and Suys are married. Distinguished by their fusion of Southern rock, punk, and metal with deliberately provocative stage shows.\n\nEight studio albums starting with *Let Them Eat Pussy* (1998). Best-known releases include *High as Hell* (2000), *Say Something Nasty* (2002), and *Get Some* (2005). The band has been a touring fixture on rock festival circuits for over 25 years.",
  "natalie-merchant":
    "American singer-songwriter born October 26, 1963, in Jamestown, New York. First gained prominence as lead vocalist of 10,000 Maniacs (1981-1993) before launching a solo career.\n\nReleased eight solo studio albums starting with *Tigerlily* (1995, multi-platinum, featuring \"Carnival\" and \"Wonder\"). Critical peak: *Tigerlily*, *Ophelia* (1998), and *Motherland* (2001). The 2010 double album *Leave Your Sleep* set century-old poetry to original music. Continues to record and tour.",
  "neil-young":
    "Canadian-American singer-songwriter and guitarist born November 12, 1945, in Toronto. First gained prominence in Buffalo Springfield (1966-1968) and Crosby, Stills, Nash & Young (1969-1970, intermittent reunions). His longtime backing band Crazy Horse has accompanied him on much of his solo work since 1969.\n\nReleased over 40 solo studio albums between *Neil Young* (1968) and *Coastal* (2025). Critical peak: *After the Gold Rush* (1970), *Harvest* (1972), *Tonight's the Night* (1975), *Zuma* (1975), and *Rust Never Sleeps* (1979). Inducted into the Rock and Roll Hall of Fame twice — as a solo artist (1995) and with Buffalo Springfield (1997). Continues to record and tour at age 80.",
  "new-kids-on-the-block":
    "American boy band formed in Boston in 1984. Lineup: Donnie Wahlberg, Jordan Knight, Jonathan Knight, Joey McIntyre, and Danny Wood. The group was assembled by producer Maurice Starr, who had previously developed the similarly-formatted New Edition.\n\nSeven studio albums between *New Kids on the Block* (1986) and *Still Kids* (2024). Commercial peak: *Hangin' Tough* (1988, including \"Please Don't Go Girl,\" \"You Got It (The Right Stuff),\" and \"I'll Be Loving You (Forever)\") and *Step by Step* (1990). The group dissolved in 1994, reformed in 2008, and has continued to tour. Donnie Wahlberg has pursued an extensive acting career; his brother Mark Wahlberg was briefly a member.",
  "neworder":
    "Same artist as the previously described New Order — different Discogs/setlist.fm spelling variant. English rock band formed in Salford in 1980 from the surviving members of Joy Division after Ian Curtis's suicide. Lineup: Bernard Sumner (vocals/guitar/keyboards), Peter Hook (bass), Stephen Morris (drums), and Gillian Gilbert (keyboards/guitar, 1980-2001, 2011-present).\n\nTen studio albums starting with *Movement* (1981). Commercial peak: *Power, Corruption & Lies* (1983), *Low-Life* (1985), and *Technique* (1989, a #1 album in the UK). The 1983 single \"Blue Monday\" remains the best-selling 12\" single in history. Hook departed in 2007; legal disputes over the band's name extended into the 2010s. Inducted into the Rock and Roll Hall of Fame in 2024.",
};

async function main() {
  const dryRun = process.argv.includes("--dry-run");
  const force = process.argv.includes("--force");
  const { containers } = await import("../lib/cosmos");
  const { getStoredArtist } = await import("../lib/artists");

  let written = 0;
  let skipped = 0;
  let missing = 0;

  for (const [slug, description] of Object.entries(DESCRIPTIONS)) {
    const existing = await getStoredArtist(slug);
    if (!existing) {
      console.log(`✗ ${slug}: no stored doc found`);
      missing += 1;
      continue;
    }
    if (existing.description && !force) {
      console.log(`↷ ${slug}: already has description — skipping`);
      skipped += 1;
      continue;
    }
    if (dryRun) {
      console.log(`◌ ${slug}: would write ${description.length} chars`);
      written += 1;
      continue;
    }
    const updated = {
      ...existing,
      description,
      updatedAt: new Date().toISOString(),
    };
    await containers.artists.item(slug, slug).replace(updated);
    console.log(`✓ ${slug}: ${description.length} chars`);
    written += 1;
  }

  console.log(`\nDone. written=${written} skipped=${skipped} missing=${missing}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
